DTS Application Library: /usr/src/dtsapplib/dtsapplib-0.1/src/openldap.c File Reference
openldap.c File Reference
#include <ldap.h>
#include <ldap_schema.h>
#include <lber.h>
#include <sasl/sasl.h>
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <sys/time.h>
#include <stdarg.h>
#include "include/dtsapp.h"
Data Structures
struct sasl_defaults
struct ldap_simple
struct ldap_conn
struct ldap_modify
struct ldap_add
struct ldap_modval
struct ldap_modreq
Functions
int ldap_count (LDAP *ld, LDAPMessage *message, int *err)
struct ldap_entry * ldap_getent (LDAP *ld, LDAPMessage **msgptr, LDAPMessage *result, int b64enc, int *err)
int dts_sasl_interact (LDAP *ld, unsigned flags, void *defaults, void *in)
void free_simple (void *data)
void free_modval (void *data)
void free_modreq (void *data)
void free_modify (void *data)
void free_add (void *data)
void free_sasl (void *data)
void free_ldapconn (void *data)
void free_result (void *data)
void free_entry (void *data)
void free_rdnarr (void *data)
void free_rdn (void *data)
void free_attr (void *data)
void free_attrvalarr (void *data)
void free_attrval (void *data)
void free_entarr (void *data)
int modify_hash (const void *data, int key)
int ldap_rebind_proc (LDAP *ld, LDAP_CONST char *url, ber_tag_t request, ber_int_t msgid, void *params)
struct ldap_conn * ldap_connect (const char *uri, enum ldap_starttls starttls, int timelimit, int limit, int debug, int *err)
int ldap_simplebind (struct ldap_conn *ld, const char *dn, const char *passwd)
int ldap_simplerebind (struct ldap_conn *ldap, const char *initialdn, const char *initialpw, const char *base, const char *filter, const char *uidrdn, const char *uid, const char *passwd)
int ldap_saslbind (struct ldap_conn *ld, const char *mech, const char *realm, const char *authcid, const char *passwd, const char *authzid)
void ldap_close (struct ldap_conn *ld)
const char * ldap_errmsg (int res)
int searchresults_hash (const void *data, int key)
struct ldap_results * dts_ldapsearch (struct ldap_conn *ld, const char *base, int scope, const char *filter, char *attrs[], int b64enc, int *err)
struct ldap_results * ldap_search_sub (struct ldap_conn *ld, const char *base, const char *filter, int b64enc, int *res,...)
struct ldap_results * ldap_search_one (struct ldap_conn *ld, const char *base, const char *filter, int b64enc, int *res,...)
struct ldap_results * ldap_search_base (struct ldap_conn *ld, const char *base, const char *filter, int b64enc, int *res,...)
char * ldap_getdn (LDAP *ld, LDAPMessage *message, int *err)
char * ldap_getattribute (LDAP *ld, LDAPMessage *message, BerElement **berptr, int *err)
char * ldap_encattr (void *attrval, int b64enc, enum ldap_attrtype *type)
struct berval ** ldap_attrvals (LDAP *ld, LDAPMessage *message, char *attr, int *cnt, int *err)
int ldapattr_hash (const void *data, int key)
struct bucket_list * attr2bl (LDAP *ld, LDAPMessage *message, struct ldap_attr **first, int b64enc, int *res)
void ldap_unref_attr (struct ldap_entry *entry, struct ldap_attr *attr)
void ldap_unref_entry (struct ldap_results *results, struct ldap_entry *entry)
struct ldap_entry * ldap_getentry (struct ldap_results *results, const char *dn)
struct ldap_attr * ldap_getattr (struct ldap_entry *entry, const char *attr)
struct ldap_modify * ldap_modifyinit (const char *dn)
struct ldap_modreq * new_modreq (struct bucket_list *modtype, const char *attr)
struct ldap_modreq * getmodreq (struct ldap_modify *lmod, const char *attr, int modop)
int add_modifyval (struct ldap_modreq *modr, const char *value)
int ldap_mod_del (struct ldap_modify *lmod, const char *attr,...)
int ldap_mod_add (struct ldap_modify *lmod, const char *attr,...)
int ldap_mod_rep (struct ldap_modify *lmod, const char *attr,...)
LDAPMod * ldap_reqtoarr (struct ldap_modreq *modr, int type)
int ldap_domodify (struct ldap_conn *ld, struct ldap_modify *lmod)
int ldap_mod_delattr (struct ldap_conn *ldap, const char *dn, const char *attr, const char *value)
int ldap_mod_remattr (struct ldap_conn *ldap, const char *dn, const char *attr)
int ldap_mod_addattr (struct ldap_conn *ldap, const char *dn, const char *attr, const char *value)
int ldap_mod_repattr (struct ldap_conn *ldap, const char *dn, const char *attr, const char *value)
struct ldap_add * ldap_addinit (const char *dn)
struct ldap_modreq * getaddreq (struct ldap_add *ladd, const char *attr)
int ldap_add_attr (struct ldap_add *ladd, const char *attr,...)
int ldap_doadd (struct ldap_conn *ld, struct ldap_add *ladd)
Function Documentation
int add_modifyval (struct ldap_modreq * modr, const char * value)
Definition at line 1154 of file openldap.c.
References ALLOC_CONST, ldap_modreq::cnt, ldap_modreq::first, free_modval(), ldap_modreq::last, ldap_modval::next, objalloc(), objunref(), and ldap_modval::value.
{
    struct ldap_modval *newval;
    if (!(newval = objalloc(sizeof(*newval), free_modval))) {
        return 1;
    }
    ALLOC_CONST(newval->value, value);
    if (!newval->value) {
        objunref(newval);
        return 1;
    }
    if (!modr->first) {
        modr->first = newval;
    }
    if (modr->last) {
        modr->last->next = newval;
    }
    modr->cnt++;
    modr->last = newval;
    return 0;
}
struct bucket_list* attr2bl (LDAP * ld, LDAPMessage * message, struct ldap_attr ** first, int b64enc, int * res) read
Definition at line 823 of file openldap.c.
References addtobucket(), ldap_attrval::buffer, ldap_attr::count, create_bucketlist(), free_attr(), free_attrval(), free_attrvalarr(), ldap_attrvals(), ldap_encattr(), ldap_getattribute(), ldapattr_hash(), ldap_attrval::len, ldap_attr::name, ldap_attr::next, objalloc(), objunref(), ldap_attr::prev, ldap_attrval::type, and ldap_attr::vals.
{
    BerElement *ber = NULL;
    struct bucket_list *bl;
    struct ldap_attr *la, *prev = NULL;
    struct ldap_attrval *lav, **lavals;
    struct berval **tmp, **vals = NULL;
    enum ldap_attrtype type;
    char *attr;
    int cnt;
    char *eval;
    if (!(bl = create_bucketlist(4, ldapattr_hash))) {
        if (res) {
            *res = LDAP_NO_MEMORY;
        }
        return NULL;
    }
    while((attr = ldap_getattribute(ld, message, &ber, res))) {
        tmp = vals = ldap_attrvals(ld, message, attr, &cnt, res);
        la = objalloc(sizeof(*la), free_attr);
        if (first && !*first) {
            *first = la;
        }
        la->next = NULL;
        if (prev) {
            prev->next = la;
            la->prev = prev;
        } else {
            la->prev = NULL;
        }
        prev = la;
        lavals = objalloc(sizeof(void*) * (cnt+1), free_attrvalarr);
        if (!lavals || !la) {
            if (res) {
                *res = LDAP_NO_MEMORY;
            }
            if (la) {
                objunref(la);
            }
            if (lavals) {
                objunref(lavals);
            }
            objunref(bl);
            ldap_value_free_len(vals);
            if (ber) {
                ber_free(ber, 0);
            }
            return NULL;
        }
        la->vals = lavals;
        la->name = attr;
        la->count = cnt;
        for(; *tmp; tmp++) {
            struct berval *bval = *tmp;
            *lavals = lav = objalloc(sizeof(*lav), free_attrval);
            lavals++;
            eval = ldap_encattr(bval, b64enc, &type);
            if (!eval || !lav) {
                if (res) {
                    *res = LDAP_NO_MEMORY;
                }
                objunref(bl);
                objunref(la);
                if (eval) {
                    objunref(eval);
                }
                ldap_value_free_len(vals);
                if (ber) {
                    ber_free(ber, 0);
                }
                return NULL;
            }
            lav->len = bval->bv_len;
            lav->buffer = eval;
            lav->type = type;
        }
        *lavals = NULL;
        ldap_value_free_len(vals);
        addtobucket(bl, la);
        objunref(la);
    }
    if (ber) {
        ber_free(ber, 0);
    }
    return bl;
}
struct ldap_results* dts_ldapsearch (struct ldap_conn * ld, const char * base, int scope, const char * filter, char * attrs[], int b64enc, int * err) read
Definition at line 527 of file openldap.c.
References addtobucket(), ldap_results::count, create_bucketlist(), ldap_results::entries, ldap_results::first_entry, free_result(), ldap_conn::ldap, ldap_count(), ldap_getent(), ldap_conn::limit, ldap_entry::next, objalloc(), objlock(), objref(), objunlock(), objunref(), ldap_entry::prev, ldap_conn::sctrlsp, searchresults_hash(), and ldap_conn::timelim.
{
    struct timeval timeout = {0,0};
    struct ldap_results *results;
    struct ldap_entry *lent, *prev = NULL;
    LDAPMessage *result, *message = NULL;
    int res = LDAP_SUCCESS;
    if (!objref(ld)) {
        if (err) {
            *err = LDAP_UNAVAILABLE;
        }
        if (attrs) {
            free(attrs);
        }
        return NULL;
    }
    if ((results = objalloc(sizeof(*results), free_result))) {
        results->entries = create_bucketlist(4, searchresults_hash);
    }
    timeout.tv_sec = ld->timelim;
    timeout.tv_usec = 0;
    objlock(ld);
    if (!results || !results->entries ||
        (res = ldap_search_ext_s(ld->ldap, base, scope, filter, attrs, 0, ld->sctrlsp, NULL, &timeout, ld->limit, &result))) {
        objunlock(ld);
        objunref(ld);
        objunref(results);
        ldap_msgfree(result);
        if (err) {
            *err = (!results || !results->entries) ? LDAP_NO_MEMORY : res;
        }
        if (attrs) {
            free(attrs);
        }
        return NULL;
    }
    objunlock(ld);
    if (attrs) {
        free(attrs);
    }
    if ((results->count = ldap_count(ld->ldap, result, err)) < 0) {
        objunref(ld);
        objunref(results);
        ldap_msgfree(result);
        return NULL;
    }
    while((lent = ldap_getent(ld->ldap, &message, result, b64enc, err))) {
        if (!results->first_entry) {
            results->first_entry = lent;
        }
        if (!addtobucket(results->entries, lent)) {
            res = LDAP_NO_MEMORY;
            objunref(lent);
            break;
        }
        lent->next = NULL;
        if (prev) {
            prev->next = lent;
            lent->prev = prev;
        } else {
            lent->prev = NULL;
        }
        prev = lent;
        objunref(lent);
    }
    ldap_msgfree(result);
    if (err) {
        *err = res;
    }
    if (res) {
        objunref(results);
        results = NULL;
    }
    objunref(ld);
    return results;
}
int dts_sasl_interact (LDAP * ld, unsigned flags, void * defaults, void * in)
void free_add (void * data)
Definition at line 115 of file openldap.c.
References ldap_add::bl, ldap_add::dn, and objunref().
{
    struct ldap_add *lmod = data;
    if (lmod->dn) {
        free((void*)lmod->dn);
    }
    if (lmod->bl) {
        objunref(lmod->bl);
    }
}
void free_attr (void * data)
Definition at line 221 of file openldap.c.
References ldap_attr::name, ldap_attr::next, objunref(), ldap_attr::prev, and ldap_attr::vals.
{
    struct ldap_attr *la = data;
    if (la->next) {
        la->next->prev = la->prev;
    }
    if (la->prev) {
        la->prev->next = la->next;
    }
    ldap_memfree((char*)la->name);
    if (la->vals) {
        objunref(la->vals);
    }
}
void free_attrval (void * data)
Definition at line 242 of file openldap.c.
References ldap_attrval::buffer, and objunref().
{
    struct ldap_attrval *av = data;
    if (av->buffer) {
        objunref(av->buffer);
    }
}
void free_attrvalarr (void * data)
Definition at line 235 of file openldap.c.
References objunref().
{
    struct ldap_attrval **av = data;
    for(;*av;av++) {
        objunref(*av);
    }
}
void free_entarr (void * data)
Definition at line 249 of file openldap.c.
References objunref().
{
    struct ldap_entry **entarr = data;
    for(;*entarr;entarr++) {
        objunref(*entarr);
    }
}
void free_entry (void * data)
Definition at line 172 of file openldap.c.
References ldap_entry::attrs, ldap_entry::dn, ldap_entry::dnufn, ldap_entry::first_attr, ldap_attr::next, ldap_entry::next, objunref(), ldap_entry::prev, and ldap_entry::rdn.
{
    struct ldap_entry *ent = data;
    struct ldap_attr *la;
    if (ent->prev) {
        ent->prev->next = ent->next;
    }
    if (ent->next) {
        ent->next->prev = ent->prev;
    }
    if (ent->dn) {
        ldap_memfree((void*)ent->dn);
    }
    if (ent->rdn) {
        objunref(ent->rdn);
    }
    if (ent->dnufn) {
        free((void*)ent->dnufn);
    }
    if (ent->attrs) {
        objunref(ent->attrs);
    }
    if (ent->first_attr) {
        for(la = ent->first_attr; la; la = la->next) {
            objunref(la);
        }
    }
}
void free_ldapconn (void * data)
Definition at line 147 of file openldap.c.
References ldap_conn::ldap, objunref(), ldap_conn::sasl, ldap_conn::sctrlsp, ldap_conn::simple, and ldap_conn::uri.
{
    struct ldap_conn *ld = data;
    if (ld->uri) {
        free(ld->uri);
    }
    if (ld->ldap) {
        ldap_unbind_ext_s(ld->ldap, ld->sctrlsp, NULL);
    }
    if (ld->sasl) {
        objunref(ld->sasl);
    }
    if (ld->simple) {
        objunref(ld->simple);
    }
}
void free_modify (void * data)
Definition at line 101 of file openldap.c.
References ldap_modify::bl, ldap_modify::dn, and objunref().
{
    struct ldap_modify *lmod = data;
    int cnt;
    if (lmod->dn) {
        free((void*)lmod->dn);
    }
    for(cnt=0; cnt < 3;cnt++) {
        if (lmod->bl[cnt]) {
            objunref(lmod->bl[cnt]);
        }
    }
}
void free_modreq (void * data)
Definition at line 89 of file openldap.c.
References ldap_modreq::attr, ldap_modreq::first, ldap_modval::next, and objunref().
{
    struct ldap_modreq *modr = data;
    struct ldap_modval *modv;
    if (modr->attr) {
        free((void*)modr->attr);
    }
    for(modv = modr->first; modv; modv = modv->next) {
        objunref(modv);
    }
}
void free_modval (void * data)
Definition at line 81 of file openldap.c.
References ldap_modval::value.
{
    struct ldap_modval *modv = data;
    if (modv->value) {
        free((void*)modv->value);
    }
}
void free_rdn (void * data)
Definition at line 210 of file openldap.c.
References ldap_rdn::name, objunref(), and ldap_rdn::value.
{
    struct ldap_rdn *rdn = data;
    if (rdn->name) {
        objunref((void*)rdn->name);
    }
    if (rdn->value) {
        objunref((void*)rdn->value);
    }
}
void free_rdnarr (void * data)
Definition at line 202 of file openldap.c.
References objunref().
{
    struct ldap_rdn **rdn = data;
    for(; *rdn; rdn++) {
        objunref(*rdn);
    }
}
void free_result (void * data)
Definition at line 165 of file openldap.c.
References ldap_results::entries, and objunref().
{
    struct ldap_results *res = data;
    if (res->entries) {
        objunref(res->entries);
    }
}
void free_sasl (void * data)
Definition at line 127 of file openldap.c.
References sasl_defaults::authcid, sasl_defaults::authzid, sasl_defaults::mech, sasl_defaults::passwd, and sasl_defaults::realm.
{
    struct sasl_defaults *sasl = data;
    if (sasl->mech) {
        free((void*)sasl->mech);
    }
    if (sasl->realm) {
        free((void*)sasl->realm);
    }
    if (sasl->authcid) {
        free((void*)sasl->authcid);
    }
    if (sasl->passwd) {
        free((void*)sasl->passwd);
    }
    if (sasl->authzid) {
        free((void*)sasl->authzid);
    }
}
void free_simple (void * data)
Definition at line 66 of file openldap.c.
References ldap_simple::cred, and ldap_simple::dn.
{
    struct ldap_simple *simple = data;
    struct berval *bv = simple->cred;
    if (bv && bv->bv_val) {
        free(bv->bv_val);
    }
    if (bv) {
        free(bv);
    }
    if (simple->dn) {
        free((void*)simple->dn);
    }
}
struct ldap_modreq* getaddreq (struct ldap_add * ladd, const char * attr) read
Definition at line 1405 of file openldap.c.
References ldap_add::bl, bucket_list_find_key(), and new_modreq().
{
    struct bucket_list *bl = ladd->bl;
    struct ldap_modreq *modr = NULL;
    if (bl && !(modr = bucket_list_find_key(bl, attr))) {
        if (!(modr = new_modreq(bl, attr))) {
            return NULL;
        }
    }
    return modr;
}
struct ldap_modreq* getmodreq (struct ldap_modify * lmod, const char * attr, int modop) read
Definition at line 1130 of file openldap.c.
References ldap_modify::bl, bucket_list_find_key(), and new_modreq().
{
    struct bucket_list *bl = NULL;
    struct ldap_modreq *modr = NULL;
    switch (modop) {
        case LDAP_MOD_REPLACE:
            bl = lmod->bl[0];
            break;
        case LDAP_MOD_DELETE:
            bl = lmod->bl[1];
            break;
        case LDAP_MOD_ADD:
            bl = lmod->bl[2];
            break;
    }
    if (bl && !(modr = bucket_list_find_key(bl, attr))) {
        if (!(modr = new_modreq(bl, attr))) {
            return NULL;
        }
    }
    return modr;
}
int ldap_add_attr (struct ldap_add * ladd, const char * attr, ...)
Definition at line 1417 of file openldap.c.
References add_modifyval(), getaddreq(), and objunref().
{
    va_list a_list;
    char *val;
    struct ldap_modreq *modr;
    if (!(modr = getaddreq(ladd, attr))) {
        return 1;
    }
    va_start(a_list, attr);
    while((val = va_arg(a_list, void*))) {
        if (add_modifyval(modr, val)) {
            objunref(modr);
            return(1);
        }
    }
    objunref(modr);
    va_end(a_list);
    return 0;
}
struct ldap_add* ldap_addinit (const char * dn) read
Definition at line 1384 of file openldap.c.
References ALLOC_CONST, ldap_add::bl, create_bucketlist(), ldap_add::dn, free_add(), modify_hash(), objalloc(), and objunref().
{
    struct ldap_add *mod;
    if (!(mod = objalloc(sizeof(*mod), free_add))) {
        return NULL;
    }
    ALLOC_CONST(mod->dn, dn);
    if (!mod->dn) {
        objunref(mod);
        return NULL;
    }
    if (!(mod->bl = create_bucketlist(4, modify_hash))) {
        objunref(mod);
        return NULL;
    }
    return mod;
}
struct berval** ldap_attrvals (LDAP * ld, LDAPMessage * message, char * attr, int * cnt, int * err) read
Definition at line 786 of file openldap.c.
References objlock(), and objunlock().
{
    struct berval **vals = NULL;
    objlock(ld);
    vals = ldap_get_values_len(ld, message, attr);
    objunlock(ld);
    if (cnt) {
        *cnt = ldap_count_values_len(vals);
    }
    if (!err) {
        return vals;
    }
    if (!vals) {
        ldap_get_option(ld, LDAP_OPT_RESULT_CODE, err);
    } else {
        *err = LDAP_SUCCESS;
    }
    return vals;
}
int ldap_count (LDAP * ld, LDAPMessage * message, int * err)
int ldap_doadd (struct ldap_conn * ld, struct ldap_add * ladd)
Definition at line 1439 of file openldap.c.
References ldap_add::bl, bucket_list_cnt(), ldap_add::dn, init_bucket_loop(), ldap_conn::ldap, ldap_reqtoarr(), next_bucket_loop(), objlock(), objunlock(), objunref(), ldap_conn::sctrlsp, and stop_bucket_loop().
{
    struct bucket_loop *bloop;
    struct ldap_modreq *modr;
    LDAPMod **modarr, **tmp, *item;
    int tot=0, res;
    tot = bucket_list_cnt(ladd->bl);
    tmp = modarr = calloc(sizeof(void*), (tot+1));
    bloop = init_bucket_loop(ladd->bl);
    while(bloop && ((modr = next_bucket_loop(bloop)))) {
        if (!(item = ldap_reqtoarr(modr, -1))) {
            ldap_mods_free(modarr, 1);
            return LDAP_NO_MEMORY;
        }
        *tmp = item;
        tmp++;
        objunref(modr);
    }
    stop_bucket_loop(bloop);
    *tmp = NULL;
    objlock(ld);
    res = ldap_modify_ext_s(ld->ldap, ladd->dn, modarr, ld->sctrlsp, NULL);
    objunlock(ld);
    ldap_mods_free(modarr, 1);
    return res;
}
char* ldap_encattr (void * attrval, int b64enc, enum ldap_attrtype * type)
Definition at line 759 of file openldap.c.
References b64enc_buf(), LDAP_ATTRTYPE_B64, LDAP_ATTRTYPE_CHAR, LDAP_ATTRTYPE_OCTET, objalloc(), and objsize().
{
    struct berval *val = attrval;
    char *aval = NULL;
    int len, pos, atype;
    len = val->bv_len;
    for(pos=0; isprint(val->bv_val[pos]); pos++);
    if (pos == len) {
        aval = objalloc(val->bv_len+1, NULL);
        strncpy(aval, val->bv_val, objsize(aval));
        atype = LDAP_ATTRTYPE_CHAR;
    } else if (b64enc) {
        aval = b64enc_buf(val->bv_val, val->bv_len, 0);
        atype = LDAP_ATTRTYPE_B64;
    } else {
        aval = objalloc(val->bv_len, NULL);
        memcpy(aval, val->bv_val, objsize(aval));
        atype = LDAP_ATTRTYPE_OCTET;
    }
    if (type) {
        *type = atype;
    }
    return aval;
}
char* ldap_getattribute (LDAP * ld, LDAPMessage * message, BerElement ** berptr, int * err)
Definition at line 734 of file openldap.c.
References objlock(), and objunlock().
{
    BerElement *ber = *berptr;
    char *attr = NULL;
    objlock(ld);
    if (ber) {
        attr = ldap_next_attribute(ld, message, ber);
    } else {
        attr = ldap_first_attribute(ld, message, berptr);
    }
    if (!err) {
        objunlock(ld);
        return attr;
    }
    if (!attr) {
        ldap_get_option(ld, LDAP_OPT_RESULT_CODE, err);
    } else {
        *err = LDAP_SUCCESS;
    }
    objunlock(ld);
    return attr;
}
char* ldap_getdn (LDAP * ld, LDAPMessage * message, int * err)
Definition at line 712 of file openldap.c.
References objlock(), and objunlock().
{
    char *dn;
    objlock(ld);
    dn = ldap_get_dn(ld, message);
    objunlock(ld);
    if (!err) {
        return dn;
    }
    if (!dn) {
        objlock(ld);
        ldap_get_option(ld, LDAP_OPT_RESULT_CODE, err);
        objunlock(ld);
    } else {
        *err = LDAP_SUCCESS;
    }
    return dn;
}
struct ldap_entry* ldap_getent (LDAP * ld, LDAPMessage ** msgptr, LDAPMessage * result, int b64enc, int * err) read
int ldap_rebind_proc (LDAP * ld, LDAP_CONST char * url, ber_tag_t request, ber_int_t msgid, void * params)
Definition at line 270 of file openldap.c.
References ldap_simple::cred, ldap_simple::dn, dts_sasl_interact(), ldap_conn::ldap, sasl_defaults::mech, objref(), objunref(), ldap_conn::sasl, ldap_conn::sctrlsp, and ldap_conn::simple.
{
    struct ldap_conn *ldap = params;
    int res = LDAP_UNAVAILABLE;
    if (!objref(ldap)) {
        return LDAP_UNAVAILABLE;
    }
    if (ldap->sasl) {
        int sasl_flags = LDAP_SASL_AUTOMATIC | LDAP_SASL_QUIET;
        struct sasl_defaults *sasl = ldap->sasl;
        res = ldap_sasl_interactive_bind_s(ld, NULL, sasl->mech, ldap->sctrlsp , NULL, sasl_flags, dts_sasl_interact, sasl);
    } else if (ldap->simple) {
        struct ldap_simple *simple = ldap->simple;
        res = ldap_sasl_bind_s(ld, simple->dn, LDAP_SASL_SIMPLE, simple->cred, ldap->sctrlsp, NULL, NULL);
    }
    objunref(ldap);
    return res;
}
LDAPMod* ldap_reqtoarr (struct ldap_modreq * modr, int type)
Definition at line 1245 of file openldap.c.
References ldap_modreq::attr, ldap_modreq::cnt, ldap_modreq::first, ldap_modval::next, and ldap_modval::value.
{
    LDAPMod *modi;
    const char **mval;
    struct ldap_modval *modv;
    if (!(modi = calloc(sizeof(LDAPMod), 1))) {
        return NULL;
    }
    if (!(modi->mod_values = calloc(sizeof(void*), modr->cnt+1))) {
        free(modi);
        return NULL;
    }
    switch (type) {
        case 0: modi->mod_op = LDAP_MOD_REPLACE;
            break;
        case 1: modi->mod_op = LDAP_MOD_DELETE;
            break;
        case 2: modi->mod_op = LDAP_MOD_ADD;
            break;
        default: modi->mod_op = 0;
            break;
    }
    if (!(modi->mod_type = strdup(modr->attr))) {
        free(modi);
        return NULL;
    }
    mval = (const char**)modi->mod_values;
    for(modv = modr->first; modv; modv=modv->next) {
        if (!(*mval = strdup(modv->value))) {
            ldap_mods_free(&modi, 0);
            return NULL;
        }
        mval++;
    }
    *mval = NULL;
    return modi;
}
int ldapattr_hash (const void * data, int key)
Definition at line 810 of file openldap.c.
References jenhash, and ldap_attr::name.
Referenced by attr2bl().
{
        int ret;
        const struct ldap_attr *la = data;
        const char* hashkey = (key) ? data : la->name;
        if (hashkey) {
                ret = jenhash(hashkey, strlen(hashkey), 0);
        } else {
                ret = jenhash(la, sizeof(la), 0);
        }
        return(ret);
}
int modify_hash (const void * data, int key)
Definition at line 257 of file openldap.c.
References ldap_modreq::attr, and jenhash.
Referenced by ldap_addinit(), and ldap_modifyinit().
{
        int ret;
        const struct ldap_modreq *modr = data;
        const char* hashkey = (key) ? data : modr->attr;
        if (hashkey) {
                ret = jenhash(hashkey, strlen(hashkey), 0);
        } else {
                ret = jenhash(modr, sizeof(modr), 0);
        }
        return(ret);
}
struct ldap_modreq* new_modreq (struct bucket_list * modtype, const char * attr) read
Definition at line 1115 of file openldap.c.
References addtobucket(), ALLOC_CONST, ldap_modreq::attr, free_modreq(), objalloc(), and objunref().
{
    struct ldap_modreq *modr;
    if (!(modr = objalloc(sizeof(*modr), free_modreq))) {
        return NULL;
    }
    ALLOC_CONST(modr->attr, attr);
    if (!modr->attr || !addtobucket(modtype, modr)) {
        objunref(modr);
        modr = NULL;
    }
    return modr;
}
int searchresults_hash (const void * data, int key)
Definition at line 514 of file openldap.c.
References ldap_entry::dn, and jenhash.
Referenced by dts_ldapsearch().
{
        int ret;
        const struct ldap_entry *ent = data;
        const char* hashkey = (key) ? data : ent->dn;
        if (hashkey) {
                ret = jenhash(hashkey, strlen(hashkey), 0);
        } else {
                ret = jenhash(ent, sizeof(ent), 0);
        }
        return(ret);
}