DTS Application Library: /usr/src/dtsapplib/dtsapplib-0.1/src/include/dtsapp.h File Reference
dtsapp.h File Reference
#include <stdint.h>
#include <signal.h>
#include <sys/socket.h>
#include <arpa/inet.h>
Data Structures
union sockstruct
Socket union describing all address types.
struct fwsocket
Socket data structure.
struct config_entry
struct zobj
Zlib buffer used for compression and decompression.
struct framework_core
Application framework data.
struct xml_attr
struct xml_node
struct ldap_rdn
struct ldap_attrval
struct ldap_attr
struct ldap_entry
struct ldap_results
Macros
#define RAD_AUTH_HDR_LEN 20
#define RAD_AUTH_PACKET_LEN 4096
#define RAD_AUTH_TOKEN_LEN 16
#define RAD_MAX_PASS_LEN 128
#define RAD_ATTR_USER_NAME 1 /*string*/
#define RAD_ATTR_USER_PASSWORD 2 /*passwd*/
#define RAD_ATTR_NAS_IP_ADDR 4 /*ip*/
#define RAD_ATTR_NAS_PORT 5 /*int*/
#define RAD_ATTR_SERVICE_TYPE 6 /*int*/
#define RAD_ATTR_ACCTID 44
#define RAD_ATTR_PORT_TYPE 61 /*int*/
#define RAD_ATTR_EAP 79 /*oct*/
#define RAD_ATTR_MESSAGE 80 /*oct*/
#define JHASH_INITVAL 0xdeadbeef
#define jenhash(key, length, initval) hashlittle(key, length, (initval) ? initval : JHASH_INITVAL);
#define clearflag(obj, flag)
#define setflag(obj, flag)
#define testflag(obj, flag) (objlock(obj) | (obj->flags & flag) | objunlock(obj))
#define FRAMEWORK_MAIN(progname, name, email, www, year, runfile, sighfunc)
#define ALLOC_CONST(const_var, val)
Typedefs
typedef struct ssldata ssldata
typedef struct natmap natmap
typedef struct radius_packet radius_packet
typedef struct nfq_queue nfq_queue
typedef struct nfq_data nfq_data
typedef struct nfct_struct nfct_struct
typedef struct nfqnl_msg_packet_hdr nfqnl_msg_packet_hdr
typedef void(* radius_cb)(struct radius_packet *, void *)
typedef void *(* threadcleanup)(void *)
typedef void *(* threadfunc)(void **)
typedef void(* syssighandler)(int, siginfo_t *, void *)
typedef int(* threadsighandler)(int, void *)
typedef int(* frameworkfunc)(int, char **)
typedef int(* blisthash)(const void *, int)
typedef void(* objdestroy)(void *)
typedef void(* socketrecv)(struct fwsocket *, void *)
typedef void(* blist_cb)(void *, void *)
typedef void(* config_filecb)(struct bucket_list *, const char *, const char *)
typedef void(* config_catcb)(struct bucket_list *, const char *)
typedef void(* config_entrycb)(const char *, const char *)
typedef uint32_t(* nfqueue_cb)(struct nfq_data *, struct nfqnl_msg_packet_hdr *, char *, uint32_t, void *, uint32_t *, void **)
typedef struct xml_node xml_node
typedef struct xml_search xml_search
typedef struct xml_doc xml_doc
typedef struct xslt_doc xslt_doc
typedef struct ldap_conn ldap_conn
typedef struct ldap_modify ldap_modify
typedef struct ldap_add ldap_add
Enumerations
enum sock_flags {
SOCK_FLAG_BIND = 1 << 0, SOCK_FLAG_CLOSE = 1 << 1, SOCK_FLAG_SSL = 1 << 2, SOCK_FLAG_BIND = 1 << 0,
SOCK_FLAG_CLOSE = 1 << 1
}
enum RADIUS_CODE {
RAD_CODE_AUTHREQUEST = 1, RAD_CODE_AUTHACCEPT = 2, RAD_CODE_AUTHREJECT = 3, RAD_CODE_ACCTREQUEST = 4,
RAD_CODE_ACCTRESPONSE = 5, RAD_CODE_AUTHCHALLENGE = 11, RAD_CODE_AUTHREQUEST = 1, RAD_CODE_AUTHACCEPT = 2,
RAD_CODE_AUTHREJECT = 3, RAD_CODE_ACCTREQUEST = 4, RAD_CODE_ACCTRESPONSE = 5, RAD_CODE_AUTHCHALLENGE = 11
}
enum ldap_starttls {
LDAP_STARTTLS_NONE, LDAP_STARTTLS_ATTEMPT, LDAP_STARTTLS_ENFORCE, LDAP_STARTTLS_NONE,
LDAP_STARTTLS_ATTEMPT, LDAP_STARTTLS_ENFORCE
}
enum ldap_attrtype {
LDAP_ATTRTYPE_CHAR, LDAP_ATTRTYPE_B64, LDAP_ATTRTYPE_OCTET, LDAP_ATTRTYPE_CHAR,
LDAP_ATTRTYPE_B64, LDAP_ATTRTYPE_OCTET
}
Functions
int framework_init (int argc, char *argv[], frameworkfunc callback, struct framework_core *core_info)
struct framework_core * framework_mkcore (char *progname, char *name, char *email, char *web, int year, char *runfile, syssighandler sigfunc)
struct thread_pvt * framework_mkthread (threadfunc, threadcleanup, threadsighandler, void *data)
void framework_shutdown (void)
void framework_unixsocket (char *sock, int protocol, int mask, threadfunc connectfunc, threadcleanup cleanup)
Create and run UNIX socket thread.
int framework_threadok (void *data)
int startthreads (void)
Initialise the threadlist and start manager thread.
void stopthreads (void)
int objlock (void *data)
Lock the reference.
int objtrylock (void *data)
Try lock a reference.
int objunlock (void *data)
Unlock a reference.
int objcnt (void *data)
Return current reference count.
int objsize (void *data)
Size requested for data.
int objunref (void *data)
Drop reference held.
int objref (void *data)
Reference a object.
void * objalloc (int size, objdestroy)
Allocate a referenced lockable object.
void * create_bucketlist (int bitmask, blisthash hash_function)
Create a hashed bucket list.
int addtobucket (struct bucket_list *blist, void *data)
Add a reference to the bucketlist.
void remove_bucket_item (struct bucket_list *blist, void *data)
Remove and unreference a item from the list.
int bucket_list_cnt (struct bucket_list *blist)
Return number of items in the list.
void * bucket_list_find_key (struct bucket_list *list, const void *key)
Find and return a reference to a item matching supplied key.
void bucketlist_callback (struct bucket_list *blist, blist_cb callback, void *data2)
Run a callback function on all items in the list.
struct bucket_loop * init_bucket_loop (struct bucket_list *blist)
Create a bucket list iterator to safely iterate the list.
void stop_bucket_loop (struct bucket_loop *bloop)
void * next_bucket_loop (struct bucket_loop *bloop)
Return a reference to the next item in the list this could be the first item.
void remove_bucket_loop (struct bucket_loop *bloop)
Safely remove a item from a list while iterating in a loop.
uint32_t hashlittle (const void *key, size_t length, uint32_t initval)
hash a variable-length key into a 32-bit value (Little Endian)
void seedrand (void)
Seed openssl random number generator.
int genrand (void *buf, int len)
Generate random sequence.
void sha512sum2 (unsigned char *buff, const void *data, unsigned long len, const void *data2, unsigned long len2)
Calculate the SHA2-512 hash accross 2 data chunks.
void sha512sum (unsigned char *buff, const void *data, unsigned long len)
Calculate the SHA2-512 hash.
void sha256sum2 (unsigned char *buff, const void *data, unsigned long len, const void *data2, unsigned long len2)
Calculate the SHA2-256 hash accross 2 data chunks.
void sha256sum (unsigned char *buff, const void *data, unsigned long len)
Calculate the SHA2-256 hash.
void sha1sum2 (unsigned char *buff, const void *data, unsigned long len, const void *data2, unsigned long len2)
Calculate the SHA1 hash accross 2 data chunks.
void sha1sum (unsigned char *buff, const void *data, unsigned long len)
Calculate the SHA1 hash.
void md5sum2 (unsigned char *buff, const void *data, unsigned long len, const void *data2, unsigned long len2)
Calculate the MD5 hash accross 2 data chunks.
void md5sum (unsigned char *buff, const void *data, unsigned long len)
Calculate the MD5 hash.
int sha512cmp (unsigned char *digest1, unsigned char *digest2)
Compare two SHA2-512 hashes.
int sha256cmp (unsigned char *digest1, unsigned char *digest2)
Compare two SHA2-256 hashes.
int sha1cmp (unsigned char *digest1, unsigned char *digest2)
Compare two SHA1 hashes.
int md5cmp (unsigned char *digest1, unsigned char *digest2)
Compare two md5 hashes.
void sha512hmac (unsigned char *buff, const void *data, unsigned long len, const void *key, unsigned long klen)
Hash Message Authentication Codes (HMAC) SHA2-512.
void sha256hmac (unsigned char *buff, const void *data, unsigned long len, const void *key, unsigned long klen)
Hash Message Authentication Codes (HMAC) SHA2-256.
void sha1hmac (unsigned char *buff, const void *data, unsigned long len, const void *key, unsigned long klen)
Hash Message Authentication Codes (HMAC) SHA1.
void md5hmac (unsigned char *buff, const void *data, unsigned long len, const void *key, unsigned long klen)
Hash Message Authentication Codes (HMAC) MD5.
int strlenzero (const char *str)
Check if a string is zero length.
char * ltrim (char *str)
Trim white space at the begining of a string.
char * rtrim (const char *str)
Trim white space at the end of a string.
char * trim (const char *str)
Trim whitesapce from the beggining and end of a string.
uint64_t tvtontp64 (struct timeval *tv)
Convert a timeval struct to 64bit NTP time.
uint16_t checksum (const void *data, int len)
Obtain the checksum for a buffer.
uint16_t checksum_add (const uint16_t checksum, const void *data, int len)
Obtain the checksum for a buffer adding a checksum.
uint16_t verifysum (const void *data, int len, const uint16_t check)
Verify a checksum.
struct zobj * zcompress (uint8_t *buff, uint16_t len, uint8_t level)
Allocate a buffer and return it with compressed data.
void zuncompress (struct zobj *buff, uint8_t *obuff)
Uncompress zobj buffer to buffer.
void touch (const char *filename, uid_t user, gid_t group)
Create a file and set user and group.
char * b64enc (const char *message, int nonl)
Base 64 encode a string.
char * b64enc_buf (const char *message, uint32_t len, int nonl)
Base 64 encode a buffer.
struct fwsocket * make_socket (int family, int type, int proto, void *ssl)
Allocate a socket structure and return reference.
struct fwsocket * sockconnect (int family, int stype, int proto, const char *ipaddr, const char *port, void *ssl)
Generic client socket.
struct fwsocket * udpconnect (const char *ipaddr, const char *port, void *ssl)
UDP Socket client.
struct fwsocket * tcpconnect (const char *ipaddr, const char *port, void *ssl)
TCP Socket client.
struct fwsocket * sockbind (int family, int stype, int proto, const char *ipaddr, const char *port, void *ssl, int backlog)
Generic server socket.
struct fwsocket * udpbind (const char *ipaddr, const char *port, void *ssl)
UDP server socket.
struct fwsocket * tcpbind (const char *ipaddr, const char *port, void *ssl, int backlog)
Generic server socket.
void close_socket (struct fwsocket *sock)
Mark the socket for closure and release the reference.
void socketclient (struct fwsocket *sock, void *data, socketrecv read, threadcleanup cleanup)
Create a server thread with a socket that has been created with sockbind udpbind or tcpbind.
void socketserver (struct fwsocket *sock, socketrecv connectfunc, socketrecv acceptfunc, threadcleanup cleanup, void *data)
Create a server thread with a socket that has been created with sockbind udpbind or tcpbind.
int checkipv6mask (const char *ipaddr, const char *network, uint8_t bits)
void ipv4tcpchecksum (uint8_t *pkt)
void ipv4udpchecksum (uint8_t *pkt)
void icmpchecksum (uint8_t *pkt)
void ipv4checksum (uint8_t *pkt)
int packetchecksumv4 (uint8_t *pkt)
int packetchecksumv6 (uint8_t *pkt)
int packetchecksum (uint8_t *pkt)
void rfc6296_map (struct natmap *map, struct in6_addr *ipaddr, int out)
int rfc6296_map_add (char *intaddr, char *extaddr)
struct nfq_queue * nfqueue_attach (uint16_t pf, uint16_t num, uint8_t mode, uint32_t range, nfqueue_cb cb, void *data)
uint16_t snprintf_pkt (struct nfq_data *tb, struct nfqnl_msg_packet_hdr *ph, uint8_t *pkt, char *buff, uint16_t len)
struct nf_conntrack * nf_ctrack_buildct (uint8_t *pkt)
uint8_t nf_ctrack_delete (uint8_t *pkt)
uint8_t nf_ctrack_nat (uint8_t *pkt, uint32_t addr, uint16_t port, uint8_t dnat)
void nf_ctrack_dump (void)
struct nfct_struct * nf_ctrack_trace (void)
void nf_ctrack_endtrace (struct nfct_struct *nfct)
uint8_t nf_ctrack_init (void)
void nf_ctrack_close (void)
int delete_kernvlan (char *ifname, int vid)
int create_kernvlan (char *ifname, unsigned short vid)
int delete_kernmac (char *macdev)
int create_kernmac (char *ifname, char *macdev, unsigned char *mac)
int interface_bind (char *iface, int protocol, int flags)
void randhwaddr (unsigned char *addr)
int create_tun (const char *ifname, const unsigned char *hwaddr, int flags)
int ifrename (const char *oldname, const char *newname)
int ifdown (const char *ifname, int flags)
int ifup (const char *ifname, int flags)
int ifhwaddr (const char *ifname, unsigned char *hwaddr)
int set_interface_flags (int ifindex, int set, int clear)
int get_iface_index (const char *ifname)
int set_interface_addr (int ifindex, const unsigned char *hwaddr)
int set_interface_name (int ifindex, const char *name)
int set_interface_ipaddr (char *ifname, char *ipaddr)
int get_ip6_addrprefix (const char *iface, unsigned char *prefix)
int eui48to64 (unsigned char *mac48, unsigned char *eui64)
void closenetlink (void)
unsigned char * addradattr (struct radius_packet *packet, char type, unsigned char *val, char len)
void addradattrint (struct radius_packet *packet, char type, unsigned int val)
void addradattrip (struct radius_packet *packet, char type, char *ipaddr)
void addradattrstr (struct radius_packet *packet, char type, char *str)
struct radius_packet * new_radpacket (unsigned char code, unsigned char id)
int send_radpacket (struct radius_packet *packet, const char *userpass, radius_cb read_cb, void *cb_data)
void add_radserver (const char *ipaddr, const char *auth, const char *acct, const char *secret, int timeout)
unsigned char * radius_attr_first (struct radius_packet *packet)
unsigned char * radius_attr_next (struct radius_packet *packet, unsigned char *attr)
void sslstartup (void)
Initialise SSL support this should be called at startup.
void * tlsv1_init (const char *cacert, const char *cert, const char *key, int verify)
Create a SSL structure for TLSv1.
void * sslv2_init (const char *cacert, const char *cert, const char *key, int verify)
Create a SSL structure for SSLv2 (If available)
void * sslv3_init (const char *cacert, const char *cert, const char *key, int verify)
Create a SSL structure for SSLv3.
void * dtlsv1_init (const char *cacert, const char *cert, const char *key, int verify)
Create a SSL structure for DTLSv1.
int socketread (struct fwsocket *sock, void *buf, int num)
Read from a socket into a buffer.
int socketwrite (struct fwsocket *sock, const void *buf, int num)
Write a buffer to a socket.
int socketread_d (struct fwsocket *sock, void *buf, int num, union sockstruct *addr)
Read from a socket into a buffer.
int socketwrite_d (struct fwsocket *sock, const void *buf, int num, union sockstruct *addr)
Write a buffer to a socket.
void ssl_shutdown (void *ssl)
void tlsaccept (struct fwsocket *sock, struct ssldata *orig)
Create SSL session for new connection.
struct fwsocket * dtls_listenssl (struct fwsocket *sock)
Implementation of "listen" for DTLSv1.
void startsslclient (struct fwsocket *sock)
Start SSL on a client socket.
void initconfigfiles (void)
void unrefconfigfiles (void)
int process_config (const char *configname, const char *configfile)
struct bucket_loop * get_category_loop (const char *configname)
struct bucket_list * get_category_next (struct bucket_loop *cloop, char *name, int len)
struct bucket_list * get_config_category (const char *configname, const char *category)
struct config_entry * get_config_entry (struct bucket_list *categories, const char *item)
void config_file_callback (config_filecb file_cb)
void config_cat_callback (struct bucket_list *categories, config_catcb entry_cb)
void config_entry_callback (struct bucket_list *entries, config_entrycb entry_cb)
struct xml_doc * xml_loaddoc (const char *docfile, int validate)
struct xml_node * xml_getfirstnode (struct xml_search *xpsearch, void **iter)
struct xml_node * xml_getnextnode (void *iter)
struct bucket_list * xml_getnodes (struct xml_search *xpsearch)
struct xml_search * xml_xpath (struct xml_doc *xmldata, const char *xpath, const char *attrkey)
int xml_nodecount (struct xml_search *xsearch)
struct xml_node * xml_getnode (struct xml_search *xsearch, const char *key)
const char * xml_getattr (struct xml_node *xnode, const char *attr)
void xml_modify (struct xml_doc *xmldoc, struct xml_node *xnode, const char *value)
void xml_setattr (struct xml_doc *xmldoc, struct xml_node *xnode, const char *name, const char *value)
struct xml_node * xml_addnode (struct xml_doc *xmldoc, const char *xpath, const char *name, const char *value, const char *attrkey, const char *keyval)
void xml_delete (struct xml_node *xnode)
char * xml_getbuffer (void *buffer)
void * xml_doctobuffer (struct xml_doc *xmldoc)
const char * xml_getrootname (struct xml_doc *xmldoc)
struct xml_node * xml_getrootnode (struct xml_doc *xmldoc)
void xml_savefile (struct xml_doc *xmldoc, const char *file, int format, int compress)
void xml_createpath (struct xml_doc *xmldoc, const char *xpath)
void xml_init ()
void xml_close ()
struct xslt_doc * xslt_open (const char *xsltfile)
void xslt_addparam (struct xslt_doc *xsltdoc, const char *param, const char *value)
void xslt_apply (struct xml_doc *xmldoc, struct xslt_doc *xsltdoc, const char *filename, int comp)
void xslt_init ()
void xslt_close ()
struct ldap_conn * ldap_connect (const char *uri, enum ldap_starttls starttls, int timelimit, int limit, int debug, int *err)
int ldap_simplebind (struct ldap_conn *ld, const char *dn, const char *passwd)
int ldap_saslbind (struct ldap_conn *ld, const char *mech, const char *realm, const char *authcid, const char *passwd, const char *authzid)
int ldap_simplerebind (struct ldap_conn *ld, const char *initialdn, const char *initialpw, const char *base, const char *filter, const char *uidrdn, const char *uid, const char *passwd)
void ldap_close (struct ldap_conn *ld)
const char * ldap_errmsg (int res)
struct ldap_results * ldap_search_sub (struct ldap_conn *ld, const char *base, const char *filter, int b64enc, int *res,...)
struct ldap_results * ldap_search_one (struct ldap_conn *ld, const char *base, const char *filter, int b64enc, int *res,...)
struct ldap_results * ldap_search_base (struct ldap_conn *ld, const char *base, const char *filter, int b64enc, int *res,...)
void ldap_unref_entry (struct ldap_results *results, struct ldap_entry *entry)
void ldap_unref_attr (struct ldap_entry *entry, struct ldap_attr *attr)
struct ldap_entry * ldap_getentry (struct ldap_results *results, const char *dn)
struct ldap_attr * ldap_getattr (struct ldap_entry *entry, const char *attr)
struct ldap_modify * ldap_modifyinit (const char *dn)
int ldap_mod_del (struct ldap_modify *lmod, const char *attr,...)
int ldap_mod_add (struct ldap_modify *lmod, const char *attr,...)
int ldap_mod_rep (struct ldap_modify *lmod, const char *attr,...)
int ldap_domodify (struct ldap_conn *ld, struct ldap_modify *lmod)
int ldap_mod_remattr (struct ldap_conn *ldap, const char *dn, const char *attr)
int ldap_mod_delattr (struct ldap_conn *ldap, const char *dn, const char *attr, const char *value)
int ldap_mod_addattr (struct ldap_conn *ldap, const char *dn, const char *attr, const char *value)
int ldap_mod_repattr (struct ldap_conn *ldap, const char *dn, const char *attr, const char *value)
Macro Definition Documentation
#define ALLOC_CONST (const_var, val)
Value:
{ \
        char *tmp_char; \
        if (val) { \
            tmp_char = malloc(strlen(val) + 1); \
            strcpy(tmp_char, val); \
            const_var = tmp_char; \
        } else { \
            const_var = NULL; \
        } \
    }
Definition at line 502 of file dtsapp.h.
#define clearflag (obj, flag)
Value:
objlock(obj); \
    obj->flags &= ~flag; \
    objunlock(obj)
Definition at line 483 of file dtsapp.h.
#define FRAMEWORK_MAIN (progname, name, email, www, year, runfile, sighfunc)
Value:
static int  framework_main(int argc, char *argv[]); \
    static struct framework_core *core_info; \
    int  main(int argc, char *argv[]) { \
        core_info = framework_mkcore(progname, name, email, www, year, runfile, sighfunc); \
        return (framework_init(argc, argv, framework_main, core_info)); \
    } \
    static int  framework_main(int argc, char *argv[])
Definition at line 493 of file dtsapp.h.
#define jenhash (key, length, initval) hashlittle(key, length, (initval) ? initval : JHASH_INITVAL);
Definition at line 478 of file dtsapp.h.
#define JHASH_INITVAL 0xdeadbeef
Definition at line 477 of file dtsapp.h.
#define RAD_ATTR_ACCTID 44
Definition at line 288 of file dtsapp.h.
#define RAD_ATTR_EAP 79 /*oct*/
Definition at line 290 of file dtsapp.h.
#define RAD_ATTR_MESSAGE 80 /*oct*/
Definition at line 291 of file dtsapp.h.
#define RAD_ATTR_NAS_IP_ADDR 4 /*ip*/
Definition at line 285 of file dtsapp.h.
#define RAD_ATTR_NAS_PORT 5 /*int*/
Definition at line 286 of file dtsapp.h.
#define RAD_ATTR_PORT_TYPE 61 /*int*/
Definition at line 289 of file dtsapp.h.
#define RAD_ATTR_SERVICE_TYPE 6 /*int*/
Definition at line 287 of file dtsapp.h.
#define RAD_ATTR_USER_NAME 1 /*string*/
Definition at line 283 of file dtsapp.h.
#define RAD_ATTR_USER_PASSWORD 2 /*passwd*/
Definition at line 284 of file dtsapp.h.
#define RAD_AUTH_HDR_LEN 20
Definition at line 278 of file dtsapp.h.
#define RAD_AUTH_PACKET_LEN 4096
Definition at line 279 of file dtsapp.h.
#define RAD_AUTH_TOKEN_LEN 16
Definition at line 280 of file dtsapp.h.
#define RAD_MAX_PASS_LEN 128
Definition at line 281 of file dtsapp.h.
#define setflag (obj, flag)
Value:
objlock(obj); \
    obj->flags |= flag; \
    objunlock(obj)
Definition at line 487 of file dtsapp.h.
#define testflag (obj, flag) (objlock(obj) | (obj->flags & flag) | objunlock(obj))
Definition at line 491 of file dtsapp.h.
Typedef Documentation
typedef void(* blist_cb)(void *, void *)
Definition at line 105 of file dtsapp.h.
typedef int(* blisthash)(const void *, int)
Definition at line 102 of file dtsapp.h.
typedef void(* config_catcb)(struct bucket_list *, const char *)
Definition at line 107 of file dtsapp.h.
typedef void(* config_entrycb)(const char *, const char *)
Definition at line 108 of file dtsapp.h.
typedef void(* config_filecb)(struct bucket_list *, const char *, const char *)
Definition at line 106 of file dtsapp.h.
typedef int(* frameworkfunc)(int, char **)
Definition at line 101 of file dtsapp.h.
typedef struct ldap_add ldap_add
Definition at line 444 of file dtsapp.h.
typedef struct ldap_conn ldap_conn
Definition at line 442 of file dtsapp.h.
typedef struct ldap_modify ldap_modify
Definition at line 443 of file dtsapp.h.
typedef struct natmap natmap
Definition at line 86 of file dtsapp.h.
typedef struct nfct_struct nfct_struct
Definition at line 90 of file dtsapp.h.
typedef struct nfq_data nfq_data
Definition at line 89 of file dtsapp.h.
typedef struct nfq_queue nfq_queue
Definition at line 88 of file dtsapp.h.
typedef struct nfqnl_msg_packet_hdr nfqnl_msg_packet_hdr
Definition at line 91 of file dtsapp.h.
typedef uint32_t(* nfqueue_cb)(struct nfq_data *, struct nfqnl_msg_packet_hdr *, char *, uint32_t, void *, uint32_t *, void **)
Definition at line 109 of file dtsapp.h.
typedef void(* objdestroy)(void *)
Definition at line 103 of file dtsapp.h.
typedef void(* radius_cb)(struct radius_packet *, void *)
Definition at line 94 of file dtsapp.h.
typedef struct radius_packet radius_packet
Definition at line 87 of file dtsapp.h.
typedef void(* socketrecv)(struct fwsocket *, void *)
Definition at line 104 of file dtsapp.h.
typedef struct ssldata ssldata
Definition at line 57 of file dtsapp.h.
typedef void(* syssighandler)(int, siginfo_t *, void *)
Definition at line 98 of file dtsapp.h.
typedef void*(* threadcleanup)(void *)
Definition at line 95 of file dtsapp.h.
typedef void*(* threadfunc)(void **)
Definition at line 96 of file dtsapp.h.
typedef int(* threadsighandler)(int, void *)
Definition at line 100 of file dtsapp.h.
typedef struct xml_doc xml_doc
Definition at line 345 of file dtsapp.h.
typedef struct xml_node xml_node
Definition at line 343 of file dtsapp.h.
typedef struct xml_search xml_search
Definition at line 344 of file dtsapp.h.
typedef struct xslt_doc xslt_doc
Definition at line 346 of file dtsapp.h.
Enumeration Type Documentation
enum ldap_attrtype
Enumerator:
LDAP_ATTRTYPE_CHAR
LDAP_ATTRTYPE_B64
LDAP_ATTRTYPE_OCTET
LDAP_ATTRTYPE_CHAR
LDAP_ATTRTYPE_B64
LDAP_ATTRTYPE_OCTET
Definition at line 397 of file dtsapp.h.
                   {
    LDAP_ATTRTYPE_CHAR,
    LDAP_ATTRTYPE_B64,
    LDAP_ATTRTYPE_OCTET
};
enum ldap_starttls
Enumerator:
LDAP_STARTTLS_NONE
LDAP_STARTTLS_ATTEMPT
LDAP_STARTTLS_ENFORCE
LDAP_STARTTLS_NONE
LDAP_STARTTLS_ATTEMPT
LDAP_STARTTLS_ENFORCE
Definition at line 391 of file dtsapp.h.
                   {
    LDAP_STARTTLS_NONE,
    LDAP_STARTTLS_ATTEMPT,
    LDAP_STARTTLS_ENFORCE
};
enum RADIUS_CODE
Enumerator:
RAD_CODE_AUTHREQUEST
RAD_CODE_AUTHACCEPT
RAD_CODE_AUTHREJECT
RAD_CODE_ACCTREQUEST
RAD_CODE_ACCTRESPONSE
RAD_CODE_AUTHCHALLENGE
RAD_CODE_AUTHREQUEST
RAD_CODE_AUTHACCEPT
RAD_CODE_AUTHREJECT
RAD_CODE_ACCTREQUEST
RAD_CODE_ACCTRESPONSE
RAD_CODE_AUTHCHALLENGE
Definition at line 293 of file dtsapp.h.
                 {
    RAD_CODE_AUTHREQUEST    =   1,
    RAD_CODE_AUTHACCEPT =   2,
    RAD_CODE_AUTHREJECT =   3,
    RAD_CODE_ACCTREQUEST    =   4,
    RAD_CODE_ACCTRESPONSE   =   5,
    RAD_CODE_AUTHCHALLENGE  =   11
};
enum sock_flags
Enumerator:
SOCK_FLAG_BIND
The socket has been bound and awaiting connections.
SOCK_FLAG_CLOSE
The socket is going away stop processing in its thread.
SOCK_FLAG_SSL
SSL has been requested on this socket dont allow clear read/send.
SOCK_FLAG_BIND
SOCK_FLAG_CLOSE
Definition at line 59 of file dtsapp.h.
                {
    SOCK_FLAG_BIND      = 1 << 0,
    SOCK_FLAG_CLOSE     = 1 << 1
};
Function Documentation
int framework_init (int argc, char * argv[], frameworkfunc callback, struct framework_core * core_info)
Definition at line 213 of file main.c.
References daemonize(), framework_shutdown(), jointhreads(), lockpidfile(), framework_core::my_pid, printgnu(), framework_core::sa, seedrand(), sslstartup(), and startthreads().
{
    int ret = 0;
    seedrand();
    sslstartup();
    framework_core_info = core_info;
    /*prinit out a GNU licence summary*/
    printgnu(core_info);
    /* fork the process to daemonize it*/
    core_info->my_pid = daemonize();
    if (lockpidfile(core_info) < 0) {
        printf("Could not lock pid file Exiting\n");
        framework_free(core_info);
        return (-1);
    }
#ifndef __WIN32__
    /* interupt handler close clean on term so physical is reset*/
    configure_sigact(core_info->sa);
#endif
    /*init the threadlist start thread manager*/
    if (!startthreads()) {
        printf("Memory Error could not start threads\n");
        framework_free(core_info);
        return (-1);
    }
    /*run the code from the application*/
    if (callback) {
        ret = callback(argc, argv);
    }
    /*join the manager thread its the last to go*/
    if (!ret) {
        jointhreads();
    } else {
        framework_shutdown();
    }
    /* turn off the lights*/
    framework_free(core_info);
    return (ret);
}
struct framework_core* framework_mkcore (char * progname, char * name, char * email, char * web, int year, char * runfile, syssighandler sigfunc) read
Definition at line 151 of file main.c.
References ALLOC_CONST, framework_core::developer, framework_core::email, framework_core::progname, framework_core::runfile, framework_core::sa, framework_core::sig_handler, framework_core::www, and framework_core::year.
{
#endif
    struct framework_core *core_info = NULL;
    if (!(core_info = malloc(sizeof(*core_info)))) {
        return NULL;
    }
#ifndef __WIN32__
    if (core_info && !(core_info->sa = malloc(sizeof(*core_info->sa)))) {
        free(core_info);
        return NULL;
    }
#endif
    ALLOC_CONST(core_info->developer, name);
    ALLOC_CONST(core_info->email, email);
    ALLOC_CONST(core_info->www, web);
    ALLOC_CONST(core_info->runfile, runfile);
    ALLOC_CONST(core_info->progname, progname);
    core_info->year = year;
#ifndef __WIN32__
    core_info->sig_handler = sigfunc;
#endif
    return (core_info);
}
struct thread_pvt* framework_mkthread (threadfunc , threadcleanup , threadsighandler , void * data) read
Definition at line 215 of file thread.c.
References addtobucket(), thread_pvt::cleanup, thread_pvt::data, thread_pvt::flags, thread_pvt::func, threadcontainer::list, thread_pvt::magic, objalloc(), objlock(), objref(), objunlock(), objunref(), thread_pvt::sighandler, startthreads(), thread_pvt::thr, THREAD_MAGIC, and threads.
{
    struct thread_pvt *thread;
    if (!(thread = objalloc(sizeof(*thread), NULL))) {
        return NULL;
    }
    thread->data = data;
    thread->flags = 0;
    thread->cleanup = cleanup;
    thread->sighandler = sig_handler;
    thread->func = func;
    thread->magic = THREAD_MAGIC;
    /* grab a ref to data for thread to make sure it does not go away*/
    objref(thread->data);
    if (pthread_create(&thread->thr, NULL, threadwrap, thread)) {
        objunref(thread);
        objunref(thread->data);
        return NULL;
    }
    /* am i up and running move ref to list*/
    if (!pthread_kill(thread->thr, 0)) {
        if ((threads && threads->list) || startthreads()) {
            objlock(threads);
            addtobucket(threads->list, thread);
            objunlock(threads);
        }
        return (thread);
    } else {
        objunref(thread->data);
        objunref(thread);
    }
    return NULL;
}
void framework_shutdown (void)
Definition at line 257 of file thread.c.
References threadcontainer::manager, SIGHUP, thread_pvt::thr, and threads.
Referenced by framework_init().
{
    pthread_kill(threads->manager->thr, SIGHUP);
}
int framework_threadok (void * data)
Definition at line 85 of file thread.c.
References thread_pvt::data, thread_pvt::magic, testflag, thread_pvt::thr, THREAD_MAGIC, and TL_THREAD_RUN.
{
    struct thread_pvt *thr = data;
    if (thr && (thr->magic == THREAD_MAGIC)) {
        return (testflag(thr, TL_THREAD_RUN));
    }
    return (0);
}
void ssl_shutdown (void * ssl)
Definition at line 90 of file sslutil.c.
References objlock(), objunlock(), and ssldata::ssl.
{
    struct ssldata *ssl = data;
    int err, ret;
    if (!ssl) {
        return;
    }
    objlock(ssl);
    if (ssl->ssl && ((ret = SSL_shutdown(ssl->ssl)) < 1)) {
        objunlock(ssl);
        if (ret == 0) {
            objlock(ssl);
            ret = SSL_shutdown(ssl->ssl);
        } else {
            objlock(ssl);
        }
        err = SSL_get_error(ssl->ssl, ret);
        switch(err) {
            case SSL_ERROR_WANT_READ:
                printf("SSL_shutdown wants read\n");
                break;
            case SSL_ERROR_WANT_WRITE:
                printf("SSL_shutdown wants write\n");
                break;
            case SSL_ERROR_SSL:
                /*ignore im going away now*/
            case SSL_ERROR_SYSCALL:
                /* ignore this as documented*/
            case SSL_ERROR_NONE:
                /* nothing to see here moving on*/
                break;
            default:
                printf("SSL Shutdown unknown error %i\n", err);
                break;
        }
    }
    if (ssl->ssl) {
        SSL_free(ssl->ssl);
        ssl->ssl = NULL;
    }
    objunlock(ssl);
}
void stop_bucket_loop (struct bucket_loop * bloop)
Definition at line 436 of file refobj.c.
References bucket_loop::blist, and objunref().
Referenced by bucketlist_callback(), ldap_doadd(), and ldap_domodify().
{
    if (bloop) {
        objunref(bloop->blist);
        objunref(bloop);
    }
}
void stopthreads (void)
Definition at line 185 of file thread.c.
References clearflag, threadcontainer::manager, threads, and TL_THREAD_RUN.
{
    if (threads) {
        clearflag(threads->manager, TL_THREAD_RUN);
    }
}