DTS Application Library: /usr/src/dtsapplib/dtsapplib-0.1/src/thread.c File Reference
thread.c File Reference
#include <pthread.h>
#include <signal.h>
#include <unistd.h>
#include "include/dtsapp.h"
Data Structures
struct thread_pvt
thread struct used to create threads data needs to be first element
struct threadcontainer
Global threads data.
Macros
#define SIGHUP 1
#define THREAD_MAGIC 0xfeedf158
Enumerations
enum threadopt {
TL_THREAD_NONE = 1 << 0, TL_THREAD_RUN = 1 << 1, TL_THREAD_DONE = 1 << 2, TL_THREAD_JOIN = 1 << 3,
TL_THREAD_STOP = 1 << 4, TL_THREAD_CAN_CANCEL = 1 << 16, TL_THREAD_JOINABLE = 1 << 17, TL_THREAD_RETURN = 1 << 18,
TL_THREAD_NONE = 0, TL_THREAD_RUN = 1 << 1, TL_THREAD_DONE = 1 << 2
}
Functions
int framework_threadok (void *data)
int startthreads (void)
Initialise the threadlist and start manager thread.
void stopthreads (void)
struct thread_pvt * framework_mkthread (threadfunc func, threadcleanup cleanup, threadsighandler sig_handler, void *data)
void framework_shutdown (void)
void jointhreads (void)
Join the manager thread.
int thread_signal (int sig)
Handle signal if its for me.
Variables
struct threadcontainer * threads = NULL
Macro Definition Documentation
#define SIGHUP 1
Definition at line 24 of file thread.c.
Referenced by framework_shutdown(), and thread_signal().
#define THREAD_MAGIC 0xfeedf158
Definition at line 29 of file thread.c.
Referenced by framework_mkthread(), and framework_threadok().
Enumeration Type Documentation
enum threadopt
Enumerator:
TL_THREAD_NONE
No status.
TL_THREAD_RUN
thread is marked as running
TL_THREAD_DONE
thread is marked as complete
TL_THREAD_JOIN
Quit when only manager is left.
Note
This flag is only valid for manager thread
TL_THREAD_STOP
Quit when only manager is left.
Note
This flag is only valid for manager thread
TL_THREAD_CAN_CANCEL
Flag to enable pthread_cancel calls.
TL_THREAD_JOINABLE
Flag to enable pthread_cancel calls.
TL_THREAD_RETURN
TL_THREAD_NONE
TL_THREAD_RUN
TL_THREAD_DONE
Definition at line 31 of file thread.c.
               {
        TL_THREAD_NONE  = 0,
        /* thread is marked as running*/
        TL_THREAD_RUN   = 1 << 1,
        /* thread is marked as complete*/
        TL_THREAD_DONE  = 1 << 2
};
Function Documentation
struct thread_pvt* framework_mkthread (threadfunc func, threadcleanup cleanup, threadsighandler sig_handler, void * data) read
Definition at line 215 of file thread.c.
References addtobucket(), thread_pvt::cleanup, thread_pvt::data, thread_pvt::flags, thread_pvt::func, threadcontainer::list, thread_pvt::magic, objalloc(), objlock(), objref(), objunlock(), objunref(), thread_pvt::sighandler, startthreads(), thread_pvt::thr, THREAD_MAGIC, and threads.
{
    struct thread_pvt *thread;
    if (!(thread = objalloc(sizeof(*thread), NULL))) {
        return NULL;
    }
    thread->data = data;
    thread->flags = 0;
    thread->cleanup = cleanup;
    thread->sighandler = sig_handler;
    thread->func = func;
    thread->magic = THREAD_MAGIC;
    /* grab a ref to data for thread to make sure it does not go away*/
    objref(thread->data);
    if (pthread_create(&thread->thr, NULL, threadwrap, thread)) {
        objunref(thread);
        objunref(thread->data);
        return NULL;
    }
    /* am i up and running move ref to list*/
    if (!pthread_kill(thread->thr, 0)) {
        if ((threads && threads->list) || startthreads()) {
            objlock(threads);
            addtobucket(threads->list, thread);
            objunlock(threads);
        }
        return (thread);
    } else {
        objunref(thread->data);
        objunref(thread);
    }
    return NULL;
}
void framework_shutdown (void)
Definition at line 257 of file thread.c.
References threadcontainer::manager, SIGHUP, thread_pvt::thr, and threads.
Referenced by framework_init().
{
    pthread_kill(threads->manager->thr, SIGHUP);
}
int framework_threadok (void * data)
Definition at line 85 of file thread.c.
References thread_pvt::data, thread_pvt::magic, testflag, thread_pvt::thr, THREAD_MAGIC, and TL_THREAD_RUN.
{
    struct thread_pvt *thr = data;
    if (thr && (thr->magic == THREAD_MAGIC)) {
        return (testflag(thr, TL_THREAD_RUN));
    }
    return (0);
}
void stopthreads (void)
Definition at line 185 of file thread.c.
References clearflag, threadcontainer::manager, threads, and TL_THREAD_RUN.
{
    if (threads) {
        clearflag(threads->manager, TL_THREAD_RUN);
    }
}
Variable Documentation
struct threadcontainer * threads = NULL