DTS Application Library: /usr/src/dtsapplib/dtsapplib-0.1/src/sslutil.c File Reference
sslutil.c File Reference
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <sys/stat.h>
#include <unistd.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include "include/dtsapp.h"
Data Structures
struct ssldata
SSL data structure for enabling encryption on sockets.
Macros
#define COOKIE_SECRET_LENGTH 32
Enumerations
enum SSLFLAGS {
SSL_TLSV1 = 1 << 0, SSL_SSLV2 = 1 << 1, SSL_SSLV3 = 1 << 2, SSL_DTLSV1 = 1 << 3,
SSL_CLIENT = 1 << 4, SSL_SERVER = 1 << 5, SSL_DTLSCON = 1 << 6, SSL_TLSV1 = 1 << 0,
SSL_SSLV2 = 1 << 1, SSL_SSLV3 = 1 << 2, SSL_DTLSV1 = 1 << 3, SSL_CLIENT = 1 << 4,
SSL_SERVER = 1 << 5, SSL_DTLSCON = 1 << 6
}
Functions
void ssl_shutdown (void *data)
void * tlsv1_init (const char *cacert, const char *cert, const char *key, int verify)
Create a SSL structure for TLSv1.
void * sslv2_init (const char *cacert, const char *cert, const char *key, int verify)
Create a SSL structure for SSLv2 (If available)
void * sslv3_init (const char *cacert, const char *cert, const char *key, int verify)
Create a SSL structure for SSLv3.
void * dtlsv1_init (const char *cacert, const char *cert, const char *key, int verify)
Create a SSL structure for DTLSv1.
void tlsaccept (struct fwsocket *sock, struct ssldata *orig)
Create SSL session for new connection.
int socketread_d (struct fwsocket *sock, void *buf, int num, union sockstruct *addr)
Read from a socket into a buffer.
int socketread (struct fwsocket *sock, void *buf, int num)
Read from a socket into a buffer.
int socketwrite_d (struct fwsocket *sock, const void *buf, int num, union sockstruct *addr)
Write a buffer to a socket.
int socketwrite (struct fwsocket *sock, const void *buf, int num)
Write a buffer to a socket.
void sslstartup (void)
Initialise SSL support this should be called at startup.
void dtsl_serveropts (struct fwsocket *sock)
Start up the DTLSv1 Server.
struct fwsocket * dtls_listenssl (struct fwsocket *sock)
Implementation of "listen" for DTLSv1.
void startsslclient (struct fwsocket *sock)
Start SSL on a client socket.
void dtlstimeout (struct fwsocket *sock, struct timeval *timeleft, int defusec)
void dtlshandltimeout (struct fwsocket *sock)
Handle DTLSv1 timeout.
Macro Definition Documentation
#define COOKIE_SECRET_LENGTH 32
Definition at line 53 of file sslutil.c.
Referenced by sslstartup().
Enumeration Type Documentation
enum SSLFLAGS
Enumerator:
SSL_TLSV1
TLSv1.
SSL_SSLV2
SSLv2 This may not be available due to security issues.
SSL_SSLV3
SSLv3.
SSL_DTLSV1
DTLSv1 (UDP Connections)
SSL_CLIENT
This session is client mode.
SSL_SERVER
This session is server mode.
SSL_DTLSCON
UDP connection is listening.
SSL_TLSV1
SSL_SSLV2
SSL_SSLV3
SSL_DTLSV1
SSL_CLIENT
SSL_SERVER
SSL_DTLSCON
Definition at line 34 of file sslutil.c.
              {
    SSL_TLSV1   = 1 << 0,
    SSL_SSLV2   = 1 << 1,
    SSL_SSLV3   = 1 << 2,
    SSL_DTLSV1  = 1 << 3,
    SSL_CLIENT  = 1 << 4,
    SSL_SERVER  = 1 << 5,
    SSL_DTLSCON = 1 << 6
};
Function Documentation
void dtlstimeout (struct fwsocket * sock, struct timeval * timeleft, int defusec)
Definition at line 611 of file sslutil.c.
References objlock(), objunlock(), ssldata::ssl, and fwsocket::ssl.
{
    if (!sock || !sock->ssl || !sock->ssl->ssl) {
        return;
    }
    objlock(sock->ssl);
    if (!DTLSv1_get_timeout(sock->ssl->ssl, timeleft)) {
        timeleft->tv_sec = 0;
        timeleft->tv_usec = defusec;
    }
    objunlock(sock->ssl);
}
void ssl_shutdown (void * data)
Definition at line 90 of file sslutil.c.
References objlock(), objunlock(), and ssldata::ssl.
{
    struct ssldata *ssl = data;
    int err, ret;
    if (!ssl) {
        return;
    }
    objlock(ssl);
    if (ssl->ssl && ((ret = SSL_shutdown(ssl->ssl)) < 1)) {
        objunlock(ssl);
        if (ret == 0) {
            objlock(ssl);
            ret = SSL_shutdown(ssl->ssl);
        } else {
            objlock(ssl);
        }
        err = SSL_get_error(ssl->ssl, ret);
        switch(err) {
            case SSL_ERROR_WANT_READ:
                printf("SSL_shutdown wants read\n");
                break;
            case SSL_ERROR_WANT_WRITE:
                printf("SSL_shutdown wants write\n");
                break;
            case SSL_ERROR_SSL:
                /*ignore im going away now*/
            case SSL_ERROR_SYSCALL:
                /* ignore this as documented*/
            case SSL_ERROR_NONE:
                /* nothing to see here moving on*/
                break;
            default:
                printf("SSL Shutdown unknown error %i\n", err);
                break;
        }
    }
    if (ssl->ssl) {
        SSL_free(ssl->ssl);
        ssl->ssl = NULL;
    }
    objunlock(ssl);
}