DTS Application Library: /usr/src/dtsapplib/dtsapplib-0.1/src/main.c File Reference
main.c File Reference
#include <unistd.h>
#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <sys/file.h>
#include "include/dtsapp.h"
#include "include/private.h"
Functions
struct framework_core * framework_mkcore (char *progname, char *name, char *email, char *web, int year, char *runfile, syssighandler sigfunc)
int framework_init (int argc, char *argv[], frameworkfunc callback, struct framework_core *core_info)
Function Documentation
int framework_init (int argc, char * argv[], frameworkfunc callback, struct framework_core * core_info)
Definition at line 213 of file main.c.
References daemonize(), framework_shutdown(), jointhreads(), lockpidfile(), framework_core::my_pid, printgnu(), framework_core::sa, seedrand(), sslstartup(), and startthreads().
{
    int ret = 0;
    seedrand();
    sslstartup();
    framework_core_info = core_info;
    /*prinit out a GNU licence summary*/
    printgnu(core_info);
    /* fork the process to daemonize it*/
    core_info->my_pid = daemonize();
    if (lockpidfile(core_info) < 0) {
        printf("Could not lock pid file Exiting\n");
        framework_free(core_info);
        return (-1);
    }
#ifndef __WIN32__
    /* interupt handler close clean on term so physical is reset*/
    configure_sigact(core_info->sa);
#endif
    /*init the threadlist start thread manager*/
    if (!startthreads()) {
        printf("Memory Error could not start threads\n");
        framework_free(core_info);
        return (-1);
    }
    /*run the code from the application*/
    if (callback) {
        ret = callback(argc, argv);
    }
    /*join the manager thread its the last to go*/
    if (!ret) {
        jointhreads();
    } else {
        framework_shutdown();
    }
    /* turn off the lights*/
    framework_free(core_info);
    return (ret);
}
struct framework_core* framework_mkcore (char * progname, char * name, char * email, char * web, int year, char * runfile, syssighandler sigfunc) read
Definition at line 151 of file main.c.
References ALLOC_CONST, framework_core::developer, framework_core::email, framework_core::progname, framework_core::runfile, framework_core::sa, framework_core::sig_handler, framework_core::www, and framework_core::year.
{
#endif
    struct framework_core *core_info = NULL;
    if (!(core_info = malloc(sizeof(*core_info)))) {
        return NULL;
    }
#ifndef __WIN32__
    if (core_info && !(core_info->sa = malloc(sizeof(*core_info->sa)))) {
        free(core_info);
        return NULL;
    }
#endif
    ALLOC_CONST(core_info->developer, name);
    ALLOC_CONST(core_info->email, email);
    ALLOC_CONST(core_info->www, web);
    ALLOC_CONST(core_info->runfile, runfile);
    ALLOC_CONST(core_info->progname, progname);
    core_info->year = year;
#ifndef __WIN32__
    core_info->sig_handler = sigfunc;
#endif
    return (core_info);
}