DTS Application Library: /usr/src/dtsapplib/dtsapplib-0.1/src/libxml2.c File Reference
libxml2.c File Reference
#include <string.h>
#include <libxml/tree.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include <libxml/xpathInternals.h>
#include "include/priv_xml.h"
#include "include/dtsapp.h"
Data Structures
struct xml_node_iter
struct xml_buffer
struct xml_search
Functions
int node_hash (const void *data, int key)
int attr_hash (const void *data, int key)
struct xml_doc * xml_loaddoc (const char *docfile, int validate)
struct xml_node * xml_nodetohash (struct xml_doc *xmldoc, xmlNodePtr node, const char *attrkey)
struct xml_node * xml_gethash (struct xml_search *xpsearch, int i, const char *attrkey)
struct xml_node * xml_getrootnode (struct xml_doc *xmldoc)
struct xml_node * xml_getfirstnode (struct xml_search *xpsearch, void **iter)
struct xml_node * xml_getnextnode (void *iter)
struct bucket_list * xml_getnodes (struct xml_search *xpsearch)
struct bucket_list * xml_setnodes (struct xml_search *xpsearch, const char *attrkey)
struct xml_search * xml_xpath (struct xml_doc *xmldata, const char *xpath, const char *attrkey)
int xml_nodecount (struct xml_search *xsearch)
struct xml_node * xml_getnode (struct xml_search *xsearch, const char *key)
const char * xml_getattr (struct xml_node *xnode, const char *attr)
const char * xml_getrootname (struct xml_doc *xmldoc)
void xml_modify (struct xml_doc *xmldoc, struct xml_node *xnode, const char *value)
void xml_setattr (struct xml_doc *xmldoc, struct xml_node *xnode, const char *name, const char *value)
void xml_createpath (struct xml_doc *xmldoc, const char *xpath)
struct xml_node * xml_addnode (struct xml_doc *xmldoc, const char *xpath, const char *name, const char *value, const char *attrkey, const char *keyval)
void xml_delete (struct xml_node *xnode)
char * xml_getbuffer (void *buffer)
void * xml_doctobuffer (struct xml_doc *xmldoc)
void xml_init ()
void xml_close ()
void xml_savefile (struct xml_doc *xmldoc, const char *file, int format, int compress)
void xml_modify2 (struct xml_search *xpsearch, struct xml_node *xnode, const char *value)
Variables
int xmlLoadExtwDtdDefaultValue
Function Documentation
int attr_hash (const void * data, int key)
Definition at line 96 of file libxml2.c.
References jenhash, and xml_attr::name.
Referenced by xml_nodetohash().
{
    int ret;
    const struct xml_attr *ai = data;
    const char* hashkey = (key) ? data : ai->name;
    ret = jenhash(hashkey, strlen(hashkey), 0);
    return(ret);
}
int node_hash (const void * data, int key)
Definition at line 83 of file libxml2.c.
References jenhash, and xml_node::key.
Referenced by xml_setnodes().
{
    int ret;
    const struct xml_node *ni = data;
    const char* hashkey = (key) ? data : ni->key;
    if (hashkey) {
        ret = jenhash(hashkey, strlen(hashkey), 0);
    } else {
        ret = jenhash(ni, sizeof(ni), 0);
    }
    return(ret);
}
struct xml_node* xml_gethash (struct xml_search * xpsearch, int i, const char * attrkey) read
Definition at line 190 of file libxml2.c.
References objlock(), objref(), objunlock(), objunref(), xml_nodetohash(), xml_search::xmldoc, and xml_search::xpathObj.
{
    xmlNodePtr node;
    xmlNodeSetPtr nodeset;
    struct xml_node *xn;
    if (!objref(xpsearch)) {
        return NULL;
    }
    objlock(xpsearch->xmldoc);
    objlock(xpsearch);
    if (!(nodeset = xpsearch->xpathObj->nodesetval)) {
        objunlock(xpsearch);
        objunlock(xpsearch->xmldoc);
        objunref(xpsearch);
        return NULL;
    }
    if (!(node = nodeset->nodeTab[i])) {
        objunlock(xpsearch);
        objunlock(xpsearch->xmldoc);
        objunref(xpsearch);
        return NULL;
    }
    xn = xml_nodetohash(xpsearch->xmldoc, node, attrkey);
    objunlock(xpsearch);
    objunlock(xpsearch->xmldoc);
    objunref(xpsearch);
    return xn;
}
void xml_modify2 (struct xml_search * xpsearch, struct xml_node * xnode, const char * value)
Definition at line 603 of file libxml2.c.
References xml_node::nodeptr, xml_buffer::size, and xml_search::xpathObj.
{
    xmlNodeSetPtr nodes;
    int size, i;
    if (!(nodes = xpsearch->xpathObj->nodesetval)) {
        return;
    }
    size = (nodes) ? nodes->nodeNr : 0;
    /*
     * http://www.xmlsoft.org/examples/xpath2.c
     * remove the reference to the modified nodes from the node set
     * as they are processed, if they are not namespace nodes.
    */
    for(i = size - 1; i >= 0; i--) {
        if (nodes->nodeTab[i] == xnode->nodeptr) {
            xmlNodeSetContent(nodes->nodeTab[i], (const xmlChar*)value);
            if (nodes->nodeTab[i]->type != XML_NAMESPACE_DECL) {
                nodes->nodeTab[i] = NULL;
            }
        }
    }
}
struct xml_node* xml_nodetohash (struct xml_doc * xmldoc, xmlNodePtr node, const char * attrkey) read
Definition at line 145 of file libxml2.c.
References addtobucket(), ALLOC_CONST, attr_hash(), xml_node::attrs, create_bucketlist(), xml_doc::doc, xml_node::key, xml_attr::name, xml_node::name, xml_node::nodeptr, objalloc(), objunref(), xml_attr::value, and xml_node::value.
{
    struct xml_node *ninfo;
    struct xml_attr *ainfo;
    xmlChar *xmlstr;
    xmlAttr* attrs;
    if (!(ninfo = objalloc(sizeof(*ninfo), free_xmlnode))) {
        return NULL;
    }
    ninfo->attrs = NULL;
    if (!(ninfo->attrs = create_bucketlist(0, attr_hash))) {
        objunref(ninfo);
        return NULL;
    }
    ALLOC_CONST(ninfo->name, (const char*)node->name);
    xmlstr = xmlNodeListGetString(xmldoc->doc, node->xmlChildrenNode, 1);
    ALLOC_CONST(ninfo->value, (const char*)xmlstr);
    xmlFree(xmlstr);
    ninfo->nodeptr = node;
    attrs = node->properties;
    while(attrs && attrs->name && attrs->children) {
        if (!(ainfo = objalloc(sizeof(*ainfo), NULL))) {
            objunref(ninfo);
            return NULL;
        }
        ALLOC_CONST(ainfo->name, (const char*)attrs->name);
        xmlstr = xmlNodeListGetString(xmldoc->doc, attrs->children, 1);
        ALLOC_CONST(ainfo->value, (const char*)xmlstr);
        if (attrkey && !strcmp((const char*)attrs->name, (const char*)attrkey)) {
            ALLOC_CONST(ninfo->key, (const char*)xmlstr);
        }
        xmlFree(xmlstr);
        addtobucket(ninfo->attrs, ainfo);
        objunref(ainfo);
        attrs = attrs->next;
    }
    if (!attrkey && ninfo->value) {
        ALLOC_CONST(ninfo->key, ninfo->value);
    }
    return ninfo;
}
struct bucket_list* xml_setnodes (struct xml_search * xpsearch, const char * attrkey) read
Definition at line 290 of file libxml2.c.
References addtobucket(), create_bucketlist(), node_hash(), objunref(), xml_gethash(), and xml_nodecount().
{
    struct xml_node *ninfo;
    struct bucket_list *nodes;
    int cnt, i;
    if (!(nodes = create_bucketlist(2, node_hash))) {
        return NULL;
    }
    cnt = xml_nodecount(xpsearch);
    for(i=0; i < cnt;i++) {
        ninfo = xml_gethash(xpsearch, i, attrkey);
        if (!addtobucket(nodes, ninfo)) {
            objunref(ninfo);
            objunref(nodes);
            nodes = NULL;
            break;
        }
        objunref(ninfo);
    }
    return nodes;
}
Variable Documentation
int xmlLoadExtwDtdDefaultValue