DTS Application Library: /usr/src/dtsapplib/dtsapplib-0.1/src/libxslt.c File Reference
libxslt.c File Reference
#include <string.h>
#include <libxslt/xsltutils.h>
#include <libxslt/transform.h>
#include "include/dtsapp.h"
#include "include/priv_xml.h"
Data Structures
struct xslt_doc
struct xslt_param
Functions
void free_xsltdoc (void *data)
void free_parser (void *data)
int xslt_hash (const void *data, int key)
struct xslt_doc * xslt_open (const char *xsltfile)
void free_param (void *data)
void xslt_addparam (struct xslt_doc *xsltdoc, const char *param, const char *value)
void xslt_clearparam (struct xslt_doc *xsltdoc)
void xslt_apply (struct xml_doc *xmldoc, struct xslt_doc *xsltdoc, const char *filename, int comp)
void xslt_init ()
void xslt_close ()
Function Documentation
void free_param (void * data)
Definition at line 64 of file libxslt.c.
References xslt_param::name, and xslt_param::value.
{
    struct xslt_param *param = data;
    if (param->name) {
        free((void*)param->name);
    }
    if (param->value) {
        free((void*)param->value);
    }
}
void free_parser (void * data)
Definition at line 33 of file libxslt.c.
References free_parser().
{
    xsltCleanupGlobals();
    xmlCleanupParser();
}
void free_xsltdoc (void * data)
Definition at line 25 of file libxslt.c.
References xslt_doc::doc, objunref(), xslt_doc::params, and xslt_close().
{
    struct xslt_doc *xsltdoc = data;
    xsltFreeStylesheet(xsltdoc->doc);
    objunref(xsltdoc->params);
    xslt_close();
}
void xslt_clearparam (struct xslt_doc * xsltdoc)
Definition at line 93 of file libxslt.c.
References create_bucketlist(), objlock(), objunlock(), objunref(), xslt_doc::params, and xslt_hash().
{
    if (!xsltdoc || !xsltdoc->params) {
        return;
    }
    objlock(xsltdoc);
    objunref(xsltdoc->params);
    xsltdoc->params = create_bucketlist(0, xslt_hash);
    objunlock(xsltdoc);
}
int xslt_hash (const void * data, int key)
Definition at line 38 of file libxslt.c.
References jenhash, and xslt_param::name.
Referenced by xslt_clearparam(), and xslt_open().
{
    int ret;
    const struct xslt_param *xp = data;
    const char* hashkey = (key) ? data : xp->name;
    if (hashkey) {
        ret = jenhash(hashkey, strlen(hashkey), 0);
    } else {
        ret = jenhash(xp, sizeof(xp), 0);
    }
    return(ret);
}