DTS Application Library: DTSDVMCtrl Class Reference
DTSDVMCtrl Class Reference
#include <DTSListView.h>
Public Member Functions
DTSDVMCtrl ()
DTSDVMCtrl (wxWindow *parent, wxWindowID id=wxID_ANY, DTSDVMListView *model=NULL, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDV_ROW_LINES, const wxValidator &validator=wxDefaultValidator)
~DTSDVMCtrl ()
virtual bool AssociateModel (DTSDVMListView *model)
void Sort (const wxDataViewItem &parent)
DTSDVMListView * GetStore ()
wxDataViewItem AppendItem (wxDataViewItem parent, const wxString &title, bool can_edit=true, bool can_sort=true, bool can_del=false, int nodeid=-1, dtsgui_treeviewpanel_cb p_cb=NULL, void *userdata=NULL)
wxDataViewItem AppendContainer (wxDataViewItem parent, const wxString &title, bool can_edit=true, bool can_sort=true, bool can_del=false, int nodeid=-1, dtsgui_treeviewpanel_cb p_cb=NULL, void *userdata=NULL)
Detailed Description
Definition at line 105 of file DTSListView.h.
Constructor & Destructor Documentation
DTSDVMCtrl::DTSDVMCtrl ()
Definition at line 551 of file DTSListView.cpp.
                       {
    model = NULL;
}
DTSDVMCtrl::DTSDVMCtrl (wxWindow * parent, wxWindowID id = wxID_ANY, DTSDVMListView * model = NULL, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDV_ROW_LINES, const wxValidator & validator = wxDefaultValidator)
Definition at line 555 of file DTSListView.cpp.
References AssociateModel().
{
    wxDataViewTextRenderer *col0_r;
    wxDataViewColumn *col0;
    this->model = NULL;
    Create(parent, id, pos, size, style, validator);
    if (model) {
        AssociateModel(model);
    }
    col0_r = new wxDataViewTextRenderer("string", wxDATAVIEW_CELL_EDITABLE);
#ifndef _WIN32
    col0_r->DisableEllipsize();
#endif //_WIN32
    col0 = new wxDataViewColumn("Title", col0_r, 0);
#ifndef _WIN32
    col0->SetWidth(wxCOL_WIDTH_AUTOSIZE);
#endif // _WIN32
    col0->SetFlags(wxCOL_RESIZABLE | wxCOL_REORDERABLE);
    col0->SetReorderable(true);
    col0->SetAlignment(wxALIGN_LEFT);
    AppendColumn(col0);
#ifdef _WIN32
    SetRowHeight(17);
#endif // _WIN32
}
DTSDVMCtrl::~DTSDVMCtrl ()
Definition at line 582 of file DTSListView.cpp.
References DTSDVMListView::DeleteAll().
{
    model->DeleteAll();
}
Member Function Documentation
wxDataViewItem DTSDVMCtrl::AppendContainer (wxDataViewItem parent, const wxString & title, bool can_edit = true, bool can_sort = true, bool can_del = false, int nodeid = -1, dtsgui_treeviewpanel_cb p_cb = NULL, void * userdata = NULL)
Definition at line 612 of file DTSListView.cpp.
Referenced by DTS_C_API::dtsgui_treecont().
{
    return AppendNode(parent, title, true, can_edit, can_sort, can_del, nodeid, p_cb, userdata);
}
wxDataViewItem DTSDVMCtrl::AppendItem (wxDataViewItem parent, const wxString & title, bool can_edit = true, bool can_sort = true, bool can_del = false, int nodeid = -1, dtsgui_treeviewpanel_cb p_cb = NULL, void * userdata = NULL)
Definition at line 608 of file DTSListView.cpp.
Referenced by DTS_C_API::dtsgui_treeitem().
{
    return AppendNode(parent, title, false, can_edit, can_sort, can_del, nodeid, p_cb, userdata);
}
bool DTSDVMCtrl::AssociateModel (DTSDVMListView * model) virtual
Definition at line 586 of file DTSListView.cpp.
References DTSDVMListView::DeleteAll().
Referenced by DTSDVMCtrl().
{
    bool res;
    res = wxDataViewCtrl::AssociateModel(model);
    if (res) {
        if (this->model) {
            model->DeleteAll();
        }
        this->model = model;
        model->DecRef();
    }
    return res;
}
DTSDVMListView * DTSDVMCtrl::GetStore ()
Definition at line 604 of file DTSListView.cpp.
Referenced by DTSTreeWindowEvent::DTSTreeWindowEvent(), and DTSTreeWindow::Show().
{
    return model;
}
void DTSDVMCtrl::Sort (const wxDataViewItem & parent)
Definition at line 600 of file DTSListView.cpp.
References DTSDVMListView::SortChildren().
{
    model->SortChildren(parent);
}
The documentation for this class was generated from the following files:
/usr/src/dtsapplib/dtsguiapp/src/include/DTSListView.h
/usr/src/dtsapplib/dtsguiapp/src/DTSListView.cpp