DTS Application Library: dtsgui_curl Class Reference
dtsgui_curl Class Reference
#include <DTSApp.h>
Public Member Functions
DTS_OJBREF_CLASS (dtsgui_curl)
dtsgui_curl (class dtsgui *dtsgui)
void Close ()
DTSFrame * GetFrame ()
Detailed Description
Definition at line 42 of file DTSApp.h.
Constructor & Destructor Documentation
dtsgui_curl::dtsgui_curl (class dtsgui * dtsgui)
Definition at line 141 of file DTSApp.cpp.
References curl_setauth_cb(), curl_setprogress(), curlinit(), and dtsgui::GetFrame().
{
    frame = dtsgui->GetFrame();
    curl = curlinit();
    curl_setprogress(curl_progress_function, curl_progress_ctrl, curl_startprogress, dtsgui);
    curl_setauth_cb(CurlPasswd, this);
}
Member Function Documentation
void dtsgui_curl::Close ()
Definition at line 154 of file DTSApp.cpp.
References curlclose().
{
    if (curl) {
        curlclose();
        curl = 0;
    }
}
dtsgui_curl::DTS_OJBREF_CLASS (dtsgui_curl)
DTSFrame * dtsgui_curl::GetFrame (void)
Definition at line 223 of file DTSApp.cpp.
{
    return frame;
}
The documentation for this class was generated from the following files:
/usr/src/dtsapplib/dtsguiapp/src/include/DTSApp.h
/usr/src/dtsapplib/dtsguiapp/src/DTSApp.cpp