DTS Application Library: DTSTreeWindowEvent Class Reference
DTSTreeWindowEvent Class Reference
#include <DTSTreeWindow.h>
Public Member Functions
DTSTreeWindowEvent (void *userdata=NULL, dtsgui_tree_cb tree_cb=NULL, class dtsgui *dtsgui=NULL, DTSTreeWindow *win=NULL)
~DTSTreeWindowEvent ()
void TreeEvent (wxDataViewEvent &event)
void OnButton (wxCommandEvent &event)
void MenuEvent (wxCommandEvent &event)
void SplitterEvent (wxSplitterEvent &event)
void TreeCallback (const wxDataViewItem item, enum tree_cbtype cbtype)
Detailed Description
Definition at line 87 of file DTSTreeWindow.h.
Constructor & Destructor Documentation
DTSTreeWindowEvent::DTSTreeWindowEvent (void * userdata = NULL, dtsgui_tree_cb tree_cb = NULL, class dtsgui * dtsgui = NULL, DTSTreeWindow * win = NULL)
Definition at line 295 of file DTSTreeWindow.cpp.
References DTSDVMCtrl::GetStore(), DTSTreeWindow::GetTreeCtrl(), and objref().
{
    if (userdata && objref(userdata)) {
        data = userdata;
    } else {
        data = NULL;
    }
    treecb = tree_cb;
    parent = win;
    tree = win->GetTreeCtrl();
    vm = tree->GetStore();
    if (dtsgui && objref(dtsgui)) {
        this->dtsgui = dtsgui;
    } else {
        this->dtsgui = NULL;
    }
}
DTSTreeWindowEvent::~DTSTreeWindowEvent ()
Definition at line 312 of file DTSTreeWindow.cpp.
References objunref().
{
    if (dtsgui) {
        objunref(dtsgui);
    }
    if (data) {
        objunref(data);
    }
}
Member Function Documentation
void DTSTreeWindowEvent::MenuEvent (wxCommandEvent & event)
Definition at line 445 of file DTSTreeWindow.cpp.
References DTSFrame::Confirm(), DTSDVMListView::Delete(), DTS_TREEWIN_MENU_DELETE, DTS_TREEWIN_MENU_MOVEDOWN, DTS_TREEWIN_MENU_MOVEUP, DTS_TREEWIN_MENU_SORT, DTSGUI_TREE_CB_DELETE, DTSGUI_TREE_CB_SELECT, DTSDVMListView::GetParent(), and TreeCallback().
Referenced by DTSTreeWindow::DTSTreeWindow().
{
    enum treewinmenu eid;
    wxDataViewItem p_cont;
    DTSFrame *frame;
    eid=(treewinmenu)event.GetId();
    switch(eid) {
        case DTS_TREEWIN_MENU_MOVEDOWN:
        case DTS_TREEWIN_MENU_MOVEUP:
        case DTS_TREEWIN_MENU_SORT:
            p_cont = (a_cont == a_item) ? vm->GetParent(a_cont) : a_cont;
            SortParent(p_cont, eid);
            break;
        case DTS_TREEWIN_MENU_DELETE:
            frame = parent->GetFrame();
            if (frame->Confirm("Are you sure you want to delete this item")) {
                p_cont = vm->GetParent(a_item);
                tree->Select(p_cont);
                TreeCallback(p_cont, DTSGUI_TREE_CB_SELECT);
                TreeCallback(a_item, DTSGUI_TREE_CB_DELETE);
                vm->Delete(a_item);
            }
            break;
    }
}
void DTSTreeWindowEvent::OnButton (wxCommandEvent & event)
Definition at line 524 of file DTSTreeWindow.cpp.
References DTSPanel::Update_XML(), wx_PANEL_EVENT_BUTTON_NO, and wx_PANEL_EVENT_BUTTON_YES.
Referenced by DTSTreeWindow::DTSTreeWindow().
{
    dtsgui_treenode tn = parent->GetActiveNode();
    wxDataViewItem item;
    int eid = event.GetId();
    DTSPanel *pane = parent->GetClientPane();
    switch(eid) {
        case wx_PANEL_EVENT_BUTTON_YES:
            pane->Update_XML();
            break;
        case wx_PANEL_EVENT_BUTTON_NO:
            item = wxDataViewItem(tn);
            parent->Select(item);
            return;
        default:
            break;
    }
    event.Skip(true);
}
void DTSTreeWindowEvent::SplitterEvent (wxSplitterEvent & event)
Definition at line 471 of file DTSTreeWindow.cpp.
References DTSTreeWindow::SetTreePaneSize().
Referenced by DTSTreeWindow::DTSTreeWindow().
{
    DTSTreeWindow *tw;
    int evid;
    tw = (DTSTreeWindow*)parent;
    evid = event.GetEventType();
    if (evid == wxEVT_SPLITTER_SASH_POS_CHANGED) {
        tw->SetTreePaneSize();
    }
}
void DTSTreeWindowEvent::TreeCallback (const wxDataViewItem item, enum tree_cbtype cbtype)
Definition at line 483 of file DTSTreeWindow.cpp.
References DTSDVMListStore::ConfigPanel(), DTSGUI_TREE_CB_DELETE, DTSGUI_TREE_CB_EDIT, DTSGUI_TREE_CB_SELECT, DTSDVMListStore::GetTitle(), objref(), and objunref().
Referenced by MenuEvent(), and TreeEvent().
{
    void *tdata = NULL;
    DTSPanel *sp = NULL;
    wxWindow *op;
    DTSDVMListStore *ndata = (item.IsOk()) ? (DTSDVMListStore*)item.GetID() : NULL;
    if (!ndata) {
        return;
    }
    if (objref(data)) {
        tdata = data;
    }
    if (treecb) {
        sp = (DTSPanel*)treecb(dtsgui, parent, ndata, type, ndata->GetTitle().ToUTF8(), tdata);
    } else {
        switch(type) {
            case DTSGUI_TREE_CB_SELECT:
                sp = parent->CreatePane(wxDataViewItem(ndata));
                break;
            case DTSGUI_TREE_CB_EDIT:
                parent->UpdateNodeXML(wxDataViewItem(ndata), ndata->GetTitle());
                break;
            case DTSGUI_TREE_CB_DELETE:
                break;
        }
    }
    if (sp) {
        ndata->ConfigPanel(sp, parent);
        op = parent->SetWindow(sp, item);
        delete op;
    }
    if (tdata) {
        objunref(tdata);
    }
}
void DTSTreeWindowEvent::TreeEvent (wxDataViewEvent & event)
Definition at line 321 of file DTSTreeWindow.cpp.
References DTSDVMListStore::can_delete, DTSDVMListStore::can_edit, DTSDVMListStore::can_sort, DTSGUI_TREE_CB_EDIT, DTSGUI_TREE_CB_SELECT, DTSDVMListView::GetChildCount(), DTSDVMListView::GetNodeID(), DTSDVMListView::GetNthChild(), DTSDVMListView::GetParent(), DTSDVMListStore::GetTitle(), DTSDVMListStore::IsContainer(), DTSDVMListView::IsContainer(), DTSTreeWindow::SetPaneTitle(), DTSTreeWindow::ShowRMenu(), TreeCallback(), and DTSTreeWindow::TreeResize().
Referenced by DTSTreeWindow::DTSTreeWindow().
{
    DTSTreeWindow *tw;
    wxDataViewItem p_cont, f_item, l_item;
    int evid, cnt;
    bool cont,first = true,last = true;
    tw = (DTSTreeWindow*)parent;
    evid = event.GetEventType();
    if (evid == wxEVT_DATAVIEW_SELECTION_CHANGED) {
        a_item = event.GetItem();
        TreeCallback(a_item, DTSGUI_TREE_CB_SELECT);
        if ((vm->GetNodeID(a_item) == -1) && vm->IsContainer(a_item)) {
            tree->Expand(a_item);
        }
    } else if (evid == wxEVT_DATAVIEW_ITEM_EXPANDED) {
        parent->TreeResize();
    } else if (evid == wxEVT_DATAVIEW_ITEM_CONTEXT_MENU) {
        DTSDVMListStore *d_p, *d_i, *d_c;
        bool c_sort, del;
        if ((a_item = event.GetItem())) {
            if (vm->IsContainer(a_item)) {
                a_cont = a_item;
                p_cont = vm->GetParent(a_item);
                cont = true;
            } else {
                a_cont = vm->GetParent(a_item);
                p_cont = a_cont;
                cont = false;
            }
            d_p = (DTSDVMListStore*)p_cont.GetID();
            d_c = (DTSDVMListStore*)a_cont.GetID();
            cnt=vm->GetChildCount(p_cont);
            if (p_cont && d_p->can_sort && (cnt > 1)) {
                f_item = vm->GetNthChild(p_cont, 0);
                if (f_item != a_item) {
                    first = false;
                }
                l_item = vm->GetNthChild(p_cont, cnt-1);
                if (l_item != a_item) {
                    last = false;
                }
            }
            c_sort = (d_p && d_p->can_sort) || (d_c && d_c->can_sort);
            d_i = (DTSDVMListStore*)a_item.GetID();
            del = d_i->can_delete;
            tw->ShowRMenu(cont, vm->GetChildCount(a_cont), first, last, c_sort, del);
        }
    } else if (evid == wxEVT_DATAVIEW_ITEM_START_EDITING) {
        a_item = event.GetItem();
        DTSDVMListStore *data = (DTSDVMListStore*)event.GetItem().GetID();
        if (!data->can_edit) {
            event.Veto();
            if (data->IsContainer()) {
                if (tree->IsExpanded(a_item)) {
                    tree->Collapse(a_item);
                } else {
                    tree->Expand(a_item);
                }
            }
        }
    } else if (evid == wxEVT_DATAVIEW_ITEM_EDITING_DONE) {
#ifndef _WIN32
        DTSDVMListStore *data = (DTSDVMListStore*)event.GetItem().GetID();
        event.SetValue(data->GetTitle());
#endif
        parent->SetPaneTitle(event.GetValue());
        TreeCallback(event.GetItem(), DTSGUI_TREE_CB_EDIT);
    }
}
The documentation for this class was generated from the following files:
/usr/src/dtsapplib/dtsguiapp/src/include/DTSTreeWindow.h
/usr/src/dtsapplib/dtsguiapp/src/DTSTreeWindow.cpp