DTS Application Library: DTSStaticPanel Class Reference
DTSStaticPanel Class Reference
#include <DTSPanel.h>
Public Member Functions
DTSStaticPanel (wxWindow *, DTSFrame *=NULL, wxString=wxEmptyString, int=0)
DTSStaticPanel ()
virtual bool Show (bool=true)
Public Member Functions inherited from DTSPanel
DTSPanel (DTSFrame *=NULL, wxString=wxEmptyString, int=0)
~DTSPanel ()
void TextBox (const char *, const char *, wxString=wxEmptyString, int flags=wxTE_LEFT, int rows=1, void *data=NULL, enum form_data_type dtype=DTSGUI_FORM_DATA_PTR)
void PasswdBox (const char *, const char *, wxString=wxEmptyString, int flags=wxTE_LEFT, void *data=NULL, enum form_data_type dtype=DTSGUI_FORM_DATA_PTR)
void CheckBox (const char *title, const char *name, int ischecked, const char *checkval, const char *uncheckval, void *data=NULL, enum form_data_type dtype=DTSGUI_FORM_DATA_PTR)
class form_item * ListBox (const char *title, const char *name, const char *value, void *data=NULL, enum form_data_type dtype=DTSGUI_FORM_DATA_PTR)
class form_item * ComboBox (const char *title, const char *name, const char *value, void *data=NULL, enum form_data_type dtype=DTSGUI_FORM_DATA_PTR)
void XMLTextBox (const char *, const char *, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr, int flags=wxTE_LEFT, int rows=1)
void XMLPasswdBox (const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr, int flags)
void XMLCheckBox (const char *title, const char *name, const char *checkval, const char *uncheckval, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
class form_item * XMLListBox (const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
class form_item * XMLComboBox (const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
void AddItem (wxWindow *item, const wxGBPosition pos, const wxGBSpan span=wxDefaultSpan, int flags=0, int border=0, int growrow=-1)
void SetEventCallback (event_callback evcb, void *userdata=NULL, bool useref=false)
void SetConfigCallback (dtsgui_configcb cb, void *userdata=NULL)
void Update_XML ()
struct xml_node * Panel2XML (const char *xpath, const char *node, const char *nodeval, const char *attrkey)
struct curl_post * Panel2Post ()
class xml_element * GetNode (const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
bool ShowPanel (bool=true)
void SetTitle (const wxString new_title, bool create=false)
void SetStatus (const wxString new_status)
class form_item * FindItem (const char *name)
const char * FindValue (const char *name)
Public Member Functions inherited from DTSObject
DTSObject (wxString=wxEmptyString)
~DTSObject ()
wxString GetName ()
wxWindow * GetPanel ()
DTSFrame * GetFrame ()
void EventHandler (int eid, wxCommandEvent *event)
struct bucket_list * GetItems (void)
void SetUserData (void *data)
void * GetUserData (void)
void SetXMLDoc (struct xml_doc *xmldoc)
struct xml_doc * GetXMLDoc (void)
Additional Inherited Members
Data Fields inherited from DTSObject
panel_type type
int buttons [6]
Protected Member Functions inherited from DTSPanel
void Title (const char *title)
void SetSizerSize (wxSize, wxWindow *)
void SetupWin ()
void Buttons (void)
Protected Attributes inherited from DTSPanel
int button_mask
Detailed Description
Definition at line 124 of file DTSPanel.h.
Constructor & Destructor Documentation
DTSStaticPanel::DTSStaticPanel (wxWindow * parent, DTSFrame * frame = NULL, wxString status = wxEmptyString, int butmask = 0)
Definition at line 1012 of file DTSPanel.cpp.
References DTSObject::dtsevthandler, DTSPanelEvent::OnDialog(), DTSObject::panel, DTSPanel::SetupWin(), DTSObject::type, and wx_DTSPANEL_PANEL.
    :wxPanel(parent, wxID_ANY),
     DTSPanel(frame, status, butmask) {
    DTSPanelEvent *dtsevt = (DTSPanelEvent*)dtsevthandler;
    type = wx_DTSPANEL_PANEL;
    panel = dynamic_cast<wxPanel *>(this);
    panel->Bind(wxEVT_TEXT_ENTER, &DTSPanelEvent::OnDialog, dtsevt);
    SetupWin();
}
DTSStaticPanel::DTSStaticPanel ()
Definition at line 1022 of file DTSPanel.cpp.
References DTSObject::type, and wx_DTSPANEL_PANEL.
{
    type = wx_DTSPANEL_PANEL;
}
Member Function Documentation
bool DTSStaticPanel::Show (bool show = true) virtual
Reimplemented in DTSDialog.
Definition at line 1026 of file DTSPanel.cpp.
References DTSPanel::ShowPanel().
{
    ShowPanel(show);
    return wxPanel::Show(show);
}
The documentation for this class was generated from the following files:
/usr/src/dtsapplib/dtsguiapp/src/include/DTSPanel.h
/usr/src/dtsapplib/dtsguiapp/src/DTSPanel.cpp