DTS Application Library: xml_element Class Reference
xml_element Class Reference
#include <pitems.h>
Public Member Functions
DTS_OJBREF_CLASS (xml_element)
xml_element (const char *xp, struct xml_search *xs, const char *xa)
void Modify (struct xml_doc *xmldoc, const char *value)
const char * GetValue ()
Detailed Description
Definition at line 26 of file pitems.h.
Constructor & Destructor Documentation
xml_element::xml_element (const char * xp, struct xml_search * xs, const char * xa)
Definition at line 46 of file pitems.cpp.
{
    xpath = xp;
    xsearch = xs;
    if (xattr) {
        attr = strdup(xattr);
    }
}
Member Function Documentation
xml_element::DTS_OJBREF_CLASS (xml_element)
const char * xml_element::GetValue ()
Definition at line 67 of file pitems.cpp.
References objunref(), xml_node::value, xml_getattr(), and xml_getfirstnode().
Referenced by DTSPanel::XMLCheckBox(), DTSPanel::XMLComboBox(), DTSPanel::XMLListBox(), and DTSPanel::XMLTextBox().
{
    struct xml_node *xn;
    const char *ret = NULL;
    const char *tmp;
    if (!xsearch) {
        return NULL;
    }
    xn = xml_getfirstnode(xsearch, NULL);
    if (!attr) {
        if (xn->value) {
            ret = strdup(xn->value);
        }
    } else if ((tmp = xml_getattr(xn, attr))) {
        ret = strdup(tmp);
    }
    objunref(xn);
    return ret;
}
void xml_element::Modify (struct xml_doc * xmldoc, const char * value)
Definition at line 54 of file pitems.cpp.
References objunref(), xml_getfirstnode(), xml_modify(), and xml_setattr().
Referenced by DTSPanel::Update_XML().
{
    struct xml_node *xn;
    if ((xn = xml_getfirstnode(xsearch, NULL))) {
        if (attr) {
            xml_setattr(xmldoc, xn, attr, (value) ? value : "");
        } else {
            xml_modify(xmldoc, xn, (value) ? value : "");
        }
        objunref(xn);
    }
}
The documentation for this class was generated from the following files:
/usr/src/dtsapplib/dtsguiapp/src/include/pitems.h
/usr/src/dtsapplib/dtsguiapp/src/pitems.cpp