DTS Application Library: DTSAPPToolBar Class Reference
DTSAPPToolBar Class Reference
Application toolbar
Application toolbar class.
Public Member Functions
DTSAPPToolBar (struct dtsgui *dtsgui, wxWindow *parent, long style, wxWindowID id, wxString name, void *data)
Application toolbar.
~DTSAPPToolBar ()
Release references held.
Static Public Member Functions
static struct curl_post * GetPostInfo (const wxString &val)
Callback from DTSXMLComboBox.
Detailed Description
Application toolbar class.
Derived from wxToolbar.
Definition at line 45 of file toolbar.cpp.
Constructor & Destructor Documentation
DTSAPPToolBar::DTSAPPToolBar (struct dtsgui * dtsgui, wxWindow * parent, long style, wxWindowID id, wxString name, void * data)
Application toolbar.
Parameters
dtsgui Application data ptr.
parent Parent window.
style Toolbar Style.
id Toolbar ID.
name Toolbar name.
data Hold reference to this user data.
Definition at line 98 of file toolbar.cpp.
References GetPostInfo(), and objref().
{
    int servid;
    if (dtsgui && objref(dtsgui)) {
        this->dtsgui = (struct dtsgui*)dtsgui;
    } else {
        this->dtsgui = NULL;
    }
    itemid = wxID_AUTO_LOWEST;
    Create(parent, id, wxDefaultPosition, wxDefaultSize, style, name);
    proto = new wxComboBox(this, itemid++, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0, NULL, wxCB_READONLY);
    servid = itemid++;
    server = new DTSXMLComboBox(this, servid, "https://sip1.speakezi.co.za:666/auth/test.php", "/servers/Server", &DTSAPPToolBar::GetPostInfo, 3);
    server->SetSize(wxSize(300,-1));
    wxStaticText *text2 = new wxStaticText(this, wxID_ANY, "://");
    wxStaticText *text = new wxStaticText(this, wxID_ANY, "Server ");
    AddControl(text);
    proto->Append("http");
    proto->Append("https");
    proto->Append("https [:666]");
    proto->SetSelection(2);
    AddControl(proto);
    AddControl(text2);
    AddControl(server);
    AddStretchableSpace();
    Bind(wxEVT_TEXT_ENTER, &DTSAPPToolBar::HandleEvent, this, servid, servid, NULL);
    Bind(wxEVT_COMBOBOX, &DTSAPPToolBar::HandleEvent, this, servid, servid, NULL);
    Bind(wxEVT_COMBOBOX_DROPDOWN, &DTSAPPToolBar::HandleEvent, this, servid, servid, NULL);
}
DTSAPPToolBar::~DTSAPPToolBar ()
Release references held.
Definition at line 133 of file toolbar.cpp.
References objunref().
{
    if (dtsgui) {
        objunref(dtsgui);
    }
}
Member Function Documentation
struct curl_post * DTSAPPToolBar::GetPostInfo (const wxString & val) static read
Callback from DTSXMLComboBox.
Parameters
val Value used to create a curl_post structure.
Returns
curl_post structure to send in XML request.
Definition at line 139 of file toolbar.cpp.
References curl_newpost(), and curl_postitem().
Referenced by DTSAPPToolBar().
{
    struct curl_post *post;
    post = curl_newpost();
    curl_postitem(post, "function", "getcust");
    curl_postitem(post, "search", val);
    return post;
}
The documentation for this class was generated from the following file:
/usr/src/dtsapplib/dtsguiapp/app/toolbar.cpp