DTS Application Library: dynamic_panel Class Reference
dynamic_panel Class Reference
#include <evdata.h>
Public Member Functions
DTS_OJBREF_CLASS (dynamic_panel)
dynamic_panel (const char *name, int blank, dtsgui_dynpanel cb, void *udata)
bool HasCallback ()
bool IsBlank ()
bool operator== (wxWindow &rhs)
wxWindow * RunCallback (class dtsgui *dtsgui)
Detailed Description
Definition at line 24 of file evdata.h.
Constructor & Destructor Documentation
dynamic_panel::dynamic_panel (const char * name, int blank, dtsgui_dynpanel cb, void * udata)
Definition at line 36 of file evdata.cpp.
References ALLOC_CONST, and objref().
{
    if (udata && objref(udata)) {
        data = udata;
    } else {
        data = NULL;
    }
    ALLOC_CONST(this->name, name);
    this->cb = cb;
    this->blank = blank;
}
Member Function Documentation
dynamic_panel::DTS_OJBREF_CLASS (dynamic_panel)
bool dynamic_panel::HasCallback ()
Definition at line 56 of file evdata.cpp.
Referenced by DTSFrame::DynamicPanelEvent().
{
    return (cb);
}
bool dynamic_panel::IsBlank ()
Definition at line 60 of file evdata.cpp.
Referenced by DTSFrame::DynamicPanelEvent().
{
    return (blank);
}
bool dynamic_panel::operator== (wxWindow & rhs)
Definition at line 64 of file evdata.cpp.
{
    return (this->w == &rhs);
}
wxWindow * dynamic_panel::RunCallback (class dtsgui * dtsgui)
Definition at line 68 of file evdata.cpp.
References DTSObject::GetPanel(), xml_node::name, objref(), and objunref().
Referenced by DTSFrame::DynamicPanelEvent().
{
    DTSObject *p;
    if (w) {
        delete w;
        w = NULL;
    }
    if (dtsgui && objref(dtsgui)) {
        if ((p = (DTSObject*)cb(dtsgui, name, data))) {
            w = p->GetPanel();
        }
        objunref(dtsgui);
    }
    return w;
}
The documentation for this class was generated from the following files:
/usr/src/dtsapplib/dtsguiapp/src/include/evdata.h
/usr/src/dtsapplib/dtsguiapp/src/evdata.cpp