DTS Application Library: DTSTabWindowEvent Class Reference
DTSTabWindowEvent Class Reference
#include <DTSTreeWindow.h>
Public Member Functions
DTSTabWindowEvent (void *userdata=NULL, DTSTabWindow *win=NULL)
~DTSTabWindowEvent ()
void PageChange (wxBookCtrlEvent &event)
void PageChanged (wxBookCtrlEvent &event)
void RightMenu (wxCommandEvent &event)
void OnButton (wxCommandEvent &event)
Detailed Description
Definition at line 136 of file DTSTreeWindow.h.
Constructor & Destructor Documentation
DTSTabWindowEvent::DTSTabWindowEvent (void * userdata = NULL, DTSTabWindow * win = NULL)
Definition at line 825 of file DTSTreeWindow.cpp.
References objref().
{
    if (userdata && objref(userdata)) {
        data = userdata;
    } else {
        data = NULL;
    }
    tw = win;
}
DTSTabWindowEvent::~DTSTabWindowEvent ()
Definition at line 834 of file DTSTreeWindow.cpp.
References objunref().
{
    if (data) {
        objunref(data);
    }
}
Member Function Documentation
void DTSTabWindowEvent::OnButton (wxCommandEvent & event)
Definition at line 840 of file DTSTreeWindow.cpp.
References DTSPanel::Update_XML(), wx_PANEL_EVENT_BUTTON_NO, and wx_PANEL_EVENT_BUTTON_YES.
Referenced by DTSTabWindow::Show().
{
    DTSTabPage *pane = dynamic_cast<DTSTabPage*>(tw->GetCurrentPage());
    int eid = event.GetId();
    int pg = tw->GetSelection();
    switch(eid) {
        case wx_PANEL_EVENT_BUTTON_YES:
            pane->Update_XML();
        /*no break here will reload tab*/
        case wx_PANEL_EVENT_BUTTON_NO:
            pg++;
            tw->Undo(pg);
            return;
        default:
            break;
    }
    event.Skip(true);
}
void DTSTabWindowEvent::PageChange (wxBookCtrlEvent & event)
Definition at line 864 of file DTSTreeWindow.cpp.
References DTSTabPage::ConfigPane().
Referenced by DTSTabWindow::Show().
{
    wxWindow *w;
    DTSTabPage *tp;
    int p = event.GetSelection();
    if (p != wxNOT_FOUND) {
        w = tw->GetPage(p);
        tp = dynamic_cast<DTSTabPage*>(w);
        tp->ConfigPane();
    }
}
void DTSTabWindowEvent::PageChanged (wxBookCtrlEvent & event)
Definition at line 876 of file DTSTreeWindow.cpp.
Referenced by DTSTabWindow::Show().
{
    wxWindow *w;
    int p = event.GetSelection();
    if (p != wxNOT_FOUND) {
        w = tw->GetPage(p);
        w->FitInside();
        w->Layout();
        w->Refresh();
    }
}
void DTSTabWindowEvent::RightMenu (wxCommandEvent & event)
Definition at line 860 of file DTSTreeWindow.cpp.
Referenced by DTSTabWindow::DTSTabWindow().
{
    printf("MENU\n");
}
The documentation for this class was generated from the following files:
/usr/src/dtsapplib/dtsguiapp/src/include/DTSTreeWindow.h
/usr/src/dtsapplib/dtsguiapp/src/DTSTreeWindow.cpp