DTS Application Library: tree_newnode Class Reference
tree_newnode Class Reference
#include <DTSTreeWindow.h>
Public Member Functions
DTS_OJBREF_CLASS (tree_newnode)
tree_newnode (dtsgui_treeview tree, dtsgui_treenode tn, const char *xpath, const char *node, const char *vitem, const char *tattr, int nid, int flags, dtsgui_xmltreenode_cb node_cb, void *data, dtsgui_treeviewpanel_cb p_cb)
Static Public Member Functions
static int handle_newtreenode_cb (class dtsgui *dtsgui, dtsgui_pane p, int type, int event, void *data)
Detailed Description
Definition at line 33 of file DTSTreeWindow.h.
Constructor & Destructor Documentation
tree_newnode::tree_newnode (dtsgui_treeview tree, dtsgui_treenode tn, const char * xpath, const char * node, const char * vitem, const char * tattr, int nid, int flags, dtsgui_xmltreenode_cb node_cb, void * data, dtsgui_treeviewpanel_cb p_cb)
Definition at line 66 of file DTSTreeWindow.cpp.
References ALLOC_CONST, and objref().
Referenced by DTS_C_API::dtsgui_newxmltreenode().
{
    if (data && objref(data)) {
        this->data = data;
    } else {
        this->data = NULL;
    }
    this->tv = tree;
    this->tn = tn;
    ALLOC_CONST(this->xpath, xpath);
    ALLOC_CONST(this->node, node);
    ALLOC_CONST(this->vitem, vitem);
    ALLOC_CONST(this->tattr, tattr);
    this->flags = flags;
    this->type = nid;
    this->node_cb = node_cb;
    this->p_cb = p_cb;
}
Member Function Documentation
tree_newnode::DTS_OJBREF_CLASS (tree_newnode)
int tree_newnode::handle_newtreenode_cb (class dtsgui * dtsgui, dtsgui_pane p, int type, int event, void * data) static
Definition at line 85 of file DTSTreeWindow.cpp.
References wx_PANEL_EVENT_BUTTON, and wx_PANEL_EVENT_BUTTON_YES.
Referenced by DTS_C_API::dtsgui_newxmltreenode().
{
    class tree_newnode *nn = (class tree_newnode*)data;
    DTSPanel *dp = (DTSPanel*)p;
    if (type != wx_PANEL_EVENT_BUTTON) {
        return 1;
    }
    switch(event) {
        case wx_PANEL_EVENT_BUTTON_YES:
            break;
        default:
            return 1;
    }
    return nn->handle_newtreenode(dtsgui, dp);
}
The documentation for this class was generated from the following files:
/usr/src/dtsapplib/dtsguiapp/src/include/DTSTreeWindow.h
/usr/src/dtsapplib/dtsguiapp/src/DTSTreeWindow.cpp