DTS Application Library: tab_newpane Class Reference
tab_newpane Class Reference
#include <DTSTreeWindow.h>
Public Member Functions
DTS_OJBREF_CLASS (tab_newpane)
tab_newpane (DTSTabWindow *tabv, const char *xpath, const char *node, const char *vitem, const char *tattr, dtsgui_tabpane_newdata_cb data_cb, dtsgui_tabpanel_cb cb, void *cdata, struct xml_doc *xmldoc, void *data)
Static Public Member Functions
static int handle_newtabpane_cb (class dtsgui *dtsgui, dtsgui_pane p, int type, int event, void *data)
Detailed Description
Definition at line 54 of file DTSTreeWindow.h.
Constructor & Destructor Documentation
tab_newpane::tab_newpane (DTSTabWindow * tabv, const char * xpath, const char * node, const char * vitem, const char * tattr, dtsgui_tabpane_newdata_cb data_cb, dtsgui_tabpanel_cb cb, void * cdata, struct xml_doc * xmldoc, void * data)
Definition at line 145 of file DTSTreeWindow.cpp.
References ALLOC_CONST, and objref().
Referenced by DTS_C_API::dtsgui_newxmltabpane().
{
    DTSTabWindow *tv = (DTSTabWindow*)tabv;
    if (data && objref(data)) {
        this->data = data;
    }
    if (cdata && objref(cdata)) {
        this->cdata = cdata;
    }
    this->tabv = tabv;
    if (xmldoc && objref(xmldoc)) {
        this->xmldoc = xmldoc;
    }
    ALLOC_CONST(this->xpath, xpath);
    ALLOC_CONST(this->node, node);
    ALLOC_CONST(this->vitem, vitem);
    ALLOC_CONST(this->tattr, tattr);
    this->last = tv->GetPageCount() - 1;
    this->cb = cb;
    this->data_cb = data_cb;
}
Member Function Documentation
tab_newpane::DTS_OJBREF_CLASS (tab_newpane)
int tab_newpane::handle_newtabpane_cb (class dtsgui * dtsgui, dtsgui_pane p, int type, int event, void * data) static
Definition at line 198 of file DTSTreeWindow.cpp.
References wx_PANEL_EVENT_BUTTON, and wx_PANEL_EVENT_BUTTON_YES.
Referenced by DTS_C_API::dtsgui_newxmltabpane().
{
    class tab_newpane *tp = (class tab_newpane*)data;
    DTSPanel *dp = (DTSPanel*)p;
    if (type != wx_PANEL_EVENT_BUTTON) {
        return 1;
    }
    switch(event) {
        case wx_PANEL_EVENT_BUTTON_YES:
            break;
        default:
            return 1;
    }
    return tp->handle_newtabpane(dtsgui, dp);
}
The documentation for this class was generated from the following files:
/usr/src/dtsapplib/dtsguiapp/src/include/DTSTreeWindow.h
/usr/src/dtsapplib/dtsguiapp/src/DTSTreeWindow.cpp