DTS Application Library: DTSFrame Class Reference
DTSFrame Class Reference
#include <DTSFrame.h>
Public Member Functions
DTSFrame (const wxString &title, const wxPoint &pos, const wxSize &size, class dtsgui *dtsgui)
~DTSFrame ()
wxMenuBar * GetMenuBar (void)
void CloseMenu (wxMenu *m, int type)
wxMenu * NewMenu (const wxString &name)
void SetAbout (wxMenu *m, const char *a_text)
bool Confirm (wxString text)
void Alert (wxString text)
class basic_auth * Passwd (const char *user, const char *passwd)
const char * FileDialog (const char *title, const char *path, const char *name, const char *filter, long style)
int StartProgress (const wxString &text, int maxval, int quit)
void EndProgress (void)
int UpdateProgress (int cval, const wxString &msg)
int IncProgress (int ival, const wxString &msg)
void SetWindow (wxWindow *window)
class dtsgui * GetDTSData (void)
virtual wxToolBar * OnCreateToolBar (long style, wxWindowID id, const wxString &name)
void SetupToolbar (dtsgui_toolbar_create cb, void *data)
DTSPanel * CreatePane (const wxString &name, const wxString &title, int butmask, enum panel_type type, void *udata)
DTSWindow * TextPanel (const wxString &title, const char *buf)
wxMenuItem * NewMenuItem (wxMenu *m, DTSObject *panel, int menuid, const wxString &hint)
wxMenuItem * NewMenuItem (wxMenu *m, int menuid, const wxString &name, const wxString &hint, int blank, dtsgui_dynpanel cb, void *data)
void SendDTSEvent (int eid, wxObject *evobj)
void SwitchWindow (wxCommandEvent &event)
void DynamicPanelEvent (wxCommandEvent &event)
void OnClose (wxCommandEvent &event)
void OnAbort (wxCloseEvent &event)
void OnAbout (wxCommandEvent &event)
Detailed Description
Definition at line 31 of file DTSFrame.h.
Constructor & Destructor Documentation
DTSFrame::DTSFrame (const wxString & title, const wxPoint & pos, const wxSize & size, class dtsgui * dtsgui)
Definition at line 43 of file DTSFrame.cpp.
References objref(), and OnAbort().
    : wxFrame(NULL, wxID_ANY, title, pos, size) {
    if (!dtsgui || !objref(dtsgui)) {
        return;
    }
    this->dtsgui = dtsgui;
    /*deleted on close*/
    menubar = new wxMenuBar;
    SetMenuBar(menubar);
    CreateStatusBar();
    tbcb = NULL;
    tb_data = NULL;
//  pbar = new wxGauge(toolbar, wxID_ANY, 1000);
    pbar = NULL;
    pdia = NULL;
    about = wxEmptyString;
    /*deleted on close*/
    sizer = new wxBoxSizer(wxHORIZONTAL);
    this->SetSizer(sizer);
    SetMinSize(size);
    blank = new wxWindow(this, -1);
    sizer->Add(blank, 1, wxALL | wxEXPAND);
    a_window = blank;
    blank->Show(true);
    abortconfirm = true;
    Bind(wxEVT_CLOSE_WINDOW, &DTSFrame::OnAbort, this);
    Bind(DTS_APP_EVENT, &DTSFrame::OnDTSEvent, this);
    Show(true);
    Raise();
}
DTSFrame::~DTSFrame ()
Definition at line 86 of file DTSFrame.cpp.
References objunref().
                    {
    objunref(dtsgui);
    if (tb_data) {
        objunref(tb_data);
    }
    delete blank;
}
Member Function Documentation
void DTSFrame::Alert (wxString text)
Definition at line 120 of file DTSFrame.cpp.
Referenced by DTS_C_API::dtsgui_alert().
{
    wxMessageDialog *alert;
    alert = new wxMessageDialog(NULL, text, wxT("Alert"),
                                  wxOK | wxICON_EXCLAMATION);
    alert->ShowModal();
    alert->Destroy();
}
void DTSFrame::CloseMenu (wxMenu * m, int type)
Definition at line 353 of file DTSFrame.cpp.
References OnClose().
Referenced by DTS_C_API::dtsgui_close(), and DTS_C_API::dtsgui_exit().
{
    switch (type) {
        case wxID_EXIT:
            m->Append(type, "&Quit", "Quit And Exit");
            Bind(wxEVT_COMMAND_MENU_SELECTED, &DTSFrame::OnClose, this, wxID_EXIT);
            break;
        case wxID_SAVE:
            m->Append(type, "E&xit", "Save And Exit");
            Bind(wxEVT_COMMAND_MENU_SELECTED, &DTSFrame::OnClose, this, wxID_SAVE);
            break;
    }
}
bool DTSFrame::Confirm (wxString text)
Definition at line 104 of file DTSFrame.cpp.
Referenced by DTS_C_API::dtsgui_confirm(), DTSTreeWindowEvent::MenuEvent(), OnAbort(), and OnClose().
{
    wxMessageDialog *confirm;
    int res;
    confirm = new wxMessageDialog(NULL, text, wxT("Confirm"),
                                  wxYES_NO | wxNO_DEFAULT | wxICON_QUESTION);
    res = confirm->ShowModal();
    confirm->Destroy();
    if (res == wxID_YES) {
        return true;
    } else {
        return false;
    }
}
DTSPanel * DTSFrame::CreatePane (const wxString & name, const wxString & title, int butmask, enum panel_type type, void * udata)
Definition at line 375 of file DTSFrame.cpp.
References DTSPanel::SetTitle(), DTSObject::SetUserData(), wx_DTSPANEL_DIALOG, wx_DTSPANEL_PANEL, wx_DTSPANEL_SCROLLPANEL, wx_DTSPANEL_TAB, wx_DTSPANEL_TREE, wx_DTSPANEL_WINDOW, and wx_DTSPANEL_WIZARD.
Referenced by dtsgui_wizard::AddPage(), DTS_C_API::dtsgui_panel(), and Passwd().
{
    DTSPanel *dp = NULL;
    switch (type) {
        case wx_DTSPANEL_SCROLLPANEL:
            dp = new DTSScrollPanel(this, this, name, butmask);
            break;
        case wx_DTSPANEL_PANEL:
            dp = new DTSStaticPanel(this, this, name, butmask);
            break;
        case wx_DTSPANEL_WINDOW:
            dp = new DTSWindow(this);
            break;
        case wx_DTSPANEL_DIALOG:
            dp = new DTSDialog(this, name, butmask);
            break;
        case wx_DTSPANEL_WIZARD:
            dp = new DTSWizardWindow(name);
            break;
        case wx_DTSPANEL_TAB:
        case wx_DTSPANEL_TREE:
            break;
    }
    if (title.Len() > 0) {
        dp->SetTitle(title, true);
    }
    if (udata) {
        dp->SetUserData(udata);
    }
    return dp;
}
void DTSFrame::DynamicPanelEvent (wxCommandEvent & event)
Definition at line 272 of file DTSFrame.cpp.
References evdata::data, dynamic_panel::HasCallback(), dynamic_panel::IsBlank(), dynamic_panel::RunCallback(), and SetWindow().
Referenced by NewMenuItem().
{
    class evdata *evdat;
    class dynamic_panel *p_dyn;
    wxWindow *w;
    if (!(evdat = (evdata *)event.m_callbackUserData)) {
        SetWindow(NULL);
        return;
    }
    if (!evdat->data || !(p_dyn = (class dynamic_panel*)evdat->data) || !p_dyn->HasCallback() ) {
        SetWindow(NULL);
        return;
    }
    if (*p_dyn == *a_window) {
        return;
    }
    if (p_dyn->IsBlank()) {
        SetWindow(NULL);
    }
    if ((w = p_dyn->RunCallback(dtsgui))) {
        SetWindow(w);
    }
}
void DTSFrame::EndProgress (void)
Definition at line 181 of file DTSFrame.cpp.
Referenced by DTS_C_API::dtsgui_progress_end().
{
    if (pdia) {
        pdia->Hide();
        delete pdia;
        pdia = NULL;
    }
/*  if (pbar) {
        pbar->Hide();
    }*/
}
const char * DTSFrame::FileDialog (const char * title, const char * path, const char * name, const char * filter, long style)
Definition at line 408 of file DTSFrame.cpp.
References objchar().
Referenced by DTS_C_API::dtsgui_fileopen(), and DTS_C_API::dtsgui_filesave().
{
    void *filename = NULL;
    wxFileDialog *fd;
    fd = new wxFileDialog(this, title, (path) ? path : "", (name) ? name : "", (filter) ? filter : wxFileSelectorDefaultWildcardStr, style);
    if (fd->ShowModal() != wxID_CANCEL) {
        filename = objchar(fd->GetPath().ToUTF8());
    }
    delete fd;
    return (const char*)filename;
}
class dtsgui * DTSFrame::GetDTSData (void)
Definition at line 307 of file DTSFrame.cpp.
References dtsgui::dtsgui(), and objref().
Referenced by DTSTreeWindow::DTSTreeWindow().
{
    if (dtsgui && objref(dtsgui)) {
        return dtsgui;
    }
    return NULL;
}
wxMenuBar * DTSFrame::GetMenuBar (void)
Definition at line 349 of file DTSFrame.cpp.
{
    return menubar;
}
int DTSFrame::IncProgress (int ival, const wxString & msg)
Definition at line 166 of file DTSFrame.cpp.
Referenced by DTS_C_API::dtsgui_progress_increment().
{
/*  if (pbar) {
        pbar->SetValue(pbar->GetValue()+ival);
    }*/
    if (pdia) {
        if (pdia->Update(pdia->GetValue()+ival, text)) {
            return 1;
        } else {
            return 0;
        }
    } else {
        return 0;
    }
}
wxMenu * DTSFrame::NewMenu (const wxString & name)
Definition at line 366 of file DTSFrame.cpp.
Referenced by DTS_C_API::dtsgui_newmenu().
{
    wxMenu *new_menu = NULL;
    new_menu = new wxMenu;
    menubar->Append(new_menu, name);
    return new_menu;
}
wxMenuItem * DTSFrame::NewMenuItem (wxMenu * m, DTSObject * panel, int menuid, const wxString & hint)
Definition at line 436 of file DTSFrame.cpp.
References DTSObject::GetName(), DTSObject::GetPanel(), and SwitchWindow().
Referenced by DTS_C_API::dtsgui_newmenucb(), and DTS_C_API::dtsgui_newmenuitem().
{
    wxMenuItem *mi;
    wxWindow *w = NULL;
    wxObject *ev_data;
    wxString name = wxEmptyString;
    if (panel) {
        w = panel->GetPanel();
        name = panel->GetName();
    }
    ev_data = new evdata(w);
    mi = m->Append(menuid, hint, name);
    Bind(wxEVT_COMMAND_MENU_SELECTED, &DTSFrame::SwitchWindow, this, menuid, menuid, ev_data);
    return mi;
}
wxMenuItem * DTSFrame::NewMenuItem (wxMenu * m, int menuid, const wxString & name, const wxString & hint, int blank, dtsgui_dynpanel cb, void * data)
Definition at line 454 of file DTSFrame.cpp.
References DynamicPanelEvent(), and objunref().
{
    wxMenuItem *mi;
    wxObject *ev_data;
    class dynamic_panel *p_dyn;
    if (!(p_dyn = new dynamic_panel(name, blank, cb, data))) {
        return NULL;
    }
    ev_data = new evdata(p_dyn, 1);
    objunref(p_dyn);
    mi = m->Append(menuid, hint, name);
    Bind(wxEVT_COMMAND_MENU_SELECTED, &DTSFrame::DynamicPanelEvent, this, menuid, menuid, ev_data);
    return mi;
}
void DTSFrame::OnAbort (wxCloseEvent & event)
Definition at line 196 of file DTSFrame.cpp.
References Confirm().
Referenced by DTSFrame().
{
    if (abortconfirm && !Confirm("Are You Sure You Want To Abort ?")) {
        event.Veto();
    } else {
        event.Skip(true);
    }
}
void DTSFrame::OnAbout (wxCommandEvent & event)
Definition at line 231 of file DTSFrame.cpp.
Referenced by SetAbout().
{
    wxMessageBox(about, "About", wxOK | wxICON_INFORMATION );
}
void DTSFrame::OnClose (wxCommandEvent & event)
Definition at line 204 of file DTSFrame.cpp.
References Confirm().
Referenced by CloseMenu().
{
    bool confirm;
    int eid;
    eid=event.GetId();
    switch (eid) {
        case wxID_EXIT:
            confirm = Confirm("Quit Without Saving ?");
            break;
        case wxID_SAVE:
            confirm = Confirm("Save And Exit ?");
            break;
        default:
            confirm = true;
    }
    if (confirm) {
        abortconfirm = false;
        Close(true);
    } else {
        event.Skip();
    }
}
wxToolBar * DTSFrame::OnCreateToolBar (long style, wxWindowID id, const wxString & name) virtual
Definition at line 314 of file DTSFrame.cpp.
References objref(), and objunref().
{
    wxToolBar *tb;
    if (tbcb) {
        objref(dtsgui);
        tb = (wxToolBar*)tbcb(dtsgui, this, style, id, name, tb_data);
        objunref(dtsgui);
    } else {
        tb = new wxToolBar(this, id, wxDefaultPosition, wxDefaultSize, style, name);
    }
    return tb;
}
class basic_auth * DTSFrame::Passwd (const char * user, const char * passwd)
Definition at line 496 of file DTSFrame.cpp.
References CreatePane(), curl_newauth(), DTSGUI_FORM_DATA_PTR, basic_auth::passwd, DTSDialog::RunDialog(), DTSPanel::TextBox(), basic_auth::user, wx_DTSPANEL_DIALOG, and wx_PANEL_BUTTON_ACTION.
Referenced by DTS_C_API::dtsgui_pwdialog().
{
    struct basic_auth *bauth;
    DTSDialog *pwbox;
    if (!(bauth = curl_newauth(user, passwd))) {
        return NULL;
    }
    pwbox = (DTSDialog*)CreatePane("Athentification", wxEmptyString, wx_PANEL_BUTTON_ACTION, wx_DTSPANEL_DIALOG, bauth);
    pwbox->TextBox("Username", "uname", bauth->user, wxTE_LEFT | wxTE_PROCESS_ENTER, 1, NULL, DTSGUI_FORM_DATA_PTR);
    pwbox->TextBox("Password", "pwd", bauth->passwd, wxTE_PASSWORD | wxTE_PROCESS_ENTER, 1, NULL,  DTSGUI_FORM_DATA_PTR);
    pwbox->RunDialog(pwevent, NULL);
    return bauth;
}
void DTSFrame::SendDTSEvent (int eid, wxObject * evobj)
Definition at line 300 of file DTSFrame.cpp.
Referenced by DTS_C_API::dtsgui_sendevent().
{
    wxCommandEvent event(DTS_APP_EVENT, eid);
    event.SetEventObject(evobj);
    event.ShouldPropagate();
    ProcessWindowEvent(event);
}
void DTSFrame::SetAbout (wxMenu * m, const char * a_text)
Definition at line 94 of file DTSFrame.cpp.
References OnAbout().
Referenced by DTS_C_API::dtsgui_about().
{
    if (about.Len() > 0) {
        return;
    }
    m->Append(wxID_ABOUT);
    Bind(wxEVT_COMMAND_MENU_SELECTED, &DTSFrame::OnAbout, this, wxID_ABOUT);
    about = a_text;
}
void DTSFrame::SetupToolbar (dtsgui_toolbar_create cb, void * data)
Definition at line 328 of file DTSFrame.cpp.
References objref(), and objunref().
Referenced by DTS_C_API::dtsgui_setuptoolbar().
{
    tbcb = cb;
    if (tb_data) {
        objunref(tb_data);
        tb_data = NULL;
    }
    if (data && objref(data)) {
        tb_data = data;
    }
    toolbar = CreateToolBar();
    if (pbar) {
        toolbar->AddControl(pbar);
        pbar->Hide();
    }
    toolbar->Realize();
}
void DTSFrame::SetWindow (wxWindow * window)
Definition at line 235 of file DTSFrame.cpp.
References dtsgui::SetStatusText().
Referenced by DTS_C_API::dtsgui_setwindow(), DynamicPanelEvent(), and SwitchWindow().
{
    if (!window) {
        window = blank;
    }
    if (window == a_window) {
        return;
    }
    a_window->Show(false);
    sizer->Replace(a_window, window);
    if (window == blank) {
        dtsgui->SetStatusText();
    }
    window->Show(true);
    sizer->Layout();
    sizer->FitInside(this);
    a_window = window;
}
int DTSFrame::StartProgress (const wxString & text, int maxval, int quit)
Definition at line 129 of file DTSFrame.cpp.
Referenced by DTS_C_API::dtsgui_progress_start().
{
    int flags;
    if (!quit && pbar) {
        pbar->SetRange(maxval);
        pbar->Show();
        pbar->Pulse();
        return 1;
    } else {
        flags = wxPD_APP_MODAL | wxPD_AUTO_HIDE | wxPD_ELAPSED_TIME;
        if (quit) {
            flags |= wxPD_CAN_ABORT;
        }
        if ((pdia = new wxProgressDialog("Progress", text, maxval, NULL, flags))) {
            pdia->Show();
            pdia->Pulse();
            return 1;
        }
    }
    return 0;
}
void DTSFrame::SwitchWindow (wxCommandEvent & event)
Definition at line 257 of file DTSFrame.cpp.
References evdata::data, and SetWindow().
Referenced by NewMenuItem().
{
    wxWindow *window;
    class evdata *evdat;
    evdat = (evdata*)event.m_callbackUserData;
    if (!evdat || (!(window = (wxWindow*)evdat->data))) {
        window = blank;
    }
    if (window != a_window) {
        SetWindow(window);
    }
}
DTSWindow * DTSFrame::TextPanel (const wxString & title, const char * buf)
Definition at line 421 of file DTSFrame.cpp.
References DTSPanel::AddItem(), and DTSObject::GetPanel().
Referenced by DTS_C_API::dtsgui_textpane().
{
    DTSWindow *p;
    wxWindow *w;
    wxTextCtrl *tc;
    p = new DTSWindow(this, this, title);
    w = p->GetPanel();
    tc = new wxTextCtrl(w, -1, buf, wxDefaultPosition, wxDefaultSize,wxTE_MULTILINE | wxHSCROLL | wxTE_READONLY);
    p->AddItem(tc, wxGBPosition(0,0), wxGBSpan(10, 6), wxEXPAND|wxGROW, 0, 0);
    return p;
}
int DTSFrame::UpdateProgress (int cval, const wxString & msg)
Definition at line 151 of file DTSFrame.cpp.
Referenced by DTS_C_API::dtsgui_progress_update().
{
/*  if (pbar) {
        pbar->SetValue(cval);
    }*/
    if (pdia) {
        if (pdia->Update(cval, text)) {
            return 1;
        } else {
            return 0;
        }
    } else {
        return 0;
    }
}
The documentation for this class was generated from the following files:
/usr/src/dtsapplib/dtsguiapp/src/include/DTSFrame.h
/usr/src/dtsapplib/dtsguiapp/src/DTSFrame.cpp