DTS Application Library: dtsgui Class Reference
dtsgui Class Reference
#include <DTSApp.h>
Public Member Functions
DTS_OJBREF_CLASS (dtsgui)
dtsgui (const char *title, const char *stat, struct point *w_size, struct point *w_pos, dtsgui_configcb confcallback_cb, void *userdata)
int SetupAPPFrame (void)
void * GetUserData (void)
void SetStatusText (void)
void AppendTitle (const char *text)
class DTSFrame * GetFrame (void)
void ShowToolbar (bool show=true)
Detailed Description
Definition at line 22 of file DTSApp.h.
Constructor & Destructor Documentation
dtsgui::dtsgui (const char * title, const char * stat, struct point * w_size, struct point * w_pos, dtsgui_configcb confcallback_cb, void * userdata)
Definition at line 35 of file DTSApp.cpp.
References ALLOC_CONST, and objref().
Referenced by DTSFrame::GetDTSData().
{
    wsize = w_size;
    wpos = w_pos;
    cb = confcallback_cb;
    if (data && objref(data)) {
        userdata = data;
    } else {
        userdata = NULL;
    }
    ALLOC_CONST(this->status, stat);
    ALLOC_CONST(this->title, title);
}
Member Function Documentation
void dtsgui::AppendTitle (const char * text)
Definition at line 105 of file DTSApp.cpp.
References objlock(), and objunlock().
Referenced by DTS_C_API::dtsgui_titleappend().
{
    char *newtitle;
    int len;
    objlock(this);
    if (text) {
        len = strlen(title)+strlen(text)+4;
        if ((newtitle=(char*)malloc(len))) {
            snprintf(newtitle, len, "%s [%s]", title, text);
        } else {
            newtitle = (char*)title;
        }
    } else {
        newtitle = (char*)title;
    }
    objunlock(this);
    appframe->SetTitle(newtitle);
    if (text && newtitle) {
        free(newtitle);
    }
}
dtsgui::DTS_OJBREF_CLASS (dtsgui)
class DTSFrame * dtsgui::GetFrame (void)
Definition at line 137 of file DTSApp.cpp.
Referenced by dtsgui_wizard::AddPage(), DTS_C_API::dtsgui_about(), DTS_C_API::dtsgui_alert(), DTS_C_API::dtsgui_close(), DTS_C_API::dtsgui_confirm(), dtsgui_curl::dtsgui_curl(), DTS_C_API::dtsgui_exit(), DTS_C_API::dtsgui_fileopen(), DTS_C_API::dtsgui_filesave(), DTS_C_API::dtsgui_newmenu(), DTS_C_API::dtsgui_newmenucb(), DTS_C_API::dtsgui_newmenuitem(), DTS_C_API::dtsgui_newwizard(), DTS_C_API::dtsgui_panel(), DTS_C_API::dtsgui_progress_end(), DTS_C_API::dtsgui_progress_increment(), DTS_C_API::dtsgui_progress_start(), DTS_C_API::dtsgui_progress_update(), DTS_C_API::dtsgui_sendevent(), DTS_C_API::dtsgui_setuptoolbar(), DTS_C_API::dtsgui_setwindow(), DTS_C_API::dtsgui_tabwindow(), DTS_C_API::dtsgui_textpane(), and DTS_C_API::dtsgui_treewindow().
{
    return appframe;
}
void * dtsgui::GetUserData (void)
Definition at line 85 of file DTSApp.cpp.
References objlock(), objref(), and objunlock().
Referenced by DTS_C_API::dtsgui_userdata().
{
    void *ud = NULL;
    objlock(this);
    if (userdata && objref(userdata)) {
        ud = userdata;
    }
    objunlock(this);
    return ud;
}
void dtsgui::SetStatusText (void)
Definition at line 97 of file DTSApp.cpp.
References objlock(), and objunlock().
Referenced by SetupAPPFrame(), and DTSFrame::SetWindow().
{
    objlock(this);
    if (appframe && status) {
        appframe->SetStatusText(status);
    }
    objunlock(this);
}
int dtsgui::SetupAPPFrame (void)
Definition at line 64 of file DTSApp.cpp.
References objlock(), objref(), objunlock(), objunref(), SetStatusText(), point::x, and point::y.
{
    void *data = NULL;
    int res;
    appframe = new DTSFrame(title, wxPoint(wpos->x, wpos->y), wxSize(wsize->x, wsize->y), this);
    SetStatusText();
    objlock(this);
    if (userdata && objref(userdata)) {
        data = userdata;
    }
    objunlock(this);
    res = cb(this, data);
    if (data) {
        objunref(data);
    }
    return res;
}
void dtsgui::ShowToolbar (bool show = true)
Definition at line 129 of file DTSApp.cpp.
Referenced by DTS_C_API::dtsgui_set_toolbar().
{
    wxToolBar *tb;
    tb = appframe->GetToolBar();
    tb->Show(show);
    appframe->Layout();
}
The documentation for this class was generated from the following files:
/usr/src/dtsapplib/dtsguiapp/src/include/DTSApp.h
/usr/src/dtsapplib/dtsguiapp/src/DTSApp.cpp