DTS Application Library: /usr/src/dtsapplib/dtsapplib-0.1/src/config.c File Reference
config.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "include/dtsapp.h"
Data Structures
struct config_category
struct config_file
Functions
void initconfigfiles (void)
void unrefconfigfiles (void)
int process_config (const char *configname, const char *configfile)
struct bucket_list * get_config_file (const char *configname)
struct bucket_list * get_config_category (const char *configname, const char *category)
struct bucket_list * get_category_next (struct bucket_loop *cloop, char *name, int len)
struct bucket_loop * get_category_loop (const char *configname)
void config_entry_callback (struct bucket_list *entries, config_entrycb entry_cb)
void config_cat_callback (struct bucket_list *categories, config_catcb cat_cb)
void config_file_callback (config_filecb file_cb)
struct config_entry * get_config_entry (struct bucket_list *categories, const char *item)
Function Documentation
struct bucket_list* get_config_file (const char * configname) read
Definition at line 241 of file config.c.
References bucket_list_find_key(), config_file::cat, objref(), and objunref().
{
    struct config_file *file;
    if ((file = bucket_list_find_key(configfiles, configname))) {
        if (file->cat) {
            if (!objref(file->cat)) {
                objunref(file);
                return (NULL);
            }
            objunref(file);
            return (file->cat);
        }
        objunref(file);
    }
    return (NULL);
}