DTS Application Library: Menu bar interface.
Menu bar interface.
Distrotech GUI Library C API
Create and manage menus.
Functions
void DTS_C_API::dtsgui_menuenable (dtsgui_menu dm, int enable)
Enable or disable all items in menu.
dtsgui_menu DTS_C_API::dtsgui_newmenu (struct dtsgui *dtsgui, const char *name)
Create a new menu and append it to the menu bar.
dtsgui_menuitem DTS_C_API::dtsgui_newmenuitem (dtsgui_menu dtsmenu, struct dtsgui *dtsgui, const char *hint, dtsgui_pane p)
Create a menu item that will activate the pane provided.
dtsgui_menuitem DTS_C_API::dtsgui_newmenucb (dtsgui_menu dtsmenu, struct dtsgui *dtsgui, const char *hint, const char *name, int blank, dtsgui_dynpanel cb, void *data)
Create a menu item that will call a function with supplied data to execute when selected.
void DTS_C_API::dtsgui_exit (dtsgui_menu dtsmenu, struct dtsgui *dtsgui)
Add Menu item that will abort the app without save event been generated.
void DTS_C_API::dtsgui_close (dtsgui_menu dtsmenu, struct dtsgui *dtsgui)
Add Menu item that will close the app after sending a save event.
void DTS_C_API::dtsgui_about (dtsgui_menu dtsmenu, struct dtsgui *dtsgui, const char *text)
Add Menu item will pop up a "about" box.
void DTS_C_API::dtsgui_menusep (dtsgui_menu dtsmenu)
Add Menu seperator to the menu.
void DTS_C_API::dtsgui_menuitemenable (dtsgui_menuitem dmi, int enable)
Enable/Disable an menu item.
Detailed Description
Create and manage menus.
Remarks
The menu bar at the top of the application contains menus, these menus contain menuitems these are the primary control interface.
Menu items when selected can call a function or place a pre created panel in the display area. If the function returns a panel it will be placed in the display area.
Menuitems can also be enabled / disabled programatically, disabled menu items are shown greyed out.
Todo:
Define and implement Exit/Quit events
Function Documentation
void DTS_C_API::dtsgui_about (dtsgui_menu dtsmenu, struct dtsgui * dtsgui, const char * text)
Add Menu item will pop up a "about" box.
Open an "about" box using the text supplied.
See Also
dtsgui_newmenu()
DTSFrame::NewMenu()
Parameters
dtsmenu Menu to append about item to
dtsgui Application data ptr
text Text displayed in box when menu is selected
Returns
The fuction does not return.
Definition at line 418 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::SetAbout().
Referenced by help_menu().
{
    DTSFrame *frame = dtsgui->GetFrame();
    frame->SetAbout((wxMenu *)dtsmenu, text);
}
void DTS_C_API::dtsgui_close (dtsgui_menu dtsmenu, struct dtsgui * dtsgui)
Add Menu item that will close the app after sending a save event.
A menu item will be appended to the supplied menu that when selected will generate a close/save event confirmation will be requested.
See Also
DTSFrame::CloseMenu()
dtsgui_newmenu()
DTSFrame::NewMenu()
Parameters
dtsmenu Menu to append item to
dtsgui Application data ptr
Returns
The fuction does not return.
Definition at line 401 of file wrapper.cpp.
References DTSFrame::CloseMenu(), and dtsgui::GetFrame().
Referenced by file_menu().
{
    DTSFrame *frame = dtsgui->GetFrame();
    frame->CloseMenu((wxMenu *)dtsmenu, wxID_SAVE);
}
void DTS_C_API::dtsgui_exit (dtsgui_menu dtsmenu, struct dtsgui * dtsgui)
Add Menu item that will abort the app without save event been generated.
A menu item will be appended to the supplied menu that when selected will generate a abort event [Alt-F4] confirmation will be requested.
See Also
DTSFrame::CloseMenu()
dtsgui_newmenu()
DTSFrame::NewMenu()
Parameters
dtsmenu Menu to append item to
dtsgui Application data ptr
Returns
The fuction does not return.
Definition at line 383 of file wrapper.cpp.
References DTSFrame::CloseMenu(), and dtsgui::GetFrame().
Referenced by file_menu().
{
    DTSFrame *frame = dtsgui->GetFrame();
    frame->CloseMenu((wxMenu *)dtsmenu, wxID_EXIT);
}
void DTS_C_API::dtsgui_menuenable (dtsgui_menu dm, int enable)
Enable or disable all items in menu.
Parameters
dm Menu to enable/disable.
enable Enable all items if set to non zero.
Definition at line 51 of file cxxapi.cpp.
Referenced by config_menu(), open_config(), and save_config().
{
    bool state =  (enable) ? true : false;
    wxMenuItemList items;
    wxMenuItem *mi;
    int cnt,i;
    wxMenu *m = (wxMenu*)dm;
    items = m->GetMenuItems();
    cnt = m->GetMenuItemCount();
    for(i=0; i < cnt;i++) {
        mi = items[i];
        mi->Enable(state);
    }
}
void DTS_C_API::dtsgui_menuitemenable (dtsgui_menuitem dmi, int enable)
Enable/Disable an menu item.
Parameters
dmi Menuitem
enable Disable the menu if set to 0.
Definition at line 443 of file wrapper.cpp.
Referenced by open_config(), and save_config().
{
    wxMenuItem *mi = (wxMenuItem*)dmi;
    mi->Enable((enable) ? true : false);
}
void DTS_C_API::dtsgui_menusep (dtsgui_menu dtsmenu)
Add Menu seperator to the menu.
A menu seperation line is appened to the menu.
See Also
dtsgui_newmenu()
DTSFrame::NewMenu()
Parameters
dtsmenu Menu to append about item to
Returns
The fuction does not return.
Definition at line 433 of file wrapper.cpp.
Referenced by config_menu(), file_menu(), and help_menu().
{
    wxMenu *m = (wxMenu *)dtsmenu;
    m->AppendSeparator();
}
dtsgui_menu DTS_C_API::dtsgui_newmenu (struct dtsgui * dtsgui, const char * name)
Create a new menu and append it to the menu bar.
A new menu is created and appended to the menu bar the returned value will be passed to menu functions to append items to.
See Also
DTSFrame::NewMenu()
Parameters
dtsgui Application data ptr
name Name of the menu.
Returns
The fuction does not return.
Definition at line 316 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::NewMenu().
Referenced by config_menu(), file_menu(), and help_menu().
{
    DTSFrame *frame = dtsgui->GetFrame();
    return frame->NewMenu(name);
}
dtsgui_menuitem DTS_C_API::dtsgui_newmenucb (dtsgui_menu dtsmenu, struct dtsgui * dtsgui, const char * hint, const char * name, int blank, dtsgui_dynpanel cb, void * data)
Create a menu item that will call a function with supplied data to execute when selected.
The specified call back will be called passing the application pointer (dtsgui), the name and data ptr supplied. if this function returns a DTSObject pane it will be displayed.
See Also
DTSFrame::NewMenuItem()
dtsgui_newmenu()
dtsgui_dynpanel
dtsgui_newmenu()
DTSFrame::NewMenu()
Parameters
dtsmenu Menu where to put append this item.
dtsgui Application data created on application startup and returned in most callbacks.
hint Menu hint with a & indicating the highlighted short key.
name displayed on status bar and returned in callback.
blank if not zero will blank the display before executing callback.
cb Callback function to execute when selected.
data A ptr to a referenced object.
Returns
Created menu item.
Definition at line 365 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::NewMenuItem().
Referenced by config_menu(), and file_menu().
{
    DTSFrame *frame = dtsgui->GetFrame();
    return frame->NewMenuItem((wxMenu *)dtsmenu, menuid++, name, hint, blank, cb, data);
}
dtsgui_menuitem DTS_C_API::dtsgui_newmenuitem (dtsgui_menu dtsmenu, struct dtsgui * dtsgui, const char * hint, dtsgui_pane p)
Create a menu item that will activate the pane provided.
this pane needs to be created and not deleted use of this function is discouraged. the callback menu function is recomended where a panel can be dynamically created and returned.
See Also
DTSFrame::NewMenuItem()
dtsgui_newmenucb()
dtsgui_newmenu()
DTSFrame::NewMenu()
Parameters
dtsmenu Menu where to put append this item.
dtsgui Application data created on application startup and returned in most callbacks.
hint Menu hint with a & indicating the highlighted short key.
p Panel must be a derived window of DTSObject.
Returns
Created menu item.
Definition at line 338 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::NewMenuItem().
Referenced by help_menu(), and test_menu().
{
    DTSFrame *frame = dtsgui->GetFrame();
    return frame->NewMenuItem((wxMenu *)dtsmenu, (DTSObject*)p, menuid++, hint);
}