DTS Application Library: Progress dialog interface.
Progress dialog interface.
Distrotech GUI Library C API
Popup dialog containing a progress bar and posible cancel button.
Functions
int DTS_C_API::dtsgui_progress_start (struct dtsgui *dtsgui, const char *text, int maxval, int quit)
Initialise the progress dialog Pop up a dialog box that can be updated to showprogress with a optional cancel button.
int DTS_C_API::dtsgui_progress_update (struct dtsgui *dtsgui, int newval, const char *newtext)
Update the progress bar counter This function updates the current progress value and optionally allows setting new displayed text.
int DTS_C_API::dtsgui_progress_increment (struct dtsgui *dtsgui, int ival, const char *newtext)
Increments the counter by adding to it not setting it.
void DTS_C_API::dtsgui_progress_end (struct dtsgui *dtsgui)
Disable the progress bar.
Detailed Description
Popup dialog containing a progress bar and posible cancel button.
Todo:
Allow multiple instances of progress dialog not only the single interface at present.
Function Documentation
void DTS_C_API::dtsgui_progress_end (struct dtsgui * dtsgui)
Disable the progress bar.
See Also
DTSFrame::EndProgress()
Parameters
dtsgui Application data ptr.
Definition at line 1063 of file wrapper.cpp.
References DTSFrame::EndProgress(), and dtsgui::GetFrame().
{
    DTSFrame *f = dtsgui->GetFrame();
    f->EndProgress();
}
int DTS_C_API::dtsgui_progress_increment (struct dtsgui * dtsgui, int ival, const char * newtext)
Increments the counter by adding to it not setting it.
See Also
DTSFrame::IncProgress()
Parameters
dtsgui Application data ptr.
ival Value to increment progress bar.
newtext Text displayed in the popup box.
Returns
0 on success may fail when the user presses cancel.
Definition at line 1054 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::IncProgress().
{
    DTSFrame *f = dtsgui->GetFrame();
    return f->IncProgress(ival, newtext);
}
int DTS_C_API::dtsgui_progress_start (struct dtsgui * dtsgui, const char * text, int maxval, int quit)
Initialise the progress dialog Pop up a dialog box that can be updated to showprogress with a optional cancel button.
See Also
DTSFrame::StartProgress()
Parameters
dtsgui Application data ptr.
text Text displayed in the popup box.
maxval the maximum expected value to update.
quit Disable the cancel button if quit is zero.
Returns
zero on failure
Definition at line 1027 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::StartProgress().
{
    DTSFrame *f = dtsgui->GetFrame();
    return f->StartProgress(text, maxval, quit);
}
int DTS_C_API::dtsgui_progress_update (struct dtsgui * dtsgui, int newval, const char * newtext)
Update the progress bar counter This function updates the current progress value and optionally allows setting new displayed text.
See Also
DTSFrame::UpdateProgress()
Parameters
dtsgui Application data ptr.
newval Update the counter with this value.
newtext Text displayed in the popup box.
Returns
0 on success may fail when the user presses cancel.
Definition at line 1042 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::UpdateProgress().
{
    DTSFrame *f = dtsgui->GetFrame();
    return f->UpdateProgress(newval, newtext);
}