DTS Application Library: Panel item interface.
Panel item interface.
Display panel interface.
Access and manage panel elements in a consistant way.
Functions
struct bucket_list * DTS_C_API::dtsgui_panel_items (dtsgui_pane pane)
Return reference to hashed bucket list of items.
struct form_item * DTS_C_API::dtsgui_finditem (dtsgui_pane p, const char *name)
Return refernece to a form element. Find a item and return it searcing the bucket list for the specified name.
void * DTS_C_API::dtsgui_item_data (struct form_item *fi)
Get refernece to data stoed on element.
const char * DTS_C_API::dtsgui_item_value (struct form_item *fi)
Return value of element. The value of the panel element is returned fo the item.
const char * DTS_C_API::dtsgui_item_name (struct form_item *fi)
Return name of element.
const char * DTS_C_API::dtsgui_findvalue (dtsgui_pane p, const char *name)
Helper function to return a value of a item. This function finds a value by name returning the value.
Detailed Description
Access and manage panel elements in a consistant way.
See Also
Panel element interface.
Remarks
Element items include Text / Password / Check / List / Combo boxes.
Information of each element is stored in a hashed bucket to provide a consistant interface to the values and references to data (XML).
Function Documentation
struct form_item* DTS_C_API::dtsgui_finditem (dtsgui_pane p, const char * name) read
Return refernece to a form element. Find a item and return it searcing the bucket list for the specified name.
See Also
DTSPanel::FindItem()
Parameters
p panel who's item list is to be searched.
name Return item with this name.
Returns
Form item if found matching the name.
Definition at line 1089 of file wrapper.cpp.
References DTSPanel::FindItem().
{
    DTSPanel *dp = (DTSPanel*)p;
    return dp->FindItem(name);
}
const char* DTS_C_API::dtsgui_findvalue (dtsgui_pane p, const char * name)
Helper function to return a value of a item. This function finds a value by name returning the value.
Note
the returned value must be freeed.
See Also
dtsgui_finditem()
dtsgui_item_value()
DTSPanel::FindValue()
DTSPanel::FindItem()
form_item::GetValue()
Parameters
p Panel to search element.
name Return value of element with this name.
Returns
Value of element.
Definition at line 1140 of file wrapper.cpp.
References DTSPanel::FindValue().
Referenced by handle_updatetabpane().
{
    DTSPanel *dp = (DTSPanel*)p;
    return dp->FindValue(name);
}
void* DTS_C_API::dtsgui_item_data (struct form_item * fi)
Get refernece to data stoed on element.
Each element is capable of storing user supplied data this returns a reference to this data.
See Also
form_item::GetData()
Parameters
fi Form item to obtain data from.
Returns
Reference to data stored in item.
Definition at line 1102 of file wrapper.cpp.
References form_item::GetData().
{
    return (fi) ? fi->GetData() : NULL;
}
const char* DTS_C_API::dtsgui_item_name (struct form_item * fi)
Return name of element.
Note
the name must not be freed and the form itme must not be un referenced
See Also
form_item::GetName()
Parameters
fi Form item.
Returns
Name of item.
Definition at line 1124 of file wrapper.cpp.
References form_item::GetName().
{
    return fi->GetName();
}
const char* DTS_C_API::dtsgui_item_value (struct form_item * fi)
Return value of element. The value of the panel element is returned fo the item.
Note
The return value must be freed.
See Also
form_item::GetValue()
Parameters
fi Form item to obtain value of.
Returns
Value of the element.
Definition at line 1113 of file wrapper.cpp.
References form_item::GetValue().
Referenced by network_config().
{
    return (fi) ? fi->GetValue() : NULL;
}
struct bucket_list* DTS_C_API::dtsgui_panel_items (dtsgui_pane pane) read
Return reference to hashed bucket list of items.
The bucket list API in dtsapplib contains more information.
See Also
DTSObject::GetItems()
Parameters
pane Panel to obtain list from.
Returns
Reference to hashed bucket list.
Definition at line 1076 of file wrapper.cpp.
References DTSObject::GetItems().
{
    DTSObject *p = (DTSObject*)pane;
    return p->GetItems();
}