DTS Application Library: SHA2-512 Hashing and digest functions
SHA2-512 Hashing and digest functions
Hashing and digest functions
SHA2-512 Hashing checking and HMAC Functions.
Functions
void sha512sum2 (unsigned char *buff, const void *data, unsigned long len, const void *data2, unsigned long len2)
Calculate the SHA2-512 hash accross 2 data chunks.
void sha512sum (unsigned char *buff, const void *data, unsigned long len)
Calculate the SHA2-512 hash.
int sha512cmp (unsigned char *digest1, unsigned char *digest2)
Compare two SHA2-512 hashes.
void sha512hmac (unsigned char *buff, const void *data, unsigned long len, const void *key, unsigned long klen)
Hash Message Authentication Codes (HMAC) SHA2-512.
Detailed Description
SHA2-512 Hashing checking and HMAC Functions.
Function Documentation
int sha512cmp (unsigned char * digest1, unsigned char * digest2)
Compare two SHA2-512 hashes.
Parameters
digest1 Digest to compare.
digest2 Digest to compare.
Returns
0 on equality.
Definition at line 253 of file util.c.
{
     return (_digest_cmp(digest1, digest2, 64));
 }
void sha512hmac (unsigned char * buff, const void * data, unsigned long len, const void * key, unsigned long klen)
Hash Message Authentication Codes (HMAC) SHA2-512.
Parameters
buff HMAC returned in this buffer (64 bytes).
data Data to sign.
len Length of data.
key Key to signwith.
klen Length of key.
Definition at line 326 of file util.c.
References sha512sum2().
{
     _hmac(buff, data, len, key, klen, sha512sum2, 64);
 }
void sha512sum (unsigned char * buff, const void * data, unsigned long len)
Calculate the SHA2-512 hash.
Parameters
buff buffer to place the hash (64 bytes).
data First data chunk to calculate.
len Length of data.
Definition at line 114 of file util.c.
References sha512sum2().
{
     sha512sum2(buff, data, len, NULL, 0);
 }
void sha512sum2 (unsigned char * buff, const void * data, unsigned long len, const void * data2, unsigned long len2)
Calculate the SHA2-512 hash accross 2 data chunks.
Parameters
buff buffer to place the hash (64 bytes).
data First data chunk to calculate.
len Length of data.
data2 Second data chunk to calculate.
len2 Length of data2.
Definition at line 97 of file util.c.
Referenced by sha512hmac(), and sha512sum().
{
     SHA512_CTX c;
     SHA512_Init(&c);
     SHA512_Update(&c, data, len);
     if (data2) {
         SHA512_Update(&c, data2, len2);
     }
     SHA512_Final(buff, &c);
 }