DTS Application Library: Tab view panel interface.
Tab view panel interface.
Display panel interface.
A tree view is a panel with tabs along the top and display area underneath.
Functions
dtsgui_pane DTS_C_API::dtsgui_newtabpage (dtsgui_tabview tv, const char *name, int butmask, void *userdata, struct xml_doc *xmldoc, dtsgui_tabpanel_cb cb, void *cdata)
Create and append a tab to the view.
dtsgui_pane DTS_C_API::dtsgui_tabpage_insert (dtsgui_tabview tv, const char *name, int butmask, void *userdata, struct xml_doc *xmldoc, dtsgui_tabpanel_cb cb, void *cdata, int pos, int undo)
Create and insert a tab in the view.
void DTS_C_API::dtsgui_newxmltabpane (dtsgui_tabview tabv, dtsgui_pane p, const char *xpath, const char *node, const char *vitem, const char *tattr, dtsgui_tabpane_newdata_cb data_cb, dtsgui_tabpanel_cb cb, void *cdata, struct xml_doc *xmldoc, void *data)
Helper function to handle "Adding" a new tab from a existing tab.
Detailed Description
A tree view is a panel with tabs along the top and display area underneath.
Todo:
Implement a right click action to allow for deletion via a confirmation dialog.
Remarks
The tab window allows grouping related panels together via the tab control when the tab is clicked its display area displays the panel associated with this control.
Function Documentation
dtsgui_pane DTS_C_API::dtsgui_newtabpage (dtsgui_tabview tv, const char * name, int butmask, void * userdata, struct xml_doc * xmldoc, dtsgui_tabpanel_cb cb, void * cdata)
Create and append a tab to the view.
Append a tab to the tab view the tab will be configured when it is selected the callback will run to configure it.
Note
Its also possible to configure the returned panel.
On win32 all tabs are configured when the view is activated.
See Also
dtsgui_tabpage_insert
dtsgui_tabwindow()
DTSTabWindow
DTSTabWindow::CreateTab()
panel_buttons
dtsgui_tabpanel_cb
Parameters
tv Tabview previously created.
name Title placed on the pane Top/Center.
butmask Mask of buttons to be placed on the panel and trigger events passed to the callback.
userdata Referenced object stored and made available in callbacks.
xmldoc Optional XML document stored and made available to XML resources.
cb Callback called to configure the panel.
cdata Referenced object passed to the configuration callback.
Definition at line 588 of file wrapper.cpp.
References DTSTabWindow::CreateTab().
Referenced by iface_config(), and pbx_settings().
{
    DTSTabWindow *tw = (DTSTabWindow*)tv;
    return tw->CreateTab(name, butmask, userdata, cb, cdata, xmldoc);
}
void DTS_C_API::dtsgui_newxmltabpane (dtsgui_tabview tabv, dtsgui_pane p, const char * xpath, const char * node, const char * vitem, const char * tattr, dtsgui_tabpane_newdata_cb data_cb, dtsgui_tabpanel_cb cb, void * cdata, struct xml_doc * xmldoc, void * data)
Helper function to handle "Adding" a new tab from a existing tab.
This implements the concept of the New button a new panel will be created from the data filled in on the pane this callback is attached too. A new XML node is created and the panel created from this node.
Note
this callback helper is rather complex.
See Also
tab_newpane
Parameters
tabv Table view the new panel will be added too.
p The panel this callback is attached too.
xpath the path of the new node.
node the name of the XML node to create in the xpath.
vitem the item in the panel to be used to create the value of the new node.
tattr the attribute to be used too create the title in the new pane.
data_cb Callback to allow setting the data used in pane creation.
cb Callback to configure the pane.
cdata Referrenced object containing initial callback data.
xmldoc XML doc reference for creating the node / panel.
data Referenced object made available in callbacks.
Returns
Nothing is returned the callback is registered on the panel.
Definition at line 645 of file wrapper.cpp.
References tab_newpane::handle_newtabpane_cb(), and tab_newpane::tab_newpane().
Referenced by network_iface_new_pane_cb().
{
    class tab_newpane *tn = new tab_newpane((DTSTabWindow*)tabv, xpath, node, vitem, tattr, data_cb, cb, cdata, xmldoc, data);
    static_cast<DTSPanel*>(p)->SetEventCallback(&tab_newpane::handle_newtabpane_cb, tn, true);
}
dtsgui_pane DTS_C_API::dtsgui_tabpage_insert (dtsgui_tabview tv, const char * name, int butmask, void * userdata, struct xml_doc * xmldoc, dtsgui_tabpanel_cb cb, void * cdata, int pos, int undo)
Create and insert a tab in the view.
Insert a tab at the position specified and recreate the panel at position undo.
See Also
dtsgui_tabpage_newtabpage
dtsgui_tabwindow()
DTSTabWindow
DTSTabWindow::CreateTab()
panel_buttons
dtsgui_tabpanel_cb
Parameters
tv Tabview previously created.
name Title placed on the pane Top/Center.
butmask Mask of buttons to be placed on the panel and trigger events passed to the callback.
userdata Referenced object stored and made available in callbacks.
xmldoc Optional XML document stored and made available to XML resources.
cb Callback called to configure the panel.
cdata Referenced object passed to the configuration callback.
pos Position to insert into
undo Delete and recreate the panel at this position
Returns
New Tab Pane
Definition at line 617 of file wrapper.cpp.
References DTSTabWindow::CreateTab().
{
    DTSTabWindow *tw = (DTSTabWindow*)tv;
    return tw->CreateTab(name, butmask, userdata, cb, cdata, xmldoc, pos, undo);
}