DTS Application Library: Display panel interface.
Display panel interface.
Distrotech GUI Library C API
Create and manage display panels shown in the application display area.
Modules
Tree view panel interface.
A tree view is a split window with a tree in the left window and display area on right.
Tab view panel interface.
A tree view is a panel with tabs along the top and display area underneath.
Panel element interface.
Interface for creating and placing elements on the panel.
Panel item interface.
Access and manage panel elements in a consistant way.
Functions
dtsgui_pane DTS_C_API::dtsgui_panel (struct dtsgui *dtsgui, const char *name, const char *title, int butmask, enum panel_type type, void *userdata)
Create a pannel to be displayed.
dtsgui_pane DTS_C_API::dtsgui_textpane (struct dtsgui *dtsgui, const char *title, const char *buf)
Create a text display box with the text in the buffer been displayed.
dtsgui_treeview DTS_C_API::dtsgui_treewindow (struct dtsgui *dtsgui, const char *title, dtsgui_tree_cb tree_cb, void *userdata, struct xml_doc *xmldoc)
Create a treepane view.
dtsgui_tabview DTS_C_API::dtsgui_tabwindow (struct dtsgui *dtsgui, const char *title, void *data)
Create a tab view panel.
void DTS_C_API::dtsgui_panel_setxml (dtsgui_pane pane, struct xml_doc *xmldoc)
Pass a reference to a XML Doc Structure to the panel.
struct xml_doc * DTS_C_API::dtsgui_panelxml (dtsgui_pane pane)
Get reference to previously allocated XML Doc.
void DTS_C_API::dtsgui_delpane (dtsgui_pane pane)
Delete a panel.
void DTS_C_API::dtsgui_setevcallback (dtsgui_pane pane, event_callback evcb, void *data)
Set event callback function for panel.
void DTS_C_API::dtsgui_xmlpanel_update (dtsgui_pane pane)
update all XML items in the panel from current element values.
struct curl_post * DTS_C_API::dtsgui_pane2post (dtsgui_pane p)
Prepare a HTTP POST structure from panel.
void * DTS_C_API::dtsgui_paneldata (dtsgui_pane pane)
Obtain a reference to the userdata of panel.
void DTS_C_API::dtsgui_settitle (dtsgui_pane pane, const char *title)
Update the title on the panel if it exists.
void DTS_C_API::dtsgui_setstatus (dtsgui_pane pane, const char *status)
Update the status bar message of panel.
void DTS_C_API::dtsgui_configcallback (dtsgui_pane pane, dtsgui_configcb cb, void *data)
Set config callback function for panel (UNUSED).
struct xml_node * DTS_C_API::dtsgui_panetoxml (dtsgui_pane p, const char *xpath, const char *node, const char *nodeval, const char *attrkey)
Create a XML node from the elements on the panel.
void DTS_C_API::dtsgui_rundialog (dtsgui_pane pane, event_callback evcb, void *data)
Execute a dialog panel. Pop up and run a dialog pane the result will be obtained in the event handler.
Detailed Description
Create and manage display panels shown in the application display area.
Remarks
The application display area can display one panel at a time these panels may be static or dynamic. static panels are created once and persist during execution. dynamic panels are created and displayed each time the associated menuitem is selected.
See Also
panel_type
Warning
The displayed dynamic panel will be removed when a new item is selected.
Todo:
Emit and allow panels to manage a event when a new panel is requested to allow saving the displayed panel.
Function Documentation
void DTS_C_API::dtsgui_configcallback (dtsgui_pane pane, dtsgui_configcb cb, void * data)
Set config callback function for panel (UNUSED).
See Also
DTSPanel::SetConfigCallback()
dtsgui_configcb
Note
Not yet implemted who knows maybe it will maybe it wont.
Parameters
pane Panel to attach callback too.
cb Config callback.
data Data supplied in the callback (panel userdata is available in the panel).
Definition at line 938 of file wrapper.cpp.
References DTSPanel::SetConfigCallback().
{
    DTSPanel *p = (DTSPanel *)pane;
    p->SetConfigCallback(cb, data);
}
void DTS_C_API::dtsgui_delpane (dtsgui_pane pane)
Delete a panel.
Note
This is unlikly too be needed as the GUI manages panels.
Parameters
pane Panel To Delete.
Definition at line 561 of file wrapper.cpp.
{
    delete (DTSPanel *)pane;
}
struct curl_post* DTS_C_API::dtsgui_pane2post (dtsgui_pane p) read
Prepare a HTTP POST structure from panel.
Create a HTTP Post structure from the values and names Of elements on a panel this can then be used with curl_post to post to a URL.
See Also
DTSPanel::Update_XML()
dtsgui_xmlpane_update()
DTSPanel::Panel2Post()
Parameters
p Panel to create from.
Returns
A CURL HTTP POST Structure.
Definition at line 887 of file wrapper.cpp.
References DTSPanel::Panel2Post().
Referenced by post_items().
{
    DTSPanel *dp = (DTSPanel*)p;
    return dp->Panel2Post();
}
dtsgui_pane DTS_C_API::dtsgui_panel (struct dtsgui * dtsgui, const char * name, const char * title, int butmask, enum panel_type type, void * userdata)
Create a pannel to be displayed.
This function is able to create and return various panels excluding Tab/Tree view panels.
See Also
DTSFrame::CreatePane()
panel_type
panel_buttons
Parameters
dtsgui Application data ptr.
name Text used in the status bar when panel is displayed.
title Title set in the window Top/Middle.
butmask Buttons to be displayed values of panel_buttons or'd together.
type Type of panel to create [Excludes Tab/Tree Views]
userdata Referenced Obect passed stored in panel and available in event handlers.
Returns
Newly created panel.
Definition at line 464 of file wrapper.cpp.
References DTSFrame::CreatePane(), and dtsgui::GetFrame().
Referenced by test_menu().
{
    DTSFrame *frame = dtsgui->GetFrame();
    return frame->CreatePane(name, title, butmask, type, userdata);
}
void DTS_C_API::dtsgui_panel_setxml (dtsgui_pane pane, struct xml_doc * xmldoc)
Pass a reference to a XML Doc Structure to the panel.
Assign a reference to a XML Doc to the panel for use latter and with XML controls.
See Also
DTSObject::SetXMLDoc()
Parameters
pane Panel to be assigned the ref.
xmldoc Document to be assigned.
Definition at line 534 of file wrapper.cpp.
References DTSObject::SetXMLDoc().
{
    DTSPanel *p = (DTSPanel *)pane;
    p->SetXMLDoc(xmldoc);
}
void* DTS_C_API::dtsgui_paneldata (dtsgui_pane pane)
Obtain a reference to the userdata of panel.
See Also
DTSObject::GetUserData().
Note
this must be un refferenced.
Parameters
pane Panel to obtain reference from.
Returns
Reference to userdata.
Definition at line 901 of file wrapper.cpp.
References DTSObject::GetUserData().
Referenced by post_items().
{
    DTSPanel *p = (DTSPanel*)pane;
    return p->GetUserData();
}
struct xml_doc* DTS_C_API::dtsgui_panelxml (dtsgui_pane pane) read
Get reference to previously allocated XML Doc.
Obtain a new reference to the xmldoc stored in the panel.
Note
This must be un refferenced.
See Also
DTSObject::GetXMLDoc()
Parameters
pane Panel to obtain the XML Info.
Returns
Reference to XML Doc.
Definition at line 550 of file wrapper.cpp.
References DTSObject::GetXMLDoc().
Referenced by network_adsl_link(), network_adsl_link_new(), network_config(), and network_newwifi().
{
    DTSPanel *p = (DTSPanel *)pane;
    return p->GetXMLDoc();
}
struct xml_node* DTS_C_API::dtsgui_panetoxml (dtsgui_pane p, const char * xpath, const char * node, const char * nodeval, const char * attrkey) read
Create a XML node from the elements on the panel.
Using the path information a node is created and elements added as attributes.
See Also
DTSPanel::Panel2XML()
Parameters
p Panel to create nodes from.
xpath Base path to create the nodes in.
node Name of the node to add.
nodeval Name of the element to use as the value of node.
attrkey Use this item to set the initial attribute and use as key.
Returns
New XML Node.
Definition at line 957 of file wrapper.cpp.
References DTSPanel::Panel2XML().
{
    DTSPanel *dp = (DTSPanel*)p;
    return dp->Panel2XML(xpath, node, nodeval, attrkey);
}
void DTS_C_API::dtsgui_rundialog (dtsgui_pane pane, event_callback evcb, void * data)
Execute a dialog panel. Pop up and run a dialog pane the result will be obtained in the event handler.
See Also
DTSDialog::RunDialog()
Parameters
pane Dialog panel to execute.
evcb Event callback to handle the results in.
data Data passed to the event handler.
Definition at line 969 of file wrapper.cpp.
References DTSDialog::RunDialog().
{
    DTSDialog *p = (DTSDialog *)pane;
    p->RunDialog(evcb, data);
}
void DTS_C_API::dtsgui_setevcallback (dtsgui_pane pane, event_callback evcb, void * data)
Set event callback function for panel.
See Also
DTSPanel::SetEventCallback()
event_callback
When a event happens the callback is called with the userdata to allow actioning the event.
Parameters
pane Panel to attach callback too.
evcb Event callback.
data Data supplied in the callback (panel userdata is available in the panel).
Definition at line 853 of file wrapper.cpp.
References DTSPanel::SetEventCallback().
Referenced by network_iface_pane_cb(), and test_menu().
{
    DTSPanel *p = (DTSPanel *)pane;
    return p->SetEventCallback(evcb, data);
}
void DTS_C_API::dtsgui_setstatus (dtsgui_pane pane, const char * status)
Update the status bar message of panel.
See Also
DTSPanel::SetStatus()
Parameters
pane Panel to update title.
status New status bar message.
Definition at line 922 of file wrapper.cpp.
References DTSPanel::SetStatus().
Referenced by handle_updatetabpane().
{
    DTSPanel *p = (DTSPanel*)pane;
    return p->SetStatus(status);
}
void DTS_C_API::dtsgui_settitle (dtsgui_pane pane, const char * title)
Update the title on the panel if it exists.
See Also
DTSPanel::SetTitle()
Parameters
pane Panel to update title.
title New title to place on panel.
Definition at line 911 of file wrapper.cpp.
References DTSPanel::SetTitle().
{
    DTSPanel *p = (DTSPanel*)pane;
    return p->SetTitle(title);
}
dtsgui_tabview DTS_C_API::dtsgui_tabwindow (struct dtsgui * dtsgui, const char * title, void * data)
Create a tab view panel.
Create a panel that will place pages as tabs along the top of the display. Clicking on the tab opens the panel in the display area.
See Also
DTSTabWindow
Parameters
dtsgui Application data ptr.
title Text displayed on status bar.
data Referenced object made available in the event callback.
Returns
Tab window.
Definition at line 520 of file wrapper.cpp.
References dtsgui::GetFrame().
Referenced by iface_config(), and pbx_settings().
{
    DTSFrame *frame = dtsgui->GetFrame();
    return  new DTSTabWindow(frame, title, data);
}
dtsgui_pane DTS_C_API::dtsgui_textpane (struct dtsgui * dtsgui, const char * title, const char * buf)
Create a text display box with the text in the buffer been displayed.
This creates a panel that only contains the supplied buffer Scrollbars are used as required.
This window is read only.
See Also
DTSFrame::TextPanel()
Parameters
dtsgui Application data ptr.
title Text displayed on the status bar.
buf The text displayed in the pane.
Returns
New text panel.
Definition at line 483 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::TextPanel().
Referenced by help_menu(), view_config_conf(), and view_config_xml().
{
    DTSFrame *f = dtsgui->GetFrame();
    return f->TextPanel(title, buf);
}
dtsgui_treeview DTS_C_API::dtsgui_treewindow (struct dtsgui * dtsgui, const char * title, dtsgui_tree_cb tree_cb, void * userdata, struct xml_doc * xmldoc)
Create a treepane view.
Create a split window with a tree control on the left and display area on right.
See Also
DTSTreeWindow
dtsgui_tree_cb
tree_cbtype
Parameters
dtsgui Aplication data ptr.
title Text displayed on the status bar.
tree_cb Callback called when a event of tree_cbtype is handled.
userdata Referenced object made available in callback.
xmldoc Optional XML doc struct available in callback's and for managing XML nodes/panels.
Definition at line 503 of file wrapper.cpp.
References dtsgui::GetFrame().
Referenced by advanced_config().
{
    DTSFrame *frame = dtsgui->GetFrame();
    return new DTSTreeWindow(frame, frame, tree_cb, title, 25, NULL, xmldoc);
}
void DTS_C_API::dtsgui_xmlpanel_update (dtsgui_pane pane)
update all XML items in the panel from current element values.
All elements on the panel that are XML will have there nodes updated Based on the value of the elements.
See Also
DTSPanel::Update_XML()
dtsgui_pane2post
DTSPanel::Panel2Post()
Parameters
pane Panel to update.
Definition at line 869 of file wrapper.cpp.
References DTSPanel::Update_XML().
{
    DTSPanel *p = (DTSPanel*)pane;
    p->Update_XML();
}