DTS Application Library: Queue interface
Queue interface
Linux Netfilter
Interface to linux netfilter queue interface.
Files
file nf_queue.c
Linux netfilter queue interface.
Data Structures
struct nfq_struct
struct nfq_queue
struct nfq_list
Typedefs
typedef struct nfq_queue nfq_queue
Forward decleration of structure.
typedef struct nfq_data nfq_data
Forward decleration of structure.
typedef struct nfqnl_msg_packet_hdr nfqnl_msg_packet_hdr
Forward decleration of structure.
typedef uint32_t(* nfqueue_cb)(struct nfq_data *, struct nfqnl_msg_packet_hdr *, char *, uint32_t, void *, uint32_t *, void **)
Enumerations
enum NF_QUEUE_FLAGS { NFQUEUE_DONE = 1 << 0 }
Functions
struct nfq_queue * nfqueue_attach (uint16_t pf, uint16_t num, uint8_t mode, uint32_t range, nfqueue_cb cb, void *data)
uint16_t snprintf_pkt (struct nfq_data *tb, struct nfqnl_msg_packet_hdr *ph, uint8_t *pkt, char *buff, uint16_t len)
Detailed Description
Interface to linux netfilter queue interface.
Typedef Documentation
typedef struct nfq_data nfq_data
Forward decleration of structure.
Definition at line 201 of file dtsapp.h.
typedef struct nfq_queue nfq_queue
Forward decleration of structure.
Definition at line 197 of file dtsapp.h.
typedef struct nfqnl_msg_packet_hdr nfqnl_msg_packet_hdr
Forward decleration of structure.
Definition at line 209 of file dtsapp.h.
typedef uint32_t(* nfqueue_cb)(struct nfq_data *, struct nfqnl_msg_packet_hdr *, char *, uint32_t, void *, uint32_t *, void **)
Definition at line 300 of file dtsapp.h.
Enumeration Type Documentation
enum NF_QUEUE_FLAGS
Enumerator
NFQUEUE_DONE
Definition at line 43 of file nf_queue.c.
                     {
     NFQUEUE_DONE    = 1 << 0
 };
Function Documentation
struct nfq_queue* nfqueue_attach (uint16_t pf, uint16_t num, uint8_t mode, uint32_t range, nfqueue_cb cb, void * data)
Definition at line 231 of file nf_queue.c.
References bucket_list_find_key(), nfq_queue::cb, nfq_queue::data, nfq_struct::h, nfq_queue::nfq, objalloc(), objlock(), objunlock(), objunref(), and nfq_queue::qh.
{
     struct nfq_queue *nfq_q;
     if (!(nfq_q = objalloc(sizeof(*nfq_q), nfqueue_close_q))) {
         return (NULL);
     }
     objlock(nfqueues);
     if (!(nfqueues && (nfq_q->nfq = bucket_list_find_key(nfqueues->queues, &pf))) &&
             !(nfq_q->nfq || (nfq_q->nfq = nfqueue_init(pf)))) {
         objunlock(nfqueues);
         objunref(nfq_q);
         return (NULL);
     }
     objunlock(nfqueues);
     if (!(nfq_q->qh = nfq_create_queue(nfq_q->nfq->h, num, &nfqueue_callback, nfq_q))) {
         objunref(nfq_q);
         return (NULL);
     }
     if (cb) {
         nfq_q->cb = cb;
     }
     if (data) {
         nfq_q->data = data;
     }
     nfq_set_mode(nfq_q->qh, mode, range);
     return (nfq_q);
 }
uint16_t snprintf_pkt (struct nfq_data * tb, struct nfqnl_msg_packet_hdr * ph, uint8_t * pkt, char * buff, uint16_t len)
Definition at line 265 of file nf_queue.c.
References inet_ntop().
{
     struct iphdr *ip = (struct iphdr *)pkt;
     char *tmp = buff;
     uint32_t id, mark, ifi;
     uint16_t tlen, left = len;
     char saddr[INET_ADDRSTRLEN], daddr[INET_ADDRSTRLEN];
     if (ph) {
         id = ntohl(ph->packet_id);
         snprintf(tmp, left, "hw_protocol=0x%04x hook=%u id=%u ",
                  ntohs(ph->hw_protocol), ph->hook, id);
         tlen = strlen(tmp);
         tmp += tlen;
         left -= tlen;
     }
     if ((mark = nfq_get_nfmark(tb))) {
         snprintf(tmp, left, "mark=%u ", mark);
         tlen = strlen(tmp);
         tmp += tlen;
         left -= tlen;
     }
     if ((ifi = nfq_get_indev(tb))) {
         snprintf(tmp, left, "indev=%u ", ifi);
         tlen = strlen(tmp);
         tmp += tlen;
         left -= tlen;
     }
     if ((ifi = nfq_get_outdev(tb))) {
         snprintf(tmp, left, "outdev=%u ", ifi);
         tlen = strlen(tmp);
         tmp += tlen;
         left -= tlen;
     }
     if (pkt && (ip->version == 4)) {
         union l4hdr *l4 = (union l4hdr *)(pkt + (ip->ihl*4));
         inet_ntop(AF_INET, &ip->saddr, saddr, INET_ADDRSTRLEN);
         inet_ntop(AF_INET, &ip->daddr, daddr, INET_ADDRSTRLEN);
         snprintf(tmp, left, "src=%s dst=%s proto=%i ", saddr, daddr, ip->protocol);
         tlen = strlen(tmp);
         tmp += tlen;
         left -= tlen;
         switch(ip->protocol) {
             case IPPROTO_TCP:
                 snprintf(tmp, left, "sport=%i dport=%i ", ntohs(l4->tcp.source), ntohs(l4->tcp.dest));
                 break;
             case IPPROTO_UDP:
                 snprintf(tmp, left, "sport=%i dport=%i ", ntohs(l4->udp.source), ntohs(l4->udp.dest));
                 break;
             case IPPROTO_ICMP:
                 snprintf(tmp, left, "type=%i code=%i id=%i ", l4->icmp.type, l4->icmp.code, ntohs(l4->icmp.un.echo.id));
                 break;
         }
         tlen = strlen(tmp);
         tmp += tlen;
         left -= tlen;
     }
     return (len - left);
 }