DTS Application Library: Zlib Interface
Zlib Interface
Distrotech Application Library
Simplified implementation of zlib functions.
Files
file zlib.c
Simplified implementation of zlib functions.
Data Structures
struct zobj
Zlib buffer used for compression and decompression.
Functions
struct zobj * zcompress (uint8_t *buff, uint16_t len, uint8_t level)
Allocate a buffer and return it with compressed data.
void zuncompress (struct zobj *buff, uint8_t *obuff)
Uncompress zobj buffer to buffer.
int is_gzip (uint8_t *buf, int buf_size)
check a buffer if it contains gzip magic
uint8_t * gzinflatebuf (uint8_t *buf_in, int buf_size, uint32_t *len)
Ungzip a buffer.
Detailed Description
Simplified implementation of zlib functions.
Function Documentation
uint8_t* gzinflatebuf (uint8_t * buf_in, int buf_size, uint32_t * len)
Ungzip a buffer.
Parameters
buf_in Buffer to inflate.
buf_size Size of buf_in buffer.
len Pointer that will contain the uncompressed data length.
Returns
Uncompressed data in a buffer or NULL on error.
Definition at line 101 of file zlib.c.
Referenced by curl_ungzip().
{
    z_stream zdat;
    uint8_t *buf = NULL, *tmp;
    int res;
    zdat.opaque = NULL;
    zdat.zalloc = NULL;
    zdat.zfree = NULL;
    zdat.next_in = buf_in;
    zdat.avail_in = buf_size;
    zdat.next_out = buf;
    zdat.avail_out = 0;
    zdat.total_out = 0;
    if (inflateInit2(&zdat, 31)) {
        return NULL;
    }
    do {
        if (!(tmp = realloc(buf,zdat.total_out + (zdat.avail_in * 5) + 1))) {
            res = Z_MEM_ERROR;
            break;
        } else {
            buf = tmp;
        }
        buf[zdat.total_out] = '\0';
        zdat.next_out = &buf[zdat.total_out];
        zdat.avail_out += zdat.avail_in * 5;
    } while ((res = inflate(&zdat, Z_NO_FLUSH)) == Z_OK);
    if (res == Z_STREAM_END) {
        buf = realloc(buf, zdat.total_out);
        *len = zdat.total_out;
    } else {
        free(buf);
        *len = 0;
        buf = NULL;
    }
    inflateEnd(&zdat);
    return buf;
}
int is_gzip (uint8_t * buf, int buf_size)
check a buffer if it contains gzip magic
Parameters
buf buffer to check.
buf_size buffer len it must be more than 4.
Returns
non zero value if the buffer contains gzip data
Definition at line 85 of file zlib.c.
Referenced by curl_ungzip().
{
    if (buf_size < 4) {
        return 0;
    }
    if (memcmp(buf, gzipMagicBytes, 4)) {
        return 0;
    }
    return 1;
}
struct zobj* zcompress (uint8_t * buff, uint16_t len, uint8_t level) read
Allocate a buffer and return it with compressed data.
Parameters
buff Buffer to compress.
len Length of the buffer.
level Compression level.
Returns
reference to zobj data structure containing compressed data or NULL on error.
Definition at line 47 of file zlib.c.
References zobj::buff, objalloc(), zobj::olen, and zobj::zlen.
{
    struct zobj *ret;
    if (!(ret = objalloc(sizeof(*ret), zobj_free))) {
        return (NULL);
    }
    ret->zlen = compressBound(len);
    ret->olen = len;
    if (!(ret->buff = malloc(ret->zlen))) {
        return (NULL);
    }
    compress2(ret->buff, (uLongf *)&ret->zlen, buff, len, level);
    return (ret);
}
void zuncompress (struct zobj * buff, uint8_t * obuff)
Uncompress zobj buffer to buffer.
Parameters
buff Compressed buffer to uncompress.
obuff Buffer to uncompress too.
Warning
obuff needs to be large enough to contain the data.
Todo:
Implement this without needing original buff len using inflate
Definition at line 71 of file zlib.c.
References zobj::buff, zobj::olen, and zobj::zlen.
{
    uLongf olen = buff->olen;
    if (!obuff) {
        return;
    }
    uncompress(obuff, &olen, buff->buff, buff->zlen);
}