DTS Application Library: Distrotech Server Configuration Application
Distrotech Server Configuration Application
Multi platform GUI server management application.
Modules
System configuration wizard
System configuration wizard.
Configuration menu functions
Configuration menu functions.
Interface configuration tab view
Tab view panel allowing configuration and addition of interfaces.
Advanced configuration tree
wAdvanced configuration tree
PBX Configuration
PBX Configuration.
Application test panel
Static window with standard elements that will post to a URL and pop up the result.
Application toolbar
Toolbar with protocol and URL box the URL box.
Files
file private.h
Main application private includes.
file wxforms.c
Main application file.
Data Structures
struct app_data
Application data structure.
struct listitem
Name value pair sturucture.
Macros
#define DATA_DIR "/usr/share/dtsguiapp"
Shared application folder.
Enumerations
enum node_id {
DTS_NODE_CUSTOMER, DTS_NODE_NETWORK_CONFIG, DTS_NODE_NETWORK_CONFIG_DNS, DTS_NODE_NETWORK_CONFIG_DNS_DYN,
DTS_NODE_NETWORK_CONFIG_DNS_SERV, DTS_NODE_NETWORK_CONFIG_DNS_ZONE, DTS_NODE_NETWORK_CONFIG_DNS_HOST_NEW, DTS_NODE_NETWORK_CONFIG_DNS_HOST,
DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_NEW, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER_NEW, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER,
DTS_NODE_NETWORK_IFACE_NEW, DTS_NODE_NETWORK_IFACE, DTS_NODE_NETWORK_WIFI_NEW, DTS_NODE_NETWORK_WIFI,
DTS_NODE_NETWORK_WAN_NEW, DTS_NODE_NETWORK_WAN, DTS_NODE_NETWORK_ROUTE_NEW, DTS_NODE_NETWORK_ROUTE,
DTS_NODE_NETWORK_MODEM, DTS_NODE_NETWORK_MODEM_ADV, DTS_NODE_NETWORK_MODEM_ANA, DTS_NODE_NETWORK_ADSL_LINK_NEW,
DTS_NODE_NETWORK_ADSL_LINK, DTS_NODE_NETWORK_ADSL_USER_NEW, DTS_NODE_NETWORK_ADSL_USER, DTS_NODE_NETWORK_TOS_NEW,
DTS_NODE_NETWORK_TOS
}
Node ID's used in application treeview.
Functions
void xml_config (struct xml_doc *xmldoc)
Display formated XML Document on the console.
struct xml_doc * app_getxmldoc (struct dtsgui *dtsgui)
return reference to xmldoc stored in userdata.
void file_menu (struct dtsgui *dtsgui)
Create the File menu in the menu bar.
void help_menu (struct dtsgui *dtsgui)
Create the Help menu in the menu bar.
int guiconfig_cb (struct dtsgui *dtsgui, void *data)
GUI application callback.
void free_appdata (void *data)
Callback called when reference count becomes 0.
FRAMEWORK_MAIN ("Distrotech System Administration","Gregory Hinton Nietsky","gregory@distrotech.co.za","http://www.distrotech.co.za", 2013, NULL, 0, NULL)
Application entry point.
Detailed Description
Multi platform GUI server management application.
Macro Definition Documentation
#define DATA_DIR "/usr/share/dtsguiapp"
Shared application folder.
This should be set correctly at build time and this value ignored.
Definition at line 32 of file private.h.
Referenced by FRAMEWORK_MAIN().
Enumeration Type Documentation
enum node_id
Node ID's used in application treeview.
Enumerator:
DTS_NODE_CUSTOMER
DTS_NODE_NETWORK_CONFIG
DTS_NODE_NETWORK_CONFIG_DNS
DTS_NODE_NETWORK_CONFIG_DNS_DYN
DTS_NODE_NETWORK_CONFIG_DNS_SERV
DTS_NODE_NETWORK_CONFIG_DNS_ZONE
DTS_NODE_NETWORK_CONFIG_DNS_HOST_NEW
DTS_NODE_NETWORK_CONFIG_DNS_HOST
DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_NEW
DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN
DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER_NEW
DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER
DTS_NODE_NETWORK_IFACE_NEW
DTS_NODE_NETWORK_IFACE
DTS_NODE_NETWORK_WIFI_NEW
DTS_NODE_NETWORK_WIFI
DTS_NODE_NETWORK_WAN_NEW
DTS_NODE_NETWORK_WAN
DTS_NODE_NETWORK_ROUTE_NEW
DTS_NODE_NETWORK_ROUTE
DTS_NODE_NETWORK_MODEM
DTS_NODE_NETWORK_MODEM_ADV
DTS_NODE_NETWORK_MODEM_ANA
DTS_NODE_NETWORK_ADSL_LINK_NEW
DTS_NODE_NETWORK_ADSL_LINK
DTS_NODE_NETWORK_ADSL_USER_NEW
DTS_NODE_NETWORK_ADSL_USER
DTS_NODE_NETWORK_TOS_NEW
DTS_NODE_NETWORK_TOS
Definition at line 36 of file private.h.
             {
    DTS_NODE_CUSTOMER,
    DTS_NODE_NETWORK_CONFIG,
    DTS_NODE_NETWORK_CONFIG_DNS,
    DTS_NODE_NETWORK_CONFIG_DNS_DYN,
    DTS_NODE_NETWORK_CONFIG_DNS_SERV,
    DTS_NODE_NETWORK_CONFIG_DNS_ZONE,
    DTS_NODE_NETWORK_CONFIG_DNS_HOST_NEW,
    DTS_NODE_NETWORK_CONFIG_DNS_HOST,
    DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_NEW,
    DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN,
    DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER_NEW,
    DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER,
    DTS_NODE_NETWORK_IFACE_NEW,
    DTS_NODE_NETWORK_IFACE,
    DTS_NODE_NETWORK_WIFI_NEW,
    DTS_NODE_NETWORK_WIFI,
    DTS_NODE_NETWORK_WAN_NEW,
    DTS_NODE_NETWORK_WAN,
    DTS_NODE_NETWORK_ROUTE_NEW,
    DTS_NODE_NETWORK_ROUTE,
    DTS_NODE_NETWORK_MODEM,
    DTS_NODE_NETWORK_MODEM_ADV,
    DTS_NODE_NETWORK_MODEM_ANA,
    DTS_NODE_NETWORK_ADSL_LINK_NEW,
    DTS_NODE_NETWORK_ADSL_LINK,
    DTS_NODE_NETWORK_ADSL_USER_NEW,
    DTS_NODE_NETWORK_ADSL_USER,
    DTS_NODE_NETWORK_TOS_NEW,
    DTS_NODE_NETWORK_TOS
};
Function Documentation
struct xml_doc* app_getxmldoc (struct dtsgui * dtsgui) read
return reference to xmldoc stored in userdata.
The user data is available from the application data handle the correct referencing und un referencing of the data.
Parameters
dtsgui Application data ptr.
Returns
XML Document.
Definition at line 56 of file wxforms.c.
References dtsgui_userdata(), objlock(), objref(), objunlock(), objunref(), and app_data::xmldoc.
Referenced by advanced_config(), export_config(), iface_config(), pbx_settings(), reconfig_wizard(), view_config_conf(), and view_config_xml().
{
    struct app_data *appdata;
    struct xml_doc *xmldoc;
    if (!(appdata = dtsgui_userdata(dtsgui))) {
        return NULL;
    }
    objlock(appdata);
    if (appdata->xmldoc && objref(appdata->xmldoc)) {
        xmldoc = appdata->xmldoc;
    } else {
        objunlock(appdata);
        objunref(appdata);
        return NULL;
    }
    objunlock(appdata);
    objunref(appdata);
    return xmldoc;
}
void file_menu (struct dtsgui * dtsgui)
Create the File menu in the menu bar.
Parameters
dtsgui Application data ptr.
Definition at line 79 of file wxforms.c.
References app_data::c_open, dtsgui_close(), dtsgui_exit(), dtsgui_menusep(), dtsgui_newmenu(), dtsgui_newmenucb(), dtsgui_userdata(), app_data::e_wiz, editsys_wizard(), app_data::n_wiz, newsys_wizard(), objlock(), objunlock(), objunref(), and open_config().
Referenced by guiconfig_cb().
{
    dtsgui_menu file;
    struct app_data *appdata;
    if (!(appdata = dtsgui_userdata(dtsgui))) {
        return;
    }
    file = dtsgui_newmenu(dtsgui, "&File");
    objlock(appdata);
    appdata->n_wiz = dtsgui_newmenucb(file, dtsgui, "&New System (Wizard)", "New System Configuration Wizard", 1, newsys_wizard, NULL);
    appdata->e_wiz = dtsgui_newmenucb(file, dtsgui, "&Edit Saved System (Wizard)", "Reconfigure Saved System File With Wizard ", 1, editsys_wizard, NULL);
    dtsgui_menusep(file);
    appdata->c_open = dtsgui_newmenucb(file, dtsgui, "&Open Config File", "Open System Config From A File", 1, open_config, NULL);
    objunlock(appdata);
    dtsgui_menusep(file);
    dtsgui_close(file, dtsgui);
    dtsgui_exit(file, dtsgui);
    objunref(appdata);
}
FRAMEWORK_MAIN ("Distrotech System Administration" , "Gregory Hinton Nietsky" , "gregory@distrotech.co.za" , "http://www.distrotech.co.za" , 2013 , NULL , 0 , NULL)
Application entry point.
The first argument (argv[0]) is the application name.
Parameters
argc Number of arguments in array argv.
argv Array of argumements passed on the commandline.
Returns
Exit code.
Definition at line 167 of file wxforms.c.
References DATA_DIR, app_data::datadir, dtsgui_config(), dtsgui_run(), free_appdata(), guiconfig_cb(), is_file(), objalloc(), objunref(), xml_close(), xml_init(), xslt_close(), and xslt_init().
             ://www.distrotech.co.za", 2013, NULL, 0, NULL) {
    struct point wsize = {800, 600};
    struct point wpos = {50, 50};
    struct app_data *appdata;
    int res;
    char apppath[PATH_MAX];
    if (!(appdata = objalloc(sizeof(*appdata), free_appdata))) {
        return -1;
    }
#ifdef __WIN32
    getwin32folder(CSIDL_COMMON_APPDATA, apppath);
    appdata->datadir = malloc(strlen(apppath)+12);
    snprintf((char*)appdata->datadir, strlen(apppath)+12, "%s\\Distrotech", apppath);
    chdir(appdata->datadir);
    _putenv("XML_DEBUG_CATALOG=\"\"");
    _putenv("XML_CATALOG_FILES=catalog.xml");
#else
    appdata->datadir = strdup(DATA_DIR);
    snprintf(apppath, strlen(appdata->datadir)+13, "%s/catalog.xml", appdata->datadir);
    if (is_file(apppath)) {
        setenv("XML_CATALOG_FILES", apppath, 1);
    }
    setenv("XML_DEBUG_CATALOG", "", 0);
#endif
    xml_init();
    xslt_init();
    dtsgui_config(guiconfig_cb, appdata, &wsize, &wpos, "Distrotech System App", "Welcome to Distrotech App!");
    res = dtsgui_run(argc, argv);
    objunref(appdata);
    xslt_close();
    xml_close();
    return res;
}
void free_appdata (void * data)
Callback called when reference count becomes 0.
Free datadir and un reference xmldoc as we going away.
Parameters
data Application user data reference.
Definition at line 149 of file wxforms.c.
References app_data::datadir, objunref(), and app_data::xmldoc.
Referenced by FRAMEWORK_MAIN().
{
    struct app_data *appdata = data;
    if (appdata->datadir) {
        free((void*)appdata->datadir);
    }
    if (appdata->xmldoc) {
        objunref(appdata->xmldoc);
    }
}
int guiconfig_cb (struct dtsgui * dtsgui, void * data)
GUI application callback.
This is called on GUI application creation returning 0 will end the GUI returning non zero will pass control to the GUI.
See Also
dtsgui_configcb
Parameters
dtsgui Application data ptr.
data Application userdata reference.
Returns
Non zero value to pass control to the GUI.
Definition at line 130 of file wxforms.c.
References app_toolbar(), config_menu(), dtsgui_setuptoolbar(), file_menu(), and help_menu().
Referenced by FRAMEWORK_MAIN().
{
    if (!data) {
        return 0;
    }
    dtsgui_setuptoolbar(dtsgui, app_toolbar, NULL);
    /* menus*/
    file_menu(dtsgui);
    config_menu(dtsgui);
    help_menu(dtsgui);
    return 1;
}
void help_menu (struct dtsgui * dtsgui)
Create the Help menu in the menu bar.
Parameters
dtsgui Application data ptr.
Definition at line 106 of file wxforms.c.
References dtsgui_about(), dtsgui_menusep(), dtsgui_newmenu(), dtsgui_newmenuitem(), dtsgui_textpane(), and test_menu().
Referenced by guiconfig_cb().
{
    dtsgui_menu help;
    dtsgui_pane p;
    help = dtsgui_newmenu(dtsgui, "&Help");
    p = dtsgui_textpane(dtsgui, "TEST", "Hello This is a text box");
    dtsgui_newmenuitem(help, dtsgui, "&Hello...\tCtrl-H", p);
    dtsgui_menusep(help);
    test_menu(dtsgui, help, "https://sip1.speakezi.co.za:666/auth/test.php");
    dtsgui_menusep(help);
    dtsgui_about(help, dtsgui, "This is a test application!!!!");
}
void xml_config (struct xml_doc * xmldoc)
Display formated XML Document on the console.
Parameters
xmldoc XML Document to display
Definition at line 42 of file wxforms.c.
References objunref(), xml_doctobuffer(), and xml_getbuffer().
{
    void *xmlbuf;
    xmlbuf = xml_doctobuffer(xmldoc);
    printf("%s\n", xml_getbuffer(xmlbuf));
    objunref(xmlbuf);
}