DTS Application Library: SHA2-256Hashing and digest functions
SHA2-256Hashing and digest functions
Hashing and digest functions
SHA2-256 Hashing checking and HMAC Functions.
Functions
void sha256sum2 (unsigned char *buff, const void *data, unsigned long len, const void *data2, unsigned long len2)
Calculate the SHA2-256 hash accross 2 data chunks.
void sha256sum (unsigned char *buff, const void *data, unsigned long len)
Calculate the SHA2-256 hash.
int sha256cmp (unsigned char *digest1, unsigned char *digest2)
Compare two SHA2-256 hashes.
void sha256hmac (unsigned char *buff, const void *data, unsigned long len, const void *key, unsigned long klen)
Hash Message Authentication Codes (HMAC) SHA2-256.
Detailed Description
SHA2-256 Hashing checking and HMAC Functions.
Function Documentation
int sha256cmp (unsigned char * digest1, unsigned char * digest2)
Compare two SHA2-256 hashes.
Parameters
digest1 Digest to compare.
digest2 Digest to compare.
Returns
0 on equality.
Definition at line 243 of file util.c.
{
    return (_digest_cmp(digest1, digest2, 32));
}
void sha256hmac (unsigned char * buff, const void * data, unsigned long len, const void * key, unsigned long klen)
Hash Message Authentication Codes (HMAC) SHA2-256.
Parameters
buff HMAC returned in this buffer (32 bytes).
data Data to sign.
len Length of data.
key Key to signwith.
klen Length of key.
Definition at line 314 of file util.c.
References sha256sum2().
{
    _hmac(buff, data, len, key, klen, sha256sum2, 32);
}
void sha256sum (unsigned char * buff, const void * data, unsigned long len)
Calculate the SHA2-256 hash.
Parameters
buff buffer to place the hash (32 bytes).
data First data chunk to calculate.
len Length of data.
Definition at line 144 of file util.c.
References sha256sum2().
{
    sha256sum2(buff, data, len, NULL, 0);
}
void sha256sum2 (unsigned char * buff, const void * data, unsigned long len, const void * data2, unsigned long len2)
Calculate the SHA2-256 hash accross 2 data chunks.
Parameters
buff buffer to place the hash (32 bytes).
data First data chunk to calculate.
len Length of data.
data2 Second data chunk to calculate.
len2 Length of data2.
Definition at line 127 of file util.c.
Referenced by sha256hmac(), and sha256sum().
{
    SHA256_CTX c;
    SHA256_Init(&c);
    SHA256_Update(&c, data, len);
    if (data2) {
        SHA256_Update(&c, data2, len2);
    }
    SHA256_Final(buff, &c);
}