DTS Application Library: XSLT Interface
XSLT Interface
XML Interface
Utilities for managing XML documents.
Files
file libxslt.c
XSLT Interface.
Data Structures
struct xslt_doc
XSLT Document.
struct xslt_param
XSLT Parameter name/value pair.
Typedefs
typedef struct xslt_doc xslt_doc
Forward decleration of structure.
Functions
struct xslt_doc * xslt_open (const char *xsltfile)
Open a XSLT file returning reference to it.
void xslt_addparam (struct xslt_doc *xsltdoc, const char *param, const char *value)
Add a parameter to the XSLT document.
void xslt_clearparam (struct xslt_doc *xsltdoc)
Delete all parameters of a XSLT document.
void xslt_apply (struct xml_doc *xmldoc, struct xslt_doc *xsltdoc, const char *filename, int comp)
Apply XSLT document to a XML document.
void * xslt_apply_buffer (struct xml_doc *xmldoc, struct xslt_doc *xsltdoc)
Apply XSLT document to a XML document returning result in buffer.
void xslt_init ()
Reference the XSLT parser.
void xslt_close ()
Release reference to XSLT parser.
Detailed Description
Utilities for managing XML documents.
Typedef Documentation
typedef struct xslt_doc xslt_doc
Forward decleration of structure.
Definition at line 634 of file dtsapp.h.
Function Documentation
void xslt_addparam (struct xslt_doc * xsltdoc, const char * param, const char * value)
Add a parameter to the XSLT document.
Parameters
xsltdoc Reference to XSLT document.
param Name of parameter.
value Parameter value.
Definition at line 94 of file libxslt.c.
References addtobucket(), ALLOC_CONST, xslt_param::name, objalloc(), objlock(), objref(), objunlock(), objunref(), xslt_doc::params, and xslt_param::value.
{
     struct xslt_param *xparam;
     int size;
     if (!xsltdoc || !xsltdoc->params || !objref(xsltdoc) || !(xparam = objalloc(sizeof(*xparam), free_param))) {
         return;
     }
     size = strlen(value) + 3;
     ALLOC_CONST(xparam->name, param);
     xparam->value = malloc(size);
     snprintf((char *)xparam->value, size, "'%s'", value);
     objlock(xsltdoc);
     addtobucket(xsltdoc->params, xparam);
     objunlock(xsltdoc);
     objunref(xparam);
     objunref(xsltdoc);
 }
void xslt_apply (struct xml_doc * xmldoc, struct xslt_doc * xsltdoc, const char * filename, int comp)
Apply XSLT document to a XML document.
Parameters
xmldoc Reference to XML document.
xsltdoc Reference to XSLT document.
filename File to write the result too.
comp Compression level 0-9 [0 = none].
Definition at line 167 of file libxslt.c.
References xslt_doc::doc, objlock(), objunlock(), objunref(), touch(), and xslt_clearparam().
{
     const char **params = NULL;
     xmlDocPtr res;
     /* ref's xml/xslt locks xslt IF set*/
     if (!(params = xslt_params(xmldoc, xsltdoc))) {
         return;
     }
 #ifndef __WIN32__
     touch(filename, 80, 80);
 #else
     touch(filename);
 #endif
     objlock(xmldoc);
     res = xsltApplyStylesheet(xsltdoc->doc, xmldoc->doc, params);
     xsltSaveResultToFilename(filename, res, xsltdoc->doc, comp);
     objunlock(xmldoc);
     objunref(xmldoc);
     objunlock(xsltdoc);
     free(params);
     xmlFreeDoc(res);
     xslt_clearparam(xsltdoc);
     objunref(xsltdoc);
 }
void* xslt_apply_buffer (struct xml_doc * xmldoc, struct xslt_doc * xsltdoc)
Apply XSLT document to a XML document returning result in buffer.
Parameters
xmldoc Reference to XML document.
xsltdoc Reference to XSLT document.
Returns
Reference to xml_buffer containing the result of the transform.
Definition at line 198 of file libxslt.c.
References xslt_doc::doc, objalloc(), objlock(), objunlock(), objunref(), xml_free_buffer(), and xslt_clearparam().
{
     struct xml_buffer *xmlbuf;
     const char **params;
     xmlDocPtr res;
     if (!(xmlbuf = objalloc(sizeof(*xmlbuf),xml_free_buffer))) {
         return NULL;
     }
     if (!(params = xslt_params(xmldoc, xsltdoc))) {
         objunref(xmlbuf);
         return NULL;
     }
     objlock(xmldoc);
     res = xsltApplyStylesheet(xsltdoc->doc, xmldoc->doc, params);
     xsltSaveResultToString(&xmlbuf->buffer, &xmlbuf->size, res, xsltdoc->doc);
     objunlock(xmldoc);
     objunref(xmldoc);
     objunlock(xsltdoc);
     free(params);
     xmlFreeDoc(res);
     xslt_clearparam(xsltdoc);
     objunref(xsltdoc);
     return xmlbuf;
 }
void xslt_clearparam (struct xslt_doc * xsltdoc)
Delete all parameters of a XSLT document.
Parameters
xsltdoc Reference to XSLT document.
Definition at line 115 of file libxslt.c.
References create_bucketlist(), objlock(), objunlock(), objunref(), and xslt_doc::params.
Referenced by xslt_apply(), and xslt_apply_buffer().
{
     if (!xsltdoc || !xsltdoc->params) {
         return;
     }
     objlock(xsltdoc);
     objunref(xsltdoc->params);
     xsltdoc->params = create_bucketlist(0, xslt_hash);
     objunlock(xsltdoc);
 }
void xslt_close ()
Release reference to XSLT parser.
Note
It is best if the application keeps a reference to the parser before use of XSLT and release it on termination.
Definition at line 241 of file libxslt.c.
References objunref().
{
     if (xslt_has_init_parser) {
         objunref(xslt_has_init_parser);
     }
 }
void xslt_init ()
Reference the XSLT parser.
Note
It is best if the application keeps a reference to the parser before use of XSLT and release it on termination.
Definition at line 230 of file libxslt.c.
References objalloc(), and objref().
Referenced by xslt_open().
{
     if (!xslt_has_init_parser) {
         xslt_has_init_parser=objalloc(0, free_parser);
     } else {
         objref(xslt_has_init_parser);
     }
 }
struct xslt_doc* xslt_open (const char * xsltfile)
Open a XSLT file returning reference to it.
Parameters
xsltfile XSLT pathname to open.
Returns
Reference to XSLT document.
Definition at line 67 of file libxslt.c.
References create_bucketlist(), xslt_doc::doc, objalloc(), xslt_doc::params, and xslt_init().
{
     struct xslt_doc *xsltdoc;
     if (!(xsltdoc = objalloc(sizeof(*xsltdoc), free_xsltdoc))) {
         return NULL;
     }
     xslt_init();
     xsltdoc->doc = xsltParseStylesheetFile((const xmlChar *)xsltfile);
     xsltdoc->params = create_bucketlist(0, xslt_hash);
     return xsltdoc;
 }