DTS Application Library: System configuration wizard
System configuration wizard
Distrotech Server Configuration Application
System configuration wizard.
Files
file wizard.c
System configuration wizard.
Functions
void wizz_custinfo (dtsgui_pane *pg)
Customer information panel.
void wizz_netinfo (dtsgui_pane pg)
Network information panel.
void wizz_dyndns (dtsgui_pane pg)
Dynamic DNS configuration panel.
void wizz_dnsinfo (dtsgui_pane pg)
DNS/Wins configuration panel.
void wizz_x509 (dtsgui_pane pg)
X.509 configuration panel.
void wizz_samba (dtsgui_pane pg)
Samba configuration panel.
void wizz_network (dtsgui_pane pg)
Network configuration panel.
void wizz_exten (dtsgui_pane pg)
Default extension settings panel.
void wizz_location (dtsgui_pane pg)
Location information panel.
void wizz_acd (dtsgui_pane pg)
ACD configuration panel.
void wizz_trunk (dtsgui_pane pg)
Telephony Trunk configuration panel.
void wizz_voip (dtsgui_pane pg)
VOIP Configuration panel.
dtsgui_pane newsys_wizard (struct dtsgui *dtsgui, const char *title, void *data)
Callback from create new system menu item.
dtsgui_pane editsys_wizard (struct dtsgui *dtsgui, const char *title, void *data)
Callback from edit customer configuration.
dtsgui_pane reconfig_wizard (struct dtsgui *dtsgui, const char *title, void *data)
Callback from configuration menu.
Detailed Description
System configuration wizard.
Function Documentation
dtsgui_pane editsys_wizard (struct dtsgui * dtsgui, const char * title, void * data)
Callback from edit customer configuration.
Open the configuration and run the wizard.
Parameters
dtsgui Application data ptr.
title Name of the menuitem as shown on status bar.
data Data supplied to the menuitem.
Returns
NULL as the wizzard will run and no panel is supplied for dislpay area.
Definition at line 523 of file wizard.c.
References dtsgui_alert(), dtsgui_fileopen(), objunref(), and xml_loaddoc().
Referenced by file_menu().
{
    struct xml_doc *xmldoc;
    const char *filename;
    if (!(filename = dtsgui_fileopen(dtsgui, "Select Customer Configuration To Edit", NULL, "", "XML Configuration|*.xml"))) {
        return NULL;
    }
    if (!(xmldoc = xml_loaddoc(filename, 1  ))) {
        objunref((void*)filename);
        dtsgui_alert(dtsgui, "Configuration failed to load.\n");
        return NULL;
    }
    system_wizard(dtsgui, data, filename, xmldoc, 1);
    objunref((void*)filename);
    return NULL;
}
dtsgui_pane newsys_wizard (struct dtsgui * dtsgui, const char * title, void * data)
Callback from create new system menu item.
Open the default configuration and run the wizard saving to a new file.
Parameters
dtsgui Application data ptr.
title Name of the menuitem as shown on status bar.
data Data supplied to the menuitem.
Returns
NULL as the wizzard will run and no panel is supplied for dislpay area.
Definition at line 491 of file wizard.c.
References app_data::datadir, dtsgui_alert(), dtsgui_userdata(), is_file(), objunref(), and xml_loaddoc().
Referenced by file_menu().
{
    char defconf[PATH_MAX];
    struct xml_doc *xmldoc;
    struct app_data *appdata;
    if (!(appdata = dtsgui_userdata(dtsgui))) {
        return NULL;
    }
    snprintf(defconf, PATH_MAX-1, "%s/default.xml", appdata->datadir);
    objunref(appdata);
    if (!is_file(defconf)) {
        dtsgui_alert(dtsgui, "Default configuration not found.\nCheck Installation.");
        return NULL;
    }
    if (!(xmldoc = xml_loaddoc(defconf, 1))) {
        dtsgui_alert(dtsgui, "Default configuration failed to load.\nCheck Installation.");
        return NULL;
    }
    system_wizard(dtsgui, data, NULL, xmldoc, 1);
    return NULL;
}
dtsgui_pane reconfig_wizard (struct dtsgui * dtsgui, const char * title, void * data)
Callback from configuration menu.
Run the wizard on the current application XML document.
Parameters
dtsgui Application data ptr.
title Name of the menuitem as shown on status bar.
data Data supplied to the menuitem.
Returns
NULL as the wizzard will run and no panel is supplied for dislpay area.
Definition at line 550 of file wizard.c.
References app_getxmldoc().
Referenced by config_menu().
{
    struct xml_doc *xmldoc;
    if (!(xmldoc = app_getxmldoc(dtsgui))) {
        return NULL;
    }
    system_wizard(dtsgui, data, NULL, xmldoc, 0);
    return NULL;
}
void wizz_acd (dtsgui_pane pg)
ACD configuration panel.
Parameters
pg Panel to configure.
Definition at line 348 of file wizard.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
{
    dtsgui_xmltextbox(pg, "Queue Timeout Checked Every 18s", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "AATimeout", NULL);
    dtsgui_xmltextbox(pg, "Auto Attendant Mailbox/Forward On No Agent/Timeout", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "AANext", NULL);
    dtsgui_xmltextbox(pg, "IVR Delay Between Digits", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "AADelay", NULL);
    dtsgui_xmlcheckbox(pg, "Disable Default Auto Attendant Prompts", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "AANOPROMPT", NULL);
    dtsgui_xmlcheckbox(pg, "Music On Hold When Calling Reception", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "AAMOH", NULL);
    dtsgui_xmlcheckbox(pg, "Record Inbound Calls", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "AAREC", NULL);
}
void wizz_custinfo (dtsgui_pane * pg)
Customer information panel.
Parameters
pg Panel to configure.
Definition at line 177 of file wizard.c.
References dtsgui_xmltextbox(), and dtsgui_xmltextbox_multi().
Referenced by customer_info().
{
    dtsgui_xmltextbox(pg, "Customer Name", NULL, "/config/Customer", "Option", "option", "Name", NULL);
    dtsgui_xmltextbox(pg, "Contact Person", NULL, "/config/Customer", "Option", "option", "Contact", NULL);
    dtsgui_xmltextbox(pg, "Email Address", NULL, "/config/Customer", "Option", "option", "Email", NULL);
    dtsgui_xmltextbox_multi(pg, "Customer Address (Postal)", NULL, "/config/Customer", "Option", "option", "Postal Addr", NULL);
    dtsgui_xmltextbox_multi(pg, "Customer Address (Physical)", NULL, "/config/Customer", "Option", "option", "Phys Addr", NULL);
    dtsgui_xmltextbox(pg, "Customer Tel", NULL, "/config/Customer", "Option", "option", "Tel", NULL);
    dtsgui_xmltextbox(pg, "Customer Company ID", NULL, "/config/Customer", "Option", "option", "ID", NULL);
    dtsgui_xmltextbox(pg, "VAT No.", NULL, "/config/Customer", "Option", "option", "VAT", NULL);
}
void wizz_dnsinfo (dtsgui_pane pg)
DNS/Wins configuration panel.
Parameters
pg Panel to configure.
Definition at line 209 of file wizard.c.
References dtsgui_xmltextbox().
{
    dtsgui_xmltextbox(pg, "Primary DNS", NULL, "/config/IP/SysConf", "Option", "option", "PrimaryDns", NULL);
    dtsgui_xmltextbox(pg, "Secondary DNS", NULL, "/config/IP/SysConf", "Option", "option", "SecondaryDns", NULL);
    dtsgui_xmltextbox(pg, "Primary WINS", NULL, "/config/IP/SysConf", "Option", "option", "PrimaryWins", NULL);
    dtsgui_xmltextbox(pg, "Secondary WINS", NULL, "/config/IP/SysConf", "Option", "option", "SecondaryWins", NULL);
    dtsgui_xmltextbox(pg, "Primary MX", NULL, "/config/Email/Config", "Option", "option", "MailExchange1", NULL);
    dtsgui_xmltextbox(pg, "Secondary MX", NULL, "/config/Email/Config", "Option", "option", "MailExchange2", NULL);
}
void wizz_dyndns (dtsgui_pane pg)
Dynamic DNS configuration panel.
Parameters
pg Panel to configure.
Definition at line 201 of file wizard.c.
References dtsgui_xmltextbox().
{
    dtsgui_xmltextbox(pg, "Dynamic DNS Server", NULL, "/config/DNS/Config", "Option", "option", "DynServ", NULL);
    dtsgui_xmltextbox(pg, "Dynamic DNS Zone", NULL, "/config/DNS/Config", "Option", "option", "DynZone", NULL);
    dtsgui_xmltextbox(pg, "Dynamic DNS KEY", NULL, "/config/DNS/Config", "Option", "option", "DynKey", NULL);
}
void wizz_exten (dtsgui_pane pg)
Default extension settings panel.
Parameters
pg Panel to configure.
Definition at line 260 of file wizard.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), dtsgui_xmltextbox(), listitem::name, objunref(), and listitem::value.
{
    struct form_item *ilist;
    struct listitem cos[] = {{"Internal Extensions", "0"},
                             {"Local PSTN", "1"},
                             {"Long Distance PSTN", "2"},
                             {"Cellular", "3"},
                             {"Premium", "4"},
                             {"International", "5"}};
    int cnt;
    ilist = dtsgui_xmllistbox(pg, "Default Extension Permision", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "Context", NULL);
    for(cnt=0;cnt <= 5; cnt++) {
        dtsgui_listbox_add(ilist, cos[cnt].name, cos[cnt].value);
    }
    objunref(ilist);
    ilist = dtsgui_xmllistbox(pg, "Default Auth Extension Permision", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "AuthContext", NULL);
    for(cnt=0;cnt <= 5; cnt++) {
        dtsgui_listbox_add(ilist, cos[cnt].name, cos[cnt].value);
    }
    objunref(ilist);
    ilist = dtsgui_xmllistbox(pg, "Default After Hours Extension Permision", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "DEFALOCK", NULL);
    for(cnt=0;cnt <= 5; cnt++) {
        dtsgui_listbox_add(ilist, cos[cnt].name, cos[cnt].value);
    }
    objunref(ilist);
    ilist = dtsgui_xmllistbox(pg, "Snom Network Port Config", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "SnomNet", NULL);
    dtsgui_listbox_add(ilist, "100Mb/s Full Duplex", "100full");
    dtsgui_listbox_add(ilist, "100Mb/s Half Duplex", "100half");
    dtsgui_listbox_add(ilist, "10Mb/s Full Duplex", "10full");
    dtsgui_listbox_add(ilist, "10Mb/s Half Duplex", "10half");
    dtsgui_listbox_add(ilist, "Auto", "auto");
    objunref(ilist);
    dtsgui_xmltextbox(pg, "Voip Vlan Interface", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "AutoVLAN", NULL);
    dtsgui_xmltextbox(pg, "Default Extension Prefix", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "DefaultPrefix", NULL);
    dtsgui_xmltextbox(pg, "Auto Config Start", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "AutoStart", NULL);
    dtsgui_xmltextbox(pg, "Auto Config End", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "AutoEnd", NULL);
    dtsgui_xmltextbox(pg, "Default Ring Timeout", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "Timeout", NULL);
    dtsgui_xmlcheckbox(pg, "Require Authorization", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "AutoAuth", NULL);
    dtsgui_xmlcheckbox(pg, "Lock Snom Phone Settings", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "AutoLock", NULL);
    dtsgui_xmlcheckbox(pg, "Enable Voice Mail", NULL, "0", "1", "/config/IP/VOIP/ASTDB", "Option", "option", "DEFNOVMAIL", NULL);
    dtsgui_xmlcheckbox(pg, "Enable Call Logging", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "DEFRECORD", NULL);
    dtsgui_xmlcheckbox(pg, "Require Extension Number With PIN", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "ADVPIN", NULL);
}
void wizz_location (dtsgui_pane pg)
Location information panel.
Parameters
pg Panel to configure.
Definition at line 311 of file wizard.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), dtsgui_xmltextbox(), and objunref().
{
    struct form_item *ilist;
    dtsgui_xmltextbox(pg, "Local Area Code", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "AreaCode", NULL);
    dtsgui_xmltextbox(pg, "Local Extension Prefix", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "ExCode", NULL);
    ilist = dtsgui_xmllistbox(pg, "ISDN PRI Framing [T1-E1]", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "PRIframing", NULL);
    dtsgui_listbox_add(ilist, "ccs - esf", "ccs");
    dtsgui_listbox_add(ilist, "cas - d4/Superframe", "cas");
    objunref(ilist);
    ilist = dtsgui_xmllistbox(pg, "ISDN PRI Coding [T1-E1]", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "PRIcoding", NULL);
    dtsgui_listbox_add(ilist, "hdb3 - b8zs", "hdb3");
    dtsgui_listbox_add(ilist, "ami", "ami");
    objunref(ilist);
    ilist = dtsgui_xmllistbox(pg, "Line Build Out", NULL, "/config/IP/VOIP/ASTDB", "Option", "option", "PRIlbo", NULL);
    dtsgui_listbox_add(ilist, "0 db (CSU) / 0-133 feet (DSX-1)", "0");
    dtsgui_listbox_add(ilist, "133-266 feet (DSX-1)", "1");
    dtsgui_listbox_add(ilist, "266-399 feet (DSX-1)", "2");
    dtsgui_listbox_add(ilist, "399-533 feet (DSX-1)", "3");
    dtsgui_listbox_add(ilist, "533-655 feet (DSX-1)", "4");
    dtsgui_listbox_add(ilist, "-7.5db (CSU)", "5");
    dtsgui_listbox_add(ilist, "-15db (CSU)", "6");
    dtsgui_listbox_add(ilist, "-22.5db (CSU)", "7");
    objunref(ilist);
    dtsgui_xmlcheckbox(pg, "Calls To Internal Extensions Follow Forward Rules", NULL, "1", "0", "the /config/IP/VOIP/ASTDB", "Option", "option", "LocalFwd", NULL);
    dtsgui_xmlcheckbox(pg, "Hangup Calls To Unknown Numbers/DDI", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "UNKDEF", NULL);
    dtsgui_xmlcheckbox(pg, "ISDN BRI Immeadiate Routeing (No MSN/DDI)", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "mISDNimm", NULL);
    dtsgui_xmlcheckbox(pg, "ISDN BRI Use Round Robin Routing", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "mISDNrr", NULL);
    dtsgui_xmlcheckbox(pg, "ISDN Allow Automatic Setting Of CLI (DDI Required)", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "AutoCLI", NULL);
    dtsgui_xmlcheckbox(pg, "ISDN PRI CRC4 Checking (E1 Only)", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "PRIcrc4", NULL);
}
void wizz_netinfo (dtsgui_pane pg)
Network information panel.
Parameters
pg Panel to configure.
Definition at line 190 of file wizard.c.
References dtsgui_xmltextbox().
{
    dtsgui_xmltextbox(pg, "IPv4 Address", NULL, "/config/IP/Interfaces/Interface[/config/IP/SysConf/Option[@option = 'Internal'] = .]", NULL, NULL, NULL, "ipaddr");
    dtsgui_xmltextbox(pg, "IPv4 Subnet Length", NULL, "/config/IP/Interfaces/Interface[/config/IP/SysConf/Option[@option = 'Internal'] = .]", NULL, NULL, NULL, "subnet");
    dtsgui_xmltextbox(pg, "Domain Name", NULL, "/config/DNS/Config", "Option", "option", "Domain", NULL);
    dtsgui_xmltextbox(pg, "Default Gateway", NULL, "/config/IP/SysConf", "Option", "option", "Nexthop", NULL);
    dtsgui_xmltextbox(pg, "SMTP Gateway", NULL, "/config/Email/Config", "Option", "option", "Smarthost", NULL);
    dtsgui_xmltextbox(pg, "NTP Server", NULL, "/config/IP/SysConf", "Option", "option", "NTPServer", NULL);
}
void wizz_network (dtsgui_pane pg)
Network configuration panel.
Parameters
pg Panel to configure.
Definition at line 242 of file wizard.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmlcombobox(), dtsgui_xmltextbox(), and objunref().
{
    struct form_item *ilist;
    ilist = dtsgui_xmlcombobox(pg, "External Interface", NULL, "/config/tmp", "extif", NULL, NULL, NULL);
    dtsgui_listbox_add(ilist, "br0", "br0");
    dtsgui_listbox_add(ilist, "ethB", "ethB");
    dtsgui_listbox_add(ilist, "br0.100", "br0.100");
    dtsgui_listbox_add(ilist, "3G", "3G");
    objunref(ilist);
    dtsgui_xmlcheckbox(pg, "External Device Is PPPoE", NULL, "ADSL", "Dialup", "/config/tmp", "extif", NULL, NULL, "pppoe");
    dtsgui_xmltextbox(pg, "Number/Service/APN", NULL, "/config/IP/Dialup", "Option", "option", "Number", NULL);
    dtsgui_xmltextbox(pg, "Username", NULL, "/config/IP/Dialup", "Option", "option", "Username", NULL);
    dtsgui_xmltextbox(pg, "Password", NULL, "/config/IP/Dialup", "Option", "option", "Password", NULL);
    dtsgui_xmltextbox(pg, "MTU", NULL, "/config/IP/Dialup", "Option", "option", "MTU", NULL);
}
void wizz_samba (dtsgui_pane pg)
Samba configuration panel.
Parameters
pg Panel to configure.
Definition at line 232 of file wizard.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
{
    dtsgui_xmltextbox(pg, "Workgroup/Domain", NULL, "/config/FileServer/Setup", "Option", "option", "Domain", NULL);
    dtsgui_xmltextbox(pg, "Aliases", NULL, "/config/FileServer/Config", "Option", "option", "netbios name", NULL);
    dtsgui_xmltextbox(pg, "Domain Controllers", NULL, "/config/FileServer/Setup", "Option", "option", "ADSServer", NULL);
    dtsgui_xmltextbox(pg, "Realm [If Joining ADS]", NULL, "/config/FileServer/Setup", "Option", "option", "ADSRealm", NULL);
    dtsgui_xmlcheckbox(pg, "Domain Controller", NULL, "1", "0", "/config/tmp", "dcon", NULL, NULL, NULL);
}
void wizz_trunk (dtsgui_pane pg)
Telephony Trunk configuration panel.
Parameters
pg Panel to configure.
Definition at line 359 of file wizard.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), dtsgui_xmltextbox(), and objunref().
{
    struct form_item *ilist;
    ilist = dtsgui_xmllistbox(pg, "Primary Trunk", NULL, NULL, NULL, NULL, NULL, NULL);
    dtsgui_listbox_add(ilist, "None", NULL);
    dtsgui_listbox_add(ilist, "ISDN PRI", NULL);
    dtsgui_listbox_add(ilist, "ISDN BRI", NULL);
    dtsgui_listbox_add(ilist, "Analogue", NULL);
    objunref(ilist);
    dtsgui_xmltextbox(pg, "No. Of Trunk Ports", NULL, NULL, NULL, NULL, NULL, NULL);
    ilist = dtsgui_xmllistbox(pg, "Gateway Trunk", NULL, NULL, NULL, NULL, NULL,NULL);
    dtsgui_listbox_add(ilist, "None", NULL);
    dtsgui_listbox_add(ilist, "ISDN PRI", NULL);
    dtsgui_listbox_add(ilist, "ISDN BRI", NULL);
    dtsgui_listbox_add(ilist, "Analogue", NULL);
    objunref(ilist);
    dtsgui_xmltextbox(pg, "No. Of Gateway Ports", NULL, NULL, NULL, NULL, NULL, NULL);
    dtsgui_xmlcheckbox(pg, "Extensions Are On Gateway By Default", NULL, "1", "0", "/config/IP/VOIP/ASTDB", "Option", "option", "REMDEF", NULL);
}
void wizz_voip (dtsgui_pane pg)
VOIP Configuration panel.
Parameters
pg Panel to configure.
Definition at line 383 of file wizard.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), and objunref().
{
    struct form_item *ilist;
    ilist = dtsgui_xmllistbox(pg, "Protocol", NULL, "/config/IP", "VOIP", NULL, NULL, "protocol");
    dtsgui_listbox_add(ilist, "SIP", "SIP");
    dtsgui_listbox_add(ilist, "IAX2", "IAX2");
    objunref(ilist);
    dtsgui_xmlcheckbox(pg, "Use DTMF INFO (SIP)", NULL, "info", "rfc2833", "/config/IP", "VOIP", NULL, NULL, "dtmf");
    dtsgui_xmlcheckbox(pg, "Use SRTP (SIP)", NULL, "true", "false", "/config/IP", "VOIP", NULL, NULL, "srtp");
    dtsgui_xmlcheckbox(pg, "Use From User (SIP [Disables Sending CLI])", NULL, "true", "false", "/config/IP", "VOIP", NULL, NULL, "fromuser");
    dtsgui_xmlcheckbox(pg, "Disable Video", NULL, "true", "false", "/config/IP", "VOIP", NULL, NULL, "novideo");
    dtsgui_xmlcheckbox(pg, "Register To Server", NULL, "true", "false", "/config/IP", "VOIP", NULL, NULL, "register");
}
void wizz_x509 (dtsgui_pane pg)
X.509 configuration panel.
Parameters
pg Panel to configure.
Definition at line 220 of file wizard.c.
References dtsgui_xmltextbox().
{
    dtsgui_xmltextbox(pg, "Country Code", NULL, "/config/X509", "Option", "option", "Country", NULL);
    dtsgui_xmltextbox(pg, "Province/State", NULL, "/config/X509", "Option", "option", "State", NULL);
    dtsgui_xmltextbox(pg, "City", NULL, "/config/X509", "Option", "option", "City", NULL);
    dtsgui_xmltextbox(pg, "Company", NULL, "/config/X509", "Option", "option", "Company", NULL);
    dtsgui_xmltextbox(pg, "Division", NULL, "/config/X509", "Option", "option", "Division", NULL);
    dtsgui_xmltextbox(pg, "Name", NULL, "/config/X509", "Option", "option", "Name", NULL);
    dtsgui_xmltextbox(pg, "Email", NULL, "/config/X509", "Option", "option", "Email", NULL);
}