DTS Application Library: INI Style config file Interface
INI Style config file Interface
Distrotech Application Library
Reads a ini config file into grouped hashed buckets.
Files
file config.c
INI style config file interface.
Data Structures
struct config_category
Configuration file category.
struct config_file
Config file.
struct config_entry
Configuration category entry.
Typedefs
typedef void(* config_filecb)(struct bucket_list *, const char *, const char *)
Calback used when processing config files.
typedef void(* config_catcb)(struct bucket_list *, const char *)
Calback used when processing a category.
typedef void(* config_entrycb)(const char *, const char *)
Callback used when processing a entry.
Functions
void unrefconfigfiles (void)
Empty out and unreference config files.
int process_config (const char *configname, const char *configfile)
Process a configfile into buckets.
struct bucket_list * get_config_file (const char *configname)
Returns the catergories bucket for a config file.
struct bucket_list * get_config_category (const char *configname, const char *category)
Return a single category.
struct bucket_list * get_category_next (struct bucket_loop *cloop, char *name, int len)
Iterate through categories returning the entries bucket.
struct bucket_loop * get_category_loop (const char *configname)
Return a bucket loop to allow iterating over categories.
void config_entry_callback (struct bucket_list *entries, config_entrycb entry_cb)
Callback Wraper that iterates through all items calling a callback for each item.
void config_cat_callback (struct bucket_list *categories, config_catcb cat_cb)
Callback wrapper that iterates through categories calling a callback on each category.
void config_file_callback (config_filecb file_cb)
Callback wrapper to iterate over all configfiles calling a callback on each file.
struct config_entry * get_config_entry (struct bucket_list *categories, const char *item)
Find the entry in a config file.
Detailed Description
Reads a ini config file into grouped hashed buckets.
Typedef Documentation
typedef void(* config_catcb)(struct bucket_list *, const char *)
Calback used when processing a category.
Parameters
entries Bucket list containing entries.
name Category name.
Definition at line 291 of file dtsapp.h.
typedef void(* config_entrycb)(const char *, const char *)
Callback used when processing a entry.
Parameters
item Name of the entry.
value Value of the entry.
Definition at line 297 of file dtsapp.h.
typedef void(* config_filecb)(struct bucket_list *, const char *, const char *)
Calback used when processing config files.
Parameters
categories Bucket list of categories.
filename The filename.
filepath The filepath.
Definition at line 285 of file dtsapp.h.
Function Documentation
void config_cat_callback (struct bucket_list * categories, config_catcb cat_cb)
Callback wrapper that iterates through categories calling a callback on each category.
See Also
config_catcb
Parameters
categories Bucketlist from a config file containing categories.
cat_cb Callback to call on each category.
Definition at line 383 of file config.c.
References bucketlist_callback().
{
     bucketlist_callback(categories, category_callback, &cat_cb);
 }
void config_entry_callback (struct bucket_list * entries, config_entrycb entry_cb)
Callback Wraper that iterates through all items calling a callback for each item.
See Also
config_entrycb
Parameters
entries Bucketlist of entries (from a category).
entry_cb The callback to call on each entry.
Definition at line 365 of file config.c.
References bucketlist_callback().
{
     bucketlist_callback(entries, entry_callback, &entry_cb);
 }
void config_file_callback (config_filecb file_cb)
Callback wrapper to iterate over all configfiles calling a callback on each file.
See Also
config_filecb
Parameters
file_cb Callback to call.
Definition at line 400 of file config.c.
References bucketlist_callback().
{
     bucketlist_callback(configfiles, file_callback, &file_cb);
 }
struct bucket_loop* get_category_loop (const char * configname)
Return a bucket loop to allow iterating over categories.
Parameters
configname Name assigned to the config file when calling process_config().
Returns
Bucket loop iterator.
Definition at line 341 of file config.c.
References get_config_file(), init_bucket_loop(), and objunref().
{
     struct bucket_loop *cloop;
     struct bucket_list *file;
     file = get_config_file(configname);
     cloop = init_bucket_loop(file);
     objunref(file);
     return (cloop);
 }
struct bucket_list* get_category_next (struct bucket_loop * cloop, char * name, int len)
Iterate through categories returning the entries bucket.
As well as the entries returned name will be filled upto len bytes with the category name
Parameters
cloop Iterator created with get_category_loop.
name Buffer where the category name is copied.
len limit the number of characters copied to len.
Returns
Entries list for category returned in paramaater name.
Definition at line 317 of file config.c.
References config_category::entries, config_category::name, next_bucket_loop(), objref(), objunref(), and strlenzero().
{
     struct config_category *category;
     if (cloop && (category = next_bucket_loop(cloop))) {
         if (category->entries) {
             if (!objref(category->entries)) {
                 objunref(category);
                 return (NULL);
             }
             if (!strlenzero(name)) {
                 strncpy(name, category->name, len);
             }
             objunref(category);
             return (category->entries);
         } else {
             objunref(category);
         }
     }
     return (NULL);
 }
struct bucket_list* get_config_category (const char * configname, const char * category)
Return a single category.
If category is NULL the category "default" is returned.
Parameters
configname Name assigned to the config file when calling process_config().
category Configuration category to return or "default" if NULL.
Returns
Bucket list containing the category.
Definition at line 286 of file config.c.
References bucket_list_find_key(), config_category::entries, get_config_file(), objref(), and objunref().
{
     struct bucket_list *file;
     struct config_category *cat;
     file = get_config_file(configname);
     if (category) {
         cat = bucket_list_find_key(file, category);
     } else {
         cat = bucket_list_find_key(file, "default");
     }
     objunref(file);
     if (cat) {
         if (!objref(cat->entries)) {
             objunref(cat);
             return (NULL);
         }
         objunref(cat);
         return (cat->entries);
     } else {
         return (NULL);
     }
 }
struct config_entry* get_config_entry (struct bucket_list * categories, const char * item)
Find the entry in a config file.
Parameters
categories Categories bucketlist.
item Item to search for.
Returns
Reference to a entry.
Definition at line 408 of file config.c.
References bucket_list_find_key().
{
     struct config_entry *entry;
     entry = bucket_list_find_key(categories, item);
     return (entry);
 }
struct bucket_list* get_config_file (const char * configname)
Returns the catergories bucket for a config file.
Parameters
configname Name assigned to the config file when calling process_config().
Returns
Categories bucketlist.
Definition at line 263 of file config.c.
References bucket_list_find_key(), config_file::cat, objref(), and objunref().
Referenced by get_category_loop(), and get_config_category().
{
     struct config_file *file;
     if ((file = bucket_list_find_key(configfiles, configname))) {
         if (file->cat) {
             if (!objref(file->cat)) {
                 objunref(file);
                 return (NULL);
             }
             objunref(file);
             return (file->cat);
         }
         objunref(file);
     }
     return (NULL);
 }
int process_config (const char * configname, const char * configfile)
Process a configfile into buckets.
Parameters
configname Name of the configuration.
configfile File to load into this configuration container.
Returns
Zero on success.
Definition at line 197 of file config.c.
References addtobucket(), config_file::cat, config_file::filepath, objunref(), strlenzero(), and trim().
{
     struct config_file *file;
     struct config_category *category = NULL;
     FILE *config;
     char line[256];
     char item[128];
     char value[128];
     char *tmp = (char *)&line;
     char *token;
     if (!configfiles) {
         initconfigfiles();
     }
     file = create_conf_file(configname, configfile);
     addtobucket(configfiles, file);
     if (!(config = fopen(file->filepath, "r"))) {
         return (-1);
     }
     while(fgets(line, sizeof(line) - 1, config)) {
         if (!(tmp = filterconf(line, 3))) {
             continue;
         }
         /*this is a new category*/
         if ((token = strchr(tmp, '[')) && (token == tmp)) {
             tmp++;
             token = strrchr(tmp, ']');
             token[0] = '\0';
             tmp = trim(tmp);
             if (!strlenzero(tmp)) {
                 if (category) {
                     objunref(category);
                 }
                 category = create_conf_category(tmp);
                 addtobucket(file->cat, category);
             }
             continue;
         }
         if (sscanf(tmp, "%[^=] %*[=] %[^\n]", (char *)&item, (char *)&value) != 2) {
             continue;
         }
         if (!category) {
             category = create_conf_category("default");
             addtobucket(file->cat, category);
         }
         add_conf_entry(category, trim(item), trim(value));
     }
     fclose(config);
     if (category) {
         objunref(category);
     }
     if (file) {
         objunref(file);
     }
     return (0);
 }
void unrefconfigfiles (void)
Empty out and unreference config files.
Definition at line 78 of file config.c.
References objunref().
Referenced by framework_init().
{
     if (configfiles) {
         objunref(configfiles);
     }
 }