DTS Application Library: CURL Url interface.
CURL Url interface.
Distrotech Application Library
Interface to libCURL.
Files
file curl.c
CURL Interface.
Data Structures
struct curl_progress
Allow progress monitoring.
struct curl_password
CURL Authentification callback.
struct curl_post
HTTP post data structure.
struct basic_auth
Basic authentification structure.
struct curlbuf
Buffer containing the result of a curl transaction.
Typedefs
typedef struct curl_post curl_post
Forward decleration of structure.
typedef struct basic_auth *(* curl_authcb)(const char *, const char *, void *)
Callback to set the authentification ie on error 401.
typedef int(* curl_progress_func)(void *, double, double, double, double)
CURL callback function called when there is progress (CURLOPT_PROGRESSFUNCTION).
typedef void(* curl_progress_pause)(void *, int)
Callback function to control the progress bar.
typedef void *(* curl_progress_newdata)(void *)
Create a new progress data structure.
Functions
int curlinit (void)
Initilise the CURL library.
void curlclose (void)
Un reference CURL. This is required for each call to curlinit().
struct curlbuf * curl_geturl (const char *def_url, struct basic_auth *bauth, curl_authcb authcb, void *auth_data)
Fetch the URL using CURL (HTTP GET)
struct curlbuf * curl_posturl (const char *def_url, struct basic_auth *bauth, struct curl_post *post, curl_authcb authcb, void *auth_data)
Fetch the URL using CURL (HTTP POST)
struct curlbuf * curl_ungzip (struct curlbuf *cbuf)
If the buffer contains GZIP data uncompress it.
struct basic_auth * curl_newauth (const char *user, const char *passwd)
Create a new auth structure with initial vallues.
struct curl_post * curl_newpost (void)
Create a HTTP Post data structure.
void curl_postitem (struct curl_post *post, const char *name, const char *value)
Add a item value pair to post structure.
char * url_escape (char *url)
Escape and return the url.
char * url_unescape (char *url)
UN escape and return the url.
void curl_setprogress (curl_progress_func cb, curl_progress_pause p_cb, curl_progress_newdata d_cb, void *data)
Configure global progress handling.
void curl_setauth_cb (curl_authcb auth_cb, void *data)
Set global password callback.
struct xml_doc * curl_buf2xml (struct curlbuf *cbuf)
Create a XML document from from buffer (application/xml)
Detailed Description
Interface to libCURL.
Typedef Documentation
typedef struct basic_auth*(* curl_authcb)(const char *, const char *, void *)
Callback to set the authentification ie on error 401.
Parameters
user Initial username (currently set)
passwd Initial password (currently set)
data Reference to data passed.
Returns
New auth structure to re attempt authentification.
Definition at line 853 of file dtsapp.h.
typedef struct curl_post curl_post
Forward decleration of structure.
Definition at line 846 of file dtsapp.h.
typedef int(* curl_progress_func)(void *, double, double, double, double)
CURL callback function called when there is progress (CURLOPT_PROGRESSFUNCTION).
Parameters
clientp Reference to userdata supplied.
dltotal Total download bytes.
dlnow Current bytes downloaded.
ultotal Total upload bytes.
ulnow Current upload bytes.
Returns
Returning a non-zero value from this callback will cause the transfer to abort.
Definition at line 862 of file dtsapp.h.
typedef void*(* curl_progress_newdata)(void *)
Create a new progress data structure.
See Also
curl_setprogress()
curl_setprogress() allows setting a default progress callback if set it will call a callback to create a new callback progress userdata for the current session.
Parameters
data Reference to userdata supplied to curl_setprogress().
Returns
Reference to userdata to be used in current session.
Definition at line 876 of file dtsapp.h.
typedef void(* curl_progress_pause)(void *, int)
Callback function to control the progress bar.
Parameters
data Reference to userdata supplied.
state one of 0, 1 or -1 for Pause, Unpause and Close respectfully.
Definition at line 867 of file dtsapp.h.
Function Documentation
struct xml_doc* curl_buf2xml (struct curlbuf * cbuf)
Create a XML document from from buffer (application/xml)
Parameters
cbuf CURL request buffer.
Returns
Reference to XML document.
Definition at line 489 of file curl.c.
References curlbuf::body, curlbuf::bsize, curlbuf::c_type, curl_ungzip(), and xml_loadbuf().
{
     struct xml_doc *xmldoc = NULL;
     if (cbuf && cbuf->c_type && !strcmp("application/xml", cbuf->c_type)) {
         curl_ungzip(cbuf);
         xmldoc = xml_loadbuf(cbuf->body, cbuf->bsize, 1);
     }
     return xmldoc;
 }
struct curlbuf* curl_geturl (const char * def_url, struct basic_auth * bauth, curl_authcb authcb, void * auth_data)
Fetch the URL using CURL (HTTP GET)
Note
if no authcb is specified and curl_setauth_cb() has been called this default will be used.
Parameters
def_url URL to fetch.
bauth Basic auth structure to initilise auth.
authcb Callback if authentification is required.
auth_data Reference to userdata passed in auth callback.
Returns
CURL buffer structure.
Definition at line 276 of file curl.c.
{
     return curl_sendurl(def_url, bauth, NULL, authcb, auth_data);
 }
struct basic_auth* curl_newauth (const char * user, const char * passwd)
Create a new auth structure with initial vallues.
Note
if NULL is supplied its replaced with zero length string
Parameters
user Optional initial username to set.
passwd Optional initial password to set.
Returns
Reference to new authentification structure.
Definition at line 328 of file curl.c.
References objalloc(), basic_auth::passwd, and basic_auth::user.
{
     struct basic_auth *bauth;
     if (!(bauth = (struct basic_auth *)objalloc(sizeof(*bauth), curl_freeauth))) {
         return NULL;
     }
     if (user) {
         bauth->user = strdup(user);
     } else {
         bauth->user = strdup("");
     }
     if (passwd) {
         bauth->passwd = strdup(passwd);
     } else {
         bauth->passwd = strdup("");
     }
     return bauth;
 }
struct curl_post* curl_newpost (void)
Create a HTTP Post data structure.
Returns
Reference to new structure.
Definition at line 356 of file curl.c.
References curl_post::first, curl_post::last, and objalloc().
{
     struct curl_post *post;
     if (!(post = objalloc(sizeof(*post), free_post))) {
         return NULL;
     }
     post->first = NULL;
     post->last = NULL;
     return post;
 }
void curl_postitem (struct curl_post * post, const char * name, const char * value)
Add a item value pair to post structure.
Parameters
post Post structure created with curl_newpost()
name Name of the pair.
value Value of the pair.
Definition at line 370 of file curl.c.
References curl_post::first, curl_post::last, objlock(), and objunlock().
{
     if (!name || !value) {
         return;
     }
     objlock(post);
     curl_formadd(&post->first, &post->last,
         CURLFORM_COPYNAME, name,
         CURLFORM_COPYCONTENTS, value,
         CURLFORM_END);
     objunlock(post);
 }
struct curlbuf* curl_posturl (const char * def_url, struct basic_auth * bauth, struct curl_post * post, curl_authcb authcb, void * auth_data)
Fetch the URL using CURL (HTTP POST)
Note
if no authcb is specified and curl_setauth_cb() has been called this default will be used.
Parameters
def_url URL to fetch.
bauth Basic auth structure to initilise auth.
post Reference to curl post structure.
authcb Callback if authentification is required.
auth_data Reference to userdata passed in auth callback.
Returns
CURL buffer structure.
Definition at line 288 of file curl.c.
{
     return curl_sendurl(def_url, bauth, post, authcb, auth_data);
 }
void curl_setauth_cb (curl_authcb auth_cb, void * data)
Set global password callback.
Note
This will only persist as long as a reference to CURL is held use curlinit() and curlclose() at application startup and shutdown.
Parameters
auth_cb Authentification call back.
data Reference to userdata passed in callback.
Definition at line 470 of file curl.c.
References objalloc(), objref(), and objunref().
{
     if (curlpassword) {
         objunref(curlpassword);
         curlpassword = NULL;
     }
     if (!(curlpassword = objalloc(sizeof(*curlpassword), free_curlpassword))) {
         return;
     }
     curlpassword->authcb = auth_cb;
     if (data && objref(data)) {
         curlpassword->data = data;
     }
 }
void curl_setprogress (curl_progress_func cb, curl_progress_pause p_cb, curl_progress_newdata d_cb, void * data)
Configure global progress handling.
Note
This will only persist as long as a reference to CURL is held use curlinit() and curlclose() at application startup and shutdown.
Parameters
cb CURL progress function callback.
p_cb CURL progress control (pause) callback.
d_cb CURL progress data allocation callback.
data initial data passed to d_cb.
See Also
curl_progress_func()
curl_progress_pause()
curl_progress_newdata()
Definition at line 442 of file curl.c.
References objalloc(), objref(), and objunref().
{
     if (curlprogress) {
         objunref(curlprogress);
         curlprogress = NULL;
     }
     if (!(curlprogress = objalloc(sizeof(*curlprogress), free_progress))) {
         return;
     }
     curlprogress->cb = cb;
     curlprogress->d_cb = d_cb;
     curlprogress->p_cb = p_cb;
     if (data && objref(data)) {
         curlprogress->data = data;
     }
 }
struct curlbuf* curl_ungzip (struct curlbuf * cbuf)
If the buffer contains GZIP data uncompress it.
Parameters
cbuf Curl buffer to uncompress.
Returns
Pointer to cbuf with the body replaced uncompressed.
Definition at line 295 of file curl.c.
References curlbuf::body, curlbuf::bsize, gzinflatebuf(), and is_gzip().
Referenced by curl_buf2xml().
{
     uint8_t *gzbuf;
     uint32_t len;
     if (is_gzip((uint8_t *)cbuf->body, cbuf->bsize) &&
             ((gzbuf = gzinflatebuf((uint8_t *)cbuf->body, cbuf->bsize, &len)))) {
         free(cbuf->body);
         cbuf->body = gzbuf;
         cbuf->bsize = len;
     }
     return cbuf;
 }
void curlclose (void)
Un reference CURL. This is required for each call to curlinit().
Definition at line 122 of file curl.c.
References objunref().
                      {
     objunref(curl_isinit);
     curl_isinit = NULL;
 }
int curlinit (void)
Initilise the CURL library.
Note
Curl functions will initilize and unreference curl when done it is best the application hold a reference to benifit from caching. curlclose() Must be called if it has been used
Definition at line 92 of file curl.c.
References objalloc(), objlock(), objref(), objunlock(), and objunref().
Referenced by url_escape(), and url_unescape().
                    {
     if (curl_isinit) {
         return objref(curl_isinit);
     }
     if (!(curl_isinit = objalloc(sizeof(void *),curlfree))) {
         return 0;
     }
     objlock(curl_isinit);
     if (!(curl = curl_easy_init())) {
         objunlock(curl_isinit);
         objunref(curl_isinit);
         return 0;
     }
     curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0);
     curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1);
     curl_easy_setopt(curl, CURLOPT_COOKIEFILE, "");
     curl_easy_setopt(curl, CURLOPT_USERAGENT, "libcurl-agent/1.0 [Distro Solutions]");
     curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, bodytobuffer);
     curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, headertobuffer);
     objunlock(curl_isinit);
     return 1;
 }
char* url_escape (char * url)
Escape and return the url.
Parameters
url URL to escape
Returns
A malloc()'d URL that needs to be free()'d
Definition at line 385 of file curl.c.
References curlinit(), objlock(), objunlock(), and objunref().
{
     char *esc;
     char *ret = NULL;
     if (!curlinit()) {
         return NULL;
     }
     objlock(curl_isinit);
     esc = curl_easy_escape(curl, url, 0);
     if (esc) {
         ret = strdup(esc);
     }
     curl_free(esc);
     objunlock(curl_isinit);
     objunref(curl_isinit);
     return ret;
 }
char* url_unescape (char * url)
UN escape and return the url.
Parameters
url URL to un escape
Returns
A malloc()'d URL that needs to be free()'d
Definition at line 407 of file curl.c.
References curlinit(), objlock(), objunlock(), and objunref().
{
     char *uesc;
     char *ret = NULL;
     if (!curlinit()) {
         return NULL;
     }
     objlock(curl_isinit);
     uesc = curl_easy_unescape(curl, url, 0, 0);
     if (uesc) {
         ret = strdup(uesc);
     }
     curl_free(uesc);
     objunlock(curl_isinit);
     objunref(curl_isinit);
     return ret;
 }