DTS Application Library: Network socket interface
Network socket interface
Distrotech Application Library
Allocate and initialise a socket for use as a client or server.
Modules
SSL socket support
TLSv1 SSLv2 SSLv3 DTLSv1 support.
Unix domain sockets
Support for unixdomain sockets using sockets interface.
Multicast sockets
Support for multicast sockets either IPv4 or IPv6.
Files
file socket.c
Allocate and initialise a socket for use as a client or server.
file sslutil.c
TLSv1 SSLv2 SSLv3 DTLSv1 support.
Data Structures
union sockstruct
Socket union describing all address types.
struct fwsocket
Socket data structure.
struct socket_handler
Socket handling thread data.
Typedefs
typedef void(* socketrecv)(struct fwsocket *, void *)
Callback function to register with a socket that will be called when there is data available.
Enumerations
enum sock_flags {
SOCK_FLAG_BIND = 1 << 0, SOCK_FLAG_CLOSE = 1 << 1, SOCK_FLAG_SSL = 1 << 2, SOCK_FLAG_UNIX = 1 << 3,
SOCK_FLAG_MCAST = 1 << 4
}
Socket flags controling a socket.
Functions
void close_socket (struct fwsocket *sock)
Mark the socket for closure and release the reference.
struct fwsocket * make_socket (int family, int type, int proto, void *ssl)
Allocate a socket structure and return reference.
struct fwsocket * accept_socket (struct fwsocket *sock)
Create and return a socket structure from accept()
struct fwsocket * sockconnect (int family, int stype, int proto, const char *ipaddr, const char *port, void *ssl)
Generic client socket.
struct fwsocket * udpconnect (const char *ipaddr, const char *port, void *ssl)
UDP Socket client.
struct fwsocket * tcpconnect (const char *ipaddr, const char *port, void *ssl)
TCP Socket client.
struct fwsocket * sockbind (int family, int stype, int proto, const char *ipaddr, const char *port, void *ssl, int backlog)
Generic server socket.
struct fwsocket * udpbind (const char *ipaddr, const char *port, void *ssl)
UDP server socket.
struct fwsocket * tcpbind (const char *ipaddr, const char *port, void *ssl, int backlog)
Generic server socket.
void socketserver (struct fwsocket *sock, socketrecv read, socketrecv acceptfunc, threadcleanup cleanup, void *data)
Create a server thread with a socket that has been created with sockbind udpbind or tcpbind.
void socketclient (struct fwsocket *sock, void *data, socketrecv read, threadcleanup cleanup)
Create a server thread with a socket that has been created with sockbind udpbind or tcpbind.
const char * sockaddr2ip (union sockstruct *addr, char *buff, int blen)
Return the ip address of a sockstruct addr.
int socketread_d (struct fwsocket *sock, void *buf, int num, union sockstruct *addr)
Read from a socket into a buffer.
int socketread (struct fwsocket *sock, void *buf, int num)
Read from a socket into a buffer.
int socketwrite_d (struct fwsocket *sock, const void *buf, int num, union sockstruct *addr)
Write a buffer to a socket.
int socketwrite (struct fwsocket *sock, const void *buf, int num)
Write a buffer to a socket.
Detailed Description
Allocate and initialise a socket for use as a client or server.
See Also
Socket Interface
Socket Example (Echo Server/Client)
Typedef Documentation
typedef void(* socketrecv)(struct fwsocket *, void *)
Callback function to register with a socket that will be called when there is data available.
Parameters
sock Socket structure data arrived on.
data Reference to data held by client/server thread.
Definition at line 259 of file dtsapp.h.
Enumeration Type Documentation
enum sock_flags
Socket flags controling a socket.
Enumerator
SOCK_FLAG_BIND
The socket has been bound and awaiting connections.
SOCK_FLAG_CLOSE
The socket is going away stop processing in its thread.
SOCK_FLAG_SSL
SSL has been requested on this socket dont allow clear read/send.
SOCK_FLAG_UNIX
UNIX Domain Socket.
SOCK_FLAG_MCAST
Multicast Socket.
Definition at line 102 of file dtsapp.h.
                 {
     SOCK_FLAG_BIND      = 1 << 0,
     SOCK_FLAG_CLOSE     = 1 << 1,
     SOCK_FLAG_SSL       = 1 << 2,
     SOCK_FLAG_UNIX      = 1 << 3,
     SOCK_FLAG_MCAST     = 1 << 4
 };
Function Documentation
struct fwsocket* accept_socket (struct fwsocket * sock)
Create and return a socket structure from accept()
Parameters
sock Reference to the socket its accepted on.
Returns
Reference to new socket.
Definition at line 144 of file socket.c.
References fwsocket::addr, objalloc(), objlock(), objunlock(), objunref(), fwsocket::proto, sockstruct::sa, fwsocket::sock, fwsocket::ssl, tlsaccept(), and fwsocket::type.
{
     struct fwsocket *si;
     socklen_t salen = sizeof(si->addr);
     if (!(si = objalloc(sizeof(*si),clean_fwsocket))) {
         return NULL;
     }
     objlock(sock);
     if ((si->sock = accept(sock->sock, &si->addr.sa, &salen)) < 0) {
         objunlock(sock);
         objunref(si);
         return NULL;
     }
     si->type = sock->type;
     si->proto = sock->proto;
     if (sock->ssl) {
         tlsaccept(si, sock->ssl);
     }
     objunlock(sock);
     return (si);
 }
void close_socket (struct fwsocket * sock)
Mark the socket for closure and release the reference.
Parameters
sock Socket to close.
Definition at line 79 of file socket.c.
References objunref(), setflag, and SOCK_FLAG_CLOSE.
Referenced by socktest(), and unixsocktest().
{
     if (sock) {
         setflag(sock, SOCK_FLAG_CLOSE);
         objunref(sock);
     }
 }
struct fwsocket* make_socket (int family, int type, int proto, void * ssl)
Allocate a socket structure and return reference.
The socket FD is assined by a call to socket.
Warning
This function should not be called directly.
Parameters
family Protocol family.
type Socket type.
proto Protocol to be used.
ssl SSL structure to associate with the socket.
Returns
Reference to socket structure holding a FD.
Definition at line 120 of file socket.c.
References objalloc(), objunref(), fwsocket::proto, fwsocket::sock, fwsocket::ssl, and fwsocket::type.
Referenced by dtls_listenssl(), mcast_socket(), unixsocket_client(), and unixsocket_server().
{
     struct fwsocket *si;
     if (!(si = objalloc(sizeof(*si),clean_fwsocket))) {
         return NULL;
     }
     if ((si->sock = socket(family, type, proto)) < 0) {
         objunref(si);
         return NULL;
     };
     if (ssl) {
         si->ssl = ssl;
     }
     si->type = type;
     si->proto = proto;
     return (si);
 }
const char* sockaddr2ip (union sockstruct * addr, char * buff, int blen)
Return the ip address of a sockstruct addr.
Parameters
addr Socketstruct to return the address for.
buff Buffer the IP will be copied too.
blen Buffer length.
Returns
a pointer to buff.
Definition at line 504 of file socket.c.
References inet_ntop(), sockstruct::sa4, sockstruct::sa6, and sockstruct::ss.
{
     if (!buff) {
         return NULL;
     }
     switch (addr->ss.ss_family) {
         case PF_INET:
             inet_ntop(PF_INET, &addr->sa4.sin_addr, buff, blen);
             break;
         case PF_INET6:
             inet_ntop(PF_INET6, &addr->sa6.sin6_addr, buff, blen);
             break;
     }
     return buff;
 }
struct fwsocket* sockbind (int family, int stype, int proto, const char * ipaddr, const char * port, void * ssl, int backlog)
Generic server socket.
See Also
udpbind
tcpbind
Parameters
family Protocol family.
stype Socket type.
proto Socket protocol.
ipaddr Ipaddr to connect too.
port Port to connect too.
ssl SSL structure to associate with socket.
backlog Connection backlog passed to listen.
Returns
Reference to socket structure.
Definition at line 290 of file socket.c.
{
     return(_opensocket(family, stype, proto, ipaddr, port, ssl, 1, backlog));
 }
struct fwsocket* sockconnect (int family, int stype, int proto, const char * ipaddr, const char * port, void * ssl)
Generic client socket.
See Also
udpconnect
tcpconnect
Parameters
family Protocol family.
stype Socket type.
proto Socket protocol.
ipaddr Ipaddr to connect too.
port Port to connect too.
ssl SSL structure to associate with socket.
Returns
Reference to socket structure.
Definition at line 250 of file socket.c.
{
     return(_opensocket(family, stype, proto, ipaddr, port, ssl, 0, 0));
 }
void socketclient (struct fwsocket * sock, void * data, socketrecv read, threadcleanup cleanup)
Create a server thread with a socket that has been created with sockbind udpbind or tcpbind.
See Also
sockclient
threadcleanup
socketrecv
Parameters
sock Reference to a bound socket.
data to send to the callbacks in paramaters.
read Callback to handle data when ready to read.
cleanup Thread cleanup function for when the socket closes.
Definition at line 493 of file socket.c.
References startsslclient().
Referenced by socktest().
{
     startsslclient(sock);
     _start_socket_handler(sock, read, NULL, cleanup, data);
 }
int socketread (struct fwsocket * sock, void * buf, int num)
Read from a socket into a buffer.
There are 2 functions each for reading and writing data to a socket.
Connected (client) sockets (Including UDP [SOCK_DGRAM])
Use of socketwrite and socketread is acceptable.
UDP (SOCK_DGRAM) servers.
These require use of socketread_d and socketwrite_d the exception is DTLS connections that use there own routines and either works.
Parameters
sock Socket structure to read from.
buf Buffer to fill.
num Size of the buffer.
Returns
Number of bytes read or -1 on error 0 will indicate connection closed.
Definition at line 489 of file sslutil.c.
References socketread_d().
Referenced by client_func().
{
     return (socketread_d(sock, buf, num, NULL));
 }
int socketread_d (struct fwsocket * sock, void * buf, int num, union sockstruct * addr)
Read from a socket into a buffer.
There are 2 functions each for reading and writing data to a socket.
Connected (client) sockets (Including UDP [SOCK_DGRAM])
Use of socketwrite and socketread is acceptable.
UDP (SOCK_DGRAM) servers.
These require use of socketread_d and socketwrite_d the exception is DTLS connections that use there own routines and either works.
Parameters
sock Socket structure to read from.
buf Buffer to fill.
num Size of the buffer.
addr Addr structure to fill remote address in.
Returns
Number of bytes read or -1 on error 0 will indicate connection closed.
Definition at line 406 of file sslutil.c.
References fwsocket::flags, objlock(), objunlock(), objunref(), sockstruct::sa, fwsocket::sock, SOCK_FLAG_CLOSE, SOCK_FLAG_SSL, ssldata::ssl, fwsocket::ssl, testflag, and fwsocket::type.
Referenced by server_func(), and socketread().
{
     struct ssldata *ssl = sock->ssl;
     socklen_t salen = sizeof(*addr);
     int ret, err, syserr;
     if (!ssl && !testflag(sock, SOCK_FLAG_SSL)) {
         objlock(sock);
         if (addr && (sock->type == SOCK_DGRAM)) {
             ret = recvfrom(sock->sock, buf, num, 0, &addr->sa, &salen);
         } else {
 #ifndef __WIN32
             ret = read(sock->sock, buf, num);
 #else
             ret = recv(sock->sock, buf, num, 0);
 #endif
         }
         if (ret == 0) {
             sock->flags |= SOCK_FLAG_CLOSE;
         }
         objunlock(sock);
         return (ret);
     } else if (!ssl) {
         return -1;
     }
     objlock(ssl);
     /* ive been shutdown*/
     if (!ssl->ssl) {
         objunlock(ssl);
         return (-1);
     }
     ret = SSL_read(ssl->ssl, buf, num);
     err = SSL_get_error(ssl->ssl, ret);
     if (ret == 0) {
         sock->flags |= SOCK_FLAG_CLOSE;
     }
     objunlock(ssl);
     switch (err) {
         case SSL_ERROR_NONE:
             break;
         case SSL_ERROR_WANT_X509_LOOKUP:
             printf("Want X509\n");
             break;
         case SSL_ERROR_WANT_READ:
             printf("Read Want Read\n");
             break;
         case SSL_ERROR_WANT_WRITE:
             printf("Read Want write\n");
             break;
         case SSL_ERROR_ZERO_RETURN:
         case SSL_ERROR_SSL:
             objlock(sock);
             objunref(sock->ssl);
             sock->ssl = NULL;
             objunlock(sock);
             break;
         case SSL_ERROR_SYSCALL:
             syserr = ERR_get_error();
             if (syserr || (!syserr && (ret == -1))) {
                 printf("R syscall %i %i\n", syserr, ret);
             }
             break;
         default
                 :
             printf("other\n");
             break;
     }
     return (ret);
 }
void socketserver (struct fwsocket * sock, socketrecv read, socketrecv acceptfunc, threadcleanup cleanup, void * data)
Create a server thread with a socket that has been created with sockbind udpbind or tcpbind.
See Also
sockclient
threadcleanup
socketrecv
Parameters
sock Reference to a bound socket.
read Callback to handle data when ready to read.
acceptfunc Function to call on connection accept.
cleanup Thread cleanup function for when the socket closes.
data to send to the callbacks in paramaters.
Definition at line 463 of file socket.c.
References fwsocket::children, create_bucketlist(), dtsl_serveropts(), fwsocket::flags, objlock(), objunlock(), fwsocket::ssl, and fwsocket::type.
Referenced by socktest().
{
     objlock(sock);
     if (sock->flags & SOCK_FLAG_BIND) {
         if (sock->ssl || !(sock->type == SOCK_DGRAM)) {
             sock->children = create_bucketlist(6, hash_socket);
         }
         if (sock->ssl && (sock->type == SOCK_DGRAM)) {
             objunlock(sock);
             dtsl_serveropts(sock);
         } else {
             objunlock(sock);
         }
     } else {
         objunlock(sock);
     }
     _start_socket_handler(sock, read, acceptfunc, cleanup, data);
 }
int socketwrite (struct fwsocket * sock, const void * buf, int num)
Write a buffer to a socket.
There are 2 functions each for reading and writing data to a socket.
Connected (client) sockets (Including UDP [SOCK_DGRAM])
Use of socketwrite and socketread is acceptable.
UDP (SOCK_DGRAM) servers.
These require use of socketread_d and socketwrite_d the exception is DTLS connections that use there own routines and either works.
Parameters
sock Socket structure to send data too.
buf Buffer to send.
num Lengthe of the buffer.
Returns
Number of bytes written or -1 on error 0 will indicate some error in SSL.
Definition at line 629 of file sslutil.c.
References socketwrite_d().
Referenced by client_func(), and socktest().
{
     return (socketwrite_d(sock, buf, num, NULL));
 }
int socketwrite_d (struct fwsocket * sock, const void * buf, int num, union sockstruct * addr)
Write a buffer to a socket.
There are 2 functions each for reading and writing data to a socket.
Connected (client) sockets (Including UDP [SOCK_DGRAM])
Use of socketwrite and socketread is acceptable.
UDP (SOCK_DGRAM) servers.
These require use of socketread_d and socketwrite_d the exception is DTLS connections that use there own routines and either works.
Todo:
implement send/sendto in WIN32
Parameters
sock Socket structure to send data too.
buf Buffer to send.
num Lengthe of the buffer.
addr Addr structure to send the buffer too (SOCK_DGRAM) see notes.
Returns
Number of bytes written or -1 on error 0 will indicate some error in SSL.
Definition at line 508 of file sslutil.c.
References fwsocket::addr, fwsocket::flags, objlock(), objunlock(), objunref(), sockstruct::sa, setflag, fwsocket::sock, SOCK_FLAG_CLOSE, SOCK_FLAG_MCAST, SOCK_FLAG_SSL, SOCK_FLAG_UNIX, sockstruct::ss, ssldata::ssl, fwsocket::ssl, testflag, fwsocket::type, and sockstruct::un.
Referenced by server_func(), socketwrite(), and unixsocktest().
{
     struct ssldata *ssl = (sock) ? sock->ssl : NULL;
     int ret, err, syserr;
     if (!sock) {
         return (-1);
     }
     if (!ssl && !testflag(sock, SOCK_FLAG_SSL)) {
         objlock(sock);
         if (addr && (sock->type == SOCK_DGRAM)) {
 #ifndef __WIN32
             if (sock->flags & SOCK_FLAG_UNIX) {
                 ret = sendto(sock->sock, buf, num, MSG_NOSIGNAL, (const struct sockaddr *)&addr->un, sizeof(addr->un));
             } else if (sock->flags & SOCK_FLAG_MCAST) {
                 ret = sendto(sock->sock, buf, num, MSG_NOSIGNAL, &sock->addr.sa, sizeof(sock->addr.ss));
             } else {
                 ret = sendto(sock->sock, buf, num, MSG_NOSIGNAL, &addr->sa, sizeof(*addr));
             }
 #else
             if (sock->flags & SOCK_FLAG_MCAST) {
                 ret = sendto(sock->sock, buf, num, 0, &sock->addr.sa, sizeof(sock->addr.ss));
             } else {
                 ret = sendto(sock->sock, buf, num, 0, &addr->sa, sizeof(*addr));
             }
 #endif
         } else {
 #ifndef __WIN32
             if (sock->flags & SOCK_FLAG_MCAST) {
                 ret = sendto(sock->sock, buf, num, MSG_NOSIGNAL, &sock->addr.sa, sizeof(sock->addr.ss));
             } else {
                 ret = send(sock->sock, buf, num, MSG_NOSIGNAL);
             }
 #else
             if (sock->flags & SOCK_FLAG_MCAST) {
                 ret = sendto(sock->sock, buf, num, 0, &sock->addr.sa, sizeof(sock->addr.ss));
             } else {
                 ret = send(sock->sock, buf, num, 0);
             }
 #endif
         }
         if (ret == -1) {
             switch(errno) {
                 case EBADF:
                 case EPIPE:
 #ifndef __WIN32
                 case ENOTCONN:
                 case ENOTSOCK:
 #endif
                     sock->flags |= SOCK_FLAG_CLOSE;
                     break;
             }
         }
         objunlock(sock);
         return (ret);
     } else if (!ssl) {
         return -1;
     }
     if (ssl && ssl->ssl) {
         objlock(ssl);
         if (SSL_state(ssl->ssl) != SSL_ST_OK) {
             objunlock(ssl);
             return (SSL_ERROR_SSL);
         }
         ret = SSL_write(ssl->ssl, buf, num);
         err = SSL_get_error(ssl->ssl, ret);
         objunlock(ssl);
     } else {
         return -1;
     }
     if (ret == -1) {
         setflag(sock, SOCK_FLAG_CLOSE);
     }
     switch(err) {
         case SSL_ERROR_NONE:
             break;
         case SSL_ERROR_WANT_READ:
             printf("Send Want Read\n");
             break;
         case SSL_ERROR_WANT_WRITE:
             printf("Send Want write\n");
             break;
         case SSL_ERROR_WANT_X509_LOOKUP:
             printf("Want X509\n");
             break;
         case SSL_ERROR_ZERO_RETURN:
         case SSL_ERROR_SSL:
             objlock(sock);
             objunref(sock->ssl);
             sock->ssl = NULL;
             objunlock(sock);
             break;
         case SSL_ERROR_SYSCALL:
             syserr = ERR_get_error();
             if (syserr || (!syserr && (ret == -1))) {
                 printf("W syscall %i %i\n", syserr, ret);
             }
             break;
         default:
             printf("other\n");
             break;
     }
     return (ret);
 }
struct fwsocket* tcpbind (const char * ipaddr, const char * port, void * ssl, int backlog)
Generic server socket.
See Also
udpbind
sockbind
Parameters
ipaddr Ipaddr to connect too.
port Port to connect too.
ssl SSL structure to associate with socket.
backlog Connection backlog passed to listen.
Returns
Reference to socket structure.
Definition at line 315 of file socket.c.
Referenced by socktest().
{
     return (_opensocket(PF_UNSPEC, SOCK_STREAM, IPPROTO_TCP, ipaddr, port, ssl, 1, backlog));
 }
struct fwsocket* tcpconnect (const char * ipaddr, const char * port, void * ssl)
TCP Socket client.
See Also
sockconnect
udpconnect
Parameters
ipaddr Ipaddr to connect too.
port Port to connect too.
ssl SSL structure to associate with socket.
Returns
Reference to socket structure.
Definition at line 274 of file socket.c.
Referenced by socktest().
{
     return (_opensocket(PF_UNSPEC, SOCK_STREAM, IPPROTO_TCP, ipaddr, port, ssl, 0, 0));
 }
struct fwsocket* udpbind (const char * ipaddr, const char * port, void * ssl)
UDP server socket.
See Also
sockbind
tcpbind
Parameters
ipaddr Ipaddr to connect too.
port Port to connect too.
ssl SSL structure to associate with socket.
Returns
Reference to socket structure.
Definition at line 302 of file socket.c.
Referenced by socktest().
{
     return (_opensocket(PF_UNSPEC, SOCK_DGRAM, IPPROTO_UDP, ipaddr, port, ssl, 1, 0));
 }
struct fwsocket* udpconnect (const char * ipaddr, const char * port, void * ssl)
UDP Socket client.
See Also
sockconnect
tcpconnect
Parameters
ipaddr Ipaddr to connect too.
port Port to connect too.
ssl SSL structure to associate with socket.
Returns
Reference to socket structure.
Definition at line 262 of file socket.c.
Referenced by socktest().
{
     return (_opensocket(PF_UNSPEC, SOCK_DGRAM, IPPROTO_UDP, ipaddr, port, ssl, 0, 0));
 }