DTS Application Library: Multicast sockets
Multicast sockets
Network socket interface
Support for multicast sockets either IPv4 or IPv6.
Functions
void mcast6_ip (struct in6_addr *addr)
Randomally assign a SSM Multicast address.param addr Ip address structure to fill out.
void mcast4_ip (struct in_addr *addr)
Randomally assign a SSM Multicast address.
struct fwsocket * mcast_socket (const char *iface, int family, const char *mcastip, const char *port, int flags)
Create a multicast socket.
Detailed Description
Support for multicast sockets either IPv4 or IPv6.
Function Documentation
void mcast4_ip (struct in_addr * addr)
Randomally assign a SSM Multicast address.
Parameters
addr Ip address structure to fill out.
Definition at line 504 of file iputil.c.
References genrand().
Referenced by mcast_socket().
{
     uint32_t mip, rand;
     do {
         rand = genrand(&mip, 3);
         mip >>= 8;
     } while (!rand || !(mip >> 8));
     mip |= 232 << 24;
     addr->s_addr = htonl(mip);
 }
void mcast6_ip (struct in6_addr * addr)
Randomally assign a SSM Multicast address.param addr Ip address structure to fill out.
Definition at line 480 of file iputil.c.
References genrand().
Referenced by mcast_socket().
{
     int mip, rand;
     uint32_t *i;
 #ifndef __WIN32
     i = (uint32_t*)&addr->s6_addr32;
 #else
     i = (uint32_t*)&addr->u.Word;
 #endif
     i[0] = htonl(0xFF350000);
     i[1] = 0;
     i[2] = 0;
     i[3] = 1 << 31;
     do {
         rand = genrand(&mip, 4);
     } while (!rand);
     i[3] = htonl(i[3] | mip);
 }
struct fwsocket* mcast_socket (const char * iface, int family, const char * mcastip, const char * port, int flags)
Create a multicast socket.
A multicast socket is both a client and server due to the nature of multicasting writing to a multicast socket should only be done with socketwrite not socketwrite_d the socket is created on a interface and the initial address can be set.
Todo:
Win32 support for inet_ntop/inet_pton
Parameters
iface Interface to send and recieve multicast traffic.
family IP address family PF_INET or PF_INET6.
mcastip Multicast ip to use must be in "family".
port Port to use.
flags Multicast flags currently disables LOOP.
Returns
Reference to multicast ocket structure.
Definition at line 536 of file socket.c.
References fwsocket::addr, fwsocket::flags, get_iface_index(), get_ifinfo(), get_ifipaddr(), ifinfo::idx, inet_lookup(), ifinfo::ipv4addr, ifinfo::ipv6addr, make_socket(), mcast4_ip(), mcast6_ip(), objref(), objunref(), sockstruct::sa, seedrand(), fwsocket::sock, and SOCK_FLAG_MCAST.
{
     struct fwsocket *fws;
     struct  addrinfo hint, *result, *rp;
     struct in_addr *srcif;
     const char *srcip;
     int ifidx;
     int on = 1;
     int off = 0;
     int ttl = 50;
     socklen_t slen = sizeof(union sockstruct);
 #ifdef __WIN32
     struct ifinfo *ifinf;
 #endif
         memset(&hint, 0, sizeof(hint));
     hint.ai_family = PF_UNSPEC;
     hint.ai_socktype = SOCK_DGRAM;
     hint.ai_protocol = IPPROTO_UDP;
 #ifndef __WIN32
     if (!(srcip = get_ifipaddr(iface, family))) {
                 return NULL;
     }
         if (getaddrinfo(srcip, port, &hint, &result) || !result) {
         free((void*)srcip);
                 return NULL;
         }
     free((void*)srcip);
 #else
     if (!(ifinf = get_ifinfo(iface))) {
         return NULL;
     }
     ifidx = ifinf->idx;
     srcip = (family == AF_INET) ? ifinf->ipv4addr : ifinf->ipv6addr;
         if (!srcip || (getaddrinfo(srcip, port, &hint, &result) || !result)) {
         objunref(ifinf);
                 return NULL;
         }
     objunref(ifinf);
 #endif
     for(rp = result; rp; rp = result->ai_next) {
         if (!(fws = make_socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol, NULL))) {
             continue;
         }
         break;
     }
     if (!rp || !fws) {
         freeaddrinfo(result);
         return NULL;
     }
     if(setsockopt(fws->sock, SOL_SOCKET, SO_REUSEADDR, (char*)&on, sizeof(on))) {
         objunref(fws);
         freeaddrinfo(result);
         return NULL;
     }
     if (rp->ai_family == PF_INET) {
         struct in_addr mcastip4;
         struct ip_mreq mg;
         struct sockaddr_in *src_ip;
         src_ip = (struct sockaddr_in*)rp->ai_addr;
         if (setsockopt(fws->sock, IPPROTO_IP, IP_MULTICAST_TTL, (char*)&ttl, sizeof(ttl))) {
             objunref(fws);
             freeaddrinfo(result);
             return NULL;
         }
         if (flags && setsockopt(fws->sock, IPPROTO_IP, IP_MULTICAST_LOOP, (char*)&off, sizeof(off))) {
             freeaddrinfo(result);
             objunref(fws);
             return NULL;
         }
         if (mcastip) {
             inet_lookup(PF_INET, mcastip, &mcastip4, sizeof(mcastip4));
         } else {
             seedrand();
             mcast4_ip(&mcastip4);
         }
         mg.imr_multiaddr = mcastip4;
         mg.imr_interface.s_addr = src_ip->sin_addr.s_addr;
         if (setsockopt(fws->sock, IPPROTO_IP, IP_ADD_MEMBERSHIP, (char*)&mg, sizeof(mg))) {
             objunref(fws);
             freeaddrinfo(rp);
             return NULL;
         }
         memset(&srcif, 0, sizeof(srcif));
         srcif = &src_ip->sin_addr;
         if(setsockopt(fws->sock, IPPROTO_IP, IP_MULTICAST_IF, (char*)srcif, sizeof(*srcif))) {
             freeaddrinfo(rp);
             objunref(fws);
             return NULL;
         }
         src_ip->sin_addr.s_addr = mcastip4.s_addr;
     } else if (rp->ai_family == PF_INET6) {
         struct in6_addr mcastip6;
         struct ipv6_mreq mg;
         struct sockaddr_in6 *src_ip;
 #ifndef __WIN32
         ifidx = get_iface_index(iface);
 #endif
         src_ip = (struct sockaddr_in6*)rp->ai_addr;
         if (setsockopt(fws->sock, IPPROTO_IPV6, IPV6_MULTICAST_HOPS, (char*)&ttl, sizeof(ttl))) {
             objunref(fws);
             freeaddrinfo(result);
             return NULL;
         }
         if (flags && setsockopt(fws->sock, IPPROTO_IPV6, IPV6_MULTICAST_LOOP, (char*)&off, sizeof(off))) {
             freeaddrinfo(result);
             objunref(fws);
             return NULL;
         }
         if (mcastip) {
             inet_lookup(PF_INET6, mcastip, &mcastip6, sizeof(mcastip6));
         } else {
             seedrand();
             mcast6_ip(&mcastip6);
         }
         mg.ipv6mr_multiaddr = mcastip6;
         mg.ipv6mr_interface = ifidx;
         if (setsockopt(fws->sock, IPPROTO_IPV6, IPV6_JOIN_GROUP, (char*)&mg, sizeof(mg))) {
             objunref(fws);
             freeaddrinfo(rp);
             return NULL;
         }
         if (setsockopt(fws->sock, IPPROTO_IPV6, IPV6_MULTICAST_IF, (char*)&ifidx, sizeof(ifidx))) {
             objref(fws);
             freeaddrinfo(rp);
             return NULL;
         }
         src_ip->sin6_addr = mcastip6;
     }
     if (bind(fws->sock, (struct sockaddr*)rp->ai_addr, sizeof(struct sockaddr_storage))) {
         freeaddrinfo(result);
         objunref(fws);
         return NULL;
     }
     getsockname(fws->sock, &fws->addr.sa, &slen);
     freeaddrinfo(result);
     fws->flags |= SOCK_FLAG_MCAST;
     return fws;
 }