DTS Application Library: Micelaneous utilities.
Micelaneous utilities.
Distrotech Application Library
Utilities commonly used.
Modules
Hashing and digest functions
MD5/SHA1/SHA2(256/512) Hashing checking and HMAC Functions.
Files
file util.c
Utilities commonly used.
Functions
void seedrand (void)
Seed openssl random number generator.
int genrand (void *buf, int len)
Generate random sequence.
int strlenzero (const char *str)
Check if a string is zero length.
char * ltrim (char *str)
Trim white space at the begining of a string.
char * rtrim (const char *str)
Trim white space at the end of a string.
char * trim (const char *str)
Trim whitesapce from the beggining and end of a string.
uint64_t tvtontp64 (struct timeval *tv)
Convert a timeval struct to 64bit NTP time.
uint16_t checksum (const void *data, int len)
Obtain the checksum for a buffer.
uint16_t checksum_add (const uint16_t checksum, const void *data, int len)
Obtain the checksum for a buffer adding a checksum.
uint16_t verifysum (const void *data, int len, const uint16_t check)
Verify a checksum.
void touch (const char *filename, uid_t user, gid_t group)
Create a file and set user and group.
char * b64enc_buf (const char *message, uint32_t len, int nonl)
Base 64 encode a buffer.
char * b64enc (const char *message, int nonl)
Base 64 encode a string.
Detailed Description
Utilities commonly used.
Function Documentation
char* b64enc (const char * message, int nonl)
Base 64 encode a string.
Parameters
message String to encode.
nonl Encode the data all on one line if non zero.
Returns
Reference to base64 encoded string.
Definition at line 539 of file util.c.
References b64enc_buf().
{
    return b64enc_buf(message, strlen(message), nonl);
}
char* b64enc_buf (const char * message, uint32_t len, int nonl)
Base 64 encode a buffer.
Parameters
message Buffer to encode.
len Length of the buffer.
nonl Encode the data all on one line if non zero.
Returns
Reference to base64 encoded string.
Definition at line 506 of file util.c.
References objalloc().
Referenced by b64enc().
{
    BIO *bmem, *b64;
    BUF_MEM *ptr;
    char *buffer;
    double encodedSize;
    encodedSize = 1.36*len;
    buffer = objalloc(encodedSize+1, NULL);
    b64 = BIO_new(BIO_f_base64());
    bmem = BIO_new(BIO_s_mem());
    b64 = BIO_push(b64, bmem);
    if (nonl) {
        BIO_set_flags(b64, BIO_FLAGS_BASE64_NO_NL);
    }
    BIO_write(b64, message, len);
    BIO_flush(b64);
    BIO_get_mem_ptr(b64, &ptr);
    buffer = objalloc(ptr->length+1, NULL);
    memcpy(buffer, ptr->data, ptr->length);
    BIO_free_all(b64);
    return buffer;
}
uint16_t checksum (const void * data, int len)
Obtain the checksum for a buffer.
Parameters
data Buffer to create checksum of.
len Buffer length.
Returns
Chechsum of data.
Definition at line 452 of file util.c.
Referenced by ipv4checksum(), ipv4icmpchecksum(), ipv4tcpchecksum(), ipv4udpchecksum(), and rfc6296_map_add().
{
    return (_checksum(data, len, 0));
}
uint16_t checksum_add (const uint16_t checksum, const void * data, int len)
Obtain the checksum for a buffer adding a checksum.
Parameters
checksum Checksum to add to generated checksum.
data Buffer to create checksum of.
len Buffer length.
Returns
Chechsum of data.
Definition at line 463 of file util.c.
Referenced by ipv4tcpchecksum(), and ipv4udpchecksum().
{
    return (_checksum(data, len, ~checksum));
}
int genrand (void * buf, int len)
Generate random sequence.
Parameters
buf Buffer to write random data.
len Length to write.
Returns
1 on success 0 otherwise.
Definition at line 82 of file util.c.
Referenced by mcast4_ip(), mcast6_ip(), new_radpacket(), randhwaddr(), and sslstartup().
{
    return (RAND_bytes(buf, len));
}
char* ltrim (char * str)
Trim white space at the begining of a string.
Parameters
str String to trim.
Returns
Pointer to trimed string.
Definition at line 353 of file util.c.
References strlenzero().
Referenced by trim().
{
    char *cur = str;
    if (strlenzero(str)) {
        return (str);
    }
    while(isspace(cur[0])) {
        cur++;
    }
    return (cur);
}
char* rtrim (const char * str)
Trim white space at the end of a string.
Parameters
str String to trim.
Returns
Pointer to trimed string.
Definition at line 372 of file util.c.
References strlenzero().
Referenced by trim().
{
    int len;
    char *cur = (char *)str;
    if (strlenzero(str)) {
        return (cur);
    }
    len = strlen(str) - 1;
    while(len && isspace(cur[len])) {
        cur[len] = '\0';
        len--;
    }
    return (cur);
}
void seedrand (void)
Seed openssl random number generator.
This should be run at application startup
Todo:
This wont work on WIN32
Definition at line 68 of file util.c.
Referenced by framework_init(), and mcast_socket().
{
    int fd = open("/dev/random", O_RDONLY);
    int len;
    char    buf[64];
    len = read(fd, buf, 64);
    RAND_seed(buf, len);
}
int strlenzero (const char * str)
Check if a string is zero length.
strlen can not be used on a NULL string this is a quick and dirty util to check it.
Parameters
str String to check.
Returns
1 if the string is null or zero length
Definition at line 341 of file util.c.
Referenced by create_kernmac(), create_kernvlan(), get_category_next(), get_ifinfo(), get_ifipaddr(), ifhwaddr(), ltrim(), process_config(), rtrim(), and unixsocket_client().
{
    if (str && strlen(str)) {
        return (0);
    }
    return (1);
}
void touch (const char * filename, uid_t user, gid_t group)
Create a file and set user and group.
Todo:
WIN32 does not use uid/gid and move to file utils module.
Parameters
filename File to create.
user User ID to set ownership.
group Group ID to set ownership.
Definition at line 484 of file util.c.
References touch().
Referenced by touch(), and xslt_apply().
{
    int res;
#else
extern void touch(const char *filename) {
#endif
    int fd;
    fd = creat(filename, 0600);
    close(fd);
#ifndef __WIN32__
    res = chown(filename, user, group);
    res++;
#endif
    return;
}
char* trim (const char * str)
Trim whitesapce from the beggining and end of a string.
Parameters
str String to trim.
Returns
Trimed string.
Definition at line 393 of file util.c.
References ltrim(), and rtrim().
Referenced by process_config().
{
    char *cur = (char *)str;
    cur = ltrim(cur);
    cur = rtrim(cur);
    return (cur);
}
uint64_t tvtontp64 (struct timeval * tv)
Convert a timeval struct to 64bit NTP time.
Parameters
tv Timeval struct to convert.
Returns
64 bit NTP time value.
Definition at line 405 of file util.c.
Referenced by get_ip6_addrprefix().
{
    return ((((uint64_t)tv->tv_sec + 2208988800u) << 32) + ((uint32_t)tv->tv_usec * 4294.967296));
}
uint16_t verifysum (const void * data, int len, const uint16_t check)
Verify a checksum.
Parameters
data Data to generate checksum.
len Length of data.
check Checksum to check against.
Returns
0 when checksum is verified.
Definition at line 473 of file util.c.
{
    return (_checksum(data, len, check));
}