DTS Application Library: Linux network interface functions
Linux network interface functions
Distrotech Application Library
Implement various interface routines from libnetlink.
Files
file interface.c
Wrapper arround Linux libnetlink for managing network interfaces.
Data Structures
struct iplink_req
IP Netlink request.
struct ipaddr_req
IP Netlink IP addr request.
Enumerations
enum ipv4_score { IPV4_SCORE_ZEROCONF = 1 << 0, IPV4_SCORE_RESERVED = 1 << 1, IPV4_SCORE_ROUTABLE = 1 << 2 }
Order of precidence of ipv4.
enum ipv6_score { IPV6_SCORE_RESERVED = 1 << 0, IPV6_SCORE_SIXIN4 = 1 << 1, IPV6_SCORE_ROUTABLE = 1 << 2 }
Return best ipv6 address in order of FFC/7 2002/16 ...
Functions
void closenetlink ()
Close netlink socket on application termination.
int get_iface_index (const char *ifname)
Get the netlink interface for a named interface.
int delete_kernvlan (char *ifname, int vid)
Delete a VLAN.
int create_kernvlan (char *ifname, unsigned short vid)
Create a VLAN on a interface.
int delete_kernmac (char *ifname)
Delete Kernel MAC VLAN.
int create_kernmac (char *ifname, char *macdev, unsigned char *mac)
Create a kernal MAC VLAN.
int set_interface_flags (int ifindex, int set, int clear)
Alter interface flags.
int set_interface_addr (int ifindex, const unsigned char *hwaddr)
Set interface MAC addr.
int set_interface_name (int ifindex, const char *name)
Rename interface.
int interface_bind (char *iface, int protocol)
Bind to device fd may be a existing socket.
void randhwaddr (unsigned char *addr)
create random MAC address
int create_tun (const char *ifname, const unsigned char *hwaddr, int flags)
Create a tunnel device.
int ifdown (const char *ifname, int flags)
Set interface down.
int ifup (const char *ifname, int flags)
Set interface up.
int ifrename (const char *oldname, const char *newname)
Rename interface helper.
int ifhwaddr (const char *ifname, unsigned char *hwaddr)
Get MAC addr for interface.
int set_interface_ipaddr (char *ifname, char *ipaddr)
Set IP addr on interface.
const char * get_ifipaddr (const char *iface, int family)
Find best IP adress for a interface.
Detailed Description
Implement various interface routines from libnetlink.
Enumeration Type Documentation
enum ipv4_score
Order of precidence of ipv4.
Enumerator
IPV4_SCORE_ZEROCONF
Zeroconf IP's 169.254/16.
IPV4_SCORE_RESERVED
Reseverd "private" ip addresses.
IPV4_SCORE_ROUTABLE
Routable IP's.
Definition at line 63 of file interface.c.
                 {
     IPV4_SCORE_ZEROCONF = 1 << 0,
     IPV4_SCORE_RESERVED = 1 << 1,
     IPV4_SCORE_ROUTABLE = 1 << 2
 };
enum ipv6_score
Return best ipv6 address in order of FFC/7 2002/16 ...
Enumerator
IPV6_SCORE_RESERVED
Adminstrivly allocated addresses (FC/7)
IPV6_SCORE_SIXIN4
6in4 address space
IPV6_SCORE_ROUTABLE
Other routable addresses.
Definition at line 73 of file interface.c.
                 {
     IPV6_SCORE_RESERVED = 1 << 0,
     IPV6_SCORE_SIXIN4 = 1 << 1,
     IPV6_SCORE_ROUTABLE = 1 << 2
 };
Function Documentation
void closenetlink (void)
Close netlink socket on application termination.
Definition at line 130 of file interface.c.
References objunref().
{
     if (nlh) {
         objunref(nlh);
     }
 }
int create_kernmac (char * ifname, char * macdev, unsigned char * mac)
Create a kernal MAC VLAN.
Parameters
ifname Interface name to create
macdev Base interface
mac MAC address to use or random if NULL.
Returns
-1 on error.
Definition at line 282 of file interface.c.
References get_iface_index(), iplink_req::n, objalloc(), objlock(), objref(), objunlock(), objunref(), randhwaddr(), and strlenzero().
{
     struct iplink_req *req;
     struct rtattr *data, *linkinfo;
     unsigned char lmac[ETH_ALEN];
     char *type = "macvlan";
     int ifindex, ret;
     if (strlenzero(ifname) || (strlen(ifname) > IFNAMSIZ) ||
             strlenzero(macdev) || (strlen(macdev) > IFNAMSIZ) ||
             (!objref(nlh) && !(nlh = nlhandle(0)))) {
         return (-1);
     }
     /*set the index of base interface*/
     if (!(ifindex = get_iface_index(ifname))) {
         objunref(nlh);
         return (-1);
     }
     if (!mac) {
         randhwaddr(lmac);
     } else {
         strncpy((char *)lmac, (char *)mac, ETH_ALEN);
     }
     if (!(req = objalloc(sizeof(*req), NULL))) {
         objunref(nlh);
         return (-1);
     }
     req->n.nlmsg_len = NLMSG_LENGTH(sizeof(struct ifinfomsg));
     req->n.nlmsg_type = RTM_NEWLINK;
     req->n.nlmsg_flags = NLM_F_CREATE | NLM_F_EXCL | NLM_F_REQUEST;
     /*config base/dev/mac*/
     addattr_l(&req->n, sizeof(*req), IFLA_LINK, &ifindex, 4);
     addattr_l(&req->n, sizeof(*req), IFLA_IFNAME, macdev, strlen(macdev));
     addattr_l(&req->n, sizeof(*req), IFLA_ADDRESS, lmac, ETH_ALEN);
     /*type*/
     linkinfo  = NLMSG_TAIL(&req->n);
     addattr_l(&req->n, sizeof(*req), IFLA_LINKINFO, NULL, 0);
     addattr_l(&req->n, sizeof(*req), IFLA_INFO_KIND, type, strlen(type));
     /*mode*/
     data = NLMSG_TAIL(&req->n);
     addattr_l(&req->n, sizeof(*req), IFLA_INFO_DATA, NULL, 0);
     addattr32(&req->n, sizeof(*req), IFLA_MACVLAN_MODE, MACVLAN_MODE_PRIVATE);
     data->rta_len = (char *)NLMSG_TAIL(&req->n) - (char *)data;
     linkinfo->rta_len = (char *)NLMSG_TAIL(&req->n) - (char *)linkinfo;
     objlock(nlh);
     ret = rtnl_talk(nlh, &req->n, 0, 0, NULL);
     objunlock(nlh);
     objunref(nlh);
     objunref(req);
     return (ret);
 }
int create_kernvlan (char * ifname, unsigned short vid)
Create a VLAN on a interface.
Parameters
ifname Interface to add VLAN to.
vid VLAN id to add.
Returns
-1 on error.
Definition at line 214 of file interface.c.
References get_iface_index(), iplink_req::n, objalloc(), objlock(), objref(), objunlock(), objunref(), and strlenzero().
{
     struct iplink_req *req;
     char iface[IFNAMSIZ+1];
     struct rtattr *data, *linkinfo;
     char *type = "vlan";
     int ifindex, ret;
     if (strlenzero(ifname) || (strlen(ifname) > IFNAMSIZ) ||
             (!objref(nlh) && !(nlh = nlhandle(0)))) {
         return (-1);
     }
     /*set the index of base interface*/
     if (!(ifindex = get_iface_index(ifname))) {
         objunref(nlh);
         return (-1);
     }
     if (!(req = objalloc(sizeof(*req), NULL))) {
         objunref(nlh);
         return (-1);
     }
     snprintf(iface, IFNAMSIZ, "%s.%i", ifname, vid);
     req->n.nlmsg_len = NLMSG_LENGTH(sizeof(struct ifinfomsg));
     req->n.nlmsg_type = RTM_NEWLINK;
     req->n.nlmsg_flags = NLM_F_CREATE | NLM_F_EXCL | NLM_F_REQUEST;
     /*config base/dev/mac*/
     addattr_l(&req->n, sizeof(*req), IFLA_LINK, &ifindex, sizeof(ifindex));
     addattr_l(&req->n, sizeof(*req), IFLA_IFNAME, iface, strlen(iface));
     /*type*/
     linkinfo  = NLMSG_TAIL(&req->n);
     addattr_l(&req->n, sizeof(*req), IFLA_LINKINFO, NULL, 0);
     addattr_l(&req->n, sizeof(*req), IFLA_INFO_KIND, type, strlen(type));
     /*vid*/
     data = NLMSG_TAIL(&req->n);
     addattr_l(&req->n, sizeof(*req), IFLA_INFO_DATA, NULL, 0);
     addattr_l(&req->n, sizeof(*req), IFLA_VLAN_ID, &vid, sizeof(vid));
     data->rta_len = (char *)NLMSG_TAIL(&req->n) - (char *)data;
     linkinfo->rta_len = (char *)NLMSG_TAIL(&req->n) - (char *)linkinfo;
     objlock(nlh);
     ret = rtnl_talk(nlh, &req->n, 0, 0, NULL);
     objunlock(nlh);
     objunref(nlh);
     objunref(req);
     return (ret);
 }
int create_tun (const char * ifname, const unsigned char * hwaddr, int flags)
Create a tunnel device.
Parameters
ifname Interface name to create..
hwaddr Hardware address to assign (optionally).
flags Flags to set device properties.
Returns
Tunnel FD or -1 on error.
Definition at line 496 of file interface.c.
References get_iface_index(), set_interface_addr(), and set_interface_flags().
{
     struct ifreq ifr;
     int fd, ifindex;
     char *tundev = "/dev/net/tun";
     /* open the tun/tap clone dev*/
     if ((fd = open(tundev, O_RDWR)) < 0) {
         return (-1);
     }
     /* configure the device*/
     memset(&ifr, 0, sizeof(ifr));
     ifr.ifr_flags = flags;
     strncpy(ifr.ifr_name, ifname, IFNAMSIZ);
     if (ioctl(fd, TUNSETIFF, (void *)&ifr) < 0 ) {
         perror("ioctl(TUNSETIFF) failed\n");
         close(fd);
         return (-1);
     }
     if (!(ifindex = get_iface_index(ifname))) {
         return (-1);
     }
     /* set the MAC address*/
     if (hwaddr) {
         set_interface_addr(ifindex, hwaddr);
     }
     /*set the network dev up*/
     set_interface_flags(ifindex, IFF_UP | IFF_RUNNING | IFF_MULTICAST | IFF_BROADCAST, 0);
     return (fd);
 }
int delete_kernmac (char * ifname)
Delete Kernel MAC VLAN.
Parameters
ifname Interface to delete.
Returns
-1 on error.
Definition at line 272 of file interface.c.
{
     return (delete_interface(ifname));
 }
int delete_kernvlan (char * ifname, int vid)
Delete a VLAN.
Parameters
ifname Interface we deleting vlan from.
vid VLAN id to delete.
Returns
-1 on error.
Definition at line 201 of file interface.c.
{
     char iface[IFNAMSIZ+1];
     /*check ifname grab a ref to nlh or open it*/
     snprintf(iface, IFNAMSIZ, "%s.%i", ifname, vid);
     return (delete_interface(iface));
 }
int get_iface_index (const char * ifname)
Get the netlink interface for a named interface.
Parameters
ifname Interface name.
Returns
Index of the interface.
Definition at line 139 of file interface.c.
References objlock(), objref(), objunlock(), and objunref().
Referenced by create_kernmac(), create_kernvlan(), create_tun(), ifdown(), ifhwaddr(), ifrename(), ifup(), interface_bind(), mcast_socket(), and set_interface_ipaddr().
{
     int ifindex;
     if (!objref(nlh) && !(nlh = nlhandle(0))) {
         return (0);
     }
     objlock(nlh);
     ll_init_map(nlh, 1);
     objunlock(nlh);
     ifindex = ll_name_to_index(ifname);
     objunref(nlh);
     return (ifindex);
 }
const char* get_ifipaddr (const char * iface, int family)
Find best IP adress for a interface.
Todo:
WIN32 Support
Parameters
iface Interface name.
family PF_INET or PF_INET6.
Returns
Best matching IP address for the interface.
Definition at line 783 of file interface.c.
References score_ipv4(), score_ipv6(), and strlenzero().
Referenced by mcast_socket().
{
     struct ifaddrs *ifaddr, *ifa;
     struct sockaddr_in *ipv4addr;
     int score = 0, nscore, iflen;
     uint32_t subnet = 0, match;
     char host[NI_MAXHOST] = "", tmp[NI_MAXHOST];
     if (!iface || getifaddrs(&ifaddr) == -1) {
         return NULL;
     }
     for (ifa = ifaddr; ifa != NULL; ifa = ifa->ifa_next) {
         iflen = strlen(iface);
         if ((ifa->ifa_addr == NULL) ||  strncmp(ifa->ifa_name, iface, iflen) || (ifa->ifa_addr->sa_family != family)) {
             continue;
         }
         /* Match aliases not vlans*/
         if ((strlen(ifa->ifa_name) > iflen) && (ifa->ifa_name[iflen] != ':')) {
             continue;
         }
         switch (ifa->ifa_addr->sa_family) {
             case AF_INET:
                 /* Find best ip address for a interface lowest priority is given to zeroconf then reserved ip's
                  * finally find hte ip with shortest subnet bits.*/
                 ipv4addr = (struct sockaddr_in*)ifa->ifa_netmask;
                 match = ntohl(~ipv4addr->sin_addr.s_addr);
                 nscore = score_ipv4((struct sockaddr_in*)ifa->ifa_addr, tmp, NI_MAXHOST);
                 /* match score and subnet*/
                 if  ((nscore > score) || ((nscore == score) && (match > subnet))) {
                     score = nscore;
                     subnet = match;
                     strncpy(host, tmp, NI_MAXHOST);
                 }
                 break;
             case AF_INET6:
                 nscore = score_ipv6((struct sockaddr_in6*)ifa->ifa_addr, tmp, NI_MAXHOST);
                 if (nscore > score) {
                     score = nscore;
                     strncpy(host, tmp, NI_MAXHOST);
                 }
                 break;
         }
     }
     freeifaddrs(ifaddr);
     return (strlenzero(host)) ? NULL : strdup(host);
 }
int ifdown (const char * ifname, int flags)
Set interface down.
Parameters
ifname Interface name.
flags Additional flags to clear.
Returns
-1 on error 0 on success.
Definition at line 535 of file interface.c.
References get_iface_index(), and set_interface_flags().
Referenced by ifrename().
{
     int ifindex;
     /*down the device*/
     if (!(ifindex = get_iface_index(ifname))) {
         return (-1);
     }
     /*set the network dev up*/
     set_interface_flags(ifindex, 0, IFF_UP | IFF_RUNNING | flags);
     return (0);
 }
int ifhwaddr (const char * ifname, unsigned char * hwaddr)
Get MAC addr for interface.
Parameters
ifname Interface name
hwaddr Buffer to place MAC in char[ETH_ALEN]
Returns
0 on success.
Definition at line 588 of file interface.c.
References get_iface_index(), objref(), objunref(), and strlenzero().
Referenced by get_ip6_addrprefix().
{
     int ifindex;
     if (!hwaddr || strlenzero(ifname) || (strlen(ifname) > IFNAMSIZ) ||
             (!objref(nlh) && !(nlh = nlhandle(0)))) {
         return (-1);
     }
     /*set the index of base interface*/
     if (!(ifindex = get_iface_index(ifname))) {
         objunref(nlh);
         return (-1);
     }
     ll_index_to_addr(ifindex, hwaddr, ETH_ALEN);
     objunref(nlh);
     return (0);
 }
int ifrename (const char * oldname, const char * newname)
Rename interface helper.
Parameters
oldname Original name.
newname New name.
Returns
0 on success.
Definition at line 571 of file interface.c.
References get_iface_index(), ifdown(), and set_interface_name().
{
     int ifindex;
     ifdown(oldname, 0);
     if (!(ifindex = get_iface_index(oldname))) {
         return (-1);
     }
     set_interface_name(ifindex, newname);
     return (0);
 }
int ifup (const char * ifname, int flags)
Set interface up.
Parameters
ifname Interface name.
flags Additional flags to set.
Returns
-1 on error 0 on success.
Definition at line 553 of file interface.c.
References get_iface_index(), and set_interface_flags().
{
     int ifindex;
     /*down the device*/
     if (!(ifindex = get_iface_index(ifname))) {
         return (-1);
     }
     /*set the network dev up*/
     set_interface_flags(ifindex, IFF_UP | IFF_RUNNING | flags, 0);
     return (0);
 }
int interface_bind (char * iface, int protocol)
Bind to device fd may be a existing socket.
Parameters
iface Interface to bind too.
protocol Protocol to use.
Returns
-1 on error.
Definition at line 453 of file interface.c.
References get_iface_index(), and set_interface_flags().
{
     struct sockaddr_ll sll;
     int proto = htons(protocol);
     int fd, ifindex;
     /*set the network dev up*/
     if (!(ifindex = get_iface_index(iface))) {
         return (-1);
     }
     set_interface_flags(ifindex, IFF_UP | IFF_RUNNING, 0);
     /* open network raw socket */
     if ((fd = socket(PF_PACKET, SOCK_RAW,  proto)) < 0) {
         return (-1);
     }
     /*bind to the interface*/
     memset(&sll, 0, sizeof(sll));
     sll.sll_family = PF_PACKET;
     sll.sll_protocol = proto;
     sll.sll_ifindex = ifindex;
     if (bind(fd, (struct sockaddr *)&sll, sizeof(sll)) < 0) {
         perror("bind failed");
         close(fd);
         return (-1);
     }
     return (fd);
 }
void randhwaddr (unsigned char * addr)
create random MAC address
Parameters
addr Buffer char[ETH_ALEN] filled with the new address.
Definition at line 485 of file interface.c.
References genrand().
Referenced by create_kernmac().
{
     genrand(addr, ETH_ALEN);
     addr [0] &= 0xfe;       /* clear multicast bit */
     addr [0] |= 0x02;       /* set local assignment bit (IEEE802) */
 }
int set_interface_addr (int ifindex, const unsigned char * hwaddr)
Set interface MAC addr.
Parameters
ifindex Interface index.
hwaddr MAC address to set.
Returns
-1 on error.
Definition at line 388 of file interface.c.
References iplink_req::i, iplink_req::n, objalloc(), objlock(), objref(), objunlock(), and objunref().
Referenced by create_tun().
{
     struct iplink_req *req;
     if ((!objref(nlh) && !(nlh = nlhandle(0)))) {
         return (-1);
     }
     if (!(req = objalloc(sizeof(*req), NULL))) {
         objunref(nlh);
         return (-1);
     }
     req->n.nlmsg_len = NLMSG_LENGTH(sizeof(struct ifinfomsg));
     req->n.nlmsg_type = RTM_NEWLINK;
     req->n.nlmsg_flags = NLM_F_REQUEST;
     req->i.ifi_index = ifindex;
     /*config base/dev/mac*/
     addattr_l(&req->n, sizeof(*req), IFLA_ADDRESS, hwaddr, ETH_ALEN);
     objlock(nlh);
     rtnl_talk(nlh, &req->n, 0, 0, NULL);
     objunlock(nlh);
     objunref(nlh);
     objunref(req);
     return (0);
 }
int set_interface_flags (int ifindex, int set, int clear)
Alter interface flags.
Parameters
ifindex Interface index.
set Flags to set.
clear Flags to clear.
Returns
-1 on error.
Definition at line 348 of file interface.c.
References iplink_req::i, iplink_req::n, objalloc(), objlock(), objref(), objunlock(), and objunref().
Referenced by create_tun(), ifdown(), ifup(), and interface_bind().
{
     struct iplink_req *req;
     int flags;
     if (!objref(nlh) && !(nlh = nlhandle(0))) {
         return (-1);
     }
     flags = ll_index_to_flags(ifindex);
     flags |= set;
     flags &= ~(clear);
     if (!(req = objalloc(sizeof(*req), NULL))) {
         objunref(nlh);
         return (-1);
     }
     req->n.nlmsg_len = NLMSG_LENGTH(sizeof(struct ifinfomsg));
     req->n.nlmsg_type = RTM_NEWLINK;
     req->n.nlmsg_flags = NLM_F_REQUEST;
     /*config base/dev/mac*/
     req->i.ifi_index = ifindex;
     req->i.ifi_flags = flags;
     req->i.ifi_change = set | clear;
     objlock(nlh);
     rtnl_talk(nlh, &req->n, 0, 0, NULL);
     objunlock(nlh);
     objunref(nlh);
     objunref(req);
     return (0);
 }
int set_interface_ipaddr (char * ifname, char * ipaddr)
Set IP addr on interface.
Parameters
ifname Interface to assign IP to
ipaddr IP Addr to assign.
Returns
-1 on error.
Definition at line 611 of file interface.c.
References get_iface_index(), ipaddr_req::i, ipaddr_req::n, objalloc(), objlock(), objref(), objunlock(), and objunref().
{
     struct ipaddr_req *req;
     inet_prefix lcl;
     int ifindex, bcast;
     if ((!objref(nlh) && !(nlh = nlhandle(0)))) {
         return (-1);
     }
     if (!(req = objalloc(sizeof(*req), NULL))) {
         objunref(nlh);
         return (-1);
     }
     /*set the index of base interface*/
     if (!(ifindex = get_iface_index(ifname))) {
         objunref(nlh);
         return (-1);
     }
     req->n.nlmsg_len = NLMSG_LENGTH(sizeof(struct ifaddrmsg));
     req->n.nlmsg_type = RTM_NEWADDR;
     req->n.nlmsg_flags = NLM_F_REQUEST | NLM_F_EXCL | NLM_F_CREATE;
     req->i.ifa_scope = RT_SCOPE_HOST;
     req->i.ifa_index = ifindex;
     get_prefix(&lcl, ipaddr, AF_UNSPEC);
     req->i.ifa_family = lcl.family;
     req->i.ifa_prefixlen = lcl.bitlen;
     addattr_l(&req->n, sizeof(*req), IFA_LOCAL, &lcl.data, lcl.bytelen);
     addattr_l(&req->n, sizeof(*req), IFA_ADDRESS, &lcl.data, lcl.bytelen);
     if (lcl.family == AF_INET) {
         bcast = htonl((1 << (32 - lcl.bitlen)) - 1);
         addattr32(&req->n, sizeof(*req), IFA_BROADCAST, lcl.data[0] | bcast);
     }
     objlock(nlh);
     rtnl_talk(nlh, &req->n, 0, 0, NULL);
     objunlock(nlh);
     objunref(nlh);
     objunref(req);
     return (0);
 }
int set_interface_name (int ifindex, const char * name)
Rename interface.
Parameters
ifindex Interface index.
name New interface name.
Returns
-1 on error.
Definition at line 421 of file interface.c.
References iplink_req::i, iplink_req::n, objalloc(), objlock(), objref(), objunlock(), and objunref().
Referenced by ifrename().
{
     struct iplink_req *req;
     if ((!objref(nlh) && !(nlh = nlhandle(0)))) {
         return (-1);
     }
     if (!(req = objalloc(sizeof(*req), NULL))) {
         objunref(nlh);
         return (-1);
     }
     req->n.nlmsg_len = NLMSG_LENGTH(sizeof(struct ifinfomsg));
     req->n.nlmsg_type = RTM_NEWLINK;
     req->n.nlmsg_flags = NLM_F_REQUEST;
     req->i.ifi_index = ifindex;
     addattr_l(&req->n, sizeof(*req), IFLA_IFNAME, name, strlen((char *)name));
     objlock(nlh);
     rtnl_talk(nlh, &req->n, 0, 0, NULL);
     objunlock(nlh);
     objunref(nlh);
     objunref(req);
     return (0);
 }