DTS Application Library: SHA1 Hashing and digest functions
SHA1 Hashing and digest functions
Hashing and digest functions
SHA1 Hashing checking and HMAC Functions.
Functions
void sha1sum2 (unsigned char *buff, const void *data, unsigned long len, const void *data2, unsigned long len2)
Calculate the SHA1 hash accross 2 data chunks.
void sha1sum (unsigned char *buff, const void *data, unsigned long len)
Calculate the SHA1 hash.
int sha1cmp (unsigned char *digest1, unsigned char *digest2)
Compare two SHA1 hashes.
void sha1hmac (unsigned char *buff, const void *data, unsigned long len, const void *key, unsigned long klen)
Hash Message Authentication Codes (HMAC) SHA1.
Detailed Description
SHA1 Hashing checking and HMAC Functions.
Function Documentation
int sha1cmp (unsigned char * digest1, unsigned char * digest2)
Compare two SHA1 hashes.
Parameters
digest1 Digest to compare.
digest2 Digest to compare.
Returns
0 on equality.
Definition at line 233 of file util.c.
{
    return (_digest_cmp(digest1, digest2, 20));
}
void sha1hmac (unsigned char * buff, const void * data, unsigned long len, const void * key, unsigned long klen)
Hash Message Authentication Codes (HMAC) SHA1.
Parameters
buff HMAC returned in this buffer (20 bytes).
data Data to sign.
len Length of data.
key Key to signwith.
klen Length of key.
Definition at line 302 of file util.c.
References sha1sum2().
{
    _hmac(buff, data, len, key, klen, sha1sum2, 20);
}
void sha1sum (unsigned char * buff, const void * data, unsigned long len)
Calculate the SHA1 hash.
Parameters
buff buffer to place the hash (20 bytes).
data First data chunk to calculate.
len Length of data.
Definition at line 173 of file util.c.
References sha1sum2().
{
    sha1sum2(buff, data, len, NULL, 0);
}
void sha1sum2 (unsigned char * buff, const void * data, unsigned long len, const void * data2, unsigned long len2)
Calculate the SHA1 hash accross 2 data chunks.
Parameters
buff buffer to place the hash (20 bytes).
data First data chunk to calculate.
len Length of data.
data2 Second data chunk to calculate.
len2 Length of data2.
Definition at line 156 of file util.c.
Referenced by get_ip6_addrprefix(), sha1hmac(), and sha1sum().
{
    SHA_CTX c;
    SHA_Init(&c);
    SHA_Update(&c, data, len);
    if (data2) {
        SHA_Update(&c, data2, len2);
    }
    SHA_Final(buff, &c);
}