DTS Application Library: Wizard Interface.
Wizard Interface.
Distrotech GUI Library C API
Multi panel pop up wizard user interface.
Functions
struct dtsgui_wizard * DTS_C_API::dtsgui_newwizard (struct dtsgui *dtsgui, const char *title)
Create a new wizard.
dtsgui_pane DTS_C_API::dtsgui_wizard_addpage (struct dtsgui_wizard *dtswiz, const char *title, void *userdata, struct xml_doc *xmldoc)
Create a panel and append it to the wizard.
int DTS_C_API::dtsgui_runwizard (struct dtsgui_wizard *dtswiz)
Run the wizard.
Detailed Description
Multi panel pop up wizard user interface.
Remarks
A wizard is a dialog box that allows for multiple panels to be dispalayed in sequence via Back/Next controls.
Note
It is important to process the panels on complition before un refrencing the wizard.
Todo:
Add a hashed list to the wizard class storing the panels to no longer need to keep a array of panels.
Function Documentation
struct dtsgui_wizard* DTS_C_API::dtsgui_newwizard (struct dtsgui * dtsgui, const char * title) read
Create a new wizard.
A wizard consists of multiple panels linked with back/next controls each panel will need to be procesed on completion.
See Also
dtsgui_wizard
Parameters
dtsgui Aplication data ptr.
title Title shown on title bar of wizard pop up.
Returns
New wizard that needs pages added too and run.
Definition at line 985 of file wrapper.cpp.
References dtsgui::GetFrame().
{
    return new dtsgui_wizard(dtsgui, dtsgui->GetFrame(), title);
}
int DTS_C_API::dtsgui_runwizard (struct dtsgui_wizard * dtswiz)
Run the wizard.
Pop up the wizard window and open first page on success its required that the panels information be processed. When the wizard is un refferenced the panels are deleted.
See Also
dtsgui_wizard::RunWizard()
Parameters
dtswiz Wizard too run.
Returns
non Zero on success.
Definition at line 1014 of file wrapper.cpp.
References dtsgui_wizard::RunWizard().
{
    return dtswiz->RunWizard();
}
dtsgui_pane DTS_C_API::dtsgui_wizard_addpage (struct dtsgui_wizard * dtswiz, const char * title, void * userdata, struct xml_doc * xmldoc)
Create a panel and append it to the wizard.
See Also
dtsgui_wizard::AddPage()
Parameters
dtswiz Wizard to add page too.
title Title of the new panel.
userdata Userdata to be referenced and stored on the panel.
xmldoc Optional XML Doc to be referenced and stored on the panel.
Returns
New panel that will need to be configured and processed after completion.
Definition at line 999 of file wrapper.cpp.
References dtsgui_wizard::AddPage().
{
    return dtswiz->AddPage(title, xmldoc, userdata);
}