DTS Application Library: Distrotech GUI Library C API
Distrotech GUI Library C API
Exported functions used for use in C code.
Modules
Menu bar interface.
Create and manage menus.
Display panel interface.
Create and manage display panels shown in the application display area.
User interface dialogs.
Common dialogs for user interaction Confirmation, File, Password.
Wizard Interface.
Multi panel pop up wizard user interface.
Progress dialog interface.
Popup dialog containing a progress bar and posible cancel button.
Files
file cxxapi.cpp
C++ Functions exported to C API.
file dtsgui.h
Main include file for the GUI Library.
file wrapper.cpp
Wrapper functions exported to C to allow interfacing with C++.
Namespaces
namespace DTS_C_API
Namespace containing exported functions used by C.
Macros
#define __DTS_C_API
Defining __DTS_C_API allows access to C API from inside a C++ file.
#define __DTS_C_API
Defining __DTS_C_API allows access to C API from inside a C++ file.
Functions
void DTS_C_API::dtsgui_config (dtsgui_configcb confcallback_cb, void *userdata, struct point *wsize, struct point *wpos, const char *title, const char *status)
Configure the GUI and create a application frame.
int DTS_C_API::dtsgui_run (int argc, char **argv)
Pass execution to the GUI and activate the frame.
void * DTS_C_API::dtsgui_userdata (struct dtsgui *dtsgui)
Obtain a reference for the application userdata.
void DTS_C_API::dtsgui_setwindow (struct dtsgui *dtsgui, dtsgui_pane p)
Set the displayed panel to pane provided.
void DTS_C_API::dtsgui_sendevent (struct dtsgui *dtsgui, int eid)
Emit a event handled by event callback's.
void DTS_C_API::dtsgui_setuptoolbar (struct dtsgui *dtsgui, dtsgui_toolbar_create cb, void *data)
Specify callback to run to create and activate the toolbar.
void DTS_C_API::dtsgui_set_toolbar (struct dtsgui *dtsgui, int show)
Disable or enable the toolbar.
void DTS_C_API::dtsgui_titleappend (struct dtsgui *dtsgui, const char *text)
Append text to the application frame title enclosed in square brackets.
Detailed Description
Exported functions used for use in C code.
Remarks
Use of this API is not recomended from inside C++ use the native API.
See Also
__DTS_C_API
DTS_C_API
Core API Interface Common to C and C++
wrapper.cpp
cxxapi.cpp
dtsgui.h
Macro Definition Documentation
#define __DTS_C_API
Defining __DTS_C_API allows access to C API from inside a C++ file.
dtsgui.h will only include the definitions for the C API using C++ if this is defined.
Definition at line 33 of file cxxapi.cpp.
#define __DTS_C_API
Defining __DTS_C_API allows access to C API from inside a C++ file.
dtsgui.h will only include the definitions for the C API using C++ if this is defined.
Definition at line 154 of file wrapper.cpp.
Function Documentation
void DTS_C_API::dtsgui_config (dtsgui_configcb confcallback_cb, void * userdata, struct point * wsize, struct point * wpos, const char * title, const char * status)
Configure the GUI and create a application frame.
This is the first process required the application is created and the callback is executed.
Application processing continues until dtsgui_run is executed at this point the call back is executed and proccessing will be passed to the GUI App.
The userdata is returned in the callback.
The Callback must return a non zero value to indicate success should the application fail returning 0 will close the application.
See Also
DTSApp
dtsgui_configcb
Parameters
confcallback_cb The callback function where processing will continue.
userdata a refrenced object passed back to the config callback.
wsize Minimum/Initial size of the application window.
wpos Application position [Top Left Corner] of application placed on screen.
title Title displayed on the application bar.
status Default text displayed on the status bar.
Returns
The fuction does not return.
Definition at line 207 of file wrapper.cpp.
Referenced by FRAMEWORK_MAIN().
{
    new DTSApp(confcallback_cb, userdata, wsize, wpos, title, status);
}
int DTS_C_API::dtsgui_run (int argc, char ** argv)
Pass execution to the GUI and activate the frame.
Pass application processing to the GUI after calling the configure callback.
See Also
dtsgui_config
DTSApp
Parameters
argc Number of paramaters contained in argv.
argv Array of paramaters to be passed.
Returns
Return value from callback function.
Definition at line 222 of file wrapper.cpp.
Referenced by FRAMEWORK_MAIN().
{
    return wxEntry(argc, argv);
}
void DTS_C_API::dtsgui_sendevent (struct dtsgui * dtsgui, int eid)
Emit a event handled by event callback's.
A event is emited and recived by all active handlers The ID can be determined as required.
See Also
DTSFrame::SendDTSEvent()
Parameters
dtsgui Application data ptr
eid Event ID to send
Definition at line 262 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::SendDTSEvent().
Referenced by open_config().
{
    DTSFrame *f =  dtsgui->GetFrame();
    f->SendDTSEvent(eid, NULL);
}
void DTS_C_API::dtsgui_set_toolbar (struct dtsgui * dtsgui, int show)
Disable or enable the toolbar.
See Also
dtsgui::ShowToolbar()
Parameters
dtsgui Application data ptr.
show Display the toolbar if non zero.
Definition at line 289 of file wrapper.cpp.
References dtsgui::ShowToolbar().
Referenced by open_config(), and save_config().
{
    dtsgui->ShowToolbar(show);
}
void DTS_C_API::dtsgui_setuptoolbar (struct dtsgui * dtsgui, dtsgui_toolbar_create cb, void * data)
Specify callback to run to create and activate the toolbar.
The toolbar has of yet not been wrapped into the C API Its recomended that a C++ object be linked that contains a derived class of wxToolbar.
See Also
DTSFrame::SetupToolbar
Warning
This needs to be done in the application configuration callback.
Parameters
dtsgui Application data ptr.
cb Toolbar create callback.
data Userdata to be passed to the toolbar
Definition at line 278 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::SetupToolbar().
Referenced by guiconfig_cb().
{
    DTSFrame *f = dtsgui->GetFrame();
    f->SetupToolbar(cb, data);
}
void DTS_C_API::dtsgui_setwindow (struct dtsgui * dtsgui, dtsgui_pane p)
Set the displayed panel to pane provided.
Switch the curent pane with the one provided this should not be done and rather use menu callbacks.
See Also
DTSFrame::SetWindow()
Parameters
dtsgui Application data ptr
p Panel to display
Definition at line 249 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::SetWindow().
{
    DTSFrame *f = dtsgui->GetFrame();
    f->SetWindow((DTSPanel*)p);
}
void DTS_C_API::dtsgui_titleappend (struct dtsgui * dtsgui, const char * text)
Append text to the application frame title enclosed in square brackets.
Update the main application title bar text.
See Also
dtsgui::AppendTitle()
Parameters
dtsgui Application Data ptr.
text Text to append
Definition at line 300 of file wrapper.cpp.
References dtsgui::AppendTitle().
Referenced by open_config(), and save_config().
{
    dtsgui->AppendTitle(text);
}
void* DTS_C_API::dtsgui_userdata (struct dtsgui * dtsgui)
Obtain a reference for the application userdata.
Note
This reference must be un refferenced.
See Also
dtsgui::GetUserData
Parameters
dtsgui Application data ptr.
Returns
Reference to application user data
Definition at line 235 of file wrapper.cpp.
References dtsgui::GetUserData().
Referenced by app_getxmldoc(), config_menu(), export_config(), file_menu(), newsys_wizard(), open_config(), save_config(), and view_config_conf().
{
    return dtsgui->GetUserData();
}