DTS Application Library: MD5 Hashing and digest functions
MD5 Hashing and digest functions
Hashing and digest functions
MD5 Hashing checking and HMAC Functions.
Functions
void md5sum2 (unsigned char *buff, const void *data, unsigned long len, const void *data2, unsigned long len2)
Calculate the MD5 hash accross 2 data chunks.
void md5sum (unsigned char *buff, const void *data, unsigned long len)
Calculate the MD5 hash.
int md5cmp (unsigned char *digest1, unsigned char *digest2)
Compare two md5 hashes.
void md5hmac (unsigned char *buff, const void *data, unsigned long len, const void *key, unsigned long klen)
Hash Message Authentication Codes (HMAC) MD5.
Detailed Description
MD5 Hashing checking and HMAC Functions.
Function Documentation
int md5cmp (unsigned char * digest1, unsigned char * digest2)
Compare two md5 hashes.
Parameters
digest1 Digest to compare.
digest2 Digest to compare.
Returns
0 on equality.
Definition at line 223 of file util.c.
{
     return (_digest_cmp(digest1, digest2, 16));
 }
void md5hmac (unsigned char * buff, const void * data, unsigned long len, const void * key, unsigned long klen)
Hash Message Authentication Codes (HMAC) MD5.
Parameters
buff HMAC returned in this buffer (16 bytes).
data Data to sign.
len Length of data.
key Key to signwith.
klen Length of key.
Definition at line 290 of file util.c.
References md5sum2().
{
     _hmac(buff, data, len, key, klen, md5sum2, 16);
 }
void md5sum (unsigned char * buff, const void * data, unsigned long len)
Calculate the MD5 hash.
Parameters
buff buffer to place the hash (16 bytes).
data First data chunk to calculate.
len Length of data.
Definition at line 202 of file util.c.
References md5sum2().
{
     md5sum2(buff, data, len, NULL, 0);
 }
void md5sum2 (unsigned char * buff, const void * data, unsigned long len, const void * data2, unsigned long len2)
Calculate the MD5 hash accross 2 data chunks.
Parameters
buff buffer to place the hash (16 bytes).
data First data chunk to calculate.
len Length of data.
data2 Second data chunk to calculate.
len2 Length of data2.
Definition at line 185 of file util.c.
Referenced by md5hmac(), and md5sum().
{
     MD5_CTX c;
     MD5_Init(&c);
     MD5_Update(&c, data, len);
     if (data2) {
         MD5_Update(&c, data2, len2);
     }
     MD5_Final(buff, &c);
 }