DTS Application Library: IPv4 functions
IPv4 functions
IPv4 and IPv6 functions
Helper functions for various calculations.
Files
file iputil.c
IPv4 And IPv6 Utiliies.
Data Structures
struct pseudohdr
IPv4 header structur to cast a packet too.
Functions
int score_ipv4 (struct sockaddr_in *sa4, char *ipaddr, int iplen)
Return a score for a IPv4 addrress.
void ipv4tcpchecksum (uint8_t *pkt)
Update the TCP checksum of a IPv4 packet.
void ipv4udpchecksum (uint8_t *pkt)
Update the UDP checksum of a IPv4 packet.
void ipv4icmpchecksum (uint8_t *pkt)
Set the checksup of a IPv4 ICMP packet.
void ipv4checksum (uint8_t *pkt)
Set the checksup of a IPv4 Packet.
int packetchecksumv4 (uint8_t *pkt)
Update the checksum of a IPv4 packet.
const char * cidrtosn (int bitlen, char *buf, int size)
Return the dotted quad notation subnet mask from a CIDR.
const char * getnetaddr (const char *ipaddr, int cidr, char *buf, int size)
Return the network address.
const char * getfirstaddr (const char *ipaddr, int cidr, char *buf, int size)
Get the first usable address.
const char * getbcaddr (const char *ipaddr, int cidr, char *buf, int size)
Return broadcast address.
const char * getlastaddr (const char *ipaddr, int cidr, char *buf, int size)
Get the last usable address.
uint32_t cidrcnt (int bitlen)
Return the number of IP addresses in a given bitmask.
int reservedip (const char *ipaddr)
Check IP against list of reserved IP's.
int check_ipv4 (const char *ip, int cidr, const char *test)
Check if a IP address is in a network.
Detailed Description
Helper functions for various calculations.
Function Documentation
int check_ipv4 (const char * ip, int cidr, const char * test)
Check if a IP address is in a network.
Note
ipaddr will be truncated to network address based on cidr.
Parameters
ip Network address to check against.
cidr Number of bits in the subnet.
test IP address to check
Returns
0 if test is not in the network ip/cidr.
Definition at line 456 of file iputil.c.
{
     uint32_t ip1, ip2;
 #ifndef __WIN32
     inet_pton(AF_INET, ip, &ip1);
     inet_pton(AF_INET, test, &ip2);
 #else
     ip1 = inet_addr(ip);
     ip2 = inet_addr(test);
 #endif
     ip1 = ntohl(ip1) >> (32-cidr);
     ip2 = ntohl(ip2) >> (32-cidr);
     if (!(ip1 ^ ip2)) {
         return 1;
     } else {
         return 0;
     }
 }
uint32_t cidrcnt (int bitlen)
Return the number of IP addresses in a given bitmask.
Parameters
bitlen Subnet bits (CIDR).
Returns
Number of IP addreses including network and broadcast address.
Definition at line 372 of file iputil.c.
{
     if (bitlen) {
         return pow(2, (32-bitlen));
     } else {
         return 0xFFFFFFFF;
     }
 }
const char* cidrtosn (int bitlen, char * buf, int size)
Return the dotted quad notation subnet mask from a CIDR.
Parameters
bitlen Subnet length bits.
buf Buffer to copy the subnet address too.
size Size of buffer.
Returns
pointer to buffer on success or NULL.
Definition at line 228 of file iputil.c.
{
     uint32_t nm;
     uint8_t *nmb = (uint8_t*)&nm;
     if (!buf) {
         return NULL;
     }
     if (bitlen) {
         nm = ~((1 << (32-bitlen))-1);
     } else {
         nm = 0;
     }
     snprintf(buf, size, "%i.%i.%i.%i", nmb[3], nmb[2], nmb[1], nmb[0]);
     return buf;
 }
const char* getbcaddr (const char * ipaddr, int cidr, char * buf, int size)
Return broadcast address.
Note
ipaddr will be truncated to network address based on cidr.
Parameters
ipaddr Network address.
cidr CIDR subnet bit length.
buf Buffer to copy address too.
size Length of buffer.
Returns
Pointer to buffer or NULL on error.
Definition at line 319 of file iputil.c.
{
     uint32_t ip, mask;
     uint8_t *ipb = (uint8_t*)&ip;
 #ifndef __WIN32
     inet_pton(AF_INET, ipaddr, &ip);
 #else
     ip = inet_addr(ipaddr);
 #endif
     if (cidr) {
         mask = (1 << (32-cidr))-1;
         ip = ntohl(ip);
         ip = (ip & ~mask) | mask;
     } else {
         ip = 0;
     }
     snprintf(buf, size, "%i.%i.%i.%i", ipb[3], ipb[2], ipb[1], ipb[0]);
     return buf;
 }
const char* getfirstaddr (const char * ipaddr, int cidr, char * buf, int size)
Get the first usable address.
Note
ipaddr will be truncated to network address based on cidr.
Parameters
ipaddr Network address.
cidr Bits in the subnet mask.
buf Buffer that the result is placed in.
size Length of buffer.
Returns
Pointer to buf with the result copied to buf.
Definition at line 286 of file iputil.c.
{
     uint32_t ip;
     uint8_t *ipb = (uint8_t*)&ip;
     if (!buf) {
         return NULL;
     }
 #ifndef __WIN32
     inet_pton(AF_INET, ipaddr, &ip);
 #else
     ip = inet_addr(ipaddr);
 #endif
     if (cidr) {
         ip = ntohl(ip);
         ip = ip & ~((1 << (32-cidr))-1);
         ip++;
     } else {
         ip = 1;
     }
     snprintf(buf, size, "%i.%i.%i.%i", ipb[3], ipb[2], ipb[1], ipb[0]);
     return buf;
 }
const char* getlastaddr (const char * ipaddr, int cidr, char * buf, int size)
Get the last usable address.
Note
ipaddr will be truncated to network address based on cidr.
Parameters
ipaddr Network address.
cidr Bits in the subnet mask.
buf Buffer that the result is placed in.
size Length of buffer.
Returns
Pointer to buf with the result copied to buf.
Definition at line 347 of file iputil.c.
{
     uint32_t ip, mask;
     uint8_t *ipb = (uint8_t*)&ip;
 #ifndef __WIN32
     inet_pton(AF_INET, ipaddr, &ip);
 #else
     ip = inet_addr(ipaddr);
 #endif
     if (cidr) {
         mask = (1 << (32-cidr))-1;
         ip = ntohl(ip);
         ip = (ip & ~mask) | mask;
         ip--;
     } else {
         ip = 0;
     }
     snprintf(buf, size, "%i.%i.%i.%i", ipb[3], ipb[2], ipb[1], ipb[0]);
     return buf;
 }
const char* getnetaddr (const char * ipaddr, int cidr, char * buf, int size)
Return the network address.
Note
ipaddr will be truncated to network address based on cidr.
Parameters
ipaddr Ipaddr to calculate for
cidr Length of the subnet bitmask.
buf Buffer that the result is placed in.
size Length of buffer.
Returns
Pointer to buf with the result copied to buf.
Definition at line 254 of file iputil.c.
{
     uint32_t ip;
     uint8_t *ipb = (uint8_t*)&ip;
     if (!buf) {
         return NULL;
     }
 #ifndef __WIN32
     inet_pton(AF_INET, ipaddr, &ip);
 #else
     ip = inet_addr(ipaddr);
 #endif
     if (cidr) {
         ip = ntohl(ip);
         ip = ip & ~((1 << (32-cidr))-1);
     } else {
         ip = 0;
     }
     snprintf(buf, size, "%i.%i.%i.%i", ipb[3], ipb[2], ipb[1], ipb[0]);
     return buf;
 }
void ipv4checksum (uint8_t * pkt)
Set the checksup of a IPv4 Packet.
Parameters
pkt Packet to update.
Definition at line 154 of file iputil.c.
References checksum().
Referenced by packetchecksumv4().
{
     struct iphdr *ip = (struct iphdr *)pkt;
     ip->check = 0;
     ip->check = checksum(ip, (4 * ip->ihl));
 }
void ipv4icmpchecksum (uint8_t * pkt)
Set the checksup of a IPv4 ICMP packet.
Parameters
pkt ICMP Packet to update.
Definition at line 143 of file iputil.c.
References checksum().
Referenced by packetchecksumv4().
{
     struct iphdr *ip = (struct iphdr *)pkt;
     struct icmphdr *icmp = (struct icmphdr *)(pkt + (4 * ip->ihl));
     icmp->checksum = 0;
     icmp->checksum = checksum(icmp, ntohs(ip->tot_len) - (ip->ihl *4));
 }
void ipv4tcpchecksum (uint8_t * pkt)
Update the TCP checksum of a IPv4 packet.
Parameters
pkt Packet to update TCP checksum.
Definition at line 101 of file iputil.c.
References checksum(), checksum_add(), pseudohdr::daddr, pseudohdr::len, pseudohdr::proto, pseudohdr::saddr, and pseudohdr::zero.
Referenced by packetchecksumv4().
{
     struct iphdr *ip = (struct iphdr *)pkt;
     struct tcphdr *tcp = (struct tcphdr *)(pkt + (4 * ip->ihl));
     uint16_t plen, csum;
     struct pseudohdr phdr;
     /* get tcp packet len*/
     plen = ntohs(ip->tot_len) - (4 * ip->ihl);
     tcp->check = 0;
     phdr.saddr = ip->saddr;
     phdr.daddr = ip->daddr;
     phdr.zero = 0;
     phdr.proto = ip->protocol;
     phdr.len = htons(plen);
     csum = checksum(&phdr, sizeof(phdr));
     tcp->check = checksum_add(csum, tcp, plen);
 }
void ipv4udpchecksum (uint8_t * pkt)
Update the UDP checksum of a IPv4 packet.
Parameters
pkt Packet to update UDP checksum.
Definition at line 122 of file iputil.c.
References checksum(), checksum_add(), pseudohdr::daddr, pseudohdr::len, pseudohdr::proto, pseudohdr::saddr, and pseudohdr::zero.
Referenced by packetchecksumv4().
{
     struct iphdr *ip = (struct iphdr *)pkt;
     struct udphdr *udp = (struct udphdr *)(pkt + (4 * ip->ihl));
     uint16_t csum, plen;
     struct pseudohdr phdr;
     /* get tcp packet len*/
     plen = ntohs(ip->tot_len) - (4 * ip->ihl);
     udp->check = 0;
     phdr.saddr = ip->saddr;
     phdr.daddr = ip->daddr;
     phdr.zero = 0;
     phdr.proto = ip->protocol;
     phdr.len = htons(plen);
     csum = checksum(&phdr, sizeof(phdr));
     udp->check = checksum_add(csum, udp, plen);
 }
int packetchecksumv4 (uint8_t * pkt)
Update the checksum of a IPv4 packet.
Parameters
pkt Packet buffer to update check.
Returns
0 on success.
Definition at line 165 of file iputil.c.
References ipv4checksum(), ipv4icmpchecksum(), ipv4tcpchecksum(), and ipv4udpchecksum().
Referenced by packetchecksum().
{
     struct iphdr *ip = (struct iphdr *)pkt;
     ipv4checksum(pkt);
     switch(ip->protocol) {
         case IPPROTO_ICMP:
             ipv4icmpchecksum(pkt);
             break;
         case IPPROTO_TCP:
             ipv4tcpchecksum(pkt);
             break;
         case IPPROTO_UDP:
             ipv4udpchecksum(pkt);
             break;
         default:
             return (-1);
     }
     return (0);
 }
int reservedip (const char * ipaddr)
Check IP against list of reserved IP's.
Parameters
ipaddr IP addr to check.
Returns
1 if its a private/resrved/not routed IP
Definition at line 384 of file iputil.c.
Referenced by score_ipv4().
{
     uint32_t ip;
 #ifndef __WIN32
     inet_pton(PF_INET, ipaddr, &ip);
 #else
     ip = inet_addr(ipaddr);
 #endif
     ip = ntohl(ip);
     if (!((0xe0000000 ^ ip) >> 28)) { /* 224/4*/
         return 1;
     } else if (!((0x00000000 ^ ip) >> 24)) { /* 0/8 */
         return 1;
     } else if (!((0x0a000000 ^ ip) >> 24)) { /* 10/8 */
         return 1;
     } else if (!((0x7f000000 ^ ip) >> 24)) { /* 127/8 */
         return 1;
     } else if (!((0x64400000 ^ ip) >> 22)) { /* 100.64/10 */
         return 1;
     } else if (!((0xac100000 ^ ip) >> 20)) { /* 172.16/12 */
         return 1;
     } else if (!((0xc6120000 ^ ip) >> 17)) { /* 198.18/15 */
         return 1;
     } else if (!((0xc0a80000 ^ ip) >> 16)) { /* 192.168/16 */
         return 1;
     } else if (!((0xa9fe0000 ^ ip) >> 16)) { /* 169.254/16 */
         return 1;
     } else if (!((0xc0000200 ^ ip) >> 8)) { /* 192.0.2/24 */
         return 1;
     } else if (!((0xc6336400 ^ ip) >> 8)) { /* 198.51.100/24 */
         return 1;
     } else if (!((0xcb007100 ^ ip) >> 8)) { /* 203.0.113/24 */
         return 1;
     }
     return 0;
 }
int score_ipv4 (struct sockaddr_in * sa4, char * ipaddr, int iplen)
Return a score for a IPv4 addrress.
Note
This does not follow the RFC as gettaddrinfo would.
Parameters
sa4 Socket addr to check.
ipaddr Buffer to place IP address.
iplen Length of IP buffer.
Returns
Score based on the IP address Highest is "routable" lowest is Zeroconf.
Definition at line 718 of file interface.c.
References inet_ntop(), IPV4_SCORE_RESERVED, IPV4_SCORE_ROUTABLE, IPV4_SCORE_ZEROCONF, and reservedip().
Referenced by get_ifinfo(), and get_ifipaddr().
{
     uint32_t addr;
     int nscore;
     addr = sa4->sin_addr.s_addr;
     /* Get ipaddr string*/
     inet_ntop(AF_INET, &sa4->sin_addr, ipaddr, iplen);
     /* Score the IP*/
     if (!((0xa9fe0000 ^  ntohl(addr)) >> 16)) {
         nscore = IPV4_SCORE_ZEROCONF;
     } else if (reservedip(ipaddr)) {
         nscore = IPV4_SCORE_RESERVED;
     } else {
         nscore = IPV4_SCORE_ROUTABLE;
     }
     return nscore;
 }