DTS Application Library: Unix domain sockets
Unix domain sockets
Network socket interface
Support for unixdomain sockets using sockets interface.
Files
file unixsock.c
Attach a thread to a unix socket start a new thread on connect.
Data Structures
struct unixserv_sockthread
Unix socket server data structure.
struct unixclient_sockthread
Unix socket client data structure.
Functions
struct fwsocket * unixsocket_server (const char *sock, int protocol, int mask, socketrecv read, void *data)
Create and run UNIX server socket thread.
struct fwsocket * unixsocket_client (const char *sock, int protocol, socketrecv read, void *data)
Create a client thread on the socket.
Detailed Description
Support for unixdomain sockets using sockets interface.
A thread is started on the sockect and will start a new client thread on each connection with the socket and data reference.
Function Documentation
struct fwsocket* unixsocket_client (const char * sock, int protocol, socketrecv read, void * data)
Create a client thread on the socket.
It is not recomended to use SOCK_DGRAM as it requires a socket endpoint [inode] created this is done in /tmp using the basename of the socket and 6 random chars. this file is set to have no permissions as we only need the inode.
Parameters
sock Path to UNIX socket
protocol Either SOCK_STREAM or SOCK_DGRAM, SOCK_STREAM is recomended.
read Call back to call when read is ready.
data Reference to data to be returned in read callback.
Returns
Socket file descriptor
Definition at line 310 of file unixsock.c.
References fwsocket::addr, fwsocket::flags, make_socket(), objref(), objunref(), fwsocket::sock, SOCK_FLAG_UNIX, strlenzero(), and sockstruct::un.
Referenced by unixsocktest().
{
     struct fwsocket *fws;
     union sockstruct caddr, *saddr;
     char *temp = NULL;
     const char *tmpsock;
     int salen;
     mode_t omask;
     /*Create a UNIX socket structure*/
     if (!(fws = make_socket(PF_UNIX, protocol, 0, NULL))) {
         return NULL;
     }
     /* bind my endpoint to temp file*/
     if (protocol == SOCK_DGRAM) {
         /*yip i want only a inode here folks*/
         omask = umask(S_IXUSR | S_IRUSR | S_IWUSR | S_IWGRP | S_IRGRP | S_IXGRP | S_IWOTH | S_IROTH | S_IXOTH);
         tmpsock = basename((char*)sock);
         temp = tempnam(NULL, tmpsock);
         if (strlenzero(temp)) {
             if (temp) {
                 free(temp);
             }
             objunref(fws);
             return NULL;
         }
         /*Allocate address and connect to the client*/
         salen = sizeof(caddr.un);
         memset(&caddr.un, 0, salen);
         caddr.un.sun_family = PF_UNIX;
         strncpy((char *)caddr.un.sun_path, temp, sizeof(caddr.un.sun_path) -1);
         if (bind(fws->sock, (struct sockaddr *)&caddr.un, salen)) {
             /*reset umask*/
             umask(omask);
             if (temp) {
                 if (!strlenzero(temp)) {
                     unlink(temp);
                 }
                 free(temp);
             }
             objunref(fws);
             return NULL;
         }
         /*reset umask*/
         umask(omask);
     }
     /*Allocate address and connect to the server*/
     saddr =  &fws->addr;
     salen = sizeof(saddr->un);
     memset(&saddr->un, 0, salen);
     saddr->un.sun_family = PF_UNIX;
     strncpy((char *)saddr->un.sun_path, sock, sizeof(saddr->un.sun_path) -1);
     if (connect(fws->sock, (struct sockaddr *)&saddr->un, salen)) {
         if (temp) {
             if (!strlenzero(temp)) {
                 unlink(temp);
             }
             free(temp);
         }
         objunref(fws);
         return NULL;
     }
     fws->flags |= SOCK_FLAG_UNIX;
     if (!(new_unixclientthread(fws, temp, read, data))) {
         if (temp) {
             if (!strlenzero(temp)) {
                 unlink(temp);
             }
             free(temp);
         }
         objunref(fws);
         return NULL;
     }
     return (objref(fws)) ? fws : NULL;
 }
struct fwsocket* unixsocket_server (const char * sock, int protocol, int mask, socketrecv read, void * data)
Create and run UNIX server socket thread.
Parameters
sock Path to UNIX socket.
protocol Protocol number.
mask Umask for the socket.
read Callback to call when there is data available.
data Data reference to pass to read callback.
Returns
Reference to a socket
Definition at line 277 of file unixsock.c.
References unixserv_sockthread::data, framework_mkthread(), make_socket(), unixserv_sockthread::mask, objalloc(), objref(), objunref(), unixserv_sockthread::protocol, unixserv_sockthread::read, unixserv_sockthread::sock, and unixserv_sockthread::sockpath.
Referenced by unixsocktest().
{
     struct unixserv_sockthread *unsock;
     if (!(unsock = objalloc(sizeof(*unsock), free_unixserv))) {
         return NULL;
     }
     strncpy(unsock->sockpath, sock, UNIX_PATH_MAX);
     unsock->mask = mask;
     unsock->read = read;
     unsock->protocol = protocol;
     unsock->data = (objref(data)) ? data : NULL;
     /*Create a UNIX socket structure*/
     if (!(unsock->sock = make_socket(PF_UNIX, protocol, 0, NULL))) {
         objunref(unsock);
         return NULL;
     }
     framework_mkthread(unsock_serv, NULL, NULL, unsock, 0);
     return (objref(unsock->sock)) ? unsock->sock : NULL;
 }