DTS Application Library: Referenced Lockable Objects
Referenced Lockable Objects
Distrotech Application Library
Utilities for managing referenced lockable objects.
Modules
Hashed bucket linked lists of referenced objects
Store references in and retrive from linked lists based on a hash.
Files
file refobj.c
Referenced Lockable Objects.
Data Structures
struct ref_obj
Internal structure of all referenced objects.
Macros
#define clearflag(obj, flag)
Atomically clear a flag in the flags field of a referenced object.
#define setflag(obj, flag)
Atomically set a flag in the flags field of a referenced object.
#define testflag(obj, flag) (objlock(obj) | (obj->flags & flag) | objunlock(obj))
Atomically test a flag in the flags field of a referenced object.
#define DTS_OJBREF_CLASS(classtype)
Add this macro to a C++ class to add refobj support.
#define REFOBJ_MAGIC 0xdeadc0de
Magic number stored as first field of all referenced objects.
#define refobj_offset sizeof(struct ref_obj);
The size of ref_obj is the offset for the data.
Typedefs
typedef void(* objdestroy)(void *)
Callback used to clean data of a reference object when it is to be freed.
Functions
void * objalloc (int size, objdestroy destructor)
Allocate a referenced lockable object.
int objref (void *data)
Reference a object.
int objunref (void *data)
Drop reference held.
int objcnt (void *data)
Return current reference count.
int objsize (void *data)
Size requested for data.
int objlock (void *data)
Lock the reference.
int objtrylock (void *data)
Try lock a reference.
int objunlock (void *data)
Unlock a reference.
void * objchar (const char *orig)
Return a reference to copy of a buffer.
Detailed Description
Utilities for managing referenced lockable objects.
See Also
Referenced Lockable Objects
Macro Definition Documentation
#define clearflag (obj, flag)
Value:
objlock(obj);\
obj->flags &= ~flag;\
objunlock(obj)
Atomically clear a flag in the flags field of a referenced object.
Definition at line 918 of file dtsapp.h.
#define DTS_OJBREF_CLASS (classtype)
Value:
void *operator new(size_t sz) {\
    return objalloc(sz, &classtype::dts_unref_classtype);\
}\
void operator delete(void *obj) {\
}\
static void dts_unref_classtype(void *data) {\
    delete (classtype*)data;\
}\
~classtype()
Add this macro to a C++ class to add refobj support.
This macro defines operator overloads for new/delete and declares a destructor.
Note
this should not be used with inheritance
Definition at line 976 of file dtsapp.h.
#define REFOBJ_MAGIC 0xdeadc0de
Magic number stored as first field of all referenced objects.
Definition at line 34 of file refobj.c.
Referenced by objalloc(), objcnt(), objlock(), objref(), objsize(), objtrylock(), objunlock(), and objunref().
#define refobj_offset sizeof(struct ref_obj);
The size of ref_obj is the offset for the data.
Definition at line 119 of file refobj.c.
Referenced by addtobucket(), objalloc(), objcnt(), objlock(), objref(), objsize(), objtrylock(), objunlock(), and objunref().
#define setflag (obj, flag)
Value:
objlock(obj);\
obj->flags |= flag; \
objunlock(obj)
Atomically set a flag in the flags field of a referenced object.
Definition at line 925 of file dtsapp.h.
Referenced by close_socket(), dtls_listenssl(), framework_mkthread(), jointhreads(), nf_ctrack_endtrace(), socketwrite_d(), stopthreads(), and tlsaccept().
#define testflag (obj, flag) (objlock(obj) | (obj->flags & flag) | objunlock(obj))
Atomically test a flag in the flags field of a referenced object.
Definition at line 932 of file dtsapp.h.
Referenced by framework_mkthread(), framework_threadok(), socketread_d(), and socketwrite_d().
Typedef Documentation
typedef void(* objdestroy)(void *)
Callback used to clean data of a reference object when it is to be freed.
Parameters
data Data held by reference about to be freed.
Definition at line 264 of file dtsapp.h.
Function Documentation
void* objalloc (int size, objdestroy destructor)
Allocate a referenced lockable object.
Use malloc to allocate memory to contain the data lock and reference the lock is initialised magic and reference set. The data begins at the end of the ref_obj set a pointer to it and return.
Parameters
size Size of the data buffer to allocate in addition to the reference.
destructor Function called before the memory is freed to cleanup.
Returns
Pointer to a data buffer size big.
Definition at line 129 of file refobj.c.
References ref_obj::cnt, ref_obj::data, ref_obj::destroy, ref_obj::lock, ref_obj::magic, REFOBJ_MAGIC, refobj_offset, and ref_obj::size.
Referenced by accept_socket(), add_radserver(), b64enc_buf(), create_bucketlist(), create_kernmac(), create_kernvlan(), curl_newauth(), curl_newpost(), curl_setauth_cb(), curl_setprogress(), curlinit(), dtls_listenssl(), framework_mkcore(), framework_mkthread(), get_ifinfo(), init_bucket_loop(), ldap_addinit(), ldap_connect(), ldap_modifyinit(), ldap_saslbind(), ldap_simplebind(), make_socket(), nfqueue_attach(), objchar(), rfc6296_map_add(), set_interface_addr(), set_interface_flags(), set_interface_ipaddr(), set_interface_name(), startthreads(), tlsaccept(), unixsocket_server(), xml_doctobuffer(), xml_getfirstnode(), xml_init(), xml_loadbuf(), xml_loaddoc(), xml_xpath(), xslt_addparam(), xslt_apply_buffer(), xslt_init(), xslt_open(), and zcompress().
{
     struct ref_obj *ref;
     int asize;
     char *robj;
     asize  = size + refobj_offset;
     if ((robj = malloc(asize))) {
         memset(robj, 0, asize);
         ref = (struct ref_obj *)robj;
         pthread_mutex_init(&ref->lock, NULL);
         ref->magic = REFOBJ_MAGIC;
         ref->cnt = 1;
         ref->data = robj + refobj_offset;
         ref->size = asize;
         ref->destroy = destructor;
         return (ref->data);
     }
     return NULL;
 }
void* objchar (const char * orig)
Return a reference to copy of a buffer.
Parameters
orig Original buffer to copy.
Returns
Reference to new instance of orig.
Definition at line 330 of file refobj.c.
References objalloc().
{
     int len = strlen(orig) + 1;
     void *nobj;
     if ((nobj = objalloc(len, NULL))) {
         memcpy(nobj, orig, len);
     }
     return nobj;
 }
int objcnt (void * data)
Return current reference count.
Parameters
data Pointer to determine active reference count.
Returns
-1 on error or the current count.
Definition at line 222 of file refobj.c.
References ref_obj::cnt, ref_obj::data, ref_obj::lock, ref_obj::magic, REFOBJ_MAGIC, and refobj_offset.
Referenced by ldap_unref_attr(), and ldap_unref_entry().
{
     char *ptr = data;
     int ret = -1;
     struct ref_obj *ref;
     if (!data) {
         return (ret);
     }
     ptr = ptr - refobj_offset;
     ref = (struct ref_obj *)ptr;
     if (ref->magic == REFOBJ_MAGIC) {
         pthread_mutex_lock(&ref->lock);
         ret = ref->cnt;
         pthread_mutex_unlock(&ref->lock);
     }
     return (ret);
 }
int objlock (void * data)
Lock the reference.
Parameters
data Reference to lock
Returns
Always returns 0 will only lock if a valid object.
Definition at line 269 of file refobj.c.
References ref_obj::data, ref_obj::lock, ref_obj::magic, REFOBJ_MAGIC, and refobj_offset.
Referenced by accept_socket(), addtobucket(), bucket_list_cnt(), create_kernmac(), create_kernvlan(), curl_postitem(), curlinit(), dtls_listenssl(), dtlshandltimeout(), dtlstimeout(), dtsl_serveropts(), framework_mkthread(), get_iface_index(), jointhreads(), ldap_doadd(), ldap_domodify(), ldap_saslbind(), ldap_simplebind(), nf_ctrack_delete(), nf_ctrack_dump(), nf_ctrack_nat(), nfqueue_attach(), remove_bucket_item(), remove_bucket_loop(), set_interface_addr(), set_interface_flags(), set_interface_ipaddr(), set_interface_name(), socketread_d(), socketserver(), socketwrite_d(), ssl_shutdown(), stopthreads(), url_escape(), url_unescape(), xml_addnode(), xml_appendnode(), xml_createpath(), xml_delete(), xml_doctobuffer(), xml_getfirstnode(), xml_getnextnode(), xml_getrootnode(), xml_modify(), xml_savefile(), xml_setattr(), xml_unlink(), xml_xpath(), xslt_addparam(), xslt_apply(), xslt_apply_buffer(), and xslt_clearparam().
{
     char *ptr = data;
     struct ref_obj *ref;
     ptr = ptr - refobj_offset;
     ref = (struct ref_obj *)ptr;
     if (data && ref->magic == REFOBJ_MAGIC) {
         pthread_mutex_lock(&ref->lock);
     }
     return (0);
 }
int objref (void * data)
Reference a object.
Parameters
data Data to obtain reference for.
Returns
0 on error or the current count (after incrementing)
Definition at line 153 of file refobj.c.
References ref_obj::cnt, ref_obj::data, ref_obj::lock, ref_obj::magic, REFOBJ_MAGIC, and refobj_offset.
Referenced by addtobucket(), bucket_list_find_key(), create_kernmac(), create_kernvlan(), curl_setauth_cb(), curl_setprogress(), curlinit(), framework_init(), framework_mkthread(), get_category_next(), get_config_category(), get_config_file(), get_iface_index(), ifhwaddr(), init_bucket_loop(), jointhreads(), ldap_domodify(), ldap_saslbind(), ldap_simplebind(), ldap_simplerebind(), mcast_socket(), next_bucket_loop(), set_interface_addr(), set_interface_flags(), set_interface_ipaddr(), set_interface_name(), startthreads(), stopthreads(), unixsocket_client(), unixsocket_server(), xml_addnode(), xml_appendnode(), xml_createpath(), xml_getfirstnode(), xml_getnextnode(), xml_getnodes(), xml_init(), xml_xpath(), xslt_addparam(), and xslt_init().
{
     char *ptr = data;
     struct ref_obj *ref;
     int ret = 0;
     ptr = ptr - refobj_offset;
     ref = (struct ref_obj *)ptr;
     if (!data || !ref || (ref->magic != REFOBJ_MAGIC)) {
         return (ret);
     }
     /*double check just incase im gone*/
     if (!pthread_mutex_lock(&ref->lock)) {
         if ((ref->magic == REFOBJ_MAGIC) && (ref->cnt > 0)) {
             ref->cnt++;
             ret = ref->cnt;
         }
         pthread_mutex_unlock(&ref->lock);
     }
     return (ret);
 }
int objsize (void * data)
Size requested for data.
Note
the size of the data is returned.
Parameters
data Pointer to data to obtain size of.
Returns
size requested for allocation not allocation [excludes refobj].
Definition at line 246 of file refobj.c.
References ref_obj::data, ref_obj::lock, ref_obj::magic, REFOBJ_MAGIC, refobj_offset, and ref_obj::size.
{
     char *ptr = data;
     int ret = 0;
     struct ref_obj *ref;
     if (!data) {
         return (ret);
     }
     ptr = ptr - refobj_offset;
     ref = (struct ref_obj *)ptr;
     if (ref->magic == REFOBJ_MAGIC) {
         pthread_mutex_lock(&ref->lock);
         ret = ref->size - refobj_offset;
         pthread_mutex_unlock(&ref->lock);
     }
     return (ret);
 }
int objtrylock (void * data)
Try lock a reference.
Parameters
data Reference to attempt to lock.
Returns
0 on success -1 on failure.
Definition at line 285 of file refobj.c.
References ref_obj::data, ref_obj::lock, ref_obj::magic, REFOBJ_MAGIC, and refobj_offset.
{
     char *ptr = data;
     struct ref_obj *ref;
     ptr = ptr - refobj_offset;
     ref = (struct ref_obj *)ptr;
     if (ref->magic == REFOBJ_MAGIC) {
         return ((pthread_mutex_trylock(&ref->lock)) ? -1 : 0);
     }
     return (-1);
 }
int objunlock (void * data)
Unlock a reference.
Parameters
data Reference to unlock.
Returns
Always returns 0.
Definition at line 301 of file refobj.c.
References ref_obj::data, ref_obj::lock, ref_obj::magic, REFOBJ_MAGIC, and refobj_offset.
Referenced by accept_socket(), addtobucket(), bucket_list_cnt(), create_kernmac(), create_kernvlan(), curl_postitem(), curlinit(), dtls_listenssl(), dtlshandltimeout(), dtlstimeout(), dtsl_serveropts(), framework_mkthread(), get_iface_index(), jointhreads(), ldap_doadd(), ldap_domodify(), ldap_saslbind(), ldap_simplebind(), nf_ctrack_delete(), nf_ctrack_dump(), nf_ctrack_nat(), nfqueue_attach(), remove_bucket_item(), remove_bucket_loop(), set_interface_addr(), set_interface_flags(), set_interface_ipaddr(), set_interface_name(), socketread_d(), socketserver(), socketwrite_d(), ssl_shutdown(), stopthreads(), url_escape(), url_unescape(), xml_addnode(), xml_appendnode(), xml_createpath(), xml_delete(), xml_doctobuffer(), xml_getfirstnode(), xml_getnextnode(), xml_getrootnode(), xml_modify(), xml_savefile(), xml_setattr(), xml_unlink(), xml_xpath(), xslt_addparam(), xslt_apply(), xslt_apply_buffer(), and xslt_clearparam().
{
     char *ptr = data;
     struct ref_obj *ref;
     ptr = ptr - refobj_offset;
     ref = (struct ref_obj *)ptr;
     if (ref->magic == REFOBJ_MAGIC) {
         pthread_mutex_unlock(&ref->lock);
     }
     return (0);
 }
int objunref (void * data)
Drop reference held.
If the reference is the last reference call the destructor to clean up and then free the memory used.
Warning
The reference should not be used again and ideally set to NULL.
Parameters
data Data we are droping a reference for
Returns
-1 on error or the refrence count after decrementing.
Definition at line 184 of file refobj.c.
References ref_obj::cnt, ref_obj::data, ref_obj::destroy, ref_obj::lock, ref_obj::magic, REFOBJ_MAGIC, refobj_offset, and ref_obj::size.
Referenced by accept_socket(), add_radserver(), addtobucket(), bucket_list_find_key(), bucketlist_callback(), close_socket(), closenetlink(), create_kernmac(), create_kernvlan(), curl_setauth_cb(), curl_setprogress(), curlclose(), curlinit(), daemonize(), dtls_listenssl(), framework_init(), framework_mkcore(), framework_mkthread(), framework_threadok(), get_category_loop(), get_category_next(), get_config_category(), get_config_file(), get_iface_index(), ifhwaddr(), jointhreads(), ldap_add_attr(), ldap_addinit(), ldap_connect(), ldap_doadd(), ldap_domodify(), ldap_mod_add(), ldap_mod_addattr(), ldap_mod_del(), ldap_mod_delattr(), ldap_mod_rep(), ldap_mod_repattr(), ldap_modifyinit(), ldap_saslbind(), ldap_simplebind(), ldap_simplerebind(), ldap_unref_attr(), ldap_unref_entry(), make_socket(), mcast_socket(), nf_ctrack_close(), nf_ctrack_endtrace(), nf_ctrack_trace(), nfqueue_attach(), process_config(), remove_bucket_item(), remove_bucket_loop(), rfc6296_map_add(), rfc6296_test(), set_interface_addr(), set_interface_flags(), set_interface_ipaddr(), set_interface_name(), socketread_d(), socketwrite_d(), startthreads(), stopthreads(), thread_signal(), unixsocket_client(), unixsocket_server(), unrefconfigfiles(), url_escape(), url_unescape(), xml_addnode(), xml_appendnode(), xml_close(), xml_createpath(), xml_getattr(), xml_getfirstnode(), xml_getnextnode(), xml_loadbuf(), xml_loaddoc(), xml_xpath(), xslt_addparam(), xslt_apply(), xslt_apply_buffer(), xslt_clearparam(), and xslt_close().
{
     char *ptr = data;
     struct ref_obj *ref;
     int ret = -1;
     if (!data) {
         return (ret);
     }
     ptr = ptr - refobj_offset;
     ref = (struct ref_obj *)ptr;
     if ((ref->magic == REFOBJ_MAGIC) && (ref->cnt)) {
         pthread_mutex_lock(&ref->lock);
         ref->cnt--;
         ret = ref->cnt;
         /* free the object its no longer in use*/
         if (!ret) {
             ref->magic = 0;
             ref->size = 0;
             ref->data = NULL;
             if (ref->destroy) {
                 ref->destroy(data);
             }
             pthread_mutex_unlock(&ref->lock);
             pthread_mutex_destroy(&ref->lock);
             free(ref);
         } else {
             pthread_mutex_unlock(&ref->lock);
         }
     }
     return (ret);
 }