DTS Application Library: User interface dialogs.
User interface dialogs.
Distrotech GUI Library C API
Common dialogs for user interaction Confirmation, File, Password.
Functions
void DTS_C_API::dtsgui_alert (struct dtsgui *dtsgui, const char *text)
Alert the user and expect a confirmation.
int DTS_C_API::dtsgui_confirm (struct dtsgui *dtsgui, const char *text)
Request Yes/No Confirmation from the user.
const char * DTS_C_API::dtsgui_filesave (struct dtsgui *dtsgui, const char *title, const char *path, const char *name, const char *filter)
Open file save dialog box.
const char * DTS_C_API::dtsgui_fileopen (struct dtsgui *dtsgui, const char *title, const char *path, const char *name, const char *filter)
Open file open dialog box.
struct basic_auth * DTS_C_API::dtsgui_pwdialog (const char *user, const char *passwd, void *data)
Return basic auth reference from a password dialog box.
Detailed Description
Common dialogs for user interaction Confirmation, File, Password.
Remarks
Custom dialog boxes can be created using DTSDialog panels.
All implementations of the wxFileDialog provide a wildcard filter. Typing a filename containing wildcards (*, ?) in the filename text item, and clicking on Ok, will result in only those files matching the pattern being displayed. The wildcard may be a specification for multiple types of file with a description for each, such as:
"BMP and GIF files (*.bmp;*.gif)|*.bmp;*.gif|PNG files (*.png)|*.png"
Copied from wxFileDialog Documentation
Function Documentation
void DTS_C_API::dtsgui_alert (struct dtsgui * dtsgui, const char * text)
Alert the user and expect a confirmation.
See Also
DTSFrame::Alert()
Parameters
dtsgui Application data ptr.
text Text to supply in the alert.
Definition at line 1151 of file wrapper.cpp.
References DTSFrame::Alert(), and dtsgui::GetFrame().
Referenced by editsys_wizard(), export_config(), handle_test(), newsys_wizard(), open_config(), post_items(), and view_config_conf().
{
    DTSFrame *f = dtsgui->GetFrame();
    f->Alert(text);
}
int DTS_C_API::dtsgui_confirm (struct dtsgui * dtsgui, const char * text)
Request Yes/No Confirmation from the user.
See Also
DTSFrame::Confirm()
Parameters
dtsgui Application data ptr.
text Text to supply in the alert.
Returns
Non zero if the user affirmed.
Definition at line 1162 of file wrapper.cpp.
References DTSFrame::Confirm(), and dtsgui::GetFrame().
{
    DTSFrame *f = dtsgui->GetFrame();
    return f->Confirm(text);
}
const char* DTS_C_API::dtsgui_fileopen (struct dtsgui * dtsgui, const char * title, const char * path, const char * name, const char * filter)
Open file open dialog box.
See Also
DTSFrame::FileDialog()
dtsgui_fileopen()
Parameters
dtsgui Application data ptr.
title Title of the file dialog.
path Original path to open dialog in.
name Suggested name to open.
filter File namr filter.
Returns
Reference to the filename that must be unreferenced.
Definition at line 1192 of file wrapper.cpp.
References DTSFrame::FileDialog(), and dtsgui::GetFrame().
Referenced by editsys_wizard(), and open_config().
{
    DTSFrame *f = dtsgui->GetFrame();
    return f->FileDialog(title, path, name, filter, wxFD_OPEN | wxFD_FILE_MUST_EXIST);
}
const char* DTS_C_API::dtsgui_filesave (struct dtsgui * dtsgui, const char * title, const char * path, const char * name, const char * filter)
Open file save dialog box.
See Also
DTSFrame::FileDialog()
Parameters
dtsgui Application data ptr.
title Title of the file dialog.
path Original path to open dialog in.
name Suggested name to save as.
filter File namr filter.
Returns
Reference to the filename that must be unreferenced.
Definition at line 1176 of file wrapper.cpp.
References DTSFrame::FileDialog(), and dtsgui::GetFrame().
Referenced by export_config().
{
    DTSFrame *f = dtsgui->GetFrame();
    return f->FileDialog(title, path, name, filter, wxFD_SAVE | wxFD_OVERWRITE_PROMPT);
}
struct basic_auth* DTS_C_API::dtsgui_pwdialog (const char * user, const char * passwd, void * data) read
Return basic auth reference from a password dialog box.
A dialog box requesting the user name and password is presented to the user. The initial values may be supplied.
Remarks
This function is used as a callback for CURL.
See Also
DTSFrame::Passwd()
Parameters
user initial username entered into the box.
passwd the initial password.
data this will always be the application data ptr.
Returns
Basic auth reference.
Definition at line 1208 of file wrapper.cpp.
References DTSFrame::Passwd().
{
    DTSFrame *f = static_cast<class dtsgui*>(data)->GetFrame();
    return f->Passwd(user, passwd);
}