DTS Application Library: Radius client interface
Radius client interface
Distrotech Application Library
Simple implementation of experimental radius client.
Files
file radius.c
Simple radius client implementation.
Data Structures
struct radius_packet
Radius Packet.
struct radius_session
Radius session.
struct radius_connection
Radius connection.
struct radius_server
Radius Server.
Macros
#define RAD_AUTH_HDR_LEN 20
Authentification header length.
#define RAD_AUTH_PACKET_LEN 4096
Auth packet length.
#define RAD_AUTH_TOKEN_LEN 16
Auth token length.
#define RAD_MAX_PASS_LEN 128
Auth max password length.
#define RAD_ATTR_USER_NAME 1 /*string*/
Radius attribute username.
#define RAD_ATTR_USER_PASSWORD 2 /*passwd*/
Radius attribute password.
#define RAD_ATTR_NAS_IP_ADDR 4 /*ip*/
Radius attribute server IP.
#define RAD_ATTR_NAS_PORT 5 /*int*/
Radius attribute server port.
#define RAD_ATTR_SERVICE_TYPE 6 /*int*/
Radius attribute service type.
#define RAD_ATTR_ACCTID 44
Radius attribute account id.
#define RAD_ATTR_PORT_TYPE 61 /*int*/
Radius attribute port type.
#define RAD_ATTR_EAP 79 /*oct*/
Radius attribute EAP.
#define RAD_ATTR_MESSAGE 80 /*oct*/
Radius attribute message.
Typedefs
typedef struct radius_packet radius_packet
Forward decleration of structure.
typedef void(* radius_cb)(struct radius_packet *, void *)
Callback to call when response arrives.
Enumerations
enum RADIUS_CODE {
RAD_CODE_AUTHREQUEST = 1, RAD_CODE_AUTHACCEPT = 2, RAD_CODE_AUTHREJECT = 3, RAD_CODE_ACCTREQUEST = 4,
RAD_CODE_ACCTRESPONSE = 5, RAD_CODE_AUTHCHALLENGE = 11
}
Radius packet codes.
Functions
void addradattrint (struct radius_packet *packet, char type, unsigned int val)
Add a integer attribute too the packet.
void addradattrip (struct radius_packet *packet, char type, char *ipaddr)
Add a integer attribute too the packet.
void addradattrstr (struct radius_packet *packet, char type, char *str)
Add a integer attribute too the packet.
struct radius_packet * new_radpacket (unsigned char code)
Create a new radius packet.
void add_radserver (const char *ipaddr, const char *auth, const char *acct, const char *secret, int timeout)
Add new radius server to list of servers.
int send_radpacket (struct radius_packet *packet, const char *userpass, radius_cb read_cb, void *cb_data)
Send radius packet.
unsigned char * radius_attr_first (struct radius_packet *packet)
Return first packet attribute.
unsigned char * radius_attr_next (struct radius_packet *packet, unsigned char *attr)
Return next packet attribute.
Detailed Description
Simple implementation of experimental radius client.
 * User password crypt function from the freeradius project (addattrpasswd)
 * Copyright (C) 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009 The FreeRADIUS Server Project
Macro Definition Documentation
#define RAD_ATTR_ACCTID 44
Radius attribute account id.
Definition at line 556 of file dtsapp.h.
#define RAD_ATTR_EAP 79 /*oct*/
Radius attribute EAP.
Definition at line 562 of file dtsapp.h.
#define RAD_ATTR_MESSAGE 80 /*oct*/
Radius attribute message.
Definition at line 565 of file dtsapp.h.
#define RAD_ATTR_NAS_IP_ADDR 4 /*ip*/
Radius attribute server IP.
Definition at line 547 of file dtsapp.h.
#define RAD_ATTR_NAS_PORT 5 /*int*/
Radius attribute server port.
Definition at line 550 of file dtsapp.h.
#define RAD_ATTR_PORT_TYPE 61 /*int*/
Radius attribute port type.
Definition at line 559 of file dtsapp.h.
#define RAD_ATTR_SERVICE_TYPE 6 /*int*/
Radius attribute service type.
Definition at line 553 of file dtsapp.h.
#define RAD_ATTR_USER_NAME 1 /*string*/
Radius attribute username.
Definition at line 541 of file dtsapp.h.
#define RAD_ATTR_USER_PASSWORD 2 /*passwd*/
Radius attribute password.
Definition at line 544 of file dtsapp.h.
#define RAD_AUTH_HDR_LEN 20
Authentification header length.
Definition at line 529 of file dtsapp.h.
Referenced by new_radpacket(), and radius_attr_next().
#define RAD_AUTH_PACKET_LEN 4096
Auth packet length.
Definition at line 532 of file dtsapp.h.
#define RAD_AUTH_TOKEN_LEN 16
Auth token length.
Definition at line 535 of file dtsapp.h.
Referenced by new_radpacket().
#define RAD_MAX_PASS_LEN 128
Auth max password length.
Definition at line 538 of file dtsapp.h.
Typedef Documentation
typedef void(* radius_cb)(struct radius_packet *, void *)
Callback to call when response arrives.
Parameters
packet Reference to radius packet.
data Reference to userdata.
Definition at line 306 of file dtsapp.h.
typedef struct radius_packet radius_packet
Forward decleration of structure.
Definition at line 193 of file dtsapp.h.
Enumeration Type Documentation
enum RADIUS_CODE
Radius packet codes.
Enumerator:
RAD_CODE_AUTHREQUEST
Radius auth request.
RAD_CODE_AUTHACCEPT
Radius auth accept.
RAD_CODE_AUTHREJECT
Radius auth reject.
RAD_CODE_ACCTREQUEST
Radius accounting request.
RAD_CODE_ACCTRESPONSE
Radius accounting response.
RAD_CODE_AUTHCHALLENGE
Radius auth challenge.
Definition at line 568 of file dtsapp.h.
                 {
    RAD_CODE_AUTHREQUEST    =   1,
    RAD_CODE_AUTHACCEPT =   2,
    RAD_CODE_AUTHREJECT =   3,
    RAD_CODE_ACCTREQUEST    =   4,
    RAD_CODE_ACCTRESPONSE   =   5,
    RAD_CODE_AUTHCHALLENGE  =   11
};
Function Documentation
void add_radserver (const char * ipaddr, const char * auth, const char * acct, const char * secret, int timeout)
Add new radius server to list of servers.
Parameters
ipaddr IP address or hostname of server.
auth Athentification port.
acct Accounting port.
secret Shared secret.
timeout Time to take offline on failure.
Definition at line 289 of file radius.c.
References radius_server::acctport, addtobucket(), ALLOC_CONST, radius_server::authport, bucket_list_cnt(), create_bucketlist(), radius_server::id, radius_server::name, objalloc(), objunref(), radius_server::secret, radius_server::service, and radius_server::timeout.
{
    struct radius_server *server;
    if ((server = objalloc(sizeof(*server), del_radserver))) {
        ALLOC_CONST(server->name, ipaddr);
        ALLOC_CONST(server->authport, auth);
        ALLOC_CONST(server->acctport, acct);
        ALLOC_CONST(server->secret, secret);
        if (!servers) {
            servers = create_bucketlist(0, hash_server);
        }
        server->id = bucket_list_cnt(servers);
        server->timeout = timeout;
        gettimeofday(&server->service, NULL);
        addtobucket(servers, server);
    }
    objunref(server);
}
void addradattrint (struct radius_packet * packet, char type, unsigned int val)
Add a integer attribute too the packet.
Parameters
packet Radius packet to add too.
type Attribute been added.
val Value to add.
Definition at line 149 of file radius.c.
{
    unsigned int tval;
    tval = htonl(val);
    addradattr(packet, type, (unsigned char *)&tval, sizeof(tval));
}
void addradattrip (struct radius_packet * packet, char type, char * ipaddr)
Add a integer attribute too the packet.
Parameters
packet Radius packet to add too.
type Attribute been added.
ipaddr IP to add.
Definition at line 160 of file radius.c.
{
    unsigned int tval;
    tval = inet_addr(ipaddr);
    addradattr(packet, type, (unsigned char *)&tval, sizeof(tval));
}
void addradattrstr (struct radius_packet * packet, char type, char * str)
Add a integer attribute too the packet.
Parameters
packet Radius packet to add too.
type Attribute been added.
str Value to add.
Definition at line 171 of file radius.c.
{
    addradattr(packet, type, (unsigned char *)str, strlen(str));
}
struct radius_packet* new_radpacket (unsigned char code) read
Create a new radius packet.
See Also
RADIUS_CODE
Parameters
code Radius packet type.
Returns
reference to new radius packet of specified type.
Definition at line 221 of file radius.c.
References radius_packet::code, genrand(), radius_packet::len, RAD_AUTH_HDR_LEN, RAD_AUTH_TOKEN_LEN, and radius_packet::token.
{
    struct radius_packet *packet;
    if ((packet = malloc(sizeof(*packet)))) {
        memset(packet, 0, sizeof(*packet));
        packet->len = RAD_AUTH_HDR_LEN;
        packet->code = code;
        genrand(&packet->token, RAD_AUTH_TOKEN_LEN);
    }
    return (packet);
}
unsigned char* radius_attr_first (struct radius_packet * packet)
Return first packet attribute.
Used with radius_attr_next() to iterate through attributes.
Parameters
packet Radius packet.
Returns
Pointer to next attribute
Definition at line 627 of file radius.c.
References radius_packet::attrs.
{
    return (packet->attrs);
}
unsigned char* radius_attr_next (struct radius_packet * packet, unsigned char * attr)
Return next packet attribute.
Parameters
packet Radius packet.
attr Last attribute.
Returns
Pointer to next attribute.
Definition at line 635 of file radius.c.
References radius_packet::attrs, radius_packet::len, and RAD_AUTH_HDR_LEN.
{
    int offset = (packet->len - RAD_AUTH_HDR_LEN) - (attr - packet->attrs);
    if (!(offset - attr[1])) {
        return NULL;
    }
    return (attr + attr[1]);
}
int send_radpacket (struct radius_packet * packet, const char * userpass, radius_cb read_cb, void * cb_data)
Send radius packet.
Parameters
packet Radius packet to send.
userpass Userpassword if required (added last requires special processing)
read_cb Callback to call when response arrives.
cb_data Reference to pass to callback.
Returns
0 on success.
Definition at line 452 of file radius.c.
{
    return (_send_radpacket(packet, userpass, NULL, read_cb, cb_data));
}