DTS Application Library: IPv6 functions
IPv6 functions
IPv4 and IPv6 functions
Helper functions for various calculations.
Files
file iputil.c
IPv4 And IPv6 Utiliies.
Functions
void eui48to64 (unsigned char *mac48, unsigned char *eui64)
Generate IPv6 address from mac address.
int get_ip6_addrprefix (const char *iface, unsigned char *prefix)
Generate Unique Local IPv6 Unicast Addresses RFC 4193.
int score_ipv6 (struct sockaddr_in6 *sa6, char *ipaddr, int iplen)
Return a score for a IPv6 addrress.
int checkipv6mask (const char *ipaddr, const char *network, uint8_t bits)
Check if ipaddr is in a network.
int packetchecksumv6 (uint8_t *pkt)
Prototype to check checksup on packet.
char * ipv6to4prefix (const char *ipaddr)
Return IPv6 to IPv4 Prefix fot the address.
Detailed Description
Helper functions for various calculations.
Function Documentation
int checkipv6mask (const char * ipaddr, const char * network, uint8_t bits)
Check if ipaddr is in a network.
Parameters
ipaddr To check.
network Network to check against.
bits Network length.
Returns
0 if the ipaddr is in the network.
Definition at line 47 of file iputil.c.
{
     uint8_t cnt, bytelen, bitlen;
     uint32_t mask, res = 0;
     uint32_t *nw = (uint32_t *)network;
     uint32_t *ip = (uint32_t *)ipaddr;
     /*calculate significant bytes and bits outside boundry*/
     if ((bitlen = bits % 32)) {
         bytelen = (bits - bitlen) / 32;
         bytelen++;
     } else {
         bytelen = bits / 32;
     }
     /*end loop on first mismatch do not check last block*/
     for(cnt = 0; (!res && (cnt < (bytelen - 1))); cnt++) {
         res += nw[cnt] ^ ip[cnt];
     }
     /*process last block if no error sofar*/
     if (!res) {
         mask = (bitlen) ? htonl(~((1 << (32 - bitlen)) - 1)) : -1;
         res += (nw[cnt] & mask) ^ (ip[cnt] & mask);
     }
     return (res);
 }
void eui48to64 (unsigned char * mac48, unsigned char * eui64)
Generate IPv6 address from mac address.
this method is sourced from the following IEEE publication Guidelines for 64-bit Global Identifier (EUI-64TM) Registration Authority mac48 is char[ETH_ALEN] eui64 is char[8]
Parameters
mac48 Buffer containing MAC address 6 bytes.
eui64 Buffer that will be written with address 8bytes.
Definition at line 668 of file interface.c.
Referenced by get_ip6_addrprefix().
{
     eui64[0] = (mac48[0] & 0xFE) ^ 0x02; /*clear multicast bit and flip local asignment*/
     eui64[1] = mac48[1];
     eui64[2] = mac48[2];
     eui64[3] = 0xFF;
     eui64[4] = 0xFE;
     eui64[5] = mac48[3];
     eui64[6] = mac48[4];
     eui64[7] = mac48[5];
 }
int get_ip6_addrprefix (const char * iface, unsigned char * prefix)
Generate Unique Local IPv6 Unicast Addresses RFC 4193.
Todo:
WIN32 support
Parameters
iface External system interface name.
prefix A buffer char[6] that will contain the prefix.
Returns
-1 on error.
Definition at line 687 of file interface.c.
References eui48to64(), ifhwaddr(), sha1sum2(), and tvtontp64().
{
     uint64_t ntpts;
     unsigned char eui64[8];
     unsigned char sha1[20];
     unsigned char mac48[ETH_ALEN];
     struct timeval tv;
     if (ifhwaddr(iface, mac48)) {
         return (-1);
     }
     gettimeofday(&tv, NULL);
     ntpts = tvtontp64(&tv);
     eui48to64(mac48, eui64);
     sha1sum2(sha1, (void *)&ntpts, sizeof(ntpts), (void *)eui64, sizeof(eui64));
     prefix[0] = 0xFD; /*0xFC | 0x01 FC00/7 with local bit set [8th bit]*/
     memcpy(prefix + 1, sha1+15, 5); /*LSD 40 bits of the SHA hash*/
     return (0);
 }
char* ipv6to4prefix (const char * ipaddr)
Return IPv6 to IPv4 Prefix fot the address.
Parameters
ipaddr IPv4 Address to obtain mapping for
Returns
6to4 Address prefix.
Definition at line 427 of file iputil.c.
{
     uint32_t ip;
     uint8_t *ipa;
     char *pre6;
 #ifndef __WIN32
     if (!inet_pton(AF_INET, ipaddr, &ip)) {
         return NULL;
     }
 #else
     if (!(ip = inet_addr(ipaddr))) {
         return NULL;
     }
 #endif
     pre6 = malloc(10);
     ipa=(uint8_t*)&ip;
     snprintf(pre6, 10, "%02x%02x:%02x%02x", ipa[0], ipa[1], ipa[2], ipa[3]);
     return pre6;
 }
int packetchecksumv6 (uint8_t * pkt)
Prototype to check checksup on packet.
Parameters
pkt Packet buffer to check.
Definition at line 189 of file iputil.c.
{
     struct iphdr *ip = (struct iphdr *)pkt;
     switch(ip->protocol) {
         case IPPROTO_ICMP:
             break;
         case IPPROTO_TCP:
             break;
         case IPPROTO_UDP:
             break;
         default:
             return (-1);
     }
     return (0);
 }
int score_ipv6 (struct sockaddr_in6 * sa6, char * ipaddr, int iplen)
Return a score for a IPv6 addrress.
Note
This does not follow the RFC as gettaddrinfo would.
Parameters
sa6 Socket addr to check.
ipaddr Buffer to place IP address.
iplen Length of IP buffer.
Returns
Score based on the IP address Highest is "routable" lowest is Internal allocation.
Definition at line 746 of file interface.c.
References inet_ntop(), IPV6_SCORE_RESERVED, IPV6_SCORE_ROUTABLE, and IPV6_SCORE_SIXIN4.
Referenced by get_ifinfo(), and get_ifipaddr().
{
     uint32_t *ipptr, match;
     int nscore;
 #ifndef __WIN32
     ipptr = sa6->sin6_addr.s6_addr32;
 #else
     ipptr = (uint32_t*)sa6->sin6_addr.u.Word;
 #endif
     match = ntohl(ipptr[0]) >> 16;
     /* exclude link local multicast and special addresses */
     if (!(0xFE80 ^ match) || !(0xFF ^ (match >> 8)) || !match) {
         return 0;
     }
     /*Score ip private/sixin4/routable*/
     if (!(0xFC ^ (match >> 9))) {
         nscore = IPV6_SCORE_RESERVED;
     } else if (match == 2002) {
         nscore = IPV6_SCORE_SIXIN4;
     } else {
         nscore = IPV6_SCORE_ROUTABLE;
     }
     inet_ntop(AF_INET6, ipptr, ipaddr, iplen);
     return nscore;
 }