DTS Application Library: SSL socket support
SSL socket support
Distrotech Application Library
TLSv1 SSLv2 SSLv3 DTLSv1 support.
Files
file sslutil.c
TLSv1 SSLv2 SSLv3 DTLSv1 support.
Data Structures
struct ssldata
Macros
#define COOKIE_SECRET_LENGTH 32
Enumerations
enum SSLFLAGS {
SSL_TLSV1 = 1 << 0, SSL_SSLV2 = 1 << 1, SSL_SSLV3 = 1 << 2, SSL_DTLSV1 = 1 << 3,
SSL_CLIENT = 1 << 4, SSL_SERVER = 1 << 5, SSL_DTLSCON = 1 << 6
}
Functions
void ssl_shutdown (void *data)
void * tlsv1_init (const char *cacert, const char *cert, const char *key, int verify)
void * sslv2_init (const char *cacert, const char *cert, const char *key, int verify)
void * sslv3_init (const char *cacert, const char *cert, const char *key, int verify)
void * dtlsv1_init (const char *cacert, const char *cert, const char *key, int verify)
void tlsaccept (struct fwsocket *sock, struct ssldata *orig)
int socketread_d (struct fwsocket *sock, void *buf, int num, union sockstruct *addr)
int socketread (struct fwsocket *sock, void *buf, int num)
int socketwrite_d (struct fwsocket *sock, const void *buf, int num, union sockstruct *addr)
int socketwrite (struct fwsocket *sock, const void *buf, int num)
void sslstartup (void)
void dtsl_serveropts (struct fwsocket *sock)
struct fwsocket * dtls_listenssl (struct fwsocket *sock)
void startsslclient (struct fwsocket *sock)
void dtlstimeout (struct fwsocket *sock, struct timeval *timeleft, int defusec)
void dtlshandltimeout (struct fwsocket *sock)
Variables
SSL_CTX * ssldata::ctx
SSL * ssldata::ssl
BIO * ssldata::bio
int ssldata::flags
const SSL_METHOD * ssldata::meth
struct ssldata * ssldata::parent
Detailed Description
TLSv1 SSLv2 SSLv3 DTLSv1 support.
The thread interface consists of a management thread managing a hashed bucket list of threads running optional clean up when done.
Macro Definition Documentation
#define COOKIE_SECRET_LENGTH 32
Definition at line 66 of file sslutil.c.
Referenced by sslstartup().
Enumeration Type Documentation
enum SSLFLAGS
Enumerator:
SSL_TLSV1
SSL_SSLV2
SSL_SSLV3
SSL_DTLSV1
SSL_CLIENT
SSL_SERVER
SSL_DTLSCON
Definition at line 47 of file sslutil.c.
              {
    SSL_TLSV1   = 1 << 0,
    SSL_SSLV2   = 1 << 1,
    SSL_SSLV3   = 1 << 2,
    SSL_DTLSV1  = 1 << 3,
    SSL_CLIENT  = 1 << 4,
    SSL_SERVER  = 1 << 5,
    SSL_DTLSCON = 1 << 6
};
Function Documentation
struct fwsocket* dtls_listenssl (struct fwsocket * sock) read
Definition at line 541 of file sslutil.c.
References fwsocket::addr, ssldata::flags, make_socket(), objalloc(), objlock(), objunlock(), objunref(), fwsocket::proto, sockstruct::sa, fwsocket::sock, ssldata::ssl, fwsocket::ssl, SSL_DTLSCON, and fwsocket::type.
{
    struct ssldata *ssl = sock->ssl;
    struct ssldata *newssl;
    struct fwsocket *newsock;
    union sockstruct client;
#ifndef __WIN32__
    int on = 1;
#endif
    if (!(newssl = objalloc(sizeof(*newssl), free_ssldata))) {
        return NULL;
    }
    newssl->flags |= SSL_DTLSCON;
    dtlssetopts(newssl, ssl, sock);
    memset(&client, 0, sizeof(client));
    if (DTLSv1_listen(newssl->ssl, &client) <= 0) {
        objunref(newssl);
        return NULL;
    }
    objlock(sock);
    if (!(newsock = make_socket(sock->addr.sa.sa_family, sock->type, sock->proto, newssl))) {
        objunlock(sock);
        objunref(newssl);
        return NULL;
    }
    objunlock(sock);
    memcpy(&newsock->addr, &client, sizeof(newsock->addr));
#ifndef __WIN32__
    setsockopt(newsock->sock, SOL_SOCKET, SO_REUSEADDR, &on, sizeof(on));
#ifdef SO_REUSEPORT
    setsockopt(newsock->sock, SOL_SOCKET, SO_REUSEPORT, &on, sizeof(on));
#endif
#endif
    objlock(sock);
    bind(newsock->sock, &sock->addr.sa, sizeof(sock->addr));
    objunlock(sock);
    connect(newsock->sock, &newsock->addr.sa, sizeof(newsock->addr));
    dtlsaccept(newsock);
    return (newsock);
}
void dtlshandltimeout (struct fwsocket * sock)
Definition at line 641 of file sslutil.c.
References objlock(), objunlock(), ssldata::ssl, and fwsocket::ssl.
{
    if (!sock->ssl) {
        return;
    }
    objlock(sock->ssl);
    DTLSv1_handle_timeout(sock->ssl->ssl);
    objunlock(sock->ssl);
}
void dtlstimeout (struct fwsocket * sock, struct timeval * timeleft, int defusec)
Definition at line 628 of file sslutil.c.
References objlock(), objunlock(), ssldata::ssl, and fwsocket::ssl.
{
    if (!sock || !sock->ssl || !sock->ssl->ssl) {
        return;
    }
    objlock(sock->ssl);
    if (!DTLSv1_get_timeout(sock->ssl->ssl, timeleft)) {
        timeleft->tv_sec = 0;
        timeleft->tv_usec = defusec;
    }
    objunlock(sock->ssl);
}
void* dtlsv1_init (const char * cacert, const char * cert, const char * key, int verify)
Definition at line 248 of file sslutil.c.
References ssldata::ctx, ssldata::ssl, and SSL_DTLSV1.
{
    const SSL_METHOD *meth = DTLSv1_method();
    struct ssldata *ssl;
    ssl = sslinit(cacert, cert, key, verify, meth, SSL_DTLSV1);
    /* XXX BIO_CTRL_DGRAM_MTU_DISCOVER*/
    SSL_CTX_set_read_ahead(ssl->ctx, 1);
    return (ssl);
}
void dtsl_serveropts (struct fwsocket * sock)
Definition at line 500 of file sslutil.c.
References ssldata::ctx, ssldata::flags, objlock(), objunlock(), ssldata::ssl, fwsocket::ssl, and SSL_SERVER.
Referenced by socketserver().
{
    struct ssldata *ssl = sock->ssl;
    if (!ssl) {
        return;
    }
    dtlssetopts(ssl, NULL, sock);
    objlock(ssl);
    SSL_CTX_set_cookie_generate_cb(ssl->ctx, generate_cookie);
    SSL_CTX_set_cookie_verify_cb(ssl->ctx, verify_cookie);
    SSL_CTX_set_session_cache_mode(ssl->ctx, SSL_SESS_CACHE_OFF);
    SSL_set_options(ssl->ssl, SSL_OP_COOKIE_EXCHANGE);
    ssl->flags |= SSL_SERVER;
    objunlock(ssl);
}
int socketread (struct fwsocket * sock, void * buf, int num)
Definition at line 373 of file sslutil.c.
References socketread_d().
{
    return (socketread_d(sock, buf, num, NULL));
}
int socketread_d (struct fwsocket * sock, void * buf, int num, union sockstruct * addr)
Definition at line 308 of file sslutil.c.
References fwsocket::flags, objlock(), objunlock(), objunref(), sockstruct::sa, fwsocket::sock, SOCK_FLAG_CLOSE, ssldata::ssl, fwsocket::ssl, and fwsocket::type.
Referenced by socketread().
{
    struct ssldata *ssl = sock->ssl;
    socklen_t salen = sizeof(*addr);
    int ret, err, syserr;
    if (!ssl || !ssl->ssl) {
        objlock(sock);
        if (addr && (sock->type == SOCK_DGRAM)) {
            ret = recvfrom(sock->sock, buf, num, 0, &addr->sa, &salen);
        } else {
            ret = read(sock->sock, buf, num);
        }
        if (ret == 0) {
            sock->flags |= SOCK_FLAG_CLOSE;
        }
        objunlock(sock);
        return (ret);
    }
    objlock(ssl);
    /* ive been shutdown*/
    if (!ssl->ssl) {
        objunlock(ssl);
        return (-1);
    }
    ret = SSL_read(ssl->ssl, buf, num);
    err = SSL_get_error(ssl->ssl, ret);
    if (ret == 0) {
        sock->flags |= SOCK_FLAG_CLOSE;
    }
    objunlock(ssl);
    switch (err) {
        case SSL_ERROR_NONE:
            break;
        case SSL_ERROR_WANT_X509_LOOKUP:
            printf("Want X509\n");
            break;
        case SSL_ERROR_WANT_READ:
            printf("Want Read\n");
            break;
        case SSL_ERROR_WANT_WRITE:
            printf("Want write\n");
            break;
        case SSL_ERROR_ZERO_RETURN:
        case SSL_ERROR_SSL:
            objlock(sock);
            objunref(sock->ssl);
            sock->ssl = NULL;
            objunlock(sock);
            break;
        case SSL_ERROR_SYSCALL:
            syserr = ERR_get_error();
            if (syserr || (!syserr && (ret == -1))) {
                printf("R syscall %i %i\n", syserr, ret);
            }
            break;
        default
                :
            printf("other\n");
            break;
    }
    return (ret);
}
int socketwrite (struct fwsocket * sock, const void * buf, int num)
Definition at line 455 of file sslutil.c.
References socketwrite_d().
{
    return (socketwrite_d(sock, buf, num, NULL));
}
int socketwrite_d (struct fwsocket * sock, const void * buf, int num, union sockstruct * addr)
Definition at line 377 of file sslutil.c.
References fwsocket::flags, objlock(), objunlock(), objunref(), sockstruct::sa, setflag, fwsocket::sock, SOCK_FLAG_CLOSE, ssldata::ssl, fwsocket::ssl, and fwsocket::type.
Referenced by socketwrite().
{
    struct ssldata *ssl = (sock) ? sock->ssl : NULL;
    int ret, err, syserr;
    if (!sock) {
        return (-1);
    }
#ifndef __WIN32__
    if (!ssl || !ssl->ssl) {
        objlock(sock);
        if (addr && (sock->type == SOCK_DGRAM)) {
            ret = sendto(sock->sock, buf, num, MSG_NOSIGNAL, &addr->sa, sizeof(*addr));
        } else {
            ret = send(sock->sock, buf, num, MSG_NOSIGNAL);
        }
        if (ret == -1) {
            switch(errno) {
                case EBADF:
                case EPIPE:
                case ENOTCONN:
                case ENOTSOCK:
                    sock->flags |= SOCK_FLAG_CLOSE;
                    break;
            }
        }
        objunlock(sock);
        return (ret);
    }
#endif
    objlock(ssl);
    if (SSL_state(ssl->ssl) != SSL_ST_OK) {
        objunlock(ssl);
        return (SSL_ERROR_SSL);
    }
    ret = SSL_write(ssl->ssl, buf, num);
    err = SSL_get_error(ssl->ssl, ret);
    objunlock(ssl);
    if (ret == -1) {
        setflag(sock, SOCK_FLAG_CLOSE);
    }
    switch(err) {
        case SSL_ERROR_NONE:
            break;
        case SSL_ERROR_WANT_READ:
            printf("Want Read\n");
            break;
        case SSL_ERROR_WANT_WRITE:
            printf("Want write\n");
            break;
        case SSL_ERROR_WANT_X509_LOOKUP:
            printf("Want X509\n");
            break;
        case SSL_ERROR_ZERO_RETURN:
        case SSL_ERROR_SSL:
            objlock(sock);
            objunref(sock->ssl);
            sock->ssl = NULL;
            objunlock(sock);
            break;
        case SSL_ERROR_SYSCALL:
            syserr = ERR_get_error();
            if (syserr || (!syserr && (ret == -1))) {
                printf("W syscall %i %i\n", syserr, ret);
            }
            break;
        default
                :
            printf("other\n");
            break;
    }
    return (ret);
}
void ssl_shutdown (void * data)
Definition at line 103 of file sslutil.c.
References objlock(), objunlock(), and ssldata::ssl.
{
    struct ssldata *ssl = data;
    int err, ret;
    if (!ssl) {
        return;
    }
    objlock(ssl);
    if (ssl->ssl && ((ret = SSL_shutdown(ssl->ssl)) < 1)) {
        objunlock(ssl);
        if (ret == 0) {
            objlock(ssl);
            ret = SSL_shutdown(ssl->ssl);
        } else {
            objlock(ssl);
        }
        err = SSL_get_error(ssl->ssl, ret);
        switch(err) {
            case SSL_ERROR_WANT_READ:
                printf("SSL_shutdown wants read\n");
                break;
            case SSL_ERROR_WANT_WRITE:
                printf("SSL_shutdown wants write\n");
                break;
            case SSL_ERROR_SSL:
                /*ignore im going away now*/
            case SSL_ERROR_SYSCALL:
                /* ignore this as documented*/
            case SSL_ERROR_NONE:
                /* nothing to see here moving on*/
                break;
            default
                    :
                printf("SSL Shutdown unknown error %i\n", err);
                break;
        }
    }
    if (ssl->ssl) {
        SSL_free(ssl->ssl);
        ssl->ssl = NULL;
    }
    objunlock(ssl);
}
void sslstartup (void)
Definition at line 459 of file sslutil.c.
References COOKIE_SECRET_LENGTH, and genrand().
Referenced by framework_init().
{
    SSL_library_init();
    SSL_load_error_strings();
    OpenSSL_add_ssl_algorithms();
    if ((cookie_secret = malloc(COOKIE_SECRET_LENGTH))) {
        genrand(cookie_secret, COOKIE_SECRET_LENGTH);
    }
}
void* sslv2_init (const char * cacert, const char * cert, const char * key, int verify)
Definition at line 232 of file sslutil.c.
References SSL_SSLV2.
{
    const SSL_METHOD *meth = SSLv2_method();
    return (sslinit(cacert, cert, key, verify, meth, SSL_SSLV2));
}
void* sslv3_init (const char * cacert, const char * cert, const char * key, int verify)
Definition at line 239 of file sslutil.c.
References ssldata::ssl, and SSL_SSLV3.
{
    const SSL_METHOD *meth = SSLv3_method();
    struct ssldata *ssl;
    ssl = sslinit(cacert, cert, key, verify, meth, SSL_SSLV3);
    return (ssl);
}
void startsslclient (struct fwsocket * sock)
Definition at line 613 of file sslutil.c.
References ssldata::flags, fwsocket::ssl, SSL_SERVER, and fwsocket::type.
Referenced by socketclient().
{
    if (!sock || !sock->ssl || (sock->ssl->flags & SSL_SERVER)) {
        return;
    }
    switch(sock->type) {
        case SOCK_DGRAM:
            dtlsconnect(sock);
            break;
        case SOCK_STREAM:
            sslsockstart(sock, NULL, 0);
            break;
    }
}
void tlsaccept (struct fwsocket * sock, struct ssldata * orig)
Definition at line 301 of file sslutil.c.
References objalloc(), and fwsocket::ssl.
{
    if ((sock->ssl = objalloc(sizeof(*sock->ssl), free_ssldata))) {
        sslsockstart(sock, orig, 1);
    }
}
void* tlsv1_init (const char * cacert, const char * cert, const char * key, int verify)
Definition at line 225 of file sslutil.c.
References SSL_TLSV1.
{
    const SSL_METHOD *meth = TLSv1_method();
    return (sslinit(cacert, cert, key, verify, meth, SSL_TLSV1));
}
Variable Documentation
BIO* ssldata::bio
Definition at line 60 of file sslutil.c.
SSL_CTX* ssldata::ctx
Definition at line 58 of file sslutil.c.
Referenced by dtlsv1_init(), and dtsl_serveropts().
int ssldata::flags
Definition at line 61 of file sslutil.c.
Referenced by dtls_listenssl(), dtsl_serveropts(), and startsslclient().
const SSL_METHOD* ssldata::meth
Definition at line 62 of file sslutil.c.
struct ssldata* ssldata::parent
Definition at line 63 of file sslutil.c.
SSL* ssldata::ssl
Definition at line 59 of file sslutil.c.
Referenced by dtls_listenssl(), dtlshandltimeout(), dtlstimeout(), dtlsv1_init(), dtsl_serveropts(), socketread_d(), socketwrite_d(), ssl_shutdown(), and sslv3_init().