DTS Application Library: src/libnetlink/ll_map.c File Reference
ll_map.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <syslog.h>
#include <fcntl.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <string.h>
#include <linux/if.h>
#include "libnetlink.h"
#include "ll_map.h"
Data Structures
struct ll_cache
Macros
#define IDXMAP_SIZE 1024
Functions
unsigned int if_nametoindex (const char *)
int ll_remember_index (const struct sockaddr_nl *who, struct nlmsghdr *n, void *arg)
const char * ll_idx_n2a (unsigned idx, char *buf)
const char * ll_index_to_name (unsigned idx)
int ll_index_to_type (unsigned idx)
unsigned ll_index_to_flags (unsigned idx)
unsigned ll_index_to_addr (unsigned idx, unsigned char *addr, unsigned alen)
unsigned ll_name_to_index (const char *name)
int ll_init_map (struct rtnl_handle *rth, int reinit)
Macro Definition Documentation
#define IDXMAP_SIZE 1024
Definition at line 38 of file ll_map.c.
Referenced by ll_name_to_index(), and ll_remember_index().
Function Documentation
unsigned int if_nametoindex (const char *)
Referenced by ll_name_to_index().
const char* ll_idx_n2a (unsigned idx, char * buf)
Definition at line 99 of file ll_map.c.
References ll_cache::idx_next, ll_cache::index, and ll_cache::name.
Referenced by ll_index_to_name().
{
    const struct ll_cache *im;
    if (idx == 0) {
        return "*";
    }
    for (im = idxhead(idx); im; im = im->idx_next)
        if (im->index == idx) {
            return im->name;
        }
    snprintf(buf, IFNAMSIZ, "if%d", idx);
    return buf;
}
unsigned ll_index_to_addr (unsigned idx, unsigned char * addr, unsigned alen)
Definition at line 149 of file ll_map.c.
References ll_cache::addr, ll_cache::alen, ll_cache::idx_next, and ll_cache::index.
Referenced by ifhwaddr().
{
    const struct ll_cache *im;
    if (idx == 0) {
        return 0;
    }
    for (im = idxhead(idx); im; im = im->idx_next) {
        if (im->index == idx) {
            if (alen > sizeof(im->addr)) {
                alen = sizeof(im->addr);
            }
            if (alen > im->alen) {
                alen = im->alen;
            }
            memcpy(addr, im->addr, alen);
            return alen;
        }
    }
    return 0;
}
unsigned ll_index_to_flags (unsigned idx)
Definition at line 135 of file ll_map.c.
References ll_cache::flags, ll_cache::idx_next, and ll_cache::index.
Referenced by set_interface_flags().
{
    const struct ll_cache *im;
    if (idx == 0) {
        return 0;
    }
    for (im = idxhead(idx); im; im = im->idx_next)
        if (im->index == idx) {
            return im->flags;
        }
    return 0;
}
const char* ll_index_to_name (unsigned idx)
Definition at line 116 of file ll_map.c.
References ll_idx_n2a().
{
    static char nbuf[IFNAMSIZ];
    return ll_idx_n2a(idx, nbuf);
}
int ll_index_to_type (unsigned idx)
Definition at line 122 of file ll_map.c.
References ll_cache::idx_next, ll_cache::index, and ll_cache::type.
{
    const struct ll_cache *im;
    if (idx == 0) {
        return -1;
    }
    for (im = idxhead(idx); im; im = im->idx_next)
        if (im->index == idx) {
            return im->type;
        }
    return -1;
}
int ll_init_map (struct rtnl_handle * rth, int reinit)
Definition at line 204 of file ll_map.c.
References ll_remember_index(), rtnl_dump_filter(), and rtnl_wilddump_request().
Referenced by get_iface_index().
{
    static int initialized;
    if (initialized && !reinit) {
        return 0;
    }
    if (rtnl_wilddump_request(rth, AF_UNSPEC, RTM_GETLINK) < 0) {
        perror("Cannot send dump request");
        exit(1);
    }
    if (rtnl_dump_filter(rth, ll_remember_index, NULL) < 0) {
        fprintf(stderr, "Dump terminated\n");
        exit(1);
    }
    initialized = 1;
    return 0;
}
unsigned ll_name_to_index (const char * name)
Definition at line 172 of file ll_map.c.
References ll_cache::idx_next, IDXMAP_SIZE, if_nametoindex(), ll_cache::index, and ll_cache::name.
Referenced by get_iface_index().
{
    static char ncache[IFNAMSIZ];
    static int icache;
    struct ll_cache *im;
    int i;
    unsigned idx;
    if (name == NULL) {
        return 0;
    }
    if (icache && strcmp(name, ncache) == 0) {
        return icache;
    }
    for (i=0; i<IDXMAP_SIZE; i++) {
        for (im = idx_head[i]; im; im = im->idx_next) {
            if (strcmp(im->name, name) == 0) {
                icache = im->index;
                strcpy(ncache, name);
                return im->index;
            }
        }
    }
    idx = if_nametoindex(name);
    if (idx == 0) {
        sscanf(name, "if%u", &idx);
    }
    return idx;
}
int ll_remember_index (const struct sockaddr_nl * who, struct nlmsghdr * n, void * arg)
Definition at line 45 of file ll_map.c.
References ll_cache::addr, ll_cache::alen, ll_cache::flags, ll_cache::idx_next, IDXMAP_SIZE, IFLA_PAYLOAD, IFLA_RTA, ll_cache::index, ll_cache::name, parse_rtattr(), and ll_cache::type.
Referenced by ll_init_map().
{
    int h;
    struct ifinfomsg *ifi = NLMSG_DATA(n);
    struct ll_cache *im, **imp;
    struct rtattr *tb[IFLA_MAX+1];
    if (n->nlmsg_type != RTM_NEWLINK) {
        return 0;
    }
    if (n->nlmsg_len < NLMSG_LENGTH(sizeof(ifi))) {
        return -1;
    }
    memset(tb, 0, sizeof(tb));
    parse_rtattr(tb, IFLA_MAX, IFLA_RTA(ifi), IFLA_PAYLOAD(n));
    if (tb[IFLA_IFNAME] == NULL) {
        return 0;
    }
    h = ifi->ifi_index & (IDXMAP_SIZE - 1);
    for (imp = &idx_head[h]; (im=*imp)!=NULL; imp = &im->idx_next)
        if (im->index == ifi->ifi_index) {
            break;
        }
    if (im == NULL) {
        im = malloc(sizeof(*im));
        if (im == NULL) {
            return 0;
        }
        im->idx_next = *imp;
        im->index = ifi->ifi_index;
        *imp = im;
    }
    im->type = ifi->ifi_type;
    im->flags = ifi->ifi_flags;
    if (tb[IFLA_ADDRESS]) {
        int alen;
        im->alen = alen = RTA_PAYLOAD(tb[IFLA_ADDRESS]);
        if (alen > sizeof(im->addr)) {
            alen = sizeof(im->addr);
        }
        memcpy(im->addr, RTA_DATA(tb[IFLA_ADDRESS]), alen);
    } else {
        im->alen = 0;
        memset(im->addr, 0, sizeof(im->addr));
    }
    strcpy(im->name, RTA_DATA(tb[IFLA_IFNAME]));
    return 0;
}