DTS Application Library: src/openldap.c File Reference
openldap.c File Reference
Openldap/SASL Interface
Openldap/SASL Implementation.
#include <ldap.h>
#include <ldap_schema.h>
#include <lber.h>
#include <sasl/sasl.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <ctype.h>
#include <sys/time.h>
#include <stdarg.h>
#include "include/dtsapp.h"
Data Structures
struct sasl_defaults
SASL Paramaters used in authentification.
struct ldap_simple
LDAP Simple bind.
struct ldap_conn
LDAP connection.
struct ldap_modify
LDAP Modify structure.
struct ldap_add
LDAP Add structure.
struct ldap_modval
Linked list of mod values.
struct ldap_modreq
LDAP mod request.
Functions
struct ldap_results * _dtsldapsearch (struct ldap_conn *ldap, const char *base, int scope, const char *filter, char **attrs, int b64enc, int *err)
struct ldap_conn * ldap_connect (const char *uri, enum ldap_starttls starttls, int timelimit, int limit, int debug, int *err)
Connect to a LDAP server.
int ldap_simplebind (struct ldap_conn *ld, const char *dn, const char *passwd)
Bind to the connection with simple bind requireing a distingushed name and password.
int ldap_simplerebind (struct ldap_conn *ldap, const char *initialdn, const char *initialpw, const char *base, const char *filter, const char *uidrdn, const char *uid, const char *passwd)
Bind to LDAP connection using rebind.
int ldap_saslbind (struct ldap_conn *ld, const char *mech, const char *realm, const char *authcid, const char *passwd, const char *authzid)
Bind to the server with SASL.
const char * ldap_errmsg (int res)
Return LDAP error for a ldap error.
struct ldap_results * ldap_search_sub (struct ldap_conn *ld, const char *base, const char *filter, int b64enc, int *res,...)
Search LDAP connection subtree.
struct ldap_results * ldap_search_one (struct ldap_conn *ld, const char *base, const char *filter, int b64enc, int *res,...)
Search LDAP connection one level.
struct ldap_results * ldap_search_base (struct ldap_conn *ld, const char *base, const char *filter, int b64enc, int *res,...)
Search LDAP connection base.
void ldap_unref_attr (struct ldap_entry *entry, struct ldap_attr *attr)
Remove a attribute from a entry.
void ldap_unref_entry (struct ldap_results *results, struct ldap_entry *entry)
Remove a entry from a result.
struct ldap_entry * ldap_getentry (struct ldap_results *results, const char *dn)
Find and return the entry from the results for a specific dn.
struct ldap_attr * ldap_getattr (struct ldap_entry *entry, const char *attr)
Find and return attribute in a entry.
struct ldap_modify * ldap_modifyinit (const char *dn)
Create a modification reference for a DN.
int ldap_mod_del (struct ldap_modify *lmod, const char *attr,...)
Delete values from a attribute.
int ldap_mod_add (struct ldap_modify *lmod, const char *attr,...)
Add values to a attribute.
int ldap_mod_rep (struct ldap_modify *lmod, const char *attr,...)
Replace a attribute.
int ldap_domodify (struct ldap_conn *ld, struct ldap_modify *lmod)
Apply the modification to the server.
int ldap_mod_delattr (struct ldap_conn *ldap, const char *dn, const char *attr, const char *value)
Delete a value from a attribute in a DN.
int ldap_mod_remattr (struct ldap_conn *ldap, const char *dn, const char *attr)
Delete a attribute from a DN.
int ldap_mod_addattr (struct ldap_conn *ldap, const char *dn, const char *attr, const char *value)
Add a value for a attribute in a DN.
int ldap_mod_repattr (struct ldap_conn *ldap, const char *dn, const char *attr, const char *value)
Replace the value of a attribute in a DN.
struct ldap_add * ldap_addinit (const char *dn)
Create a reference to add a new DN.
int ldap_add_attr (struct ldap_add *ladd, const char *attr,...)
Add a attribute to new DN.
int ldap_doadd (struct ldap_conn *ld, struct ldap_add *ladd)
Write new DN to server.
Detailed Description
Openldap/SASL Implementation.
Definition in file openldap.c.
Function Documentation
struct ldap_results * _dtsldapsearch (struct ldap_conn * ldap, const char * base, int scope, const char * filter, char ** attrs, int b64enc, int * err) read
Definition at line 1559 of file openldap.c.
References addtobucket(), ldap_results::count, create_bucketlist(), ldap_results::entries, ldap_results::first_entry, ldap_conn::ldap, ldap_conn::limit, ldap_entry::next, objalloc(), objlock(), objref(), objunlock(), objunref(), ldap_entry::prev, ldap_conn::sctrlsp, and ldap_conn::timelim.
Referenced by ldap_search_base(), ldap_search_one(), and ldap_search_sub().
{
    struct timeval timeout;
    struct ldap_results *results;
    struct ldap_entry *lent, *prev = NULL;
    LDAPMessage *result, *message = NULL;
    int res = LDAP_SUCCESS;
    if (!objref(ldap)) {
        if (err) {
            *err = LDAP_UNAVAILABLE;
        }
        if (attrs) {
            free(attrs);
        }
        return NULL;
    }
    if ((results = objalloc(sizeof(*results), free_result))) {
        results->entries = create_bucketlist(4, searchresults_hash);
    }
    timeout.tv_sec = ldap->timelim;
    timeout.tv_usec = 0;
    objlock(ldap);
    if (!results || !results->entries ||
        (res = ldap_search_ext_s(ldap->ldap, base, scope, filter, attrs, 0, ldap->sctrlsp, NULL, &timeout, ldap->limit, &result))) {
        objunlock(ldap);
        objunref(ldap);
        objunref(results);
        ldap_msgfree(result);
        if (err) {
            *err = (!results || !results->entries) ? LDAP_NO_MEMORY : res;
        }
        if (attrs) {
            free(attrs);
        }
        return NULL;
    }
    objunlock(ldap);
    if (attrs) {
        free(attrs);
    }
    if ((results->count = ldap_count(ldap->ldap, result, err)) < 0) {
        objunref(ldap);
        objunref(results);
        ldap_msgfree(result);
        return NULL;
    }
    while((lent = ldap_getent(ldap->ldap, &message, result, b64enc, err))) {
        if (!results->first_entry) {
            results->first_entry = lent;
        }
        if (!addtobucket(results->entries, lent)) {
            res = LDAP_NO_MEMORY;
            objunref(lent);
            break;
        }
        lent->next = NULL;
        if (prev) {
            prev->next = lent;
            lent->prev = prev;
        } else {
            lent->prev = NULL;
        }
        prev = lent;
        objunref(lent);
    }
    ldap_msgfree(result);
    if (err) {
        *err = res;
    }
    if (res) {
        objunref(results);
        results = NULL;
    }
    objunref(ldap);
    return results;
}