DTS Application Library: src/libnetlink/include/rt_names.h File Reference
rt_names.h File Reference
#include <asm/types.h>
Functions
char * rtnl_rtprot_n2a (int id, char *buf, int len)
char * rtnl_rtscope_n2a (int id, char *buf, int len)
char * rtnl_rttable_n2a (__u32 id, char *buf, int len)
char * rtnl_rtrealm_n2a (int id, char *buf, int len)
char * rtnl_dsfield_n2a (int id, char *buf, int len)
int rtnl_rtprot_a2n (__u32 *id, char *arg)
int rtnl_rtscope_a2n (__u32 *id, char *arg)
int rtnl_rttable_a2n (__u32 *id, char *arg)
int rtnl_rtrealm_a2n (__u32 *id, char *arg)
int rtnl_dsfield_a2n (__u32 *id, char *arg)
int rtnl_group_a2n (int *id, char *arg)
const char * inet_proto_n2a (int proto, char *buf, int len)
int inet_proto_a2n (char *buf)
const char * ll_type_n2a (int type, char *buf, int len)
const char * ll_addr_n2a (unsigned char *addr, int alen, int type, char *buf, int blen)
int ll_addr_a2n (char *lladdr, int len, char *arg)
const char * ll_proto_n2a (unsigned short id, char *buf, int len)
int ll_proto_a2n (unsigned short *id, char *buf)
Function Documentation
int inet_proto_a2n (char * buf)
Definition at line 45 of file inet_proto.c.
References get_u8().
{
    static char ncache[16];
    static int icache = -1;
    struct protoent *pe;
    if (icache>=0 && strcmp(ncache, buf) == 0) {
        return icache;
    }
    if (buf[0] >= '0' && buf[0] <= '9') {
        __u8 ret;
        if (get_u8(&ret, buf, 10)) {
            return -1;
        }
        return ret;
    }
    pe = getprotobyname(buf);
    if (pe) {
        icache = pe->p_proto;
        strncpy(ncache, pe->p_name, 16);
        return pe->p_proto;
    }
    return -1;
}
const char* inet_proto_n2a (int proto, char * buf, int len)
Definition at line 25 of file inet_proto.c.
{
    static char ncache[16];
    static int icache = -1;
    struct protoent *pe;
    if (proto == icache) {
        return ncache;
    }
    pe = getprotobynumber(proto);
    if (pe) {
        icache = proto;
        strncpy(ncache, pe->p_name, 16);
        strncpy(buf, pe->p_name, len);
        return buf;
    }
    snprintf(buf, len, "ipproto-%d", proto);
    return buf;
}
int ll_addr_a2n (char * lladdr, int len, char * arg)
Definition at line 59 of file ll_addr.c.
References inet_prefix::data, and get_addr_1().
{
    if (strchr(arg, '.')) {
        inet_prefix pfx;
        if (get_addr_1(&pfx, arg, AF_INET)) {
            fprintf(stderr, "\"%s\" is invalid lladdr.\n", arg);
            return -1;
        }
        if (len < 4) {
            return -1;
        }
        memcpy(lladdr, pfx.data, 4);
        return 4;
    } else {
        int i;
        for (i=0; i<len; i++) {
            int temp;
            char *cp = strchr(arg, ':');
            if (cp) {
                *cp = 0;
                cp++;
            }
            if (sscanf(arg, "%x", &temp) != 1) {
                fprintf(stderr, "\"%s\" is invalid lladdr.\n", arg);
                return -1;
            }
            if (temp < 0 || temp > 255) {
                fprintf(stderr, "\"%s\" is invalid lladdr.\n", arg);
                return -1;
            }
            lladdr[i] = temp;
            if (!cp) {
                break;
            }
            arg = cp;
        }
        return i+1;
    }
}
const char* ll_addr_n2a (unsigned char * addr, int alen, int type, char * buf, int blen)
Definition at line 32 of file ll_addr.c.
{
    int i;
    int l;
    if (alen == 4 &&
            (type == ARPHRD_TUNNEL || type == ARPHRD_SIT || type == ARPHRD_IPGRE)) {
        return inet_ntop(AF_INET, addr, buf, blen);
    }
    if (alen == 16 && type == ARPHRD_TUNNEL6) {
        return inet_ntop(AF_INET6, addr, buf, blen);
    }
    l = 0;
    for (i=0; i<alen; i++) {
        if (i==0) {
            snprintf(buf+l, blen, "%02x", addr[i]);
            blen -= 2;
            l += 2;
        } else {
            snprintf(buf+l, blen, ":%02x", addr[i]);
            blen -= 3;
            l += 3;
        }
    }
    return buf;
}
int ll_proto_a2n (unsigned short * id, char * buf)
Definition at line 103 of file ll_proto.c.
References get_u16(), and name.
{
    int i;
    for (i=0; i<sizeof(llproto_names)/sizeof(llproto_names[0]); i++) {
        if (strcasecmp(llproto_names[i].name, buf) == 0) {
            *id = htons(llproto_names[i].id);
            return 0;
        }
    }
    if (get_u16(id, buf, 0)) {
        return -1;
    }
    *id = htons(*id);
    return 0;
}
const char* ll_proto_n2a (unsigned short id, char * buf, int len)
Definition at line 89 of file ll_proto.c.
{
    int i;
    id = ntohs(id);
    for (i=0; i<sizeof(llproto_names)/sizeof(llproto_names[0]); i++) {
        if (llproto_names[i].id == id) {
            return llproto_names[i].name;
        }
    }
    snprintf(buf, len, "[%d]", id);
    return buf;
}
const char* ll_type_n2a (int type, char * buf, int len)
Definition at line 30 of file ll_types.c.
References __PF, and name.
{
#define __PF(f,n) { ARPHRD_##f, #n },
    static const struct {
        int type;
        const char *name;
    } arphrd_names[] = {
        { 0, "generic" },
        __PF(ETHER,ether)
        __PF(EETHER,eether)
        __PF(AX25,ax25)
        __PF(PRONET,pronet)
        __PF(CHAOS,chaos)
        __PF(IEEE802,ieee802)
        __PF(ARCNET,arcnet)
        __PF(APPLETLK,atalk)
        __PF(DLCI,dlci)
        __PF(ATM,atm)
        __PF(METRICOM,metricom)
        __PF(IEEE1394,ieee1394)
        __PF(INFINIBAND,infiniband)
        __PF(SLIP,slip)
        __PF(CSLIP,cslip)
        __PF(SLIP6,slip6)
        __PF(CSLIP6,cslip6)
        __PF(RSRVD,rsrvd)
        __PF(ADAPT,adapt)
        __PF(ROSE,rose)
        __PF(X25,x25)
        __PF(HWX25,hwx25)
        __PF(CAN,can)
        __PF(PPP,ppp)
        __PF(HDLC,hdlc)
        __PF(LAPB,lapb)
        __PF(DDCMP,ddcmp)
        __PF(RAWHDLC,rawhdlc)
        __PF(TUNNEL,ipip)
        __PF(TUNNEL6,tunnel6)
        __PF(FRAD,frad)
        __PF(SKIP,skip)
        __PF(LOOPBACK,loopback)
        __PF(LOCALTLK,ltalk)
        __PF(FDDI,fddi)
        __PF(BIF,bif)
        __PF(SIT,sit)
        __PF(IPDDP,ip/ddp)
        __PF(IPGRE,gre)
        __PF(PIMREG,pimreg)
        __PF(HIPPI,hippi)
        __PF(ASH,ash)
        __PF(ECONET,econet)
        __PF(IRDA,irda)
        __PF(FCPP,fcpp)
        __PF(FCAL,fcal)
        __PF(FCPL,fcpl)
        __PF(FCFABRIC,fcfb0)
        __PF(FCFABRIC+1,fcfb1)
        __PF(FCFABRIC+2,fcfb2)
        __PF(FCFABRIC+3,fcfb3)
        __PF(FCFABRIC+4,fcfb4)
        __PF(FCFABRIC+5,fcfb5)
        __PF(FCFABRIC+6,fcfb6)
        __PF(FCFABRIC+7,fcfb7)
        __PF(FCFABRIC+8,fcfb8)
        __PF(FCFABRIC+9,fcfb9)
        __PF(FCFABRIC+10,fcfb10)
        __PF(FCFABRIC+11,fcfb11)
        __PF(FCFABRIC+12,fcfb12)
        __PF(IEEE802_TR,tr)
        __PF(IEEE80211,ieee802.11)
        __PF(IEEE80211_PRISM,ieee802.11/prism)
        __PF(IEEE80211_RADIOTAP,ieee802.11/radiotap)
        __PF(IEEE802154, ieee802.15.4)
        __PF(PHONET, phonet)
        __PF(PHONET_PIPE, phonet_pipe)
        __PF(CAIF, caif)
        __PF(NONE, none)
        __PF(VOID,void)
    };
#undef __PF
    int i;
    for (i=0; i<sizeof(arphrd_names)/sizeof(arphrd_names[0]); i++) {
        if (arphrd_names[i].type == type) {
            return arphrd_names[i].name;
        }
    }
    snprintf(buf, len, "[%d]", type);
    return buf;
}
int rtnl_dsfield_a2n (__u32 * id, char * arg)
Definition at line 436 of file rt_names.c.
{
    static char *cache = NULL;
    static unsigned long res;
    char *end;
    int i;
    if (cache && strcmp(cache, arg) == 0) {
        *id = res;
        return 0;
    }
    if (!rtnl_rtdsfield_init) {
        rtnl_rtdsfield_initialize();
    }
    for (i=0; i<256; i++) {
        if (rtnl_rtdsfield_tab[i] &&
                strcmp(rtnl_rtdsfield_tab[i], arg) == 0) {
            cache = rtnl_rtdsfield_tab[i];
            res = i;
            *id = res;
            return 0;
        }
    }
    res = strtoul(arg, &end, 16);
    if (!end || end == arg || *end || res > 255) {
        return -1;
    }
    *id = res;
    return 0;
}
char* rtnl_dsfield_n2a (int id, char * buf, int len)
Definition at line 418 of file rt_names.c.
References id.
{
    if (id<0 || id>=256) {
        snprintf(buf, len, "%d", id);
        return buf;
    }
    if (!rtnl_rtdsfield_tab[id]) {
        if (!rtnl_rtdsfield_init) {
            rtnl_rtdsfield_initialize();
        }
    }
    if (rtnl_rtdsfield_tab[id]) {
        return rtnl_rtdsfield_tab[id];
    }
    snprintf(buf, len, "0x%02x", id);
    return buf;
}
int rtnl_group_a2n (int * id, char * arg)
Definition at line 484 of file rt_names.c.
References rtnl_hash_entry::id, rtnl_hash_entry::name, and rtnl_hash_entry::next.
{
    static char *cache = NULL;
    static unsigned long res;
    struct rtnl_hash_entry *entry;
    char *end;
    int i;
    if (cache && strcmp(cache, arg) == 0) {
        *id = res;
        return 0;
    }
    if (!rtnl_group_init) {
        rtnl_group_initialize();
    }
    for (i=0; i<256; i++) {
        entry = rtnl_group_hash[i];
        while (entry && strcmp(entry->name, arg)) {
            entry = entry->next;
        }
        if (entry) {
            cache = entry->name;
            res = entry->id;
            *id = res;
            return 0;
        }
    }
    i = strtol(arg, &end, 0);
    if (!end || end == arg || *end || i < 0) {
        return -1;
    }
    *id = i;
    return 0;
}
int rtnl_rtprot_a2n (__u32 * id, char * arg)
Definition at line 162 of file rt_names.c.
{
    static char *cache = NULL;
    static unsigned long res;
    char *end;
    int i;
    if (cache && strcmp(cache, arg) == 0) {
        *id = res;
        return 0;
    }
    if (!rtnl_rtprot_init) {
        rtnl_rtprot_initialize();
    }
    for (i=0; i<256; i++) {
        if (rtnl_rtprot_tab[i] &&
                strcmp(rtnl_rtprot_tab[i], arg) == 0) {
            cache = rtnl_rtprot_tab[i];
            res = i;
            *id = res;
            return 0;
        }
    }
    res = strtoul(arg, &end, 0);
    if (!end || end == arg || *end || res > 255) {
        return -1;
    }
    *id = res;
    return 0;
}
char* rtnl_rtprot_n2a (int id, char * buf, int len)
Definition at line 145 of file rt_names.c.
References id.
{
    if (id<0 || id>=256) {
        snprintf(buf, len, "%d", id);
        return buf;
    }
    if (!rtnl_rtprot_tab[id]) {
        if (!rtnl_rtprot_init) {
            rtnl_rtprot_initialize();
        }
    }
    if (rtnl_rtprot_tab[id]) {
        return rtnl_rtprot_tab[id];
    }
    snprintf(buf, len, "%d", id);
    return buf;
}
int rtnl_rtrealm_a2n (__u32 * id, char * arg)
Definition at line 295 of file rt_names.c.
{
    static char *cache = NULL;
    static unsigned long res;
    char *end;
    int i;
    if (cache && strcmp(cache, arg) == 0) {
        *id = res;
        return 0;
    }
    if (!rtnl_rtrealm_init) {
        rtnl_rtrealm_initialize();
    }
    for (i=0; i<256; i++) {
        if (rtnl_rtrealm_tab[i] &&
                strcmp(rtnl_rtrealm_tab[i], arg) == 0) {
            cache = rtnl_rtrealm_tab[i];
            res = i;
            *id = res;
            return 0;
        }
    }
    res = strtoul(arg, &end, 0);
    if (!end || end == arg || *end || res > 255) {
        return -1;
    }
    *id = res;
    return 0;
}
char* rtnl_rtrealm_n2a (int id, char * buf, int len)
Definition at line 277 of file rt_names.c.
References id.
{
    if (id<0 || id>=256) {
        snprintf(buf, len, "%d", id);
        return buf;
    }
    if (!rtnl_rtrealm_tab[id]) {
        if (!rtnl_rtrealm_init) {
            rtnl_rtrealm_initialize();
        }
    }
    if (rtnl_rtrealm_tab[id]) {
        return rtnl_rtrealm_tab[id];
    }
    snprintf(buf, len, "%d", id);
    return buf;
}
int rtnl_rtscope_a2n (__u32 * id, char * arg)
Definition at line 230 of file rt_names.c.
{
    static char *cache = NULL;
    static unsigned long res;
    char *end;
    int i;
    if (cache && strcmp(cache, arg) == 0) {
        *id = res;
        return 0;
    }
    if (!rtnl_rtscope_init) {
        rtnl_rtscope_initialize();
    }
    for (i=0; i<256; i++) {
        if (rtnl_rtscope_tab[i] &&
                strcmp(rtnl_rtscope_tab[i], arg) == 0) {
            cache = rtnl_rtscope_tab[i];
            res = i;
            *id = res;
            return 0;
        }
    }
    res = strtoul(arg, &end, 0);
    if (!end || end == arg || *end || res > 255) {
        return -1;
    }
    *id = res;
    return 0;
}
char* rtnl_rtscope_n2a (int id, char * buf, int len)
Definition at line 213 of file rt_names.c.
References id.
{
    if (id<0 || id>=256) {
        snprintf(buf, len, "%d", id);
        return buf;
    }
    if (!rtnl_rtscope_tab[id]) {
        if (!rtnl_rtscope_init) {
            rtnl_rtscope_initialize();
        }
    }
    if (rtnl_rtscope_tab[id]) {
        return rtnl_rtscope_tab[id];
    }
    snprintf(buf, len, "%d", id);
    return buf;
}
int rtnl_rttable_a2n (__u32 * id, char * arg)
Definition at line 368 of file rt_names.c.
References rtnl_hash_entry::id, rtnl_hash_entry::name, and rtnl_hash_entry::next.
{
    static char *cache = NULL;
    static unsigned long res;
    struct rtnl_hash_entry *entry;
    char *end;
    __u32 i;
    if (cache && strcmp(cache, arg) == 0) {
        *id = res;
        return 0;
    }
    if (!rtnl_rttable_init) {
        rtnl_rttable_initialize();
    }
    for (i=0; i<256; i++) {
        entry = rtnl_rttable_hash[i];
        while (entry && strcmp(entry->name, arg)) {
            entry = entry->next;
        }
        if (entry) {
            cache = entry->name;
            res = entry->id;
            *id = res;
            return 0;
        }
    }
    i = strtoul(arg, &end, 0);
    if (!end || end == arg || *end || i > RT_TABLE_MAX) {
        return -1;
    }
    *id = i;
    return 0;
}
char* rtnl_rttable_n2a (__u32 id, char * buf, int len)
Definition at line 347 of file rt_names.c.
References rtnl_hash_entry::id, rtnl_hash_entry::name, and rtnl_hash_entry::next.
{
    struct rtnl_hash_entry *entry;
    if (id > RT_TABLE_MAX) {
        snprintf(buf, len, "%u", id);
        return buf;
    }
    if (!rtnl_rttable_init) {
        rtnl_rttable_initialize();
    }
    entry = rtnl_rttable_hash[id & 255];
    while (entry && entry->id != id) {
        entry = entry->next;
    }
    if (entry) {
        return entry->name;
    }
    snprintf(buf, len, "%u", id);
    return buf;
}