DTS Application Library: src/libnetlink/include/utils.h File Reference
utils.h File Reference
#include <asm/types.h>
#include <resolv.h>
#include <stdlib.h>
#include "libnetlink.h"
#include "ll_map.h"
#include "rtm_map.h"
Data Structures
struct inet_prefix
struct dn_naddr
struct ipx_addr
Macros
#define IPPROTO_ESP 50
#define IPPROTO_AH 51
#define IPPROTO_COMP 108
#define IPSEC_PROTO_ANY 255
#define SPRINT_BSIZE 64
#define SPRINT_BUF(x) char x[SPRINT_BSIZE]
#define NEXT_ARG() do { argv++; if (--argc <= 0) incomplete_command(); } while(0)
#define NEXT_ARG_OK() (argc - 1 > 0)
#define PREV_ARG() do { argv--; argc++; } while(0)
#define PREFIXLEN_SPECIFIED 1
#define DN_MAXADDL 20
#define AF_DECnet 12
#define IPX_NODE_LEN 6
#define get_byte get_u8
#define get_ushort get_u16
#define get_short get_s16
#define ARRAY_SIZE(x) (sizeof(x) / sizeof((x)[0]))
Functions
void incomplete_command (void) __attribute__((noreturn))
__u32 get_addr32 (const char *name)
int get_addr_1 (inet_prefix *dst, const char *arg, int family)
int get_prefix_1 (inet_prefix *dst, char *arg, int family)
int get_addr (inet_prefix *dst, const char *arg, int family)
int get_prefix (inet_prefix *dst, char *arg, int family)
int mask2bits (__u32 netmask)
int get_integer (int *val, const char *arg, int base)
int get_unsigned (unsigned *val, const char *arg, int base)
int get_time_rtt (unsigned *val, const char *arg, int *raw)
int get_u64 (__u64 *val, const char *arg, int base)
int get_u32 (__u32 *val, const char *arg, int base)
int get_s32 (__s32 *val, const char *arg, int base)
int get_u16 (__u16 *val, const char *arg, int base)
int get_s16 (__s16 *val, const char *arg, int base)
int get_u8 (__u8 *val, const char *arg, int base)
int get_s8 (__s8 *val, const char *arg, int base)
char * hexstring_n2a (const __u8 *str, int len, char *buf, int blen)
__u8 * hexstring_a2n (const char *str, __u8 *buf, int blen)
const char * format_host (int af, int len, const void *addr, char *buf, int buflen)
const char * rt_addr_n2a (int af, int len, const void *addr, char *buf, int buflen)
void missarg (const char *) __attribute__((noreturn))
void invarg (const char *, const char *) __attribute__((noreturn))
void duparg (const char *, const char *) __attribute__((noreturn))
void duparg2 (const char *, const char *) __attribute__((noreturn))
int matches (const char *arg, const char *pattern)
int inet_addr_match (const inet_prefix *a, const inet_prefix *b, int bits)
const char * dnet_ntop (int af, const void *addr, char *str, size_t len)
int dnet_pton (int af, const char *src, void *addr)
const char * ipx_ntop (int af, const void *addr, char *str, size_t len)
int ipx_pton (int af, const char *src, void *addr)
int __get_hz (void)
int __get_user_hz (void)
int print_timestamp (FILE *fp)
ssize_t getcmdline (char **line, size_t *len, FILE *in)
int makeargs (char *line, char *argv[], int maxargs)
int iplink_parse (int argc, char **argv, struct iplink_req *req, char **name, char **type, char **link, char **dev, int *group)
Variables
int preferred_family
int show_stats
int show_details
int show_raw
int resolve_hosts
int oneline
int timestamp
char * _SL_
int max_flush_loops
int __iproute2_hz_internal
int __iproute2_user_hz_internal
int cmdlineno
Macro Definition Documentation
#define AF_DECnet 12
Definition at line 56 of file utils.h.
Referenced by dnet_ntop(), dnet_pton(), format_host(), get_addr_1(), get_prefix_1(), and rt_addr_n2a().
#define ARRAY_SIZE (x) (sizeof(x) / sizeof((x)[0]))
Definition at line 144 of file utils.h.
#define DN_MAXADDL 20
Definition at line 54 of file utils.h.
#define get_byte get_u8
Definition at line 81 of file utils.h.
#define get_short get_s16
Definition at line 83 of file utils.h.
#define get_ushort get_u16
Definition at line 82 of file utils.h.
#define IPPROTO_AH 51
Definition at line 26 of file utils.h.
#define IPPROTO_COMP 108
Definition at line 29 of file utils.h.
#define IPPROTO_ESP 50
Definition at line 23 of file utils.h.
#define IPSEC_PROTO_ANY 255
Definition at line 32 of file utils.h.
#define IPX_NODE_LEN 6
Definition at line 64 of file utils.h.
#define NEXT_ARG () do { argv++; if (--argc <= 0) incomplete_command(); } while(0)
Definition at line 40 of file utils.h.
#define NEXT_ARG_OK () (argc - 1 > 0)
Definition at line 41 of file utils.h.
#define PREFIXLEN_SPECIFIED 1
Definition at line 52 of file utils.h.
Referenced by get_prefix_1().
#define PREV_ARG () do { argv--; argc++; } while(0)
Definition at line 42 of file utils.h.
#define SPRINT_BSIZE 64
Definition at line 35 of file utils.h.
#define SPRINT_BUF (x) char x[SPRINT_BSIZE]
Definition at line 36 of file utils.h.
Function Documentation
int __get_hz (void)
Definition at line 502 of file utils.c.
References name.
                   {
    char name[1024];
    int hz = 0;
    FILE *fp;
    if (getenv("HZ")) {
        return atoi(getenv("HZ")) ? : HZ;
    }
    if (getenv("PROC_NET_PSCHED")) {
        snprintf(name, sizeof(name)-1, "%s", getenv("PROC_NET_PSCHED"));
    } else
        if (getenv("PROC_ROOT")) {
            snprintf(name, sizeof(name)-1, "%s/net/psched", getenv("PROC_ROOT"));
        } else {
            strcpy(name, "/proc/net/psched");
        }
    fp = fopen(name, "r");
    if (fp) {
        unsigned nom, denom;
        if (fscanf(fp, "%*08x%*08x%08x%08x", &nom, &denom) == 2)
            if (nom == 1000000) {
                hz = denom;
            }
        fclose(fp);
    }
    if (hz) {
        return hz;
    }
    return HZ;
}
int __get_user_hz (void)
Definition at line 537 of file utils.c.
{
    return sysconf(_SC_CLK_TCK);
}
const char* dnet_ntop (int af, const void * addr, char * str, size_t len)
Definition at line 97 of file dnet_ntop.c.
References AF_DECnet.
Referenced by rt_addr_n2a().
{
    switch(af) {
        case AF_DECnet:
            errno = 0;
            return dnet_ntop1((struct dn_naddr *)addr, str, len);
        default
                :
            errno = EAFNOSUPPORT;
    }
    return NULL;
}
int dnet_pton (int af, const char * src, void * addr)
Definition at line 59 of file dnet_pton.c.
References AF_DECnet.
Referenced by get_addr_1().
{
    int err;
    switch (af) {
        case AF_DECnet:
            errno = 0;
            err = dnet_pton1(src, (struct dn_naddr *)addr);
            break;
        default
                :
            errno = EAFNOSUPPORT;
            err = -1;
    }
    return err;
}
void duparg (const char * , const char *)
Definition at line 453 of file utils.c.
{
    fprintf(stderr, "Error: duplicate \"%s\": \"%s\" is the second value.\n", key, arg);
    exit(-1);
}
void duparg2 (const char * , const char *)
Definition at line 458 of file utils.c.
{
    fprintf(stderr, "Error: either \"%s\" is duplicate, or \"%s\" is a garbage.\n", key, arg);
    exit(-1);
}
const char* format_host (int af, int len, const void * addr, char * buf, int buflen)
Definition at line 616 of file utils.c.
References AF_DECnet, resolve_hosts, and rt_addr_n2a().
{
#ifdef RESOLVE_HOSTNAMES
    if (resolve_hosts) {
        const char *n;
        if (len <= 0) {
            switch (af) {
                case AF_INET:
                    len = 4;
                    break;
                case AF_INET6:
                    len = 16;
                    break;
                case AF_IPX:
                    len = 10;
                    break;
#ifdef AF_DECnet
                    /* I see no reasons why gethostbyname
                       may not work for DECnet */
                case AF_DECnet:
                    len = 2;
                    break;
#endif
                default
                        :
                    ;
            }
        }
        if (len > 0 &&
                (n = resolve_address(addr, len, af)) != NULL) {
            return n;
        }
    }
#endif
    return rt_addr_n2a(af, len, addr, buf, buflen);
}
int get_addr (inet_prefix * dst, const char * arg, int family)
Definition at line 405 of file utils.c.
References get_addr_1().
{
    if (family == AF_PACKET) {
        fprintf(stderr, "Error: \"%s\" may be inet address, but it is not allowed in this context.\n", arg);
        exit(1);
    }
    if (get_addr_1(dst, arg, family)) {
        fprintf(stderr, "Error: an inet address is expected rather than \"%s\".\n", arg);
        exit(1);
    }
    return 0;
}
__u32 get_addr32 (const char * name)
Definition at line 429 of file utils.c.
References inet_prefix::data, and get_addr_1().
{
    inet_prefix addr;
    if (get_addr_1(&addr, name, AF_INET)) {
        fprintf(stderr, "Error: an IP address is expected rather than \"%s\"\n", name);
        exit(1);
    }
    return addr.data[0];
}
int get_addr_1 (inet_prefix * dst, const char * arg, int family)
Definition at line 296 of file utils.c.
References dn_naddr::a_addr, AF_DECnet, inet_prefix::bitlen, inet_prefix::bytelen, inet_prefix::data, dnet_pton(), and inet_prefix::family.
Referenced by get_addr(), get_addr32(), get_prefix_1(), and ll_addr_a2n().
{
    memset(addr, 0, sizeof(*addr));
    if (strcmp(name, "default") == 0 ||
            strcmp(name, "all") == 0 ||
            strcmp(name, "any") == 0) {
        if (family == AF_DECnet) {
            return -1;
        }
        addr->family = family;
        addr->bytelen = (family == AF_INET6 ? 16 : 4);
        addr->bitlen = -1;
        return 0;
    }
    if (strchr(name, ':')) {
        addr->family = AF_INET6;
        if (family != AF_UNSPEC && family != AF_INET6) {
            return -1;
        }
        if (inet_pton(AF_INET6, name, addr->data) <= 0) {
            return -1;
        }
        addr->bytelen = 16;
        addr->bitlen = -1;
        return 0;
    }
    if (family == AF_DECnet) {
        struct dn_naddr dna;
        addr->family = AF_DECnet;
        if (dnet_pton(AF_DECnet, name, &dna) <= 0) {
            return -1;
        }
        memcpy(addr->data, dna.a_addr, 2);
        addr->bytelen = 2;
        addr->bitlen = -1;
        return 0;
    }
    addr->family = AF_INET;
    if (family != AF_UNSPEC && family != AF_INET) {
        return -1;
    }
    if (get_addr_ipv4((__u8 *)addr->data, name) <= 0) {
        return -1;
    }
    addr->bytelen = 4;
    addr->bitlen = -1;
    return 0;
}
int get_integer (int * val, const char * arg, int base)
Definition at line 33 of file utils.c.
{
    long res;
    char *ptr;
    if (!arg || !*arg) {
        return -1;
    }
    res = strtol(arg, &ptr, base);
    if (!ptr || ptr == arg || *ptr || res > INT_MAX || res < INT_MIN) {
        return -1;
    }
    *val = res;
    return 0;
}
int get_prefix (inet_prefix * dst, char * arg, int family)
Definition at line 417 of file utils.c.
References get_prefix_1().
Referenced by set_interface_ipaddr().
{
    if (family == AF_PACKET) {
        fprintf(stderr, "Error: \"%s\" may be inet prefix, but it is not allowed in this context.\n", arg);
        exit(1);
    }
    if (get_prefix_1(dst, arg, family)) {
        fprintf(stderr, "Error: an inet prefix is expected rather than \"%s\".\n", arg);
        exit(1);
    }
    return 0;
}
int get_prefix_1 (inet_prefix * dst, char * arg, int family)
Definition at line 350 of file utils.c.
References AF_DECnet, inet_prefix::bitlen, inet_prefix::bytelen, inet_prefix::family, inet_prefix::flags, get_addr_1(), and PREFIXLEN_SPECIFIED.
Referenced by get_prefix().
{
    int err;
    unsigned plen;
    char *slash;
    memset(dst, 0, sizeof(*dst));
    if (strcmp(arg, "default") == 0 ||
            strcmp(arg, "any") == 0 ||
            strcmp(arg, "all") == 0) {
        if (family == AF_DECnet) {
            return -1;
        }
        dst->family = family;
        dst->bytelen = 0;
        dst->bitlen = 0;
        return 0;
    }
    slash = strchr(arg, '/');
    if (slash) {
        *slash = 0;
    }
    err = get_addr_1(dst, arg, family);
    if (err == 0) {
        switch(dst->family) {
            case AF_INET6:
                dst->bitlen = 128;
                break;
            case AF_DECnet:
                dst->bitlen = 16;
                break;
            default
                    :
            case AF_INET:
                dst->bitlen = 32;
        }
        if (slash) {
            if (get_netmask(&plen, slash+1, 0)
                    || plen > dst->bitlen) {
                err = -1;
                goto done;
            }
            dst->flags |= PREFIXLEN_SPECIFIED;
            dst->bitlen = plen;
        }
    }
done:
    if (slash) {
        *slash = '/';
    }
    return err;
}
int get_s16 (__s16 * val, const char * arg, int base)
Definition at line 232 of file utils.c.
{
    long res;
    char *ptr;
    if (!arg || !*arg) {
        return -1;
    }
    res = strtol(arg, &ptr, base);
    if (!ptr || ptr == arg || *ptr || res > 0x7FFF || res < -0x8000) {
        return -1;
    }
    *val = res;
    return 0;
}
int get_s32 (__s32 * val, const char * arg, int base)
Definition at line 213 of file utils.c.
{
    long res;
    char *ptr;
    errno = 0;
    if (!arg || !*arg) {
        return -1;
    }
    res = strtol(arg, &ptr, base);
    if (ptr == arg || *ptr ||
            ((res ==  LONG_MIN || res == LONG_MAX) && errno == ERANGE) ||
            res > INT32_MAX || res < INT32_MIN) {
        return -1;
    }
    *val = res;
    return 0;
}
int get_s8 (__s8 * val, const char * arg, int base)
Definition at line 247 of file utils.c.
{
    long res;
    char *ptr;
    if (!arg || !*arg) {
        return -1;
    }
    res = strtol(arg, &ptr, base);
    if (!ptr || ptr == arg || *ptr || res > 0x7F || res < -0x80) {
        return -1;
    }
    *val = res;
    return 0;
}
int get_time_rtt (unsigned * val, const char * arg, int * raw)
Definition at line 106 of file utils.c.
{
    double t;
    unsigned long res;
    char *p;
    if (strchr(arg,'.') != NULL) {
        t = strtod(arg,&p);
        if (t < 0.0) {
            return -1;
        }
    } else {
        res = strtoul(arg, &p, 0);
        if (res > UINT_MAX) {
            return -1;
        }
        t = (double)res;
    }
    if (p == arg) {
        return -1;
    }
    *raw = 1;
    if (*p) {
        *raw = 0;
        if (strcasecmp(p, "s") == 0 || strcasecmp(p, "sec")==0 ||
                strcasecmp(p, "secs")==0) {
            t *= 1000;
        } else
            if (strcasecmp(p, "ms") == 0 || strcasecmp(p, "msec")==0 ||
                    strcasecmp(p, "msecs") == 0) {
                t *= 1.0;    /* allow suffix, do nothing */
            } else {
                return -1;
            }
    }
    /* emulate ceil() without having to bring-in -lm and always be >= 1 */
    *val = t;
    if (*val < t) {
        *val += 1;
    }
    return 0;
}
int get_u16 (__u16 * val, const char * arg, int base)
Definition at line 183 of file utils.c.
Referenced by ll_proto_a2n().
{
    unsigned long res;
    char *ptr;
    if (!arg || !*arg) {
        return -1;
    }
    res = strtoul(arg, &ptr, base);
    if (!ptr || ptr == arg || *ptr || res > 0xFFFF) {
        return -1;
    }
    *val = res;
    return 0;
}
int get_u32 (__u32 * val, const char * arg, int base)
Definition at line 168 of file utils.c.
{
    unsigned long res;
    char *ptr;
    if (!arg || !*arg) {
        return -1;
    }
    res = strtoul(arg, &ptr, base);
    if (!ptr || ptr == arg || *ptr || res > 0xFFFFFFFFUL) {
        return -1;
    }
    *val = res;
    return 0;
}
int get_u64 (__u64 * val, const char * arg, int base)
Definition at line 153 of file utils.c.
{
    unsigned long long res;
    char *ptr;
    if (!arg || !*arg) {
        return -1;
    }
    res = strtoull(arg, &ptr, base);
    if (!ptr || ptr == arg || *ptr || res == 0xFFFFFFFFULL) {
        return -1;
    }
    *val = res;
    return 0;
}
int get_u8 (__u8 * val, const char * arg, int base)
Definition at line 198 of file utils.c.
Referenced by inet_proto_a2n().
{
    unsigned long res;
    char *ptr;
    if (!arg || !*arg) {
        return -1;
    }
    res = strtoul(arg, &ptr, base);
    if (!ptr || ptr == arg || *ptr || res > 0xFF) {
        return -1;
    }
    *val = res;
    return 0;
}
int get_unsigned (unsigned * val, const char * arg, int base)
Definition at line 84 of file utils.c.
{
    unsigned long res;
    char *ptr;
    if (!arg || !*arg) {
        return -1;
    }
    res = strtoul(arg, &ptr, base);
    if (!ptr || ptr == arg || *ptr || res > UINT_MAX) {
        return -1;
    }
    *val = res;
    return 0;
}
ssize_t getcmdline (char ** line, size_t * len, FILE * in)
Definition at line 733 of file utils.c.
References cmdlineno.
{
    ssize_t cc;
    char *cp;
    if ((cc = getline(linep, lenp, in)) < 0) {
        return cc;    /* eof or error */
    }
    ++cmdlineno;
    cp = strchr(*linep, '#');
    if (cp) {
        *cp = '\0';
    }
    while ((cp = strstr(*linep, "\\\n")) != NULL) {
        char *line1 = NULL;
        size_t len1 = 0;
        ssize_t cc1;
        if ((cc1 = getline(&line1, &len1, in)) < 0) {
            fprintf(stderr, "Missing continuation line\n");
            return cc1;
        }
        ++cmdlineno;
        *cp = 0;
        cp = strchr(line1, '#');
        if (cp) {
            *cp = '\0';
        }
        *lenp = strlen(*linep) + strlen(line1) + 1;
        *linep = realloc(*linep, *lenp);
        if (!*linep) {
            fprintf(stderr, "Out of memory\n");
            *lenp = 0;
            return -1;
        }
        cc += cc1 - 2;
        strcat(*linep, line1);
        free(line1);
    }
    return cc;
}
__u8* hexstring_a2n (const char * str, __u8 * buf, int blen)
Definition at line 674 of file utils.c.
{
    int cnt = 0;
    for (;;) {
        unsigned acc;
        char ch;
        acc = 0;
        while ((ch = *str) != ':' && ch != 0) {
            if (ch >= '0' && ch <= '9') {
                ch -= '0';
            } else
                if (ch >= 'a' && ch <= 'f') {
                    ch -= 'a'-10;
                } else
                    if (ch >= 'A' && ch <= 'F') {
                        ch -= 'A'-10;
                    } else {
                        return NULL;
                    }
            acc = (acc<<4) + ch;
            str++;
        }
        if (acc > 255) {
            return NULL;
        }
        if (cnt < blen) {
            buf[cnt] = acc;
            cnt++;
        }
        if (ch == 0) {
            break;
        }
        ++str;
    }
    if (cnt < blen) {
        memset(buf+cnt, 0, blen-cnt);
    }
    return buf;
}
char* hexstring_n2a (const __u8 * str, int len, char * buf, int blen)
Definition at line 655 of file utils.c.
{
    char *ptr = buf;
    int i;
    for (i=0; i<len; i++) {
        if (blen < 3) {
            break;
        }
        sprintf(ptr, "%02x", str[i]);
        ptr += 2;
        blen -= 2;
        if (i != len-1 && blen > 1) {
            *ptr++ = ':';
            blen--;
        }
    }
    return buf;
}
void incomplete_command (void)
Definition at line 438 of file utils.c.
{
    fprintf(stderr, "Command line is not complete. Try option \"help\"\n");
    exit(-1);
}
int inet_addr_match (const inet_prefix * a, const inet_prefix * b, int bits)
Definition at line 471 of file utils.c.
References inet_prefix::data.
{
    const __u32 *a1 = a->data;
    const __u32 *a2 = b->data;
    int words = bits >> 0x05;
    bits &= 0x1f;
    if (words)
        if (memcmp(a1, a2, words << 2)) {
            return -1;
        }
    if (bits) {
        __u32 w1, w2;
        __u32 mask;
        w1 = a1[words];
        w2 = a2[words];
        mask = htonl((0xffffffff) << (0x20 - bits));
        if ((w1 ^ w2) & mask) {
            return 1;
        }
    }
    return 0;
}
void invarg (const char * , const char *)
Definition at line 448 of file utils.c.
{
    fprintf(stderr, "Error: argument \"%s\" is wrong: %s\n", arg, msg);
    exit(-1);
}
int iplink_parse (int argc, char ** argv, struct iplink_req * req, char ** name, char ** type, char ** link, char ** dev, int * group)
const char* ipx_ntop (int af, const void * addr, char * str, size_t len)
Definition at line 64 of file ipx_ntop.c.
Referenced by rt_addr_n2a().
{
    switch(af) {
        case AF_IPX:
            errno = 0;
            return ipx_ntop1((struct ipx_addr *)addr, str, len);
        default
                :
            errno = EAFNOSUPPORT;
    }
    return NULL;
}
int ipx_pton (int af, const char * src, void * addr)
Definition at line 101 of file ipx_pton.c.
{
    int err;
    switch (af) {
        case AF_IPX:
            errno = 0;
            err = ipx_pton1(src, (struct ipx_addr *)addr);
            break;
        default
                :
            errno = EAFNOSUPPORT;
            err = -1;
    }
    return err;
}
int makeargs (char * line, char * argv[], int maxargs)
Definition at line 780 of file utils.c.
{
    static const char ws[] = " \t\r\n";
    char *cp;
    int argc = 0;
    for (cp = strtok(line, ws); cp; cp = strtok(NULL, ws)) {
        if (argc >= (maxargs - 1)) {
            fprintf(stderr, "Too many arguments to command\n");
            exit(1);
        }
        argv[argc++] = cp;
    }
    argv[argc] = NULL;
    return argc;
}
int mask2bits (__u32 netmask)
Definition at line 48 of file utils.c.
{
    unsigned bits = 0;
    __u32 mask = ntohl(netmask);
    __u32 host = ~mask;
    /* a valid netmask must be 2^n - 1 */
    if ((host & (host + 1)) != 0) {
        return -1;
    }
    for (; mask; mask <<= 1) {
        ++bits;
    }
    return bits;
}
int matches (const char * arg, const char * pattern)
Definition at line 463 of file utils.c.
{
    int len = strlen(cmd);
    if (len > strlen(pattern)) {
        return -1;
    }
    return memcmp(pattern, cmd, len);
}
void missarg (const char *)
Definition at line 443 of file utils.c.
{
    fprintf(stderr, "Error: argument \"%s\" is required\n", key);
    exit(-1);
}
int print_timestamp (FILE * fp)
Definition at line 717 of file utils.c.
{
    struct timeval tv;
    char *tstr;
    memset(&tv, 0, sizeof(tv));
    gettimeofday(&tv, NULL);
    tstr = asctime(localtime(&tv.tv_sec));
    tstr[strlen(tstr)-1] = 0;
    fprintf(fp, "Timestamp: %s %lu usec\n", tstr, tv.tv_usec);
    return 0;
}
const char* rt_addr_n2a (int af, int len, const void * addr, char * buf, int buflen)
Definition at line 541 of file utils.c.
References dn_naddr::a_addr, AF_DECnet, dnet_ntop(), and ipx_ntop().
Referenced by format_host().
{
    switch (af) {
        case AF_INET:
        case AF_INET6:
            return inet_ntop(af, addr, buf, buflen);
        case AF_IPX:
            return ipx_ntop(af, addr, buf, buflen);
        case AF_DECnet: {
            struct dn_naddr dna = { 2, { 0, 0, }};
            memcpy(dna.a_addr, addr, 2);
            return dnet_ntop(af, &dna, buf, buflen);
        }
        default
                :
            return "???";
    }
}
Variable Documentation
int __iproute2_hz_internal
Definition at line 500 of file utils.c.
int __iproute2_user_hz_internal
Definition at line 535 of file utils.c.
char* _SL_
int cmdlineno
Definition at line 730 of file utils.c.
Referenced by getcmdline().
int max_flush_loops
int oneline
int preferred_family
int resolve_hosts
Referenced by format_host().
int show_details
int show_raw
int show_stats
int timestamp